### ISSUE TITLE
Issue with Attachments & Request for Inline Attachment Support

### ISSUE THREAD

**Issue by dahomz** [calcinai/xero-php#100]
Greatly appreciating this library  - but unfortunately having an issue with adding attachments to a new invoice.

Notice: Undefined index: FileName in XeroPHP/Models/Accounting/Attachment.php at line 174

Here's a snippet from my code (I've probably got something wrong)

            // save the new invoice
            $invoice->save();

            $attachment = new \XeroPHP\Models\Accounting\Attachment(); 
            $attachment->createFromLocalFile("c:\\path\\to\\file.pdf", 'application/pdf');

            $invoice->addAttachment($attachment);

I've been able to successfully attach/upload this file after I hacked around in "XeroPHP\Traits\AttachmentTraits" and hardcoded the file contents directly into the upload.

Additionally it would be nice to have a way to attach a file generated on-the-fly (instead of taking one from disk) - for example when generating a PDF invoice/receipt from a query script.  

As a workaround to the issue and hoping the inline attachments feature could be added in the future, I added a function to \XeroPHP\Traits\AttachmentTraits.  (I'm not too sure about the return??)

 
    public function addInlineAttachment($file_name, $file_content, $mime_type = 'application/pdf'){
        /** @var Object $this */

        $uri = sprintf('%s/%s/Attachments/%s', $this::getResourceURI(), $this->getGUID(), $file_name);

        $url = new URL($this->_application, $uri);
        $request = new Request($this->_application, $url, Request::METHOD_POST);

        $request->setBody($file_content, $mime_type);
        $request->send();

        $response = $request->getResponse();

        return $response->getElements();

    }

A quick snippet of how I'm now using this in our application (Symfony) 

        // render a html page of the invoice query
        $html =  $this->renderView('invoice_template.html.twig');

        // generate a pdf from the HTML template
        $pdf_content = $this->get('pdf.generator')->generatePDF($html);

        // add the inline attachment to the invoice
        $invoice->addInlineAttachment('my_file_name.pdf', $pdf_content, 'application/pdf')

Hope this helps!

**Comment by calcinai** [comment]
Hey, thanks for the feedback.  There are a couple of things that I'm not happy about with he attachents logic!

Your issue is just that the ```::createFromLocalFile()``` returns a new instance of an attachment, so your code should read:

```php
    $invoice->save();
    $attachment = Attachment ::createFromLocalFile("c:\\path\\to\\file.pdf", 'application/pdf');
    $invoice->addAttachment($attachment);
```
I wish PHP warned you when you called static methods non-staticly!

In terms of the other comment, yes! That'd be a useful function alongside ```createFromLocalFile```, say ```createFromBinary```?  It's on my list to make all of the file handling stream-based, freeing up memory and just being a bit more elegant in general.

**Comment by dahomz** [comment]
Hi, Thanks for the reply and assistance.  Yes that fixed the issue for me, still learning something new every day :) Most appreciated!

createFromBinary would be a nice addition to the list.  I'm good to go now using the rather rough at the edges addInlineAttachment.

**Comment by calcinai** [comment]
Added in v1.2.6
