### ISSUE TITLE
Details of current user?

### ISSUE THREAD

**Issue by judgej** [calcinai/xero-php#103]
I'm not sure if this is possible, or whether it is an OAuth thing, or an API thing, but I would like to identify the user logged in through the API. It does not matter how they are identified - a user ID, an email, a full name - I just need to be able to keep track of which combinations of users and organisations have authorised use to the (Partner) application, so when an authorisation fails for any reason (changed their password, so tokens revoked, cancelled account etc.) I can go through the list of other organisations that user had authorised and mark them all as needing to be dealt with.

In my application, some agents will be registering multiple (sometimes dozens) of Xero organisations. I just need to know where this is happening.

**Comment by calcinai** [comment]
From what I understand, the authorisation process is done without explicit user context.  When the user gets sent to the Xero authorise endpoint, they'll be returned with a token unique for that user/organisation.

All I can think of doing is dynamically crafting the callback url to contain something recognisable at your end.  You probably can't add qs parameters, but I'm sure you could have it coming back to ```https://yourapp.com/user/11234/authorised``` or something?

**Comment by judgej** [comment]
The user's don't exist on my application - we have email addresses of people who have authority in an organisation to link up a Xero account to an endpoint in our application. We can see what organisation it is that has been authorised (Accounting\Organisation[0]->LegalName) but we just don't know who ultimately logged into Xero to provide that authorisation. That end Xero user is what we would like to know - not any of their login credentials, just some kind of ID.

**Comment by judgej** [comment]
Just an aside - it is turning into a bit of an issue for us that during authentication, if the user is already logged into Xero, then they cannot switch to a different user if they happen to be logged in as the wrong user. I am going to raise this with Xero, because being able to chose the user as well as the organisation *during* the authorisation process should be a thing.

Back to the original question. We have a single endpoint used for all authorisation - the Xero authorisers are not application users, so there are no user-specific URLs. Besides, the user we email with the authorisation link is not necessarily the user that logs into Xero - they are two completely different things.

Yes about the domain - the Partner app can have up to three domains, and they are useful for dev server, staging server, production server, with as many apps as you like on each server. I'm not sure whether apps on two domains can register the same Xero organisation without causing issues though, so you need different sets of Xero users for each domain.

Beyond that, I'm stumped. I am guessing OAuth has the ability to pass some of these details across, but I don't know whether Xero is set up to do this, or whether the application needs to add the request for those details explicitly (and if this API library supports that). OAuth still has too many mysteries in it for me.

**Comment by calcinai** [comment]
Yeah, I see I've completely missed your issue.  I wonder if there's another endpoint that might return that information?

**Comment by judgej** [comment]
Nothing I can see in the documentation.

**Comment by judgej** [comment]
We'll see if this gets any response:

https://community.xero.com/developer/discussion/12137453/

**Comment by calcinai** [comment]
I had a quick play.  2 things learned.

1. You seem to be able to get the user who last logged into xero for that organisation (may not be the source of truth, but could be better than nothing).
2. As soon as you're in API context, all actions you do seem to be disassociated from he user that authorised it.  I did this by uploading a file via the files API, then getting the GUID from the user that uploaded it.  It is not any of the GUIDs int he /User endpoint.  I'm interested if that 'User' is distinct by organisation, or by app, or possibly not at all!

**Comment by judgej** [comment]
1. This could be close enough, though there could be half an hour between the user logging in, and then authorising the app, with any number of oher users logging into that organisation in the meantime. Thinking about it, what does "logging into an organisation" even mean? You log into your Xero account, and them you chose an org to manage or authorise.Seems a strange one.
2. Very interesting. Gives some insights into how Xero works under the lid.

**Comment by judgej** [comment]
Xero confirm that this information is not available - you cannot discover which user an API is accessing the system as. There is a vote linked [from the forum post](https://community.xero.com/developer/discussion/12137453/) for anyone who would like this feature.

**Comment by calcinai** [comment]
I'm going to close this.  Unfortunately it seems like there's nothing that can be done.

**Comment by judgej** [comment]
I think you are right. I'll just keep my eye on updates to the Xero API and it may become a feature one day. We have restructured our application in the meantime, so that authentication is done at a different level. When users want to reuse an authentication, they do so by linking to an existing auth that is named on out side. We have no idea what the Xero user is, but with the application user on our end able to name that authorisation, they are able to keep track of resuses. Not ideal, but works well enough.

**Comment by judgej** [comment]
Just found this note, which looks promising:

> Our new OAuth2.0 authorisation will include an OpenID Connect identity layer that will allow apps to retrieve the connecting user’s details.
> 
> It’s a big project and still probably a few months away from general release but we’ll update this post with more details as we have them.

Posted by Xero, Jan 17 2019 https://xero.uservoice.com/forums/5528-xero-core-api/suggestions/5688571-expose-which-user-connected-the-organization-via-o

**Comment by mogilvie** [comment]
Under OAuth 2.0
