### ISSUE TITLE
Exception with DateTime::__construct()  capturing RepeatingInvoices 

### ISSUE THREAD

**Issue by web-factor** [calcinai/xero-php#104]
Firstly awesome library, easily the best thing out there as far as Xero connectivity goes.
Just wanted to report what appears to be a parsing error when capturing repeating invoices, it appears to fall-over attempting to create a PHP DateTime object from the value provided.
I've dumped the data provided and it appears to be valid so not sure what's going on .. details below:

Exception thrown with message &quot;DateTime::__construct(): Failed to parse time string (15) at position 0 (1): Unexpected character&quot;
Stacktrace:
#6 Exception in /home/mpp/public_html/workshop/vendor/calcinai/xero-php/src/XeroPHP/Remote/Object.php:291
#5 DateTime:__construct in /home/mpp/public_html/workshop/vendor/calcinai/xero-php/src/XeroPHP/Remote/Object.php:291

**Comment by calcinai** [comment]
I've identified the issue, I think it's safest that the due date on repeating invoices just doesn't get parsed since the ```DueDate``` is not always a date. 

eg:

```
    [DueDate] => 7
    [DueDateType] => DAYSAFTERBILLDATE
```

As you can see, it is trying to parse '7' (or in your case, 15) and it can't.  

I'll get a fix out.

**Comment by web-factor** [comment]
Cheers for the quick fix , we're fiddling with this library quite a bit right now will keep u posted if we come across anything else
