### ISSUE TITLE
How can I set bank account number into Account object?

### ISSUE THREAD

**Issue by wisoot** [calcinai/xero-php#106]

**Comment by calcinai** [comment]
Does ```->setBankAccountNumber()``` not work?

**Comment by wisoot** [comment]
Call to undefined method XeroPHP\Models\Accounting\Account::setBankAccountNumber()

**Comment by wisoot** [comment]
I'm testing it with that function being put on now, if it works. I'll make a pull request.

**Comment by calcinai** [comment]
From the docs, it looks like that is "only returned in a GET request" - http://developer.xero.com/documentation/api/accounts/#title1

**Comment by wisoot** [comment]
Yep the document is confusing.
But look below at this section "3. Below is an example of creating a new bank account with the minimum elements required. "

**Comment by calcinai** [comment]
Hmm.  I might have to do something special to overcome that.  All of the models are currently generated based on what the docs say.  

I'll email Xero and ask them to update the docs if it works.

**Comment by wisoot** [comment]
I have the pull-request here:
https://github.com/calcinai/xero-php/pull/107

**Comment by calcinai** [comment]
Can't merge it sorry since it's in generated code.  I'll email Xero now.

**Comment by wisoot** [comment]
Thanks.
BTW, I really like this package, much better than official version

**Comment by calcinai** [comment]
Still waiting on Xero for this.  They responded heaps on the day I first explained the issue but I haven't heard since.  I've just chased them up.

**Comment by iveoles** [comment]
Any more on this? I've noticed that you have Code as a required field, which it isn't for Bank Accounts.

The minimum XML is 

    <Account>
        <Name>Cheque Account</Name>
       <Type>BANK</Type>
       <BankAccountNumber>121-121-1234567</BankAccountNumber>
    </Account>

**Comment by calcinai** [comment]
Still waiting on xero for this. Got 

> Yes it did - I'll chase the team that was adding this to the docs.

On 27/10 - will chase again today.

**Comment by calcinai** [comment]
This has finally been updated.  Thanks @XeroAPI!

**Comment by wisoot** [comment]
Thanks @calcinai
