### ISSUE TITLE
Undefined Index

### ISSUE THREAD

**Issue by iveoles** [calcinai/xero-php#112]
Hi

Following the documentation I'm fetching all contacts and trying to build an array I can then use to save the data.

```php
    $contacts = $xero->load('Accounting\\Contact')->execute();
    foreach ($contacts as $contact) {

        $data = [
                'first_name' => $contact->getFirstName(),
                'last_name'  => $contact->getLastName(),
                'email'      => $contact->getEmailAddress(),
            ];

    }
```

However I'm receiving an error of 
```
    Undefined index: FirstName
```

This is because the first name isn't set within Xero, but would it not be better to return null rather than undefined?

**Comment by calcinai** [comment]
Yeah, i'm not opposed to that behaviour, for some reason that's just how it's always been.  I can't imagine that it'll have any negative consequences.

Does the XML come from Xero with an empty element or without the element altogether?  If it's an empty element, I'd argue that it (in this case) should be an empty string.  What do you think?

**Comment by iveoles** [comment]
They appear to be missing from the XML entirely, which is why I thought NULL would be appropriate. I also lends itself nicely to shorter if statements. Here's a sample of the XML from the Demo Company contacts

```xml

<Contact>
  <ContactID>e4c9d0e2-c285-4e85-b579-6d28b180c730</ContactID>
  <ContactStatus>ACTIVE</ContactStatus>
  <Name>24 Locks</Name>
  <Addresses>
	<Address>
	  <AddressType>STREET</AddressType>
	</Address>
	<Address>
	  <AddressType>POBOX</AddressType>
	</Address>
  </Addresses>
  <Phones>
	<Phone>
	  <PhoneType>DDI</PhoneType>
	</Phone>
	<Phone>
	  <PhoneType>DEFAULT</PhoneType>
	</Phone>
	<Phone>
	  <PhoneType>FAX</PhoneType>
	</Phone>
	<Phone>
	  <PhoneType>MOBILE</PhoneType>
	</Phone>
  </Phones>
  <UpdatedDateUTC>2015-11-11T02:26:12.093</UpdatedDateUTC>
  <IsSupplier>false</IsSupplier>
  <IsCustomer>false</IsCustomer>
  <HasAttachments>false</HasAttachments>
</Contact>
```

I've created a pull request, it seems a little simplistic but it's working without issues for me. Let me know what you think.

https://github.com/calcinai/xero-php/pull/115

**Comment by calcinai** [comment]
Looks fine. Merged

**Comment by calcinai** [comment]
Thanks for your input on this.

**Comment by iveoles** [comment]
Not a problem, really enjoying the library so far. I'm sure I'll be back
