### ISSUE TITLE
Please document, or at least mention in usage examples, ->page(x) method.

### ISSUE THREAD

**Issue by lunchboffin** [calcinai/xero-php#113]
Had a moment of worry when I thought this might not be in there:
$contacts = $xero->load('Accounting\\Contact')->page(1)->execute();

Here's an updated README.md

Would love to be a contributor, am working on a Xero project atm, and have had a little experience with Xero APIs when working on a Java project a little while ago.

[README.md.txt](https://github.com/calcinai/xero-php/files/43973/README.md.txt)

**Comment by calcinai** [comment]
Can you please convert this to a PR and I'll merge it.  Thanks!
