### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by iveoles** [calcinai/xero-php#117]
I'm in the middle of a project which involves migrating large amounts of data from a system into Xero, as such I'm making a lot of calls and making use of the saveAll feature.

Despite all that I often hit the rate limits imposed by Xero. I'm using this on Laravel, so my plan was to use a combination of Redis and Beanstalk queue manager to delay sending data within the Rate Limits imposed.

Before I head down this path does anyone have any better ideas about avoiding the rate limits or even better a more generic solution I could work on that I could add back into the library, rather than Laravel specific.

**Comment by calcinai** [comment]
I'm not aware of an immediate solution to this.  Short of blocking to simulate the correct rate, I don't think anything can really be built in.

Xero specifically say not to try to circumvent their rate limits, but they do say to contact them if you have a legitimate need for a higher limit.  I'm not aware of anyone who has done this yet though..

**Comment by coop182** [comment]
We constantly run into these rate limits... we just keep a track of the count of them in Redis and use that number as a multiple on our standard retry timeout for our Xero job queues (I think around 20 seconds)... if we have a successful request we take the count down by 1... this means for smaller Xero companies we can normally get all the data in or out as quick as possible and for larger ones they pump as much data through at fast as they can but then reach a good equilibrium once they start coming up against the limit.

**Comment by iveoles** [comment]
Any code you have handy to get me started?

**Comment by mhlavac** [comment]
@iveoles We used similar approach as @coop182 and as you suggested. We are running Gearman to queue jobs and if we hit the limits then we try to do request every 10 seconds. Because we have some customers with a lot documents in Xero and we can get some only by doing 1 request per document we also added option to use public and private integrations. User can add private and public integration keys and that way we are able to get 3x as much requests through a day.

I've asked Xero if they can give us special requests limit, but they said it's not possible at the moment because such a feature is not implemented on their side.

**Comment by calcinai** [comment]
What do you think should be done here?  Is it the responsibility of this library to handle?  I don't think blocking execution is a very nice way to achieve, and anything that deals with catching the ```RateLimitExceeded``` exceptions is likely to be app-specific.  Can this be closed?

**Comment by iveoles** [comment]
Afraid I'm not near a PC right now. Does it throw the RateLimitedException when that fails? Does it return the current rate limit values and headers? I guess if it returns all he information it can then that's enough. 

Maybe I could at least share some code in the read me that gives people a starting point?

**Comment by calcinai** [comment]
That'd be good - if you make a PR to the docs I'll merge it.
