### ISSUE TITLE
DateTimeInterface instead of DateTime

### ISSUE THREAD

**Issue by M1ke** [calcinai/xero-php#118]
Having received fatal errors when trying to pass a `DateTimeImmutable` into a set method I'm wondering if we should alter all typehints to allow the interface rather than the specific object.

I'll do the work; from what I can see a simple replace of:

* `(\DateTime` => `(\DateTimeInterface`
* `@property \DateTime` => `@property \DateTimeInterface`
* `@return \DateTime` => `@return \DateTimeInterface`

Would work, however you might have more of an insight. Let me know if that would seem sensible.

**Comment by calcinai** [comment]
I don't see any reason that this wouldn't work.  There's a bit of stuff around changing timezones for UTC which might be the only issue?

Have you tested it?

**Comment by M1ke** [comment]
I've submitted a PR for this:

https://github.com/calcinai/xero-php/pull/119

**Comment by calcinai** [comment]
Hey, did you use the generator to make the changes to the models?  (Just before I merge this in)

**Comment by M1ke** [comment]
Nope just made text changes. What's the process? Can try and see what's
different

**Comment by calcinai** [comment]
Oh, sorry I don't see this! you can just run ```./generator/generate``` from the root of the project.

**Comment by calcinai** [comment]
Have you had a chance to run the generator?

**Comment by M1ke** [comment]
I've now run the generator and pushed up to my master branch:

https://github.com/sturents/xero-php/commit/675fe35647e040d80d355b24c1db46f1bbb11d7b

Has this worked as expected?
