### ISSUE TITLE
Is SummarizeErrors=false implemented?

### ISSUE THREAD

**Issue by paulsschwarz** [calcinai/xero-php#12]
_The following is taking from http://developer.xero.com/documentation/api/invoices/_

If you are entering many invoices in a single API call then we recommend you utilise our new response format that shows validation errors for each invoice. The new response messages for validating bulk API calls would mean a breaking change so to utilise this functionality you’ll need to append ?SummarizeErrors=false to the end of your API calls e.g. POST /api.xro/2.0/Invoices?SummarizeErrors=false

Below is an example of the altered response format. Note that each Invoice is now returned with a status element which will either contain the value OK or ERROR. If an invoice has a error then one or more validation errors will be returned.

```
<Response>
  <Invoices>
    <Invoice status="OK">
      ...
    </Invoice>
    <Invoice status="ERROR">
      <ValidationErrors>
          <ValidationError>
              <Message>....</Message>
          </ValidationError>
          .....
     </ValidationErrors>
    </Invoice>
    <Invoice status="OK">
      ...
    </Invoice>
</Invoices>
</Response>
```

**Comment by calcinai** [comment]
I'm a little unsure how to handle this.  The ```Response``` class searches for errors, and throws an exception if there are any.  Would you suggest that it should continue as normal if there is an invalid element and set some property on a per-object basis indicating that there was an issue?

**Comment by paulsschwarz** [comment]
Take this scenario:
- Create an XML document with root element `Invoices` and in that create two `Invoice`s.
- Give the first invoice a valid `InvoiceNumber` that won't fail.
- Give the second invoice a duplicate `InvoiceNumber` which will fail.
- Do a `PUT` using the traditional `Invoice` endpoint.
You will notice an error is returned, however when you go into Xero and hunt for the invoices you'll notice that the first invoice was actually created. Now imagine you're interested in knowing the Xero `InvoiceID` (so you can store a reference to it locally for example), well, even though the first invoice was successfully created, you don't get to see that in the response. Having done some reading in the docs I believe that _?SummarizeErrors=false_ is meant to solve this.

This is only applicable to our new `saveAll()` method, not the `save()` method because that only deals in singles anyway.

Perhaps when using `save()` it's right to simply throw an exception, while in `saveAll()` it's not right to _always_ throw an exception. For `STATUS_BAD_REQUEST` maybe it could be handled differently. https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/Response.php#L57-L64. 

My opinion is split between whether, for absolute clarity, it's necessary to introduce a flag in the method, `saveAll($models, $summarise_errors)` or whether in the case of `saveAll()` it is naturally desirable to always get a summary and never an exception for `STATUS_BAD_REQUEST`.

Ideas?

**Comment by calcinai** [comment]
This actually leads into something else I am yet to implement - when saving an object that has a GUID property, it should be set on the original model if it's successful.  Maybe this is sufficient to cover this case?

Then you could call ```saveAll()```, then iterate the models you've just saved, and maybe have a ```isSaved()``` (or something) method on each one?

**Comment by paulsschwarz** [comment]
We've arrived at the same thing, our goal is to get the GUID from the saved models. So yes, implementing that feature would solve this.

So now we just need to figure out the mechanics of it. So no exception will be thrown but instead it's up to the developer to iterate and inspect each model in turn? I like that. How would `isSaved()` work? You'd need to do some internal bookkeeping in the model to keep track of its state. If it failed, where would the developer access the failure message?

Also, how do you match up requests with responses? Does Xero make it explicit that the array of responses will line up one for one in the correct order as the array of requests? It would be pretty dumb if that's not how it worked, but would be nice to see some guarantee of it.

**Comment by calcinai** [comment]
I've pushed this basic functionality onto master - would you like to test and see if it's what you'd expect?
You can see if the element saving was successful with $object->isDirty() after save, I saw no need to implement another method that did the same thing..
