### ISSUE TITLE
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase'

### ISSUE THREAD

**Issue by manishkvaish** [calcinai/xero-php#122]
i am a newbie as far as namespace,composer are concerned.

using the library ,after putting the consumer key and secret,but getting everything blank,while running tests/ApplicationTest.php

in error_log getting error:
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase'

need help.

**Comment by calcinai** [comment]
Hey, 

If you installed this package via composer, you'll need to make sure to include the composer autoloader file.  If you're new to namespaces, I'd recommend reading https://getcomposer.org/doc/00-intro.md and http://php.net/manual/en/language.namespaces.php.

In regards to your specific error, you'll need to run the tests via phpunit, which should be installed as a dev dependency.

**Comment by manishkvaish** [comment]
thank you very much sir for this valuable information
