### ISSUE TITLE
Examples for Nested/Related objects

### ISSUE THREAD

**Issue by highpanda** [calcinai/xero-php#124]
Hello, is it possible to get some examples for nested/related objects? There is a link for this in the readme, but the folder it links to doesn't contain any.

Many thanks,
Sam

**Comment by calcinai** [comment]
Hey, sorry about that.  I haven't had time to write up all the cases as they're different class to class.  Do you have a specific query?

**Comment by highpanda** [comment]
Please don't apologise! I'm specifically using the Invoice object with LineItems.

**Comment by calcinai** [comment]
LineItems is a reasonably funny one, If you've got an intelligent IDE, it'll probably be pretty self-explanatory.  You can basically create ```Invoice\Lineitem``` objects, then use the ```->addLineItem()``` method on the invoice to add them.  The saving should cascade when you save the invoice.

There is also ```->removeLineItem()``` for taking them off.

**Comment by highpanda** [comment]
Awesome. Ok, that is what I was doing. Thank you.
