### ISSUE TITLE
When sending a request for an oAuth token, include oauth_problem_advice in error msg

### ISSUE THREAD

**Issue by victormacko** [calcinai/xero-php#125]
Currently when an error in encountered when requesting an oAuth token, the exception message is simply 'Bad request'.

Internally, Xero however has sent back a more detailed message indicating the source (eg. callback url is not in the registered callback domain) in the oauth_problem_advice request param.

This isn't getting picked up though as the status_code is 400 (bad request), and XeroPHP/Remote/Response.php, line 72 (in the parse method) doesn't look for a oauth_problem_advice variable (as the STATUS_UNAUTHORISED handling does).

Is this something which might be looked?

**Comment by calcinai** [comment]
Hey, apologies for the late response.  I know a couple of people have played around with error messages in the past; most recently "here":https://github.com/calcinai/xero-php/blob/4a210d2baea2cfd9eeee1cc9f26da9398336c78b/src/XeroPHP/Remote/Response.php#L85 on commit e975cc1.

Is that the kind of thing you're looking for?

**Comment by victormacko** [comment]
Yes -- for some reason it was coming through as a 'bad request', so the 'unauthorised' block wasn't getting used (and thus the 'oauth_problem_advice' var wasn't getting returned at all)
