### ISSUE TITLE
Error saving SalesDetails and PurchaseDetails in ..\Accounting\Item 

### ISSUE THREAD

**Issue by dot5enko** [calcinai/xero-php#126]
when calling addSalesDetail on Item object it should assign one element the $this->_data['SalesDetails'] instead of adding element to Remote\Collection();

**Comment by calcinai** [comment]
Hey, I've had a very quick look at this.  It looks like this is a special case, where the name of there XML tags aren't consistent with what's in them.  I'll try to get it going tonight.

**Comment by calcinai** [comment]
This is actually a duplicate of #81, I'll try to sort them both out.

**Comment by dot5enko** [comment]
ok
