### ISSUE TITLE
Getting oauth authorise URL with scope data doesn't generate a proper url

### ISSUE THREAD

**Issue by victormacko** [calcinai/xero-php#129]
In src/XeroPHP/Application.php (line 78) the token is added to the end of the url -- this doesn't work when payroll scope variables are added to the authorise url;

$xero = new PublicApplication(['oauth' => ['authorize_url' => 'https://api.xero.com/oauth/Authorize?scope=payroll.employees,payroll.payslip,payroll.timesheets']]);

Generating the url;
$xero->getAuthorizeURL($oauth_response['oauth_token'])

The resulting URL is the following;
https://api.xero.com/oauth/Authorize?scope=payroll.employees,payroll.payslip,payroll.timesheets?oauth_token=ABCDEFG12345678

It can be worked around by;
$xero->getOAuthClient()->getAuthorizeURL() . '&oauth_token=' . $oauth_response['oauth_token'];

But a check to see if '?' is in the url might fix it.

This is following xero's instructions for payroll; http://developer.xero.com/documentation/payroll-api/overview/#permissions

**Comment by calcinai** [comment]
Can you please check out that branch and see if it's any better?  Seems OK to me.

**Comment by victormacko** [comment]
Looks great, and works perfectly with and without the scope :D

**Comment by victormacko** [comment]
Sorry, wasn't sure if you needed me to keep this open for you to merge into the main branch or close...
