### ISSUE TITLE
Error saving PayrollAU/Employee

### ISSUE THREAD

**Issue by dot5enko** [calcinai/xero-php#130]
When trying to save the object, it fails with "No resource found" because Application class generates wrong url to resource. (at first there is no possibility to create an payroll entity,because payroll items has only POST an GET options  - following to your code in Application class there is no action for that situation because create action using PUT),

**Comment by calcinai** [comment]
Can you see if this fixes the issue?  The API is riddled with little inconsistencies like this!

**Comment by dot5enko** [comment]
sorry for long response. i haven't received any email for that. no, it's not a solluton :)  
i added on line 173:
>   if ($object->getAPIStem() == URL::API_PAYROLL) {
>                 $method = Request::METHOD_POST;
>                 if (!$object->hasGUID()) {
>                     $uri = $object::getResourceURI();
>                 } else {
>                     $uri = sprintf('%s/%s', $object::getResourceURI(), $object->getGUID());
>                 }
>             } elseif ($object->hasGUID()) { 

because all the payroll objects has ability to create and update over api, but via POST method

**Comment by calcinai** [comment]
I actually did something similar to what you've described, although I seem to have lost it in another branch.  I'll push the original change up now.

**Comment by dot5enko** [comment]
ok, waiting for you to merge it to master
