### ISSUE TITLE
Undefined variable - '$errors'

### ISSUE THREAD

**Issue by victormacko** [calcinai/xero-php#131]
The following notice/warning came up when a validation error came up;

<br />
<b>Notice</b>:  Undefined variable: errors in <b>../vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php</b> on line <b>126</b><br />
<br />
<b>Warning</b>:  implode(): Invalid arguments passed in <b>../vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php</b> on line <b>126</b><br />

**Comment by calcinai** [comment]
I'll sort this out - links like it was introduced in #111, It needs a little tidy up.

**Comment by iveoles** [comment]
It looks as though this is back. I received it while doing a saveAll() on some Bank Transactions 

```
Undefined variable: errors

vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php on Line 126

**Comment by calcinai** [comment]
How odd. Can you please submit a quick PR

**Comment by iveoles** [comment]
Submitted 

https://github.com/calcinai/xero-php/pull/172
