### ISSUE TITLE
Is there a way to get all invoices for a particular client?

### ISSUE THREAD

**Issue by Phorce** [calcinai/xero-php#132]
Is there a possible way of getting an invoice for a particular user?

I.e. I want to display all of the active invoices for a particular user with a GUID e.g.

```
$x = $xero->load('Accounting\\Invoice')
    ->where('Status', \XeroPHP\Models\Accounting\Invoice::INVOICE_STATUS_AUTHORISED)
    ->where('Contact', '[GUID]')
    ->execute();
```

Any idea?

**Comment by calcinai** [comment]
What you're doing should be fine - except for one thing

    ->where('Contact.ContactID', '[GUID]')

I've just pushed some updates for guid handling at #136
