### ISSUE TITLE
Implement delete method

### ISSUE THREAD

**Issue by kylevorster** [calcinai/xero-php#137]
Hey,

If possible could you please add the ability to delete a item (transaction) on xero.

Thanks.

**Comment by calcinai** [comment]
Sorry it's taken so long to get on to this, I'm currently doing a bit of traveling so have limited access tot he internet.  It's next on my list!

**Comment by kylevorster** [comment]
Thanks calcinai .

**Comment by calcinai** [comment]
This is done.

**Comment by calcinai** [comment]
A further note: this is is just the implementation of the HTTP delete method for those that support it.  If it's an object like a ```BankTransaction```, you'll still need to use:

```php
$bankTransaction->setStatus(BankTransaction::BANK_TRANSACTION_STATUS_DELETED);
$bankTransaction->save();
```

**Comment by kylevorster** [comment]
Thank you @calcinai
