### ISSUE TITLE
Paying invoices?

### ISSUE THREAD

**Issue by Phorce** [calcinai/xero-php#138]
Hi, 

I don't know if this has been implemented or not, as could not find any documentation. Is it possible to have an option to pay for an invoice? 

Something like: https://in.xero.com/[GUID] 

But, where could I pull through this GUID?

**Comment by calcinai** [comment]
Can you please elaborate?

**Comment by kylevorster** [comment]
I'm not sure if this would work but, maybe it points you in the right direction.
`<?php
    

$invoice = $xero->loadByGUID('Accounting\\Invoice', [GUID]);

// or

$invoice = new \XeroPHP\Models\Accounting\Invoice($xero);     

$invoice->setInvoiceID('bleh');

// make payment

$payment = new \XeroPHP\Models\Accounting\Payment($xero);

$payment->setInvoice($invoice)
        // ->setCreditNote()
        // ->setPrepayment()
        // ->setOverpayment()
        ->setAccount('200')
        ->setAmount('10.00')
        ->setDate()
        ->setIsReconciled(1)
        ->setStatus(\XeroPHP\Models\Accounting\PaymentPAYMENT_STATUS_AUTHORISED);

$r = $payment->save();
        
var_dump($r);   `

**Comment by mayankvadiya** [comment]
@kylevorster is it working ? In my case it will not working

**Comment by kylevorster** [comment]
I haven't used this package in ages, so I won't be able to comment.

Sorry.
