### ISSUE TITLE
Payroll Api 

### ISSUE THREAD

**Issue by dot5enko** [calcinai/xero-php#139]
Timesheet and Payitem not parsed right. When parsing responses from those endpoints at `xero-php/src/XeroPHP/Remote/Response.php:227` you said: 
`//Happy to make the assumption that there will only be one root node with > than 2D children` - its wrong, because there are not only one root element in that entities

**Comment by calcinai** [comment]
Bugger.  Is it possible for you to attach some example XML as I've never actually had access to the payroll API.

**Comment by dot5enko** [comment]
when getting timesheet by GUID there one <Timesheet></Timesheet> instead of
 <Timesheets></Timesheet></T..></T..>
examples

[payitem.txt](https://github.com/calcinai/xero-php/files/123295/payitem.txt)
[timesheet.txt](https://github.com/calcinai/xero-php/files/123298/timesheet.txt)


Payitem has completely another structure

**Comment by calcinai** [comment]
I think the parsing function needs a bit of a rewrite.  Have you got any ideas?

**Comment by dot5enko** [comment]
i think you should add some extra data to Models via `generate` file 
add parsing examples 
if there is example of getting element by GUID you should check if the structure of response is not general (one plural parent -> singular element(s)). then, i think, it's possible to determine the actual structure of response acording to structure you got above in documentation.

Just add to models some data like `ResponseDataAttribute` or `ResponseDataPath` which would say what the path to the data  e.g /root/`Employees/Employee`. 

Now, when parsing data in `Response.php`  just use that data. it should be public static 

example of `generate` modifications

```php
case 'pre':
    $examples = [];

    // get the example of getting by GUID
    if (preg_match('/^Example response for GET (.+)\//', $section_name, $examples)) {

        $nodeVal = $node->text();
        libxml_use_internal_errors(true); // supress  warnings when parsing xml in next line
        $xmlParsed = simplexml_load_string($nodeVal);
        if (!$xmlParsed) {
            // wrong xml document 
            // there's some errors in documentation. for example BrandingThemes
        } else {
            $modelName = Helpers::singularize($primary_model->getName());

            // if its not a standart situation when: 
            // <plural>
            //      <singular></singular>
            //      ...
            // </plural>
            if (empty($xmlParsed->{$modelName}->asXML())) {
                // try to get the structure according to the structure got above    
                // TODO whole work goes 
            }
        }
    }
    break;

//END HANDLING FOR TABLE ELEMENT

**Comment by calcinai** [comment]
Thanks for that @dot5enko - does that change work? If so, can you make a PR or a branch so I can test?

**Comment by dot5enko** [comment]
ok. i'll make a pull request when finish all that stuff

**Comment by calcinai** [comment]
Any joy?

**Comment by dot5enko** [comment]
not yet. try to accomplish this in few days

**Comment by dot5enko** [comment]
i started working on this changes and have bad news: seems like there is no another way like hardcoding of some models (like PayItems), because they have cardinally another structure. in case of PayItems there's only one PayItem (you can't actually get some payitem by GUID as other entitys). What would be a solution for this ?

**Comment by calcinai** [comment]
I've got the generation process spitting out a swagger file which will then be a 'base' file that we can define overrides for.  That will then be used to generate the models as they are now.  This is all for 2.0

My suggestion, hardcode for now (or make an extension of the model and use that instead for now).

**Comment by dot5enko** [comment]
ok. if i find some better solution i'll let you know

**Comment by calcinai** [comment]
Hey, I think this has been fixed in #183 and #184 - does that seem right?

**Comment by dot5enko** [comment]
yeah, seems to be working right now

**Comment by calcinai** [comment]
Cool
