### ISSUE TITLE
Q: How to get response/warnings when invoice saved?

### ISSUE THREAD

**Issue by netmit** [calcinai/xero-php#140]
Apologies for the newbie question! 

I'm creating basic invoices with the API and I have got everything working fine when I save the invoice to Xero. I'm just wondering what the best way of parsing the response I get back to check it's OK or not. 

At the moment I'm just using DD to dump the response for testing but would like to know the invoice has saved OK or if there are any warnings in the Xero response but I can't figure out how to parse the response I get back. And should I be looking for a response on the Xero private application object or on the invoice object (if that makes sense?)?

I've tried using $xero->getOAuthClient() and looking at that but not sure that I should be using that.

Thanks.

**Comment by calcinai** [comment]
Hey, is it just the warnings you're after?  I'm assuming you've worked out that an exception will be thrown if there's an actual error.

You can probably get the warnings from the response object, as most of it is parsed out in one way or another.  Have a look at the ```->getEmelemtErrors()``` method

**Comment by netmit** [comment]
Thanks Michael.

Yes, I'll be catching exceptions eventually to handle actual errors so I'm really just looking for any warnings that Xero returns (e.g. incorrect account codes etc.).

I think the problem might be in the way I'm creating the invoice. I've looked through your public application example and see how to access the request and response but I'm using a private application so my basic code looks like this:
````
$xero = new PrivateApplication($config);

$contact = $xero->loadByGUID('Accounting\\Contact', '12345678-1234-1234-1234-12345678abcd');

$xeroInvoice = new \XeroPHP\Models\Accounting\Invoice($xero);
$xeroInvoice->setType('ACCREC')->setContact($contact)->setReference('123456');

$xeroLineItem = new \XeroPHP\Models\Accounting\Invoice\LineItem($xero);
$xeroLineItem->setQuantity(1);
$xeroLineItem->setDescription('Test Item');
$xeroLineItem->setUnitAmount('100.00');
$xeroLineItem->setTaxType('OUTPUT2');

$xeroInvoice->addLineItem($xeroLineItem);

$xeroInvoice->save();
```

I can see how you access the response object in a public application but in my private application I only have the $xero object and the $xeroInvoice object and I can't seem to find any methods for getting the response out of those (other than the actual invoice data). The code I'm using seems wonderfully simple and works perfectly but do I need to expand it and create a request object if I want to access the warnings?

Sorry if I'm making a schoolboy error somewhere - I'm new to OOP and still learning ;-).

**Comment by calcinai** [comment]
Hey, there's actually no difference between the different types of apps in terms of what functions are available.

Unfortunately, if you want to get the raw data out you will need to expand it out into a request object (basically just what's int he save method) and then interrogate it.  The only other way I can think of would be to pass-by-reference a variable tot he save method that was populated with warnings.

If you find something that works for you, create a PR and I'll take a look.

**Comment by netmit** [comment]
Thanks MIchael. No problem - just happy it wasn't just me ;-)
