### ISSUE TITLE
Save invoice action does not populate line item data

### ISSUE THREAD

**Issue by radonjic** [calcinai/xero-php#142]
Hi,

I have notice that when Invoice record is save, InvoiceID is populate from response, but Line Item Id is not populate. 
Can you add small fix by adding optional parameter to save method in Application class and to paste it in fromStringArray method(see attachment).

Thanks in advance,

Ivan 
<img width="1440" alt="xero_php" src="https://cloud.githubusercontent.com/assets/7442790/13111596/fb2c715a-d586-11e5-9892-3a6c32911bef.png">

**Comment by calcinai** [comment]
Will merge when this is rebased.
