### ISSUE TITLE
Deep Links

### ISSUE THREAD

**Issue by iveoles** [calcinai/xero-php#147]
Hi

I've started adding some Xero deep links into my app, but I couldn't find anything in the library for it. Am I missing something or is this something I should look at adding?

http://developer.xero.com/documentation/advanced-docs/deep-links/

**Comment by calcinai** [comment]
Yeah, this would probably be useful.  I'm about to start the 2.0 branch with a whole lot of improvements from learnings here, so maybe it can be included in that?  Unless you've got a quick PR you want to merge?

**Comment by iveoles** [comment]
Afraid I just have a basic function written with everything hardcoded.
