### ISSUE TITLE
IDE notices about duplicate class name definition

### ISSUE THREAD

**Issue by e1himself** [calcinai/xero-php#154]
Hi! 

There's a problem with having that *generator* symlink referencing another sources folder: IDE complains about dupicate class names definitions and thus code-autocompletion does not work. Even if both definitions are exactly the same, IDE doesn't know that.

![2016-03-31 11-42-42](https://cloud.githubusercontent.com/assets/370680/14170352/efc68c1c-f735-11e5-8080-89600c8f0363.png)

Is that possible to avoid using that symlink within repo?

Thanks.

**Comment by calcinai** [comment]
Ah, yes.  It was just for the sake of the generator simplicity.  I'l remove it in 2.x if that's not too far away?

**Comment by e1himself** [comment]
It depends on how long will it take to roll out 2.x and how much will it be break BC :)

**Comment by calcinai** [comment]
Ok, I'll just whip it out.

**Comment by e1himself** [comment]
Thanks man!
