### ISSUE TITLE
Reports API

### ISSUE THREAD

**Issue by iveoles** [calcinai/xero-php#159]
Am I missing something or are the reports not covered by the library?

http://developer.xero.com/documentation/api/reports

**Comment by calcinai** [comment]
Hey, yeah they've been omitted.  This was just due tot he docs format being so different to the rest of the requests.  They don't really even return "models" as such either.  You can still manually build up a request object and parse the request into an object.

(https://github.com/calcinai/xero-php/blob/master/generator/generate#L59)

**Comment by iveoles** [comment]
Yeah that's what I've started doing, but I've had to build it manually due to time constraints. As such it's not something I'd want to feed back into the library.

**Comment by calcinai** [comment]
Ok, I'll try to get it out soon!
