### ISSUE TITLE
 Class 'XeroPHP\Application' not found 

### ISSUE THREAD

**Issue by tronghuan** [calcinai/xero-php#160]
Hi,
I downloaded zip file and extract to /var/www/html/ and run composer install.

When I visit http://127.0.0.1/xero-php-1.3.0/examples/public.php then I get this error:

Fatal error: Class 'XeroPHP\Application' not found in /var/www/html/xero-php-1.3.0/src/XeroPHP/Application/PublicApplication.php on line 8.

Is it a error? Thank you

**Comment by calcinai** [comment]
Does composer install without any errors?

**Comment by tronghuan** [comment]
Yes, composer install ok without any errors. The vendor directory created and has contents.
