### ISSUE TITLE
Editing invoice, add line item not updating invoice total

### ISSUE THREAD

**Issue by jwGeorge** [calcinai/xero-php#161]
Hi there,

I'm loading a Credit Note from Xero that does not have any payments associated and am adding a line item, but when i go to save the object, i get a error on response that the document total does not match the sum of the line items.

EDIT: It appears as though when i load the Credit Notes from Xero using the following, the LineItems  property is empty.

```
$credits_outstanding_temp = $xero->load('Accounting\\CreditNote')
    ->where('RemainingCredit>0')
    ->execute();
```

Any idea?

**Comment by calcinai** [comment]
Hmm, I suspect that the local total either needs to be manually set to the total of the items, or the CN total needs to be cleared so it doesn't try to set it manually.

**Comment by jwGeorge** [comment]
Seems like the line items are not actually pulled through with the credit note. Invoices need you to page the request in order for them to come through with the line items attached but credit notes don't seem to support paging and there doesn't appear to be any way to get the current line items. 

So if you get a current credit note say $1000 and add a line item of $100, the total adds up to what it theoretically should be $1100, but when you save it it's only got the $100 line and throws the error.

**Comment by calcinai** [comment]
Oh I see.  Do you think the way to solve this is being able to 'unset' a property that needs to be saved? I'm not sure the best way to achieve is we keep the actual models intact.  I guess we could make it += the value of any line items added?

**Comment by calcinai** [comment]
After reading your comment again, would this be solved if it just lazy fetched that property if it didn't come down in the initial request?

**Comment by calcinai** [comment]
@jwGeorge - did you try anything else with this?

**Comment by jwGeorge** [comment]
@calcinai - Sorry for the late reply, was overseas for a few months. No resolution from my end. I just worked around the issue by adjusting the process.
