### ISSUE TITLE
Operation timed out

### ISSUE THREAD

**Issue by Redshift-Web-Design** [calcinai/xero-php#162]
Hey guys. Not sure if this is an issue or just me being an idiot. But I cannot seem to filter a load('Accounting\\Contact') with a ->where('IsSupplier', true) without getting a Curl: Operation timeout error. Any ideas?

Thanks,

**Comment by jwGeorge** [comment]
It could be trying to pull more data than can be done with the default timeout, usually 20-30 seconds. Try increasing the timeout value by setting the following in the config array:

CURLOPT_TIMEOUT 	=> 120

That will set the curl timeout to 120 seconds.

**Comment by calcinai** [comment]
Yeah, the Xero API can be terribly slow at times, so increase the timeout or limit your query and see if that helps.

**Comment by Redshift-Web-Design** [comment]
Hey guys. I appreciate the feedback but unfortunately that hasn't fixed the issue. Did increase the CURL timeout and I don't get a timeout error anymore. I get this...

InternalErrorException in Response.php line 95: An unhandled error with the Xero API. Contact the Xero API team if problems persist.

Literally just using this basic logic below.
`        $xero = App::make('XeroPrivate');

        $contacts = $xero->load('Accounting\\Contact')
            ->page(1)
            ->where('IsSupplier', true)
            ->execute();`

Any other ideas?

Thanks

**Comment by calcinai** [comment]
Hmm. That error comes from Xero itself - it might be worth contacting them and see if that request should be working. I reckon it's timing out at their end.

**Comment by calcinai** [comment]
Did this ever get resolved?

**Comment by Redshift-Web-Design** [comment]
Hi Michael,

No it didnt unfortunately and It wasn't enough of a priority at the time to be chasing xero. It is in next weeks sprint though so I will update this issue with anymore details I uncover. 

Thanks

Kind Regards

Jason Hill

**Comment by Redshift-Web-Design** [comment]
Looks like this has been resolved now at Xero's end. Thanks
