### ISSUE TITLE
Xero won't amend invoice via API because (prepopulated) TotalDiscount is 0.0, not null

### ISSUE THREAD

**Issue by amh15** [calcinai/xero-php#163]
I'm doing the following, which basically changes an invoice from draft to authorised and sets a date and due date:
`$inv = $xero->loadByGUID('Accounting\\Invoice', $convert_order['quoteID']);`
`$now = new DateTime("now");`
`$due = new DateTime($now->format('Y-m-t')); // end of this month`
`$due->add(new DateInterval('P30D'));`
`$res = $inv->setStatus(\XeroPHP\Models\Accounting\Invoice::INVOICE_STATUS_AUTHORISED)`
`                    ->setDate($now)`
`                    ->setDueDate($due)`
`                    ->save();`

This previously worked nicely.

I now notice that (since today?) for some of the draft invoices on our Xero account, the TotalDiscount field retrieved within $inv appears to be NULL. In others it's float(0).

If it's float(0), the attempt to write the invoice appears to fail with the following error: 

> Discounts are only supported on individual line items. You can specify the same DiscountRate on each line item to achieve a discount across an entire invoice.

By contrast if the TotalDiscount is NULL, there's no error.

To the best of our knowledge we have never tried to amend this field so perhaps Xero has changed in the way it handles it. Apparently the library is trying to write the value back to the API. 

Given that we are not supposed to write to TotalDiscount for the invoice, only GET it (http://developer.xero.com/documentation/api/invoices/), could you amend the library to not to try to save such read-only values? I don't see how to alter the stored value from 0 to NULL using your library or indeed in Xero, which means that I can't work with these invoices via the API.

By the way I CAN convert them to approved in the Xero web interface. But if I then copy that invoice to create a new draft invoice, TotalDiscount is float(0) again in the new copy.

**Comment by calcinai** [comment]
That definitely sounds like an issue. I'll look in to it first thing in the morning.

**Comment by calcinai** [comment]
Can you please check out the issue-163 branch and see if that helps.  I've updated the serialisation to only pass rw properties to the save method.

**Comment by amh15** [comment]
That sounds great, thank you. I only started using composer a few weeks ago so I don't know how to do that, however I suspect Google will be my friend as usual. I found a method yesterday involving composer.json. I will take another look today.

**Comment by calcinai** [comment]
You should just be able to use

```    "calcinai/xero-php": "dev-issue-163" ```

**Comment by amh15** [comment]
Hi there. It may seem pretty basic but I'm unable to get this to work, as follows.

composer.json:
`{`
`    "require": {`
`        "calcinai/xero-php": "dev-issue-163"`
`    }`
`}`

I tried the above with and without the hash before 163. Either way I get the following. Should I be trying to escape the # character in some way?

`/usr/bin/php5.5-cli composer.phar update`

> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package calcinai/xero-php dev-issue-163 exists as calcinai/xero-php[dev-guid-handling, dev-issue-#130, dev-issue-#137, dev-issue-#163, dev-issue-131, dev-master, dev-rename-excpetion, dev-scrutinizer, v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.5, v1.1.6, v1.1.7, v1.2.0, v1.2.1, v1.2.10, v1.2.11, v1.2.12, v1.2.2, v1.2.3, v1.2.4, v1.2.5, v1.2.6, v1.2.7, v1.2.8, v1.2.9, v1.3.0, v1.3.1] but these are rejected by your constraint.

**Comment by amh15** [comment]
Further to the above, I can build it successfully with dev-issue-131, but there seems to be an issue with the hash character that prevents me from updating it to dev-issue-#163.

**Comment by amh15** [comment]
OK don't worry, I can manually install the files. Let me see if this cures the problem.

**Comment by amh15** [comment]
That appears to have solved the problem. I had to update my php version from 5.4 to 5.5 for it to run (otherwise it failed complaining of a DateTimeInterface versus DateTime mismatch on the setDate method).

Many thanks for the help. Should I look out for this getting rolled into the main release version?

**Comment by calcinai** [comment]
That's a good point - I'll update the composer definition to reflect that. 

I'll release it on the 1.3 base.  Sorry about that branch name, I must've accidentally put a hash in there - I usually try to do it for commits so github makes the association.
