### ISSUE TITLE
Receipts Model inconsistencies

### ISSUE THREAD

**Issue by tomcastleman** [calcinai/xero-php#165]
- I notice `Receipt->Status` is not settable currently. I assume this is because Status is missing from the Xero docs under [Elements for Receipts - optional for a PUT / POST request](https://developer.xero.com/documentation/api/receipts/#title1).
  I have sent a request to Xero to get this added in here. Is this the best approach?
- In the Xero docs `LineItems` is mandatory which actually is incorrect because, for example, when updating a Status to DELETED you don't need or want to provide that.
  Again is asking Xero to move LineItems to the optional heading the best approach here?
- The DELETED status constant is missing. I can't immediately see in the generator where you get these `Enums` from. Could you advise how we can get the DELETED status in here?

Thanks for your great work on this package!

**Comment by tomcastleman** [comment]
I have had a response from Xero which I include below.

I am impressed with the level of detail and I can understand their stance however this makes the automatic parsing of the Receipt API less straightforward if we want to enable deleting of receipts.

A more RESTful way would be if they accepted a DELETE request on the individual receipt endpoint, but this wouldn't enable multiple deletions per request.

What do you suggest for enabling the deletion of a receipt within this library?

Thanks

```
Hi 
 
Thank you for your feedback.

Status is not available for most uses of PUT and POST.  If you are creating or editing an active receipt, including Status will cause your call to fail.  As this is the majority of the calls made on this endpoint, we've chosen to show Status as a Read Only field.

Lower down the page we have an example of how to delete a draft receipt on the Receipt page which shows the call with the minimum required elements which includes a status of DELETED.  The reason Status is available in this one instance is because updating Status to DELETED is the only way the system knows that the receipt should be deleted.  

You'll need to manually update your client to include Status when deleting receipts, but make sure to omit it on all other calls.  If your client is scraping what's available, it sounds like if we add this then you would be able to delete receipts but no longer create or edit them as it would start including Status in the calls.
 
Please let us know if you have any other questions.
 
```

**Comment by calcinai** [comment]
Wow, what a pain.  I had thoughts initially of models that supported 'soft deleting' which updated the status and sent.  Maybe this should be re-explored.

The logic was basically if it supported a `delete` then do it, if not see if it has a deleted status and try to set it.
