### ISSUE TITLE
$item->addSalesDetail - Sales details not being saved in Xero

### ISSUE THREAD

**Issue by nathangoss** [calcinai/xero-php#168]
I am creating a new untracked Item and the Sales details are not being saved in Xero.

The item is created successfully, with no errors, however it is missing the Sales details.

Here is my code:

```
        $inventory_item = new \XeroPHP\Models\Accounting\Item($xero);
        $sale = new \XeroPHP\Models\Accounting\Item\Sale($xero);

        $inventory_item->setIsSold(true);
        $inventory_item->setName($payload['data']['object']['name']);
        $inventory_item->setCode($payload['data']['object']['id']);

        $sale->setUnitPrice($payload['data']['object']['amount'] / 100);
        $sale->setAccountCode(env('XERO_INVENTORY_ACCOUNT', '200'));

        $inventory_item->addSalesDetail($sale);

        $xero->save($inventory_item);
```

**Comment by nathangoss** [comment]
Looks like there is an extra <SalesDetails> tags being added:

`<Item><Code>TST-123</Code><Name>Test Item</Name><IsSold>true</IsSold><SalesDetails><SalesDetail><UnitPrice>9.99</UnitPrice><AccountCode>200</AccountCode></SalesDetail></SalesDetails></Item>`

**Comment by nathangoss** [comment]
Found the cause:

XeroPHP/Models/Accounting/Item.php  line 390

Change from:
$this->_data['SalesDetails'][] = $value;
to
$this->_data['SalesDetails'] = $value;

**Comment by calcinai** [comment]
Hey, I assume this is still an issue?
