### ISSUE TITLE
URL not set in Models/Accounting/Organisation/ExternalLink model when recieve Organisation

### ISSUE THREAD

**Issue by gigi** [calcinai/xero-php#170]
Hi! 
Thank you for nice SDK! This lib saved me a lot of time :)

I found a little bug

```
        $organisations = $->getApp()->load('Accounting\\Organisation')->execute();

        /** @var \XeroPHP\Models\Accounting\Organisation $a */
        $a = $organisations[0]->getExternalLinks();
        foreach ($a as $link) {
            /* @var ExternalLink $link */
            var_dump($link->getLinkType());
            var_dump($link->getURL());
        }
```
Outputs:
```
XeroController.php:96:string 'Website' (length=7)
XeroController.php:97:null
```

```URL``` should be replaced with ```Url``` everywhere in /vendor/calcinai/xero-php/src/XeroPHP/Models/Accounting/Organisation/ExternalLink.php

So I tried to start generator/generate script. however it has wrong path to autoloader on line 17
I've changed it to require GEN_ROOT.'/../../../autoload.php';

```
$ ./generate
PHP Warning:  require(PATH/vendor/calcinai/xero-php/generator/../vendor/autoload.php): failed to open stream: No such file or directory in PATH/vendor/calcinai/xero-php/generator/generate on line 18
PHP Fatal error:  require(): Failed opening required 'PATH/vendor/calcinai/xero-php/generator/../vendor/autoload.php' (include_path='.:') in /srv/www/yaypay.local/databooth-common/vendor/calcinai/xero-php/generator/generate on line 18
```

Then strange bugs from composer. 
```Class Goutte\Client was not found``` and ```Class 'Twig_Loader_Filesystem' not found```

I've installed them manualy and finally got

`````
PHP Fatal error:  Uncaught exception 'Twig_Error_Loader' with message 'The "generator/templates/" directory does not exist.' in PATH/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:93
```
```
$loader = new Twig_Loader_Filesystem('generator/templates/');
```
Should be changed to ```__DIR__ . '/templates/'``` in my case
```
$loader = new Twig_Loader_Filesystem(__DIR__ . '/templates/');
```
Maybe something wrong with my environment...

Generation finished succesfully.
However URL is still in upper case and doesn't work.... 
Can you fix it please? Thank you!

**Comment by calcinai** [comment]
I'll look at it now - what PHP version are you running?

**Comment by calcinai** [comment]
I can see this issue, just not sure what to do about it!  The Xero documentation shows *URL* in uppercase, where in the XML it's lowercase.  

Easiest fix is to get them to fix their docs!

**Comment by gigi** [comment]
$ php -v
PHP 5.5.34 (cli)
I'll try to write on their forum

**Comment by calcinai** [comment]
I have emailed their developer team so just give it a couple of days first.  As a temporary fix, just change your local copy of the code until this is fixed.  Composer will let you stash & reapply if you need to.

**Comment by gigi** [comment]
Ok! Thank you!!!

**Comment by calcinai** [comment]
Also, re: the generator - try running it from he directory above - from `xero-php/`, so you'll be going `./generator/generate`

I should really fix the relative references in there or make it a registered bin in composer!

**Comment by gigi** [comment]
> Also, re: the generator - try running it from he directory above - from xero-php/, so you'll be going ./generator/generate

No luck.
```
xero-php gigi$ ./generator/generate
PHP Warning:  require(PATH/vendor/calcinai/xero-php/generator/../vendor/autoload.php): failed to open stream: No such file or directory in PATH/vendor/calcinai/xero-php/generator/generate on line 18
PHP Fatal error:  require(): Failed opening required 'PATH/vendor/calcinai/xero-php/generator/../vendor/autoload.php' (include_path='.:') in PATH/vendor/calcinai/xero-php/generator/generate on line 18
```

If relative path is used then I should run from /vendor/calcinai folder
```
calcinai gigi$ ./xero-php/generator/generate
PHP Warning:  require(PATH/vendor/calcinai/xero-php/generator/../vendor/autoload.php): failed to open stream: No such file or directory in PATH/vendor/calcinai/xero-php/generator/generate on line 18
PHP Fatal error:  require(): Failed opening required 'PATH/vendor/calcinai/xero-php/generator/../vendor/autoload.php' (include_path='.:') in PATH/vendor/calcinai/xero-php/generator/generate on line 18
```
But ```__DIR__``` will always return parent of ```generate``` script

``` PATH/vendor/calcinai/xero-php/generator ```

**Comment by calcinai** [comment]
Is it possible you've got a funny PATH environment variable?  Why is it showing in the path?

**Comment by gigi** [comment]
I've just replaced realpath by virtual 'PATH' in messages to hide project name from public)

**Comment by calcinai** [comment]
Ahh - I it could be as simple as needing to do a composer install in xero-php itself.

**Comment by gigi** [comment]
I see) It doesn't matter actualy... Nevermind) You've done a great work!
Waiting for Xero docs updated and xero-php v1.3.2 with corrected Url :)

**Comment by calcinai** [comment]
Hopefully we'll hear back from Xero today.

**Comment by gigi** [comment]
Hi! Any updates?)
Looks like they've changed docs. 
https://developer.xero.com/documentation/api/organisation/
Can you re-generate models?

**Comment by calcinai** [comment]
Fixed at @c427d73 - was nice of them to reply!

**Comment by gigi** [comment]
Thank you!!!

**Comment by calcinai** [comment]
Don't thank me, thank Xero!
