### ISSUE TITLE
How to update/delete contact persons on a contact

### ISSUE THREAD

**Issue by ImperialXT** [calcinai/xero-php#171]
So from what I can tell from looking through the code there's no way to remove/update contactPersons on an contact?

**Comment by calcinai** [comment]
You could be right, although can you decipher what the xero API allows from their docs?  Do you just `put` a new list overtop of the old one?

**Comment by ImperialXT** [comment]
Going by: https://developer.xero.com/documentation/api/contacts
 "When you are updating a contact you don’t need to specify every element. If you exclude an element then the existing value of that field will be preserved. For example in the example above the existing phone numbers will be preserved as they were not specified."

You just put a new list over the top of the old one, have tested it by doing.

$contact = new Models\Accounting\Contact($xero);.
$contactPerson = new Models\Accounting\Contact\ContactPerson($xero);
contactPerson->setFirstName("Bob");
  $contactPerson->setLastName("Jones");
  $contactPerson->setEmailAddress("bob.jones@example.com");
$contact->addContactPerson($contactPerson);
$contact->save();

This overwrote the existing contact persons I had with just the one which is the desired result. It's just a bit counter intuitive to do it this way. It's identical to the workaround for the issue with voiding/deleting invoices that have discounted line items.

**Comment by calcinai** [comment]
I'll try to make the collections handle this in 2.0

**Comment by edwade3** [comment]
I'm not sure if Xero updated their API, or if I'm being daft but just sending the updated data to Xero resulted in an error saying the contact already existed. I had to write an update function that first made a GET to retrieve the record, and then use set's and save to update it so my code now looks like this:
`$contact = new \XeroPHP\Models\Accounting\Contact($xero);

$contact->setName($contact_info['name'])
	->setFirstName($contact_info['firstName'])
	->setLastName($contact_info['lastName'])
	->setEmailAddress($contact_info['emailAddress'])
	->setContactNumber(strtoupper($contact_info['id']));

$contact->save();`

**Comment by ImperialXT** [comment]
Sorry, I'm not working on this code anymore. I've since moved jobs so not able to help as I don't have access to my code anymore. But this issue was specifically about contact persons not contacts themselves, the terminology is a bit confusing.

**Comment by calcinai** [comment]
I think if you're working with an object that already exists, you can chain a `->setClean()` after the `->setContactID()` so it doesn't try to create it.  

```
$contact = new \XeroPHP\Models\Accounting\Contact($xero);

$contact->setContactID($contact_info['xero-guid'])
->setClean() //Indicates that it's not trying to create it. 
->setName($contact_info['name'])
->setFirstName($contact_info['firstName'])
->setLastName($contact_info['lastName'])
->setEmailAddress($contact_info['emailAddress'])
->setContactNumber(strtoupper($contact_info['id']));

$contact->save();
```

Maybe the `->setGUID()` method should do this for you, since you can never choose the GUID...

**Comment by itokallad** [comment]
Can we  update/delete the existing bank accounts of the employee without creating a new bank account?
