### ISSUE TITLE
Online Invoice URL is finally here!

### ISSUE THREAD

**Issue by andy1547** [calcinai/xero-php#173]
https://developer.xero.com/documentation/api/invoices/#onlineinvoice

This seems to be added as a quick hack by Xero as it has its own endpoint URL instead of being an Invoice attribute as you may expect, I'm hoping this won't be an issue with the auto generator scrubber? :/

**Comment by calcinai** [comment]
Nah, should be easy enough!

**Comment by andy1547** [comment]
I ran the auto-generator and it was unable to pick this up :/
We need this functionality in our app, I'm trying to restrain from adding the model manually but I'm not sure how I'd change the scrubber to pick this up...
Any ideas?

**Comment by calcinai** [comment]
I'm still slowly working through the new schema parser, but that's no use to you at this point.

I'd imagine it'll be presented as an sub object in an array - `$invoice->getOnlineInvoices()`, so if you can work from that, in the interim, that's probably best.  Why it needs to be another endpoint I have no idea!

I think the best forward compatible way to handle it would be to create a OnlineInvoice model with those parameters, then link it to the invoice in the same way as LineItems.

Alternatively, how about a manual request:

```php
$url = new URL($xero, sprintf('%s/%s/OnlineInvoice', Invoice::getResourceURI(), [GUID]));
$request = new Request($xero, $url);
$request->send();

$online_invoices = $request->getResponse()->getElements();

foreach($online_invoices as $invoice){
    var_dump($invoice['OnlineInvoiceUrl']);
}
```

At least the above will always work..

**Comment by TakesTheBiscuit** [comment]
If you're using the wrapper from @amochohan 
https://github.com/amochohan/xerolaravel/issues/12
