### ISSUE TITLE
Date set to previous day

### ISSUE THREAD

**Issue by nfauchelle** [calcinai/xero-php#177]
I've just noticed some odd behaviour.

In our app, for our invoice we just store the date of the invoice in the database with no time. When we build the invoice, the data object gets built and because there is no time it's set to 00:00:00.

When this is pushed to Xero for a new invoice the date gets set to the previous day.

The server has the PHP timezone set to Pacific/Auckland.
The Xero account is set to use NZ timezone also.

Looking in the code at the **Object.php** -> **castToString** function, the ```format('c')``` result looks fine with +12 as expected, but it seems Xero will convert to UTC and then just store that YYYY-MM-DD.

If I change the ```format('c')``` to ```format('Y-m-d')``` as mentioned in the docs 
https://developer.xero.com/documentation/advanced-docs/dates-and-timestamps-explained/
then it seems to work fine, even with the Pacific/Auckland timezone.

**Comment by calcinai** [comment]
Is this for the `Date` property? This might be as simple as just splitting out the dates vs timestamps.  To a degree, this is already being done.

As we speak, I've almost finished the new doc parser and code generator, so this whole process is going to be made a lot easier.

**Comment by nfauchelle** [comment]
Yes sorry, I should of been a bit more explicit.
:)

**Comment by calcinai** [comment]
Hey, can you checkout the issue-177 branch and see if it corrects your issue?

**Comment by calcinai** [comment]
Fixed in #188
