### ISSUE TITLE
Contact->getContactGroups() returns an empty array

### ISSUE THREAD

**Issue by alexkb** [calcinai/xero-php#180]
I'm loading my contacts like so:

    $xero = new PrivateApplication($config);
    $contacts = $xero->load('Accounting\\Contact')->execute();

My contacts return as expected but when I call `$contacts[0]->getContactGroups()` I get an empty array back,  even though the contacts have been assigned a group (double checked through the Xero UI). 

I know I can do another `load()` call on 'Accounting\\ContactGroup' and then use `getContacts()` but that requires a lot more heavy lifting,

Am I doing something wrong?

**Comment by calcinai** [comment]
I think this just comes down to the lazy loading not being fully implemented. This will be fixed in 2.0. 

In the interim, see what you can make the API previewer return - if that's actually returning the contact groups, it should be working.

**Comment by alexkb** [comment]
Thanks for the prompt reply @calcinai. I just re-read the sourcecode on the ContactGroup model:

    /**
     * The ContactID and Name of Contacts in a contact group. Returned on GETs when the ContactGroupID is
     * supplied in the URL.
     *
     * @property Contact[] Contacts
     */

So it looks like you can't get them all unless you specifically query a group like so `$xero->loadByGUID('Accounting\\ContactGroup', '####');`, which kinda sucks, but I think it's the Xero API that's the issue, not your library, as the same thing happens in the Previewer as you suggested trying.

**Comment by calcinai** [comment]
I might have to leave this one until the next version if that's ok?

**Comment by alexkb** [comment]
Hey @calcinai, I wouldn't worry - like I said, it's the Xero side, not this library. I wouldn't want your library doing subsequent calls to the Xero side to get this data, given the API limit 1000 req/per 24h. Thanks again for the prompt reply.
