### ISSUE TITLE
TaxRate CanApply properties always return 0

### ISSUE THREAD

**Issue by richardcbrief** [calcinai/xero-php#182]
e.g. CanApplyToAssets, CanApplyToEquity etc.

I suspect this is due to these properties having their PHP Type element assigned as PROPERTY_TYPE_FLOAT in the TaxRate getProperties() method. The XeroPHP\Remote\Object castFromString is converting 'true' to 0 for PROPERTY_TYPE_FLOAT

Otherwise, thanks for a great library!

**Comment by calcinai** [comment]
Yeah, looks like you're right. Will put in a fix asap.
