### ISSUE TITLE
Contact - TrackingCategory properties incorrect

### ISSUE THREAD

**Issue by Sixfifty** [calcinai/xero-php#185]
I'm encountering an issue when loading contacts that have a SalesTrackingCategory. It is not loading the properties on the TrackingCategory correctly, it seems that Xero might have changed the properties they are returning.

This issue is currently causing Invoicing to fail for me. I have a small fix which appears to work.

I added these two items to the array in the `getProperties()` function in `Accounting\TrackingCategory` and it has solved the issue for me:

`'TrackingCategoryName' => array (false, self::PROPERTY_TYPE_STRING, null, false, false),`
`'TrackingOptionName' => array (false, self::PROPERTY_TYPE_STRING, null, false, false),`

Is this the best way to fix this issue? If it is then how can I create a pull request?

This is my first bug report, let me know if I can improve on my reporting as well.

**Comment by calcinai** [comment]
There is very little in the documentation regarding the use of tracking categories.  Can you please attach some example XML?

**Comment by Sixfifty** [comment]
Here is a text file containing the full XML, I have removed personal details.

[SampleContact.txt](https://github.com/calcinai/xero-php/files/427023/SampleContact.txt)

The key part is this:
```
      <SalesTrackingCategories>
        <SalesTrackingCategory>
          <TrackingCategoryName>Clients</TrackingCategoryName>
          <TrackingOptionName>Saunderson</TrackingOptionName>
        </SalesTrackingCategory>
      </SalesTrackingCategories>
```

**Comment by Sixfifty** [comment]
Ah, I see what you mean by scraping their API documentation now.

Their API does not match what they are sending back to me:

https://developer.xero.com/documentation/api/tracking-categories/

I'll drop Xero a line with this as well. I have a bug report open with them regarding an issue that was caused by this.

**Comment by Sixfifty** [comment]
Xero have now updated their documentation on this page to show the change:

https://developer.xero.com/documentation/api/contacts/#title14

The don't appear to have updated the page for tracking categories. Worth me chasing them about that?

**Comment by calcinai** [comment]
Great! If you can that'd be good - it's in their interests to have accurate docs!

**Comment by Sixfifty** [comment]
Message sent, let's see if they update it.

**Comment by Sixfifty** [comment]
Fantastic! I'll give that a try when I get back onto the project in a few days.

Thanks for helping!

**Comment by calcinai** [comment]
All I had to do was type `generator/generate` and commit the code.  You and Xero did all the work!

**Comment by 00dani** [comment]
Unfortunately this doesn't fix the issue. I just upgraded the package to ae43b44 in our project, and the same thing's happening: the category and option names are thrown away when XeroPHP parses the response, so when you try to save anything using that contact it fails.

It can be fixed quite easily by adding the two lines @Sixfifty mentioned in the original description to the `Accounting\TrackingCategory` model. Can the generator be convinced to add those lines, or is there a better place to add support for these tags?

**Comment by calcinai** [comment]
I see the issue here - the fix actually added those properties to the `Contact` model, when they need to be attached to the `TrackingCategory` one.  I'll see if I can sort that out.

**Comment by calcinai** [comment]
It seems that Xero have actually added the wrong documentation, the properties don't even exist where they say they do, and the ones that do have different names.

The issue is that sometimes the `Tracking Category` object has a property `Name` and the other time it's `TrackingCategoryName`.  To me, this looks like `SalesTrackingCategories` and `PurchaseTrackingCategories` don't actually accept a `SalesTrackingCategory` object.

What should happen here?

**Comment by Sixfifty** [comment]
You are correct, it doesn't look like it is returning the object we expect. Instead it's just returning a mini-object with two values.

I have been chasing Xero to get their documentation updated because I discovered that it wasn't working correctly as well.

In the meantime I have been using my own little fork with the two lines above to keep my client happy but I wouldn't recommend anyone else use it.

**Comment by gitstashgithub** [comment]
Hi guys I have the same issue, and the fix @Sixfifty provided does solve the it. This thread was created last year so I am not sure Xero's document has been updated or not. Can you merge the fix to the next release, or there's a problem with this fix? Thanks.

**Comment by Sixfifty** [comment]
The Xero documentation is still incorrect and they don't seem to be interested in updating. I'm temporarily running on my branch of this code with the fix.
