### ISSUE TITLE
Load CreditNote = "Curl Error: Empty reply from server"

### ISSUE THREAD

**Issue by jwGeorge** [calcinai/xero-php#187]
Hi guys,
Not sure if this is a coincidence, but since Xero moved to AWS (Sunday 4AM AEST) I cannot load Credit Notes from Xero. I get the following uncaught exception.

> ``Fatal error: Uncaught exception 'XeroPHP\Remote\Exception' with message 'Curl error: Empty reply from server' in <removed>/XeroPHP/Remote/Request.php:105 Stack trace: #0 <removed>/XeroPHP/Remote/Query.php(240): XeroPHP\Remote\Request->send() #1 <removed>/helper_functions.php(273): XeroPHP\Remote\Query->execute() #2 <removed>/private.php(185): GetOutstandingCredits() #3 {main} thrown in <removed>/XeroPHP/Remote/Request.php on line 105"

The request is a simple one:

```
$outstanding_credit = $xero->load('Accounting\\CreditNote')
    ->where('RemainingCredit>0')
    ->execute();
```

I've attempted without the condition and same issue.

Any ideas?

**Comment by calcinai** [comment]
Is it still occurring? I know they had a bit of drama immediately following the migration…

**Comment by jwGeorge** [comment]
Yeah still happening... I've had a play around - on one of our organisations it happens 100% of the time, but for the others it works once in a while. I also got a "Temporarily not available" error while i was testing.L

**Comment by calcinai** [comment]
This is very odd - it might be worth emailing them directly? I wonder if their SSL has changed again...

I haven't had any other reports of issues and everything seems fine in my tests.

**Comment by jwGeorge** [comment]
Yeah i've opened a support case with them. They told me they had an issue last night but it doesn't seem to be related. I've emailed them further details and just waiting on a response. 

At this stage it looks like its happening on 2 of my organisations. 

Will keep you posted

**Comment by calcinai** [comment]
Has this come right?

**Comment by jwGeorge** [comment]
No luck yet. Apparently on the Xero side it shows as a successful GET of CreditNotes but I still experience the curl error. What is confusing me is if it was a client side code issue, then why is it only happening on 2 of 6 organisations... with one of those 2 having the issue intermittently.

**Comment by calcinai** [comment]
Ok, are the failing apps hosted in AWS?  I heard some chapter about IPv6 issues internally in EC2 a while back and it could be related? 

Not sure if you know, but Xero moved to AWS last weekend (I think `us-east`), and that maybe what has caused this?  I don't have any of testing, but maybe try adding 
```
CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4
```
to the curl config?

**Comment by jwGeorge** [comment]
It has been happening since they moved to AWS (Sunday 4AM AEST). Tried your suggestion - no luck :/ 

The odd thing is that it's only the GET Credit Notes that is failing - I'm still able to create Credit Notes! I'll try to get something escalated with Xero Support. This really does not seem to be a client side issue.

**Comment by calcinai** [comment]
Any response on this one?

**Comment by calcinai** [comment]
I'd love to know if this is solved!

**Comment by jwGeorge** [comment]
I had to remove the credit note functionality from my scripts so ill add them back tomorrow and test it out.
