### ISSUE TITLE
Allocation Credit Notes to Invoices not working

### ISSUE THREAD

**Issue by tiran133** [calcinai/xero-php#189]
I I tried to allocate a Credit Note to an outstanding invoice. Everything was fine I didn't get an error from XERO but when I check in Xero the credit wasn't allocated. I had a closer look.
What I found is that the CreditNote\Allocation has to be saved directly. 
Here: https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Application.php#L274

Unfortunately, it is not reflected in the property array.
https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Models/Accounting/CreditNote.php#L237

After I changed it to
```
'Allocations' => array (false, self::PROPERTY_TYPE_OBJECT, 'Accounting\\CreditNote\\Allocation', true, true),

```

All was working fine. Would be great if you could push an update and look into it why this flag is false?

BTW Overpayments and Pre-Payments are all working fine.

Have a nice day.
Alex

**Comment by tiran133** [comment]
I just looked at it again and I found the problem. 
The generator doesn't pick up on it because in Xero Docs it's described as 

"For e.g. PUT CreditNotes/{CreditNoteID}/Allocations";

The generator doesn't pick up on {CreditNoteID}

I created a pull request. and made the curly braces optional in the regex that should do the trick

https://github.com/calcinai/xero-php/pull/190

**Comment by calcinai** [comment]
Cheers for sorting that, I've merged and regenerated.

**Comment by futurewebsites** [comment]
I am trying to allocate a credit note to an invoice like so: 

`public function allocateCreditNote($creditNote, $invoice, $amount, $date){

		$xeroCreditNoteAllocation = new Allocation($this->xero);
		$xeroCreditNoteAllocation->setInvoice($this->getInvoice($invoice))
			                     ->setAppliedAmount((float)$amount)
								 ->setDate(\DateTime::createFromFormat('Y-m-d',$date))
								 ->addAssociatedObject('CreditNote', $this->getCreditNote($creditNote->CreditNoteID));

		$xeroCreditNoteAllocation->save();

		return $xeroCreditNoteAllocation;
	}`

Any ideas why this fails?
