### ISSUE TITLE
setIsCustomer

### ISSUE THREAD

**Issue by avishnev** [calcinai/xero-php#192]
I am using $contact->setIsCustomer(true);$contact->save();  sequence. However the newly created contact record is not marked customer in Xero and is not being displayed when Xero UI pulls Contact->Customers from the list.Is that a known issue?

**Comment by calcinai** [comment]
I'm not sure if that's actually a writable field. So the docs say that it is?

**Comment by avishnev** [comment]
setIsCustomer is a setter method.Code states i can provide value. However i think it is updating isProvider  in the record.I say that because i pull the records with APIPreview from Xero and isProvider=true & isCustomer=false where it should be the other way

**Comment by avishnev** [comment]
IsProvider is independent of isCustomer

**Comment by calcinai** [comment]
I've just had a look in the contact model - it states that isCustomer and isSupplier can not be set by PUT/POST, so they need to be removed from the code for clarity. 

This is consistent with the xero documentation.
