### ISSUE TITLE
Selecting Invoice by Country

### ISSUE THREAD

**Issue by olimortimer** [calcinai/xero-php#193]
This isn't an issue, rather a call for assistance.

What I would like to do is only pull back invoices with an address from certain countries. At the moment I'm looping over all invoices, then grabbing the contact by ContactID and checking the address country from there.  However, I'm sure this is very inefficient as I'm hitting the Xero API limits.  Would anyone be able to advise if I'm missing a trick please?  Many thanks!

	$xero = new \XeroPHP\Application\PrivateApplication($this->config());

	// Get our invoices
	$invoices = $xero->load('Accounting\\Invoice')
		->where('Type', \XeroPHP\Models\Accounting\Invoice::INVOICE_TYPE_ACCREC)
		->execute();

	foreach($invoices as $invoice) {

		// Load our contact by our GUID
		$contact = $xero->loadByGUID('Accounting\\Contact', $invoice->Contact->ContactID);

		foreach($contact->Addresses as $address) {

			// Skip excluded countries
			if(in_array($address->Country, $this->exludeCountries()) || $address->Country == '') continue;

			echo $address->Country.'<br>';

		}

	}

**Comment by calcinai** [comment]
I honestly don't know this one. My first thought would be to filter the contacts by country and then load their invoices. Unfortunately I don't think the API allows this. 

Are you creating the contacts programmatically?  Or the invoices? Or anything that can be tracked and stored locally?

**Comment by olimortimer** [comment]
Everything is created on Xero - I just want to run a report to ensure I've coded the VAT correctly on EU / Non-EU customer's invoices.

I've updated it to run through all customers, then grab invoices for the customers I'm interested in instead, and I still hit the limit, but not as much.

**Comment by calcinai** [comment]
Ah I see.  Sorry I can't think of a better solution - I'm going to close this as it's not strictly an issue with the library.  Is that ok?

**Comment by olimortimer** [comment]
Yeah no problem

**Comment by calcinai** [comment]
Whoops
