### ISSUE TITLE
create single and multiple line items for invoice and setting the method to PUT

### ISSUE THREAD

**Issue by iamreb** [calcinai/xero-php#194]
Hi!

I was wondering how can I create a single or multiple line items for invoices.

so far this is what I got:

```php
try{
            $lineitem = new LineItem();
            $lineitem->setAccountCode('200')
            ->setQuantity('5.400')
            ->setDescription('this is awesome test')
            ->setUnitAmount('9900.00');



			$invoice = new Invoice($this->_xi);
			$invoice->setType(Invoice::INVOICE_TYPE_ACCREC)
				->setStatus(Invoice::INVOICE_STATUS_AUTHORISED)
				->setContact('john doe')
				->setDate('2013-05-13T00:00:00')
                ->setDueDate('2018-05-20T00:00:00')
                ->setLineAmountType(Invoice::LINEAMOUNT_TYPE_EXCLUSIVE)
                ->addLineItem($lineitem)
                ->setInvoiceNumber('10')
				->save();

		}catch ( Exception $e ){
			$GLOBALS['log']->fatal('[Xero-createContact]-' . $e->getMessage());
			echo $e->getMessage();
		}
```

The invoice is not created and I'm not sure if I added the line items correctly on this one.

Also according to the available method we can use PUT in accordance with Xero API, so I was wondering how do I set my save that it will use PUT instead of POST as I want to make it so that I can just update an existing entry or create one if it doesn't exist by using only one function

**Comment by calcinai** [comment]
What's the exception that you get?

To add multiple `LineItems`, you just need to repeat exactly what you're doing then call the `->addLineItem()` method again.

You might need to manually create the request if you want to override the method:

```
            $data = array(Invoice::getRootNodeName() => $invoice->toStringArray());
            $url = new URL($xero, Invoice::getResourceURI());
            $request = new Request($xero, $url, Request::METHOD_POST);

            $request->setBody(Helpers::arrayToXML($data))->send();
```

**Comment by iamreb** [comment]
I don't get any exception error which is weird since if there was something wrong it should state it.

So which of these is the correct way for me to set the line items:

```
$lineitem = new LineItem();
            $lineitem->setAccountCode('200')
            ->setQuantity('5.400')
            ->setDescription('this is awesome test')
            ->setUnitAmount('9900.00');

or

$lineitem = new LineItem($this->_xi);
            $lineitem->setAccountCode('200')
            ->setQuantity('5.400')
            ->setDescription('this is awesome test')
            ->setUnitAmount('9900.00');
```

or do I need to add ->save()?

Can I just add this after the ->save() for the invoice?

```
$data = array(Invoice::getRootNodeName() => $invoice->toStringArray());
$url = new URL($xero, Invoice::getResourceURI());
$request = new Request($xero, $url, Request::METHOD_POST);

$request->setBody(Helpers::arrayToXML($data))->send();
```

thank you for the fast reply, this is really troubling for me.

**Comment by calcinai** [comment]
Those error messages tell you what you need to do.

> Catchable fatal error: Argument 1 passed to XeroPHP\Models\Accounting\Invoice::setContact() must be an instance of XeroPHP\Models\Accounting\Contact, string given

means that you need to pass a `Contact` object, but you gave a string

> Catchable fatal error: Argument 1 passed to XeroPHP\Models\Accounting\Invoice::setDate() must implement interface DateTimeInterface, string given

means that you need to pass an object which implements `DateTimeInterface` e.g. `DateTime`, but you gave a string

> Catchable fatal error: Argument 1 passed to XeroPHP\Models\Accounting\Invoice::setDueDate() must implement interface DateTimeInterface, string given

as above.

> Catchable fatal error: Argument 1 passed to XeroPHP\Remote\URL::__construct() must be an instance of XeroPHP\Application, instance of CB\Integrations\Provider\Xero given

means that you need to pass your `$xero` object, but you gave a class from your application..

Not a lot more I can suggest sorry.

**Comment by iamreb** [comment]
I am using this:

```
$cfg = new Configurator();
		$x = new Xero($cfg->config['xero_settings']);	
		$this->_xi = $x->xeroInstance;

try{
            $lineitem = new LineItem($this->_xi);
            $lineitem->setAccountCode('200')
            ->setQuantity('2')
            ->setDescription('this is awesome test')
            ->setUnitAmount('1900.00');

            $lineitem2 = new LineItem($this->_xi);
            $lineitem2->setAccountCode('200')
                ->setQuantity('2')
                ->setDescription('this is awesome test 2')
                ->setUnitAmount('900.00');

            $contact = new Contact($this->_xi);
            $contact->setName("John Doe")
                ->setFirstName("John")
                ->setLastName("Doe")
                ->setEmailAddress("johngwapo@hot.com")
                ->setContactStatus(Contact::CONTACT_STATUS_ACTIVE);



			$invoice = new Invoice($this->_xi);
			$invoice->setType(Invoice::INVOICE_TYPE_ACCREC)
				->setStatus(Invoice::INVOICE_STATUS_AUTHORISED)
				->setContact($contact)
				->setDate(\DateTime::createFromFormat('Y-m-d', "2016-09-09"))
                ->setDueDate(\DateTime::createFromFormat('Y-m-d', "2018-09-23"))
                ->setLineAmountType(Invoice::LINEAMOUNT_TYPE_EXCLUSIVE)
                ->addLineItem($lineitem)
                ->addLineItem($lineitem2)
                ->setInvoiceNumber('15')
                ->save();

            $data = array(Invoice::getRootNodeName() => $invoice->toStringArray());
            $url = new URL($x, Invoice::getResourceURI(), Invoice::getAPIStem());
            $request = new Request($x, $url, Request::METHOD_PUT);
            $request->setBody(Helpers::arrayToXML($data))->send();


		}catch ( Exception $e ){
			$GLOBALS['log']->fatal('[Xero-createContact]-' . $e->getMessage());
			echo $e->getMessage();

		}
```

Can you explain further:

> means that you need to pass your $xero object, but you gave a class from your application..

Thank you, you're a big help already for this I just need to get this to update and everything will be good to go. Or if you have any example for updating then it would be great as well.

**Comment by calcinai** [comment]
Try something like this:

```php
$this->_xi = new PrivateApplication($cfg->config['xero_settings']);
//Or
//$this->_xi = new PublicApplication($cfg->config['xero_settings']);

try {
    $lineitem = new LineItem($this->_xi);
    $lineitem->setAccountCode('200')
        ->setQuantity(2)
        ->setDescription('this is awesome test')
        ->setUnitAmount(1900.00);

    $lineitem2 = new LineItem($this->_xi);
    $lineitem2->setAccountCode('200')
        ->setQuantity(2)
        ->setDescription('this is awesome test 2')
        ->setUnitAmount(900.00);

    $contact = new Contact($this->_xi);
    $contact->setName("John Doe")
        ->setFirstName("John")
        ->setLastName("Doe")
        ->setEmailAddress("johngwapo@hot.com");



    $invoice = new Invoice($this->_xi);
    $invoice->setType(Invoice::INVOICE_TYPE_ACCREC)
        ->setStatus(Invoice::INVOICE_STATUS_AUTHORISED)
        ->setContact($contact)
        ->setDate(\DateTime::createFromFormat('Y-m-d', "2016-09-09"))
        ->setDueDate(\DateTime::createFromFormat('Y-m-d', "2018-09-23"))
        ->setLineAmountType(Invoice::LINEAMOUNT_TYPE_EXCLUSIVE)
        ->addLineItem($lineitem)
        ->addLineItem($lineitem2)
        ->setInvoiceNumber('15');

    $data = array(Invoice::getRootNodeName() => $invoice->toStringArray());
    $url = new URL($this->_xi, Invoice::getResourceURI(), Invoice::getAPIStem());
    $request = new Request($this->_xi, $url, Request::METHOD_PUT);
    $request->setBody(Helpers::arrayToXML($data))->send();

} catch ( Exception $e ){
    $GLOBALS['log']->fatal('[Xero-createContact]-' . $e->getMessage());
    echo $e->getMessage();
}
```

**Comment by iamreb** [comment]
Tried that and got this errors and notices:

The try catch returned this error:

**Cannot access private key for signing: openssl_pkey_get_private('') returned false**

Notices:

**Notice: Undefined index: rsa_private_key in /var/www/cbcrm/vendor/calcinai/xero-php/src/XeroPHP/Remote/OAuth/SignatureMethod/RSASHA1.php**
**Undefined index: consumer_secret in /var/www/cbcrm/vendor/calcinai/xero-php/src/XeroPHP/Remote/OAuth/Client.php** 
**Notice: Undefined index: oauth in /var/www/cbcrm/vendor/calcinai/xero-php/src/XeroPHP/Application/PrivateApplication.php**
**Notice: Undefined index: consumer_key in /var/www/cbcrm/vendor/calcinai/xero-php/src/XeroPHP/Remote/OAuth/Client.php**

I'm sorry for asking this much, I'm not that used to OOP.

Thank you so much for the help, It is greatly appreciated.

**Comment by calcinai** [comment]
Ok, it looks like your config isn't correct.  Refer to the examples directory in the repo.

**Comment by iamreb** [comment]
I changed my config to this and added this to the file:

```
$cfg = new Configurator();
        $rsaPath = realpath(dirname(__FILE__)) . '/certs/xero/privatekey.pem';
        $caPath = realpath(dirname(__FILE__)) . '/certs/xero/ca-bundle.crt';
        $config = array(
            'oauth' => array(
                'callback' => $cfg->config['xero_settings']['callbackUrl'],
                'consumer_key' => $cfg->config['xero_settings']['consumerKey'],
                'consumer_secret' => $cfg->config['xero_settings']['consumerSecret'],
                'rsa_private_key' => 'file://' . $rsaPath,
            ),
            'curl' => array(
                CURLOPT_CAINFO => $caPath,
            ),
        );

        $this->_xi = new PrivateApplication($config);
```

But I got this error now:

**Cannot access private key for signing: openssl_pkey_get_private('file:///var/www/test/custom/modules/AOS_Invoices/certs/xero/privatekey.pem') returned false**

**Comment by mayankvadiya** [comment]
Hello @calcinai 
I have same flow as above but my lineitmes are dynamic, so how can I all lineitems into invoice ?

**Comment by calcinai** [comment]
@mayankvadiya I'm guessing you'll need to use a loop

**Comment by mayankvadiya** [comment]
Thanks @calcinai 
How can I create invoice with `PAID` payment ?
Here I will try to make something like below.

```
$account =  new  Account();
		$invoices_raw = $xero->load('Accounting\\Invoice')->where('Status', 'AUTHORISED')->execute();
		$invoices = array();
		foreach ($invoices_raw as $k=> $invoiceData) {
    		$invoice = $invoiceData->toStringArray();
    		$payment = new Payment($xero);
    		$payment->setAccount($account)->setInvoice($invoices_raw[$k])->setAmount($invoice['AmountDue']);
			$payment->save();
		}
```

I doing from reference of [this ](https://developer.xero.com/documentation/api/invoices#status-codes) 
 link.
But I am getting error _**You must specify and Account code or Account ID for the paymentYou must specify and Account code or Account ID for the payment**_

So how can I resolve this or create paid invoice  ?

**Comment by calcinai** [comment]
I am completely lost as to what you're trying to do here..

Are you setting an **Account code** or **Account ID**?

**Comment by mayankvadiya** [comment]
@calcinai   Here I am trying to make invoice with `PAID` status, I have synced all invoices but they synced with `Awaiting Payment` status. So I created new function where all invoices make due payment  so status will change `Awaiting Payment` to  `PAID` .

**Comment by calcinai** [comment]
@mayankvadiya See above comment
