### ISSUE TITLE
Adding address to the invoice

### ISSUE THREAD

**Issue by iamreb** [calcinai/xero-php#195]
How can I add address to my invoice I already tried this:

```
$address = new Accounting\Address($this->_xi);
            $address->setAddressLine1("test")
                    ->setAddressType("STREET")
                    ->setAddressLine2("test 2")
                    ->setCity("test")
                    ->setRegion("test")
                    ->setPostalCode("5656")
                    ->setCountry("Mars")
                    ->save();
```

there is not set or add address for the invoice

**Comment by calcinai** [comment]
The address needs to be associated with the `Contact`, then the `Contact` with the `Invoice`

I will add an example for this if you get stuck.

**Comment by iamreb** [comment]
An example would be great. Thank you. I can already associate my contact to my invoice so all that's left is the address.

**Comment by calcinai** [comment]
```php
$contact->addAddress($address);
$invoice->setContact($contact);
```

You don't need to save the address object if you add it to a `Contact`.
