### ISSUE TITLE
Get invoices after a certain date?

### ISSUE THREAD

**Issue by devonmather** [calcinai/xero-php#196]
I'm trying to load invoices after a certain date, and having trouble mapping the syntax given in the Xero Documentation to what is used here. If anyone could shed some light on how to query it properly that would be awesome. 

```
$invoices = $xero->load('Accounting\\Invoice')
    ->where('Contact.ContactID', $centre->xero_contact_id)
    ->where('Date >= "'. date('Y-m-d H:i:s', $billingDuration) .'"');
    ->execute();
print_r($invoices);
```

Thanks,
Devon Mather

**Comment by calcinai** [comment]
What's the error you're getting from Xero on this one?

**Comment by devonmather** [comment]
Ok, your where statement looks to work perfectly, thanks for the quick response!

**Comment by calcinai** [comment]
Cool
