### ISSUE TITLE
setCurrencyCode not supported in Account model

### ISSUE THREAD

**Issue by williamrenfrew** [calcinai/xero-php#197]
setCurrencyCode when creating a Bank account isn't supported. I have run a test using the App previewer and the Xero API does accept it, so would suggest just needs adding to this library.

**Comment by calcinai** [comment]
Does it look like CurrencyCode is properly documented in the docs?

**Comment by williamrenfrew** [comment]
It lists it within Elements for Accounts. The PUT example is very basic mind you and by its own admission shows an example with only the minimum requirements.

**Comment by williamrenfrew** [comment]
Ok - scrap that, I see what you're saying and yes, the docs are wrong, as it says it's only returned on a GET request. I'll contact Xero and see if they'll update it as having tested with the Previewer, it does accept it.

**Comment by williamrenfrew** [comment]
Documentation has been updated: https://developer.xero.com/documentation/api/accounts/

**Comment by calcinai** [comment]
Cool.  I guess at least this library is a nice way to ensure their documentation is correct!
