### ISSUE TITLE
Xero tracked inventory

### ISSUE THREAD

**Issue by iamreb** [calcinai/xero-php#198]
I'm trying to track the sales of products and was hoping to follow this [http://developer.xero.com/documentation/api-guides/tracked-inventory-in-xero/](url), Will you be able to help on where I can find the necessary functions for this?

I already tried doing this for adding the item code:

```
$item_code = new Item($this->_xi);
                    $item_code->setCode('test1');

                    $line_items_new[$x] = new LineItem($this->_xi);
                    $line_items_new[$x]->setAccountCode('200')
                        ->setQuantity($product_qty[$x])
                        ->setDescription($product_name[$x])
                        ->setItemCode($item_code)
                        ->setTaxAmount($clean_tax_prod)
                        ->setDiscountRate($product_disc)
                        ->setUnitAmount($clean_amount_prod);
                    $invoice->addLineItem($line_items_new[$x]);
```

But the Item code is not reflected on Xero, though I was told that I still need to set the InventoryAssetAccountCode and COGSAccountCode fields in the API.

Which I don't know where do I get those code or do I just randomly assign values for them in my own discretion.

Thank you

**Comment by calcinai** [comment]
I'm not sure exactly how the platform works, but from what I just read, it looks like there are some prerequisites:

>Before you get started you will need to ensure the Xero organisation has the required accounts in its chart of accounts:
>
>* Inventory Asset Account – An asset account of type INVENTORY to track the value of stock on hand.
>* Inventory Adjustment Account – An account to track the value of inventory adjustments.
>* Cost of Goods Sold Account – An expense account to track the cost of goods sold.
>
>You may want to have more than one inventory asset account if you want to distinguish between different stock lines on your balance sheet.

If you've done that, you'll need to 

>Once you know the Inventory Asset Account and Cost of Goods Sold Account you can create the inventory items in Xero (if they haven’t been created yet). See our documentation on the [Items](http://developer.xero.com/documentation/api/items/) endpoint for details how to create and update tracked items.

Once you've done that, it looks like it happens automatically when you assign the corresponding account code.

**Comment by calcinai** [comment]
@iamreb - Has this solved your problem?

**Comment by iamreb** [comment]
@calcinai - I'm still in talk with our accounting on how to proceed with the inventory so for now, I am putting this on the back burner. Thank you for the tip and I still have yet to fully understood the Xero documentation regarding their items as it is very lengthy.

**Comment by calcinai** [comment]
That's ok.

In future, can you please only raise issues for issues with the library, not because you need the documentation explained - I'm not the best person to ask about business rules within Xero, this library is purely a wrapper for functions outlined in their docs.
