### ISSUE TITLE
Why return an array?

### ISSUE THREAD

**Issue by paulsschwarz** [calcinai/xero-php#2]
What is the idea behind a call such as this one `$this->xero->load('Accounting\\Organisation')->execute()` returning an array of Organisations? Is there a better way to structure the query API?

**Comment by calcinai** [comment]
I'm open to suggestions on this. Organisations are really an exceptional case, as there's only one, but every other query could return ```n``` results.  it might be sensible to extend and overload the Organisation model if you want to make the behavior different to the other ones. 

Does that answer your question?

**Comment by paulsschwarz** [comment]
Yeah you're quite right. I keep using Organisation as an example since it's such a simple query to run, but indeed it's an exceptional case.
