### ISSUE TITLE
Incorrect handling of tracking categories throughout

### ISSUE THREAD

**Issue by acoulton** [calcinai/xero-php#205]
This is related to #84 and #185 but on exploring the issue it's actually a bigger problem : tracking categories aren't shown correctly on any models, nor can they be properly assigned or edited. The fix in #179 doesn't resolve this, because it only deals with fixing the node name in the XML when saving, not:

* Correctly mapping the values from incoming XML when loading
* the fact that assigning or accessing a tracking category of an item requires accessing the `Option` parameter (note singular) which is not defined in Accounting/TrackingCategory.

The fundamental issue seems to be that there are (at least) three ways tracking categories appear in the Xero API - and unlike pretty much everything else, the versions that appear embedded in other entities (eg a BankTransaction\LineItem) are actually totally different models to the ones that appear standalone in the TrackingCategories collection, rather than being just cut-down versions with only some properties populated (as when for example an account or contact is embedded).

The three variations I've found are:

* The `<TrackingCategories><TrackingCategory>` structure returned from GET TrackingCategories - this is the one currently modelled in the php `TrackingCategory` class. Its properties are `TrackingCategoryID`, `Name`, `Status`, `Options`.
* The `<SalesTrackingCategories><SalesTrackingCategory>` and `<PurchaseTrackingCategories><PurchaseTrackingCategory>` structures in a Contact (also mentioned in #185) - these carry only the `TrackingCategoryName` and `TrackingCategoryOptionName` properties
* The `<Tracking><TrackingCategory>` structure embedded in line items on bank transactions, invoices, journals etc. These have `TrackingCategoryID`, `OptionID`, `Name` and `Option`.

Currently all of these properties are being defined as instances of `Accounting\TrackingCategory`, but as you can see they actually have very different property lists.

 In fact, they should probably be more like:

* Accounting\TrackingCategory for the GET TrackingCategories
* Accounting\DefaultTrackingAllocation for the Contact
* Accounting\TrackingCategoryAllocation for the various transaction objects

I think it will be difficult to parse the actual definitions of the latter two from the docs at the moment, but I have worked out how I could manually define their metadata for the generator, and update the generator so that it detects the correct property types.

This would produce breaking changes (methods like `setTracking` will now require a `TrackingCategoryAllocation` instead of a `TrackingCategory`) but only at the PHP level : currently none of this is actually showing the expected data or producing expected results on Xero - it may be acceptable if people who are using it without realising get errors that force them to fix their local implementations?

If you think this is a reasonable approach, I can put together a pull request for review.

**Comment by calcinai** [comment]
I'm a little concerned about introducing breaking changes - I found out the hard way last week that there were people using functions that actually did nothing and then started getting fatals when I removed them.

Re: the `TrackingCategory` types - I'm migrating the scraping part of this project to [xero-schemas](https://github.com/calcinai/xero-schemas), and have a pattern in place (dev) for overriding any unparsable properties/models.  That'll leave this project free to generate from a consistent set of schemas from `2.0`.  It's turned into a bit more work that I had hoped!

**Comment by davidwindell** [comment]
Realise you are working on this for v2 but heads up that Xero recently sent the email below to one of our customers that was having a problem with our app applying the category to invoice line items. 

```
The problem is most likely with how your app is sending the tracking information. It looks like the app is using the format used when creating tracking categories as opposed to the format to apply them to a line item of an invoice. The format should be:

 <Tracking>
    <TrackingCategory>
        <Name>category name</Name>
        <Option>option name</Option>
    </TrackingCategory>
</Tracking>

You can see an example of this in our Developer Center which I've linked to below. You or the module developers will need to upgrade the integration to send the information in the correct format.

Xero Developer Center: https://developer.xero.com/documentation/api/invoices#get
```

We will hack around this for now my directly modifying the output.

**Comment by calcinai** [comment]
Ah yes - basically all of the issues with tracking stem from this I think.  The documentation website has very recently been updated which has broken the current schema generators, so that might allow a bit more information to differentiate between the creating of and using of.

Do the [xero-schemas](https://github.com/calcinai/xero-schemas) look right to you?

**Comment by davidwindell** [comment]
Nope, the schemas don't like correct as they refer to the core `TrackingCategories` definition which includes the `Options` key for multiple option names whereas the LineItems can only have one `Option` key (see above).

**Comment by direvus** [comment]
To be clear, the Xero docs *do not* actually define the API for applying tracking categories to items, at least not anywhere that I can find.

You can see how to do it in the example XML, but under e.g. Invoices / LineItems / Tracking, it just says "Optional Tracking Category - see Tracking. Any LineItem can have a maximum of 2 TrackingCategory elements", and if you follow the link to "Tracking" what you get is the format for creating/viewing categories, not how to apply them to invoices.

It is deeply unfortunate that the API re-uses the same element name `<TrackingCategory>` to do two different jobs.  Somebody at Xero had too few (or too many) coffees that day.

It may be possible to get Xero to add this to their docs, but unless/until that happens, I don't think you can get a working solution purely by scraping the documentation.  It might be necessary to manually overlay some additional object definitions on top of the auto-scraped stuff.

I think @acoulton had the right idea about adding new model classes for the contact-default and item-tracking cases.  I would call the latter object `ItemTracking` rather than `TrackingCategoryAllocation`, but obviously the name is less important than the function.

**Comment by calcinai** [comment]
Ok, well then I think these can just be make manually for this branch, and then if we add overrides to the new schema gen [here](https://github.com/calcinai/xero-schemas/blob/master/bin/generate#L103)  (for lack of a better place for now), it'll roll in to the 2.x branch.

Part of me thinks we should be less reliant on the docs, but I've lost count of how many little updates have happened automagically when they add a new property/remove a property/change a type/add a description etc.

**Comment by calcinai** [comment]
FYI, I've made a little change for this in 82382db, so they can at least be read.

This all needs to be fixed properly!

**Comment by direvus** [comment]
Thanks for the update on the read side @calcinai.

Any further thoughts on what a proper fix would look like?  On the read side, I suppose that you would need to react differently to a `<TrackingCategory>` element depending on what its parent element is.  On the write side, I don't see any decent alternative to manually writing up a few special class definitions that get overlaid on the auto-scraped definitions.

If we can settle on a rough concept for the fix, I'd be happy to go ahead and write up a PR for you, if you would find that helpful.  I recognise that vetting contributions isn't always a time-saver, but the offer is open.

**Comment by calcinai** [comment]
This should now be resolved
