### ISSUE TITLE
\XeroPHP\Remote\Object->toStringArray not working for report rows

### ISSUE THREAD

**Issue by c-m-hunt** [calcinai/xero-php#206]
When returning a report, for whatever reason, the `static::getProperties()` of the report Rows property returns a type of `string` and therefore the output gets returned as an empty string.

As a quick and dirty fix, adding in at https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/Object.php#L271
```
                if ($value instanceof \stdClass) {
                    return (array)$value;
                }
```
solves the issue but doesn't seem ideal.

I can try and find a better solution and raise a pull request or can leave it with you?

Cheers

Chris

**Comment by calcinai** [comment]
Hey @c-m-hunt, I've never used the reports models so am not sure what implications there might be in changing it, but I do know that they are not generated models, so it's probably ok to just change the properties array to reflect the correct data type.

Do you know if this fixes the issue?

**Comment by c-m-hunt** [comment]
The Rows property on the Report object returns a collection of \stdClass (which can be converted to an array just fine). Changing the property type to object and type \stdClass means that the `Object->castFromString` method fails when trying to create an instance.

Slight amend to the above works and I don't think breaks stuff but there's no specific tests to run against....
Amend https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Models/Accounting/Report/Report.php#L109 to
```            'Rows' => array (true, self::PROPERTY_TYPE_OBJECT, '\\stdClass', true, false),```

Insert at https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/Object.php#L265
```                if (is_array($value)) {                    
                    return (array)$value;
                }```

Insert at https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/Object.php#L312
```                if ($php_type == '\\stdClass') {
                    return (array)$value;
                }```

Assumption is (I think) that \stdClass are not ever built and sent back to the server. I don't know Xero well enough really to confirm.

**Comment by calcinai** [comment]
Ugh.  What an annoying issue - maybe we just go with plan A?

**Comment by c-m-hunt** [comment]
That works fine with me :-) Thank you

**Comment by gurubobnz** [comment]
Hi team (@c-m-hunt, @calcinai) can you clarify what you mean here by going with plan A? I see this is still an issue in the latest release.
