### ISSUE TITLE
Fetch Online Invoice URL

### ISSUE THREAD

**Issue by woganmay** [calcinai/xero-php#210]
Loving this library! It's saved me a ton of time already :)

Is there any chance that this method could be added? https://developer.xero.com/documentation/api/invoices/#onlineinvoice

Something like `$invoice->getOnlineUrl()`?

**Comment by calcinai** [comment]
It exists as a workaround already as at #173 - this almost has a perminant solution!

**Comment by woganmay** [comment]
Excellent, thanks @calcinai - I was just busy picking apart the Remote class to figure out how to do that :)
