### ISSUE TITLE
How to use orderBy

### ISSUE THREAD

**Issue by sn0rcha** [calcinai/xero-php#211]
Hey there,

Just a quick question, I can't seem to figure out how to use the "orderBy" when loading resources.

If I do:

```$xero->load('Accounting\\Contact')->orderBy('Name', 'asc')->execute();```

It errors with:

```Uncaught Error: Call to a member function execute() on null ```

This works however:

```$xero->load('Accounting\\Contact')->execute();```

Am I doing it wrong? I couldn't find an example in the documentation or code.

Cheers,
Ben

**Comment by calcinai** [comment]
Hey, I can't seem to replicate this.  Based on the error, it looks like you're somehow getting null back from the `->orderBy()`, but I don't see how this is happing since there's an implicit `return $this;`
