### ISSUE TITLE
Attachment -> Include Online invoice

### ISSUE THREAD

**Issue by stephenc01** [calcinai/xero-php#212]
Please add the option to include attachments with online invoice.
https://developer.xero.com/documentation/api/attachments/

The xml would be similar to 
If you have set IncludeOnline to true, the element will be returned in the response message:
`
<Response>
  <Attachments>
    <Attachment>
      <AttachmentID>e59a2c7f-1306-4078-a0f3-73537afcbba9</AttachmentID>
      <FileName>Image00394.png</FileName>
      <Url>http://api.xero.com/api.xro/2.0/</Url>
      <MimeType>image/png</MimeType>
      <ContentLength>10294</ContentLength>
      <IncludeOnline>true<IncludeOnline>
    </Attachment>
  </Attachments>
</Response>
`

**Comment by calcinai** [comment]
Hey @stephenc01 - I'm not completely sure what you're asking - is this over and above the `->getAttachments()` method ion the invoice?

**Comment by stephenc01** [comment]
When uploading an attachment to an invoice there are 2 options. With the api you have to add "IncludeOnline=true" to include the attachment when the invoice is viewed online.


<img width="406" alt="screen shot 2016-11-25 at 9 23 57 am" src="https://cloud.githubusercontent.com/assets/4701543/20627884/f0eebe8a-b2f0-11e6-8c4d-e9be8ffaf332.png">

**Comment by calcinai** [comment]
Ah right, had no idea this even existed.  You're welcome to submit a PR for this - I imagine the best approach would be an extra argument on `->addAttachment()` in the `AttachmentTrait`.  Otherwise I'll have to have a look at it next week sorry.

**Comment by calcinai** [comment]
Actually, this will be super quick - I'll do it now.

**Comment by calcinai** [comment]
#213 look ok to you?

**Comment by stephenc01** [comment]
It looks good, ill be able to test today and im working on that part of my code.

**Comment by stephenc01** [comment]
I've tested the change and it works.

<img width="487" alt="screen shot 2016-11-25 at 11 57 41 am" src="https://cloud.githubusercontent.com/assets/4701543/20631759/71be5c04-b306-11e6-80db-ad2bbe8ad661.png">
<img width="408" alt="screen shot 2016-11-25 at 11 57 31 am" src="https://cloud.githubusercontent.com/assets/4701543/20631758/71be4408-b306-11e6-915c-18d96d1dc5aa.png">
