### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by lfcsupporter** [calcinai/xero-php#214]
Hi 

Thanks for the great work.

I just wanted to know if there is way to get the Reports information? I don't see it as one of the modules or maybe I am not looking properly?

Thanks.

**Comment by lfcsupporter** [comment]
Hi 

Sorry, I did manage to find the Reports but it only has BalanceSheet and ProfitLoss. I added BankSummary, which works but the fromDate and toDate is not refining the search. The summary is done for the whole month?

**Comment by calcinai** [comment]
Hey, I'm not sure about that specific functionality - are you able to get the correct result using the API previewer?

**Comment by lfcsupporter** [comment]
Hi

Yes, I do get the correct results with the API previewer. I also tried the ProfitLoss Module and it seems the fromDate and toDate does not get set.

`
$xero->load('Accounting\\Report\\ProfitLoss')->where('fromDate', '2016-12-01')->where('toDate', '2016-12-07')->execute();

### In Dev Tools:
[parameters:XeroPHP\Remote\Request:private] => Array
    (
        [where] => fromDate=="2016-12-01" AND toDate=="2016-12-07"
    )

[fromDate] => 
[toDate] => 
[UpdatedDateUTC] => DateTime Object
`

### The response I receive from the above code:
<ReportTitle>Profit &amp; Loss</ReportTitle>
<ReportTitle>Demo Company (Global)</ReportTitle>
<ReportTitle>1 December 2016 to 31 December 2016</ReportTitle>
<ReportDate>12 December 2016</ReportDate>
<UpdatedDateUTC>2016-12-12T20:08:42.6878455Z</UpdatedDateUTC>


### Response from the API Previewer:
<ReportTitle>Profit &amp; Loss</ReportTitle>
<ReportTitle>Demo Company (Global)</ReportTitle>
<ReportTitle>1 December 2016 to 7 December 2016</ReportTitle>
<ReportDate>12 December 2016</ReportDate>
<UpdatedDateUTC>2016-12-12T20:05:25.1386952Z</UpdatedDateUTC>

**Comment by calcinai** [comment]
Ah, Ive just had a look at the developer docs and it looks like the dates can't be used as a where clause - you just need to use `->fromDate()` and `->toDate()` on the query object..

**Comment by lfcsupporter** [comment]
Hi 

Thanks so much.

Again, really great work. Saved me so much time and stopped the urge to pull out my hair :-D.
