### ISSUE TITLE
Allow forcing PUT vs POST

### ISSUE THREAD

**Issue by davidwindell** [calcinai/xero-php#217]
This is somewhat in relation to the comment [here](https://github.com/calcinai/xero-php/pull/24#commitcomment-12218899)

We need to use `POST` for our saveAll() on the Contacts endpoint but instead of the GUID we are relying on Xero's matching against ContactNumber. The same goes for Invoices.

At the moment, we have had to overwrite the saveAll() function as it forces PUT in the absense of a GUID.

Would there be any opposition to adding a flag to saveAll() to allow this? i.e.

```
public funcition saveAll($objects, $checkGuid = true)
{
...
```

I'm happy to raise a PR if there is consensus

**Comment by Dhruv-Jauhar** [comment]
Tell we reach a consensus, could you explain how did you force a POST? I am having issues for updating contacts.

**Comment by wbercx** [comment]
Ran into this issue a few moments ago when trying to batch insert Timesheets. The Timesheets API only has `GET` and `POST` endpoints, but `saveAll()` is assuming the new timesheets should go to the non-existent `PUT` endpoint instead.

Flag sounds great.

**Comment by calcinai** [comment]
@davidwindell Still got time to have a look at this?

**Comment by davidwindell** [comment]
@calcinai Yep, happy to do this with your blessing but just heading off for a two week holiday. If not done in my absence will do on return.
