### ISSUE TITLE
Missing AppliedAmount on OverPayments, PrePayments and CreditNotes

### ISSUE THREAD

**Issue by davidwindell** [calcinai/xero-php#220]
When Xero returns an invoice, the associated OverPayments. PrePayments and CreditNotes have a field `AppliedAmount` which refers to how much of the payment has been applied to the invoice retrieved.

For some reason Xero doesn't return the Allocations with these entities when retrieving an invoice either so this field isn't in the usual place.

I've hacked this in for now https://github.com/calcinai/xero-php/compare/master...outeredge:allocation-patch but without this field being documented I'm unsure how to add this to the generator?

**Comment by calcinai** [comment]
@davidwindell I think it's the end for the current generator.  Xero look like they're going o start maintaining a set of definitive schemas that we can generate from.  If you can hang on for a bit I'l try and get 2.0 out the door!

**Comment by davidwindell** [comment]
Great, thanks @calcinai, feel free to close the issue for nor
