### ISSUE TITLE
includeArchived unavailable

### ISSUE THREAD

**Issue by williamrenfrew** [calcinai/xero-php#222]
Hi,

When doing a GET against the Contacts endpoint, we want to be able to use the includeArchived=true parameter however it appears unsupported.

There was a PR 18 months ago that hasn't been touched for nearly a year (https://github.com/calcinai/xero-php/pull/52). Is there any known workaround in the current version?

Thanks!

**Comment by mhlavac** [comment]
@williamrenfrew my fault. I put too much code in #52. I planned to update it, but then we were done with our Xero integration and moved on other things.

I might have a time this week to propose a new PR with a fix for this. If someone doesn't beat me to it :-)

**Comment by calcinai** [comment]
Sorry guys! This is my fault too.

For some reason I thought this was already implemented - it appears not.  What you can still do is a manual query and add the 'includeArchived' parameter to the request.

**Comment by williamrenfrew** [comment]
Hi @calcinai It doesn't seem to work in the ->where() call though, are we breaking out before the normal load()->where() style function and using the connector directly?

**Comment by Josh-G** [comment]
I've provided a minimal pull request to add this.
