### ISSUE TITLE
Version bump needed

### ISSUE THREAD

**Issue by SidneyAllen** [calcinai/xero-php#225]
Hi Michael,

I just downloaded the current version 1.4.1 and it still includes the PartnerApplication.php with the api-partner.network.xero.com URLs defined. 

Any changes you could release 1.4.2 with the changes I submitted?

Thanks!

**Comment by calcinai** [comment]
Hey, there are potentially BC in there so I've released as v1.5.0

I've got a working draft of 2.0 on my local copy, so will also keep you int he loop about that.
