### ISSUE TITLE
Contacts customer/supplier

### ISSUE THREAD

**Issue by karthik1987** [calcinai/xero-php#227]
How can we differentiate the contacts for customer or supplier? the following code not saving the contact as supplier
```
$contact->setName($collection->getData('vendor_name'))
    ->setEmailAddress($collection->getData('email'))
    ->setIsSupplier(true);
$contact->save();
```

**Comment by williamrenfrew** [comment]
You can't set that value (see the comments at https://github.com/calcinai/xero-php/blob/550e50a95023c2982716f592c339c456c5515413/src/XeroPHP/Models/Accounting/Contact.php#L678). Xero will set the isCustomer and isSupplier booleans when an sales ledger item or purchase ledger item is created for that Contact.

**Comment by calcinai** [comment]
As @williamrenfrew said, this is get-only.  The methods will disappear in future versions.
