### ISSUE TITLE
API rate limit

### ISSUE THREAD

**Issue by karthik1987** [calcinai/xero-php#228]
Hi,

I'm getting "The API rate limit for your organisation/application pairing has been exceeded"

I want to import contact and I have 95 contacts with me.. but XERO allow only 60 requests per min.. How can I write the logic for that???.. please see my code below and let me know.
```php
$xero = new \XeroPHP\Application\PrivateApplication($config);
$contact = new \XeroPHP\Models\Accounting\Contact($xero);
$address = new \XeroPHP\Models\Accounting\Address($xero);
$phone = new \XeroPHP\Models\Accounting\Phone($xero);
//Collect the vendor details
$collections = Mage::getModel('udropship/vendor')->getCollection();
foreach($collections as $collection)
{
$id = 'V60000'.$collection->getData('vendor_id');
$vendorName = $collection->getData('vendor_name');
$email 		= $collection->getData('email');
$telephone 	= $collection->getData('telephone');
$vendorAttn = $collection->getData('vendor_attn');
$street 	= $collection->getData('street');
$city 		= $collection->getData('city');
$country_id = $collection->getData('country_id');

$contact->setName($vendorName)
	->setEmailAddress($email)
	->setAccountNumber($id);

$phone->setPhoneType('DEFAULT');
$phone->setPhoneNumber($telephone);

$address->setAddressType('POBOX');
$address->setAddressLine1($street);
$address->setCity($city);
$address->setCountry($country_id);

$contact->addPhone($phone);
$contact->addAddress($address);
$contact->save();
}
```

**Comment by calcinai** [comment]
You should be able to make an array of contacts, then pass it to `$xero->saveAll()`.

**Comment by karthik1987** [comment]
Hi,

I want to add this `$xero->saveAll()` out of the loop?

**Comment by calcinai** [comment]
Yes, you'll need to construct an array of contacts inside the loop, then instead of saving each one, pass the array to `saveAll()`

**Comment by karthik1987** [comment]
Hi,

I have added below code at final instead of save. Is that correct?
`$contacts[] = $contact;
}
$xero->saveAll($contacts);`

**Comment by calcinai** [comment]
Should be fine - have you tested it?

**Comment by karthik1987** [comment]
Yes. I did but only one contact was imported.

**Comment by karthik1987** [comment]
`foreach($collections as $collection)
{
$id = 'V680000'.$collection->getData('vendor_id');
$vendorName = $collection->getData('vendor_name');
$email 		= $collection->getData('email');
$telephone 	= $collection->getData('telephone');
$vendorAttn = $collection->getData('vendor_attn');
$street 	= $collection->getData('street');
$city 		= $collection->getData('city');
$country_id = $collection->getData('country_id');

$contact->setName($vendorName)
	->setEmailAddress($email)
	->setAccountNumber($id);

$phone->setPhoneType('DEFAULT');
$phone->setPhoneNumber($telephone);

$address->setAddressType('POBOX');
$address->setAddressLine1($street);
$address->setCity($city);
$address->setCountry($country_id);

$contact->addPhone($phone);
$contact->addAddress($address);

$contacts[] = $contact;
}
$xero->saveAll($contacts);`

**Comment by calcinai** [comment]
This:
```php
$contact = new \XeroPHP\Models\Accounting\Contact($xero);
$address = new \XeroPHP\Models\Accounting\Address($xero);
$phone = new \XeroPHP\Models\Accounting\Phone($xero);
```

Should all be in the loop

**Comment by karthik1987** [comment]
Great!!.... It's worked... Thanks

**Comment by karthik1987** [comment]
If I trigger the function next time it supposed to be update.. how can I do that?

**Comment by calcinai** [comment]
Best way would be to just update the objects as they change.  You'll need to update your local UUID for each contact after saving.
