### ISSUE TITLE
Account code must be specified

### ISSUE THREAD

**Issue by karthik1987** [calcinai/xero-php#230]
Hi,

I'm getting this error. Please let me know the issue & refer my code below.
`$invoices = $xero->load('Accounting\\Invoice')->where('Type=="' . \XeroPHP\Models\Accounting\Invoice::INVOICE_TYPE_ACCPAY . '"')->execute();
	foreach ($invoices as $invoice) {
		$lineitem = new \XeroPHP\Models\Accounting\Invoice\LineItem($xero);
		$id = $invoice->getInvoiceID();
		$master = $xero->loadByGUID('Accounting\\Invoice', $id);
		$master->setStatus('VOIDED');
		$lineitem->setItemCode($master->LineItems[0]->getItemCode());
		$lineitem->setDescription($master->LineItems[0]->getDescription());
		$lineitem->setUnitAmount($master->LineItems[0]->getUnitAmount());
		$lineitem->setQuantity($master->LineItems[0]->getQuantity());
		$lineitem->setAccountCode(200);
		$master->addLineItem($lineitem);
		$xero->save($master);
	}`

**Comment by karthik1987** [comment]
Hi,

I didn't get answer for this? then why you closed?

Please let me know.

Thanks

**Comment by calcinai** [comment]
Hi @karthik1987, sorry it sounded like you had solved the issue since the resolution was in the title of the issue. You just need to specify the account code and you should be ok.

**Comment by karthik1987** [comment]
Hi,

No problem.. I posted the code with the Account code `$lineitem->setAccountCode(200);`

I don't know why it's not working.

**Comment by karthik1987** [comment]
Any update?

**Comment by calcinai** [comment]
Have you tried passing an `Account` object as per the docs?
