### ISSUE TITLE
Making Payment on Invoice

### ISSUE THREAD

**Issue by kieranheadley** [calcinai/xero-php#233]
I am using the Xero Laravel wrapper (https://github.com/amochohan/xerolaravel) and want to record payments made against an invoice. I can get the invoice but cannot find how to record a payment using the Laravel Wrapper provided;

I have tried a couple of solutions but none seem to work;

```
// Load the Invoice (Working)
$invoice = XeroPrivate::loadByGUID('Accounting\\Invoice', 'RPT445-1');

$payment = \App::make('XeroPayment');
$payment->setInvoice($invoice);
$payment->setDate(Carbon::now());
$payment->setAmount(100);

$xero->save($payment);
```
The above returns the issue

> Class XeroPayment does not exist

I can find the Xero documentation but this doesn't help to how it could translate into Laravel. It may be that the wrapper doesn't have this functionality built in, if so how would I complete using https://github.com/calcinai/xero-php which the wrapper is based on?

**Comment by calcinai** [comment]
Good question! I'm not actually sure on this specific functionality - perhaps @amochohan could shed some light on this?

From what I can see there's a facade for the payment in there..

**Comment by kieranheadley** [comment]
Not had a response from Amo Chohan, how would you complete this using your library?

**Comment by williamrenfrew** [comment]
Here's how we push a payment against a Xero invoice using the xero-php library.
`            $invoice_obj = new \XeroPHP\Models\Accounting\Invoice($xero->getInstance());
            $invoice_obj->setInvoiceID($invoice_guid);

            $newPayment = new \XeroPHP\Models\Accounting\Payment();
            $newPayment
                ->setInvoice($invoice_obj)
                ->setAccount($currency)
                ->setDate($date_time_obj)
                ->setAmount($amount)
                ->setIsReconciled(true)
                ->setReference('Payment '.$payment->reference);
            $posted_payment = $xero->save($newPayment);`

I've toned down some of our values but hopefully this gives you the gist?

**Comment by kieranheadley** [comment]
Thanks for the response, without sounding too stupid, how would you grab the account used in setAccount?

**Comment by kieranheadley** [comment]
That worked perfectly, thank you so much @williamrenfrew

**Comment by calcinai** [comment]
Thanks @williamrenfrew for clarifying that. Maybe it's time for some more docs! as in #86...
