### ISSUE TITLE
getNonce() assumes microtime() will have a decimal part

### ISSUE THREAD

**Issue by Josh-G** [calcinai/xero-php#235]
The getNonce() method in XeroPHP/Remote/OAuth/Client.php assumes that microtime will return a decimal part, and explodes on the decimal point:
https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/OAuth/Client.php#L232

However, it is possible that microtime will land exactly on the second, and no decimal part will be returned.

**Comment by Josh-G** [comment]
Okay, I don't understand why, but this change **has** resulted in
> The nonce value "\<value\>" has already been used

It doesn't occur often. I'm having difficulty verifying whether we are actually re-using nonces or if this is Xero's API being flaky. If it is, then I don't understand how the previous nonce implementation didn't have the same issue.

Any thoughts?

**Comment by calcinai** [comment]
No idea at all.  As I think I said, I never actually encountered this issue - it was someone a long time ago.
