### ISSUE TITLE
Get the Invoice Url (OnlineInvoice)

### ISSUE THREAD

**Issue by cezzre** [calcinai/xero-php#246]
I've been searching a while for this method – which seems to be absent.
I eventually managed to get it working.
I think it is worth to add this method to the Invoice object.

Ref: https://developer.xero.com/documentation/api/invoices#onlineinvoice

```php
private function getInvoiceUrl(\XeroPHP\Models\Accounting\Invoice $invoice)
{
    $url = new \XeroPHP\Remote\URL($this->conn, 'Invoices/' . $invoice->getGUID() . '/OnlineInvoice');
    $request = new \XeroPHP\Remote\Request($this->conn, $url);
    $request->send();

    return $request->getResponse()->getElements()[0]['OnlineInvoiceUrl'];
}
```

`$this->conn`  – which is a property of the class I've created to _talk_ with Xero – is the instance of `PrivateApplication` (in my case).

**Comment by timacdonald** [comment]
@cezzre that pull request to add this feature has been pulled in, so once a new version is out you should be right to close this issue 👍
