### ISSUE TITLE
Files\Folder and Files\File

### ISSUE THREAD

**Issue by calumbrash** [calcinai/xero-php#247]
Having issues with retrieving and creating new files and folders
$folder = $xero->loadByGUID('Files\\Folder', 'f5cecc39-f2e1-4993-ac3d-043da91a8572');
Will always return null even though the folder exists.
When trying to create a new Folder it requires all of its variables as mandatory even though in the API docs all it should require is the Name.

My main issue is with adding a new file. It doesn't seem to have the createFromLocalFile function like Attachment has. What is the work around for this?

**Comment by calcinai** [comment]
I think you're the first person to comment on this.  These models were automatically generated, so it's quite possibly untested.

Do you know where it's failing, i.e. is the ```$xero->load()``` actually constructing the correct query? 

Re: the `File`, I wonder if applying the same logic as `Attachments` here would be enough?

**Comment by calumbrash** [comment]
With the retrieval of loading files it seems to be failing in Response.php where it is looping through the elements line 227
The $xero->load is definitely constructing the correct query (after doing some dumps) just the response is messing up I think...
I'm wondering if it is to do with the returned data not being the same due to the File api using 1.0 rather than 2.0?
I tried using the Attachments logic but had no luck unfortunately.

**Comment by calumbrash** [comment]
Sorry I meant to say "With the retrieval of loading **folders** it..."

**Comment by Aplear** [comment]
Hi! Are there anybody who resolved the problem?
