### ISSUE TITLE
Payment->setStatus('DELETED') validation error

### ISSUE THREAD

**Issue by johnnydee8** [calcinai/xero-php#250]
Thanks for the great work on the project, I find it really useful. 
However, recently I've been trying to change status of existing payment to deleted, and I'm getting the following error message: 
```
XeroPHP\Remote\Exception\BadRequestException: A validation exception occurred (Only Status accepted for updates)
Validation errors:
Only Status accepted for updates.
```
The code I'm trying to execute is: 
```
use XeroPHP\Models\Accounting\Payment as XeroPayment;
...
$payment->setStatus(XeroPayment::PAYMENT_STATUS_DELETED);
$payment->save();
```
Please note that creating a payment and getting it back from api seems to be working just fine. 
Not sure if I'm doing something wrong here or if it's a bug? Spent few hours trying to fix it and researching it online, no luck though.

**Comment by williamrenfrew** [comment]
This is what we do:

`                $xero_payment = new \XeroPHP\Models\Accounting\Payment();
                $xero_payment->setGUID($payment->xero_payment_guid);
                $xero_payment->setStatus(\XeroPHP\Models\Accounting\Payment::PAYMENT_STATUS_DELETED);
                $xero->save($xero_payment);`

**Comment by johnnydee8** [comment]
Thanks for swift reply @williamrenfrew, this solution works great for me! :tada:

**Comment by calcinai** [comment]
That was easy!
