### ISSUE TITLE
What should be the parameter in Contact::setBatchPayment function?

### ISSUE THREAD

**Issue by gitstashgithub** [calcinai/xero-php#254]
Hi guys, I tried to set the BatchPayments for contact but don't know what shouldbe the setBatchPayment() parameter. I tried string and array of items
```
$xeroContact->setBatchPayment('<BankAccountNumber>123456</BankAccountNumber>
        <BankAccountName>bank acccount</BankAccountName>
        <Details>details</Details>');
```
```
$xeroContact->setBatchPayment([
                    "BankAccountNumber" => "123456",
                    "BankAccountName" => "bank acccount",
                    "Details" => "details"
                ]);
```
but neither works.

Can someone let me know how to make it work? Thanks!

**Comment by calcinai** [comment]
From the looks of it, that property is read only, so the getter shouldn't actually exist.  Have you successfully set it using the API previewer?

**Comment by gitstashgithub** [comment]
Do you mean the setter shouldn't exist? You are right I cannot use API previewer to set the BatchPayments either.

**Comment by calcinai** [comment]
Ah yes -  the setter.  I'll deprecate it.
