### ISSUE TITLE
addTracking to Transaction

### ISSUE THREAD

**Issue by mediavariance** [calcinai/xero-php#255]
Hi,
I'm trying to editing a unreconciled transaction, adjust some line items, and set a tracking option on each, but I'm not sure how to accomplish this?

Snippet:
```
$newLineItem = new \XeroPHP\Models\Accounting\BankTransaction\LineItem($xero);
$newLineItem->setDescription($Description);
$newLineItem->setQuantity("1");
$newLineItem->setLineAmount($Amount);
$newLineItem->setUnitAmount($Amount);
$newLineItem->setTaxType("OUTPUT");
$newLineItem->setAccountCode("CHECKDEPO");


// Load Up Existing Category
$categoryItem = $xero->loadByGUID('Accounting\\TrackingCategory', $existingTrackingCategoryID );

// We have a existing option that matches this name, but I'm unable to use loadByGUID to look it up (Resource Not Found)
$categoryOptionItem = (new \XeroPHP\Models\Accounting\TrackingCategory\TrackingOption($xero));
$categoryOptionItem->setName("My Location"); // This method does not exist, but I saw it mentioned on another issue?
$categoryOptionItem->save();

$newLineItem->addTracking($categoryItem->addOption($categoryOptionItem));
$newLineItem->save();
```

Excuse the terrible naming conventions please, was trying to make it easier to read :). Any suggestions on how to set the tracking option correctly?

**Comment by richinnz** [comment]
This may/may not help - It looks the same issue as tracking categories in invoices. The format for tracking categories in these are different from adding/editing tracking categories directly it seems. I changed the Model by hand to review it and its working now.

This is Models/Accounting/TrackingCategory.php
.....
public static function getProperties()
    {
        return [
            //MANUALLY ADDED PROPERTY
            'Option' => [false, self::PROPERTY_TYPE_STRING, null, false, false],
            'TrackingOptionID' => [false, self::PROPERTY_TYPE_STRING, null, false, false],
            
            
            'TrackingCategoryID' => [false, self::PROPERTY_TYPE_STRING, null, false, false],
            'Name' => [false, self::PROPERTY_TYPE_STRING, null, false, false],
            'Status' => [false, self::PROPERTY_TYPE_STRING, null, false, false],
            'Options' => [false, self::PROPERTY_TYPE_OBJECT, 'Accounting\\TrackingCategory\\TrackingOption', true, true]
        ];
    }
    //MANUALLY ADDED FUNCTION
    public function setOption($value)
    {
        $this->propertyUpdated('Option', $value);
        $this->_data['Option'] = $value;
        return $this;
    }
    //MANUALLY ADDED FUNCTION
    public function setTrackingOptionID($value)
    {
        $this->propertyUpdated('TrackingOptionID', $value);
        $this->_data['TrackingOptionID'] = $value;
        return $this;
    }
.....

then in my code I use it as follows [just the relevant parts..]: I've previously downloaded and stored the relevant tracking category values.
$trackingCategory = (new \XeroPHP\Models\Accounting\TrackingCategory($xero))
                                         ->setTrackingCategoryID( $category_xero_id )
                                         ->setName( $categoryName)
                                         ->setOption($itemName)
                                         ->setTrackingOptionID($option_xero_id);

$lineitem = (new \XeroPHP\Models\Accounting\Invoice\LineItem($xero))
                               ->addTracking(trackingCategory);

 $invoice = (new \XeroPHP\Models\Accounting\Invoice($xero))
                            ->addLineItem($lineitem)

**Comment by futurewebsites** [comment]
has this been resolved? I have done the following but can't see the tracking category or option has been applied anywhere:

`public function addLineItems($lineItem){

		$tracking_category = new TrackingCategory();
		$tracking_category->setName("Country");
		$tracking_option = new TrackingCategory\TrackingOption();
		$tracking_option->setName($lineItem['tracking']);
		$tracking_category->addOption($tracking_option);

		$xeroLineItem = new Invoice\LineItem();

		$xeroLineItem->setDescription($lineItem['p_id'] . ' - '. $lineItem['p_name'])
						 ->setUnitAmount($lineItem['p_price'])
				         ->setQuantity($lineItem['p_quantity'])
						 ->setLineAmount($lineItem['total'])
						 ->setAccountCode("200")
						 ->addTracking($tracking_category);

		return $xeroLineItem;
	}`
