### ISSUE TITLE
Removing LineItems from an Invoice

### ISSUE THREAD

**Issue by mrchimp** [calcinai/xero-php#259]
As far as I can see there's no way to remove a LineItem from an existing Invoice. According to the [Documentation](https://developer.xero.com/documentation/api/invoices#modify-invoice) you can remove a LineItem by excluding it with an update request.

Assuming I'm not missing something and there isn't already a way to do this, I'm happy to submit a pull request. The only way I can see to do it at the moment is to create a new Invoice, apply all the existing data to i except for the relevant LineItem and then save that but that seems like a roundabout way to do things.

**Comment by mnwalker** [comment]
Easier than that, just need to modify the $this->_data['LineItems'] and then save.
Already got a working version so will submit a PR

**Comment by calcinai** [comment]
Is it too counterintuitive to do something like:
```
$invoice->getLineItems()->removeAt($x)
```
?

**Comment by calcinai** [comment]
This is now supported via the collection.
