### ISSUE TITLE
Getting EarningsLines from Employees' PayTemplates

### ISSUE THREAD

**Issue by wbercx** [calcinai/xero-php#260]
Hi there,

I am having trouble accessing EarningsLines through an employee's PayTemplate. I am getting `[1,1]` as a result for an employee with 2 EarningsLines, rather than 2 detailed objects.

```php
$employee = $xero->loadByGUID('PayrollAU\\Employee', $guid);
$employee->getPayTemplate()->getEarningsLines(); // [1,1]
```

Am I missing something here, or is it not supported at this stage?

**Comment by calcinai** [comment]
It actually seems like the EarningsLine object doesn't exist.  These models were generated a long time ago, and the scraper no longer works for the current docs.  If you create the class and make a PR I'll merge it in.

**Comment by wbercx** [comment]
#261 :)
