### ISSUE TITLE
Undefined index: message : Response.php (line 74)

### ISSUE THREAD

**Issue by ZarBoXa** [calcinai/xero-php#263]
I installed new Laravel 5.4 project and just required "calcinai/xero-php": "1.5.*" package .. i tried all methods available 
`
$config=[ //data ];
$xero = new \XeroPHP\Application\PrivateApplication($config);
*$contacts = $xero->load('Accounting\\Contact')->execute();
*$contact = new \XeroPHP\Models\Accounting\Contact($xero);`
*......

and every time i receive this error :
`
(1/1) ErrorException
Undefined index: message 
.../vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php', 74,
in Response.php (line 74)`

i have checked that file and found that it returns BadRequest with 400 status code .. but the array which holds error data is empty! so i get Undefined index: message .. thus i can't figure out where the problem is.

can you help me plz ?

**Comment by Healyhatman** [comment]
I'm having the exact same problem, have you made any progress?

**Comment by ZarBoXa** [comment]
@Healyhatman  Yup! the problem was with the  SSL certification,
"Private and Partner applications must sign messages using the OAuth RSA-SHA1 method."
so you have to generate your own and add it in the API config file, 

`openssl genrsa -out privatekey.pem 1024
openssl req -new -x509 -key privatekey.pem -out publickey.cer -days 1825
openssl pkcs12 -export -out public_privatekey.pfx -inkey privatekey.pem -in publickey.cer`

this commands will generate you the SSL certifications for both public and private.

you can find more details on this link : [https://developer.xero.com/documentation/api-guides/create-publicprivate-key](Create a public/private key pair)

**Comment by calcinai** [comment]
Sort @ZarBoXa and @Healyhatman - I somehow missed this one, looks like you're on top of it though.  I'll update the response class to give a better error message.

**Comment by Healyhatman** [comment]
Hey @ZarBoXa I followed those instructions and put the files on the server and I'm still getting the issue. Any possibility you could walk me through it, I'm a bit nub so I'm almost certainly doing something very easy very wrong.

**Comment by ZarBoXa** [comment]
@Healyhatman you r not a nub, you just don't know so it's ok ..
what Operating system do you use ?
first you should know the file path .. you need to use this method to get things work fine ..
`.....`
`'private_key' => get_file_contents($path) ;`
`....`
try it and let me know.

**Comment by Healyhatman** [comment]
OK it seems my problem is different to your problem. Mine appears to be a validation error - I think I have the bank account object set wrong (still can't figure out what setRemainder and setAmount should be). When I simply don't put in a bank account, the code works and submits correctly.
