### ISSUE TITLE
Undefined index: message : Response.php (line 74), validation errors, empty response - NOT SSL issue

### ISSUE THREAD

**Issue by Healyhatman** [calcinai/xero-php#265]
Getting the same error as in https://github.com/calcinai/xero-php/issues/263#issuecomment-311303556

However it's NOT because of an SSL issue. As mentioned in a comment on that closed issue, I get the issue when attempting to save an employee with what I assume is a badly formed BankAccount object - if I comment out my bank account code and submit the employee it works. 

Currently my bank account object looks like
$bankAccount -> setStatementText("Wages")
             -> setRemainder(false)
			 -> setAccountName($bankAccountName)
			 -> setBSB($bankBSB)
			 -> setAccountNumber($bankAccountNumber);

**Comment by calcinai** [comment]
Are you able to intercept the raw response and see if there's an error in there? I know that in some situations the Xero API has been known to 500 with no explanation.. Would like to rule that out first.

**Comment by Healyhatman** [comment]
If you tell me how to do that I'd love to help out haha

**Comment by calcinai** [comment]
Whoops, sorry.  Have a look in the `Response.php` file and print the `$response_body` variable in the constructor.  If you post anything here make sure to exclude anything sensitive!

**Comment by Healyhatman** [comment]
I got it to work correctly - I was accidentally providing an empty string for the bsb when creating the bank account. Works now. I'll break it again and do that thing for you though hang on.
