### ISSUE TITLE
Cannot add attachments which have special characters in the name

### ISSUE THREAD

**Issue by gitstashgithub** [calcinai/xero-php#267]
If the attachment file name has special character like `$` then calling the `addAttachment()` function will cause 'Failed to validate signature' UnauthorizedException. 
It's because the the file name has been encoded twice.
In `xero-php/src/XeroPHP/Traits/AttachmentTrait.php` file `addAttachment` function, the file name has been encoded:
`$uri = sprintf('%s/%s/Attachments/%s', $this::getResourceURI(), $this->getGUID(), rawurlencode($attachment->getFileName()));`

Then when generating the signature, in `xero-php/src/XeroPHP/Remote/OAuth/Client.php` file `getSBS` file, the $url which contains the file name has been encoded again:
`Helpers::escape($url),`

My solution is removing the rawurlencode function in the `addAttachment` function, but I am not 100% sure it won't cause other issues.

**Comment by calcinai** [comment]
This was only added recently, have you seen #240 - does this contradict what your testing has found?
