### ISSUE TITLE
Creating Multiple Records

### ISSUE THREAD

**Issue by sn0rcha** [calcinai/xero-php#27]
Hey There,

Many thanks for this module, it's great! - I was wondeirng what the process was for creating multiple records at a time. I need to do an initial sync of our data to Xero, and don't want to do individual requests for each object. 

Using your example for contacts:

`$contact = new \XeroPHP\Models\Accounting\Contact();`
`$contact->setName('Test Contact')
            ->setFirstName('Test')
            ->setLastName('Contact')
            ->setEmailAddress('test@example.com');`

How would I create multiple contacts in one request?

Cheers,
Ben

**Comment by calcinai** [comment]
Short answer: ```$xero->saveAll()```

Long answer is at #8

**Comment by coop182** [comment]
We happen to do this using this library... so example code would look like this:

```php
$xero = new \XeroPHP\Application\PartnerApplication($config);

$contacts = array(
	array(
		'first' => 'Test 1',
		'last' => 'Contact 1',
		'email' => 'test1@example.com'
	),
	array(
		'first' => 'Test 2',
		'last' => 'Contact 2',
		'email' => 'test2@example.com'
	),
	array(
		'first' => 'Test 3',
		'last' => 'Contact 3',
		'email' => 'test3@example.com'
	)
);

$sendContacts = array();

foreach($contacts as $contact) {
	$newContact = new \XeroPHP\Models\Accounting\Contact();
	$newContact
		->setFirstName($contact['first'])
		->setLastName($contact['last'])
		->setEmailAddress($contact['email']);

	$sendContacts[] = $newContact;
}

$response = $xero->saveAll($sendContacts);
```

**Comment by sn0rcha** [comment]
Many thanks for all your replies. If there is an error in the saveAll(), does it let you know which one?

**Comment by coop182** [comment]
Yes it does, if you take the example above, `$responses` will be an nested array with 3 arrays in it, so you can do something like this to process it.

```php
foreach($responses as $response) {
	// Process validation errors
	if(isset($response['ValidationErrors'])) {
		foreach ($response['ValidationErrors'] as $error) {
			if(preg_match('/.*(error message).*/', $error['Message'])) {
				// Do something
			}
		}
	}
}
```

**Comment by sn0rcha** [comment]
Many thanks all, coop182 you're a legend!

**Comment by calcinai** [comment]
Just further to this, there are a couple of ways yo get the errors.  You can use:

```$response->getErrorsForElement($element_index)``` (which will return ```null``` on no error)

or, if you're less concerned with the actual error, and just need to do something if it failed, you can iterate the original objects:

```php
foreach($sendContacts as $contact){
    if ($contact->isDirty()){
        //Handle
    }
}
```

**Comment by sn0rcha** [comment]
Thanks for that info calcinai!

**Comment by sn0rcha** [comment]
I have one more question if that's ok. Is it possible to update an invoice that has no payments or activity? - I've looked through the Invoice model but cannot find the ability to set the InvoiceID?

**Comment by coop182** [comment]
You should be able to use `->setInvoiceID`, does that work?

**Comment by sn0rcha** [comment]
nope, I'm remove line all the line items and add a new one after doing a $xero->loadByGUID('23234');

**Comment by nelwa** [comment]
In the example above that sends all the contacts at once like this:

> $responses = $xero->saveAll($sendContacts);

How do you get the ContactID for each sent contact?
