### ISSUE TITLE
[Discussion] Refactor the Application out of the models

### ISSUE THREAD

**Issue by timacdonald** [calcinai/xero-php#271]
Hey @calcinai,

So this is probably a massive task - but I would be happy to help.

I get why the application is in the models. It allows for a ORM style `$invoice->save()` which I love. However there is an issue when you serialize the models, it contains the application AND any responses tied to the application.

This was an issue I had to work around - where I was adding jobs the a database queue and needed to pass the invoice instance between jobs. It was serialized and saved no worries - until I hit the job to download the PDF of the invoice as the application IN the model still contained all the PDF data and was causing encoding issues, not to mentioned it just adds bloat to the serialized model.

Or is the better solution here to simply remove the application when serializing the models. Considering thats the quickest fix...now I've written this, I probably think that would be the best solution haha.

**Comment by calcinai** [comment]
Yeah, can the base model just implement Serializable and JsonSerializable, then just overload it to return the data only?

**Comment by timacdonald** [comment]
Yea, if we just `$this->_application = null` in those to remove that? Would that cause any issues you can imagine?

We're you thinking more of just removing the request responses from the application but keeping the application in the model during serialization? That way when you restore the model you don't have to add the application again?

**Comment by calcinai** [comment]
The main issue here is actually just the fact the oauth client is setting that `request` property. I think this can be easily removed and just passed into the relevant functions..

**Comment by timacdonald** [comment]
hmmm - what if we just a `removeApplication` method. Then everything is a little more explicit. You don't have to do any magic to make sure things are deserialized properly etc. And it doesn't have an BC issues.

**Comment by timacdonald** [comment]
I mean I could just pass in a fresh instance of the app when I serialize, but I think just having the ability to remove it would be good - because it will still have to serialize that object - which I'd prefer not to be storing if possible - because it would have credentials etc in it as well.
