### ISSUE TITLE
Tracking seems to always be null

### ISSUE THREAD

**Issue by jamie-selesti** [calcinai/xero-php#272]
I am having troubles trying to get the department / tracking infomation for a line item in an invoice

I am trying to get the value "50/50 Web/DM" for this particular line item
![image](https://user-images.githubusercontent.com/1398649/28420366-d2445cc8-6d59-11e7-8531-c3933045a00f.png)

Calling the tracking api endpoint I can see that its active
![image](https://user-images.githubusercontent.com/1398649/28420406-f0a25b84-6d59-11e7-81b3-7e6e4ea82579.png)

**But then when I get call the line item the tracking information is missing.**

![image](https://user-images.githubusercontent.com/1398649/28420433-0b7baf3c-6d5a-11e7-9f30-d36a097bbd45.png)

Am I doing something wrong or is this a bug?

**Comment by calcinai** [comment]
This is by far the most common issue reported! The issue is around how Xero treats tracking categories differently depending on what request it comes with.

That said, I'm not sure why it's there but null.  Have you had a look in the api request log?

**Comment by futurewebsites** [comment]
I am having exactly the same issue has there been any resolution or work-arounds for this ?
