### ISSUE TITLE
Can't load a SuperFundProduct

### ISSUE THREAD

**Issue by Healyhatman** [calcinai/xero-php#273]
Probably doing this the wrong way but anyway.

Making an onboarding system for someone where a worker puts in all their details and it gets sent off to Xero. Trying to do the Super. Trying to check if a super product exists. 
$xero->load('\\XeroPHP\\Models\\PayrollAU\\SuperFundProduct')->where('ABN == "11099645885"')->execute() or variations of the same gives me Uncaught XeroPHP\Remote\Exception\BadRequestException: You must provide an ABN and/or a USI for the superannuation fund product. 

So either I'm doing something wrong (highly likely) or something's not right.

**Comment by Healyhatman** [comment]
Doing the same thing but with SuperFund gives me a blank validation error.

**Comment by calcinai** [comment]
Are you able to log into the Xero API console and see if there's any more info on the error?

**Comment by Healyhatman** [comment]
If you mean the Previewer there's no SuperFund endpoint in the dropdown list. I don't know where the console is and googling gives me nothing.

Also from research I need SuperFund (not SuperFundProduct) and doing the same request gives me a blank empty validation error.

**Comment by calcinai** [comment]
I'm meaning in here: https://app.xero.com/Application/History/

**Comment by Healyhatman** [comment]
<Response xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><ErrorNumber>0</ErrorNumber><Type>Error</Type><Message>ABN property is not supported for Where or Order clause.</Message></Response>

**Comment by calcinai** [comment]
That seems to answer it then..

**Comment by Healyhatman** [comment]
How do I find a SuperFund's ID then? Trying to load SuperFundProduct by ABN or USI (or both) gives me 

`<Response xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Id>3fb4cc48-00ec-4199-a673-6064b8f3846a</Id><ProviderName>DevApp</ProviderName><ErrorNumber>0</ErrorNumber><Type>ValidationException</Type><Message>You must provide an ABN and/or a USI for the superannuation fund product.</Message><SuperFundProducts i:nil="true"/></Response>`

to add Super details for an employee I need to get Xero's ID for the super fund

**Comment by calcinai** [comment]
Hmm, I'm not sure.  I don't actually know that much about the Xero API - most of the code in this library is automatically generated, so if you can't get the call working manually or in the API previewer you might need to contact Xero support and ask.

**Comment by Healyhatman** [comment]
The documentation at https://developer.xero.com/documentation/payroll-api/superfunds claims I should be able to get a record using any parameter.  We'll see what Xero says.

**Comment by Healyhatman** [comment]
https://community.xero.com/developer/discussion/7686335

Apparently I need to use SuperFundProducts to search, and I can't use a where clause I have to "search it directly". Is such a thing possible with this api?

**Comment by Healyhatman** [comment]
Apparently according to https://community.xero.com/developer/discussion/7686335 I need to do it directly as in /payroll.xro/1.0/SuperFund?USI=APF0100AU, so I did $myFund = $xero->load(...SuperFund)->setParameters("USI", a valid USI)->execute() and it "works" - there's no error and the console shows a 200 response code - but you can't view the request on the console and doing var_dump($myFund) it appears to have downloaded ALL the SuperFunds from my Xero. 

Doing the same thing with SuperFundProducts (instead of SuperFund) also "works" but returns an empty Collection object.

**Comment by Healyhatman** [comment]
OK I managed to get the ID by going $superFunds[] = $xero->load(...SuperFund)->execute to get everything, then iterating over $superFunds[0] to find the right superfund.  There's currently no way I can tell though to get a single super fund from Xero, everything I try just gets all of them. I'll make a separate issue soon regarding the SuperFundProducts search not working as intended as well - doing $fund = $xero->load(...SuperFundProduct)->setParameter("USI", the usi I'm searching)->execute does not give me a single SuperFundProduct, but again gives me an array of all the SuperFunds stored by my Xero.

**Comment by calcinai** [comment]
I'm curious to see what Xero says on this - I can't see any reason why those parameters wouldn't be being passed through at this end..

Since the API previewer is a no-go, can you try and just hardcode that url and see what it returns?

**Comment by Healyhatman** [comment]
Sorry but where and how would I do that?

**Comment by Healyhatman** [comment]
Hello again - where should I try to hardcode the url at please

**Comment by Healyhatman** [comment]
GOT IT. Or at least got the SuperFundProduct.

So - the documentation at https://developer.xero.com/documentation/payroll-api/superfundproducts says "at least one parameter (of USI or ABN) is required". For some reason though, it only works if you have the ABN. Trying to load with the USI on its own gives me nothing, even though USIs are unique and an ABN might possibly be associated with more than one business. 

So putting the ABN in (or ABN and USI) using setParameter will (if it exists) return a SuperFundProduct. Using invalid details will return an empty collection object.

**Comment by Healyhatman** [comment]
#363 Solution in referenced issue.
