### ISSUE TITLE
Can't save a SMSF type Super Fund

### ISSUE THREAD

**Issue by Healyhatman** [calcinai/xero-php#275]
As usual it's probably just me doing something wrong BUT:

I'm building my onboarding system and I have my Regulated Super Funds saving correctly (in a roundabout way as previously mentioned) now I'm working on getting SMSf fund types to save.

I create a new \XeroPHP\Models\PayrollAU\SuperFund\SuperFund($xero)   because \XeroPHP\Models\PayrollAU\SuperFund appears to be only for Regulated types and has no methods for BSB, ESA, and the rest of the fields a SMSF requires.
I set all the required fields (ABN, BSB, Name, etc etc)
I do $superFund->save()  aaaaaaand....... nothing. No errors, no exceptions, no request shown in Xero console, nothing.

By putting a bunch of echoes in various places, it seems to get to line 230 in Application.php (in the save function, where it checks if(!object->isDirty())) and returns null.

**Comment by calcinai** [comment]
I suspect that model is not correct.  The sub models can almost never be created directly from what I've seen..

Can you test merging those two classes (methods, variables etc) and deleting the sub model?

**Comment by Healyhatman** [comment]
So, copy all the code in SuperFund\SuperFund into just SuperFund?

**Comment by Healyhatman** [comment]
I put all the SuperFund\SuperFund code into SuperFund and renamed SuperFund\SuperFund to _SuperFund, same problem still. The echo says the object isn't "dirty".

**Comment by Healyhatman** [comment]
OK I copied all the ***missing*** properties and methods from SuperFund\SuperFund into SuperFund and it's saving to Xero. 

As an item of interest however, I can save the same details over and over again and it makes a new copy of the SuperFund in Xero. So I sure hope I don't have a whole bunch of people using the same super fund.
