### ISSUE TITLE
Q: Is it possible to query using WHERE IN?

### ISSUE THREAD

**Issue by Asia321** [calcinai/xero-php#276]
I would like to get Invoices for a specified invoiceNumbers?

```
$xero = new \XeroPHP\Application\PrivateApplication($config);

//something like this doesnt work:
$invoices = $xero->load('Accounting\\Invoice')->where('InvoiceNumbers IN (1,2,3,4)')->execute();
```

**Comment by calcinai** [comment]
Hey, I can't see any reference to this in the Xero documentation - can you please attach a link?

**Comment by Asia321** [comment]
Yeah, I also couldn't find it. As I see the replacement for that are multiple 'OR' queries.

**Comment by calcinai** [comment]
Sounds like it's not possible then
