### ISSUE TITLE
Credit Note is Pageable

### ISSUE THREAD

**Issue by iveoles** [calcinai/xero-php#278]
On 1.5.0 the CreditNote model is showing as Non-Pagable, but according to the docs it is

https://developer.xero.com/documentation/api/credit-notes

Updating the function to the below will run correctly. I'd submit a pull request but if I remember this is generated dynamically?

    public static function isPageable()
    {
        return false;
    }

**Comment by calcinai** [comment]
Yeah you are correct. It's gotten too hard to base it on the docs now since there are so many discrepancies. If you make a PR I'll merge it in.

**Comment by iveoles** [comment]
Sorry for the delay, but here's the pull request
