### ISSUE TITLE
Updating an Invoice

### ISSUE THREAD

**Issue by sn0rcha** [calcinai/xero-php#28]
Hey guys,

I've been struggling trying to figure out how to update an invoice using the package. If I do the following:

`$master = $xero->loadByGUID('Accounting\\Invoice', 'a0ff65bc-xxxx-xxxx');`
`$master->setStatus('DRAFT');`
`$xero->save($master)`

I'm getting the following error:

`Instance validation error: '0' is not a valid value for global::Xero.API.Library.DataContracts.LineAmountType`

What is the correct process to update an Invoice using the package? Ultimately I need to replace all the current line items with new ones on an invoice that has no payments or activity.

Many thanks!

**Comment by calcinai** [comment]
I'll try to replicate - that error is directly from Xero's validation, so it must be due to how the request is being sent. 

I'd say that it doesn't allow an invoice to be updated in its full form (containing sub-resources/LineItems), may be a matter of handling directly once they exist.

**Comment by calcinai** [comment]
This was due to a property being parsed as a float, not a string.   The following is now working for me:

```php
$master = $xero->loadByGUID('Accounting\\Invoice', 'xxxx-xxxx');
$master->setStatus(Invoice::INVOICE_STATUS_DRAFT);
$xero->save($master);
```

You may notice that there are also predefined constants for all statuses and flags.

**Comment by sn0rcha** [comment]
Is it possible once the invoice status is "DRAFT", to replace the line items by following the same way you do when creating one ie. ($master->addLineItem(LineItemObject))? - I read on the Xero forums that was an invoice is in the "AUTHORISED" status, you can't really alter the line items.

**Comment by calcinai** [comment]
I honestly don't know about that one.  Maybe I need to add corresponding ```->removeXXX``` methods along side the others?  Does that behaviour work in the API previewer?

**Comment by sn0rcha** [comment]
Also, sorry for the multiple posts. I've tried the following, I had to use `\XeroPHP\Models\Account\Invoice::INVOICE_STATUS_DRAFT` as I have an eqloquent model with the name "Invoice" :)

`$master->setStatus(\XeroPHP\Models\Accounting\Invoice::INVOICE_STATUS_DRAFT);`
`$xero->save($master);`

But still get the same error:

`Instance validation error: '0' is not a valid value for global::Xero.API.Library.DataContracts.LineAmountType`

**Comment by calcinai** [comment]
First issue may be a lack of: ```use XeroPHP\Models\Accounting\Invoice;```

Second thing, what version of this lib are you using?  Those recent changes were only on dev-master, I've just released a version, so a composer update should get v1.1.7 to you.

**Comment by sn0rcha** [comment]
Hey Calcinai, i've updated and that kinda worked... 

Now I get `A validation exception occurred (Invoice not of valid status for modification)` so it looks like you can't switch back an "AUTHORISED" invoice to "DRAFT"... I scratch my head with their API sometimes, as I can do that via the UI....

. We are trying to have just 1 invoice that we can constantly update with a figure as we don't want to use the invoice system that xero provides (we generate thousands of small invoices a day) as we are only interested in a debtor figure. Is there a better way to do this via a cash flow account or something.. might be a question for Xero themselves!

**Comment by coop182** [comment]
@sn0rcha could you use a manual journal?

**Comment by calcinai** [comment]
I'm not too familiar with that sorry.

This is a table from their docs, looks like you don't fit in with the allowed transitions.

Existing status	| New status
----------------|-----------
DRAFT | DRAFT
DRAFT | SUBMITTED
DRAFT | AUTHORISED
DRAFT | DELETED
SUBMITTED | SUBMITTED
SUBMITTED | AUTHORISED
SUBMITTED | DRAFT
SUBMITTED | DELETED
AUTHORISED | AUTHORISED
AUTHORISED | VOIDED

**Comment by sn0rcha** [comment]
Hey guys, I went down the manual journal entry route, however, when I pull an entry back, and update the line items, it never saves, it doesn't trigger and error, it just doesn't update. If I inspect the object prior to calling ```$xero->save($journal)``` it has the changes. Any ideas?

**Comment by calcinai** [comment]
Does the API actually let you update the LineItems?  If so, and there's no error, maybe it is actually doing it and just not reflecting the changes locally?

**Comment by coop182** [comment]
Are you pulling down and editing the manual journals? If so it should be working fine... when you edit a manual journal it should generate a reversal journal and a new journal... we do this all the time and it is all good... have you got an example of the code you are using... I can take a look and compare it to what we are using.

**Comment by sn0rcha** [comment]
Here is my code:

```
        $xero = new \XeroPHP\Application\PrivateApplication(XeroApi::getConfig());
        $journal = $xero->loadByGUID("Accounting\\ManualJournal", "xxxx-xxxx-xxxx-xxxx-xxxx");
        foreach ($journal->getJournalLines() as $j) {
            $acctcode = $j->getAccountCode();
            if ($acctcode == 41100) {
                $cur = $j->getLineAmount();
                $cur = $cur - $company_sales;
                $j->setLineAmount($cur);
            }
            if ($acctcode == 11220) {
                $cur = $j->getLineAmount();
                $cur = $cur + $company_sales;
                $j->setLineAmount($cur);
            }
        }
       $xero->save($journal);
```

If I inspect the ```$journal``` prior to saving, it has the line item changes, it doesn't error, it just never changes on the ui on xero :(

**Comment by coop182** [comment]
Are you sure `$journal` is actually being updated... in your example above I would have thought you would have to pass `$j` by reference to actually update `$journal` ?

```php
foreach ($journal->getJournalLines() as &$j) {
```

**Comment by sn0rcha** [comment]
Same deal.. here is my inspected altered object ($journal) prior to saving after the updates:

```
XeroPHP\Models\Accounting\ManualJournal Object ( [_data:protected] => Array ( [ManualJournalID] => xxxx-xxxx-xxxx-xxxx-xxxx [Narration] => TEST - NEW SALES [JournalLines] => Array ( [0] => XeroPHP\Models\Accounting\ManualJournal\JournalLine Object ( [_data:protected] => Array ( [LineAmount] => -2274 [AccountCode] => 41100 [Description] => TEST - NEW SALES [TaxType] => OUTPUT ) [_dirty:protected] => Array ( [LineAmount] => 1 ) ) [1] => XeroPHP\Models\Accounting\ManualJournal\JournalLine Object ( [_data:protected] => Array ( [LineAmount] => -400.00 [AccountCode] => 41200 [Description] => TEST - NEW SALES [TaxType] => OUTPUT ) [_dirty:protected] => Array ( ) ) [2] => XeroPHP\Models\Accounting\ManualJournal\JournalLine Object ( [_data:protected] => Array ( [LineAmount] => -600.00 [AccountCode] => 41300 [Description] => TEST - NEW SALES [TaxType] => OUTPUT ) [_dirty:protected] => Array ( ) ) [3] => XeroPHP\Models\Accounting\ManualJournal\JournalLine Object ( [_data:protected] => Array ( [LineAmount] => 3274 [AccountCode] => 11220 [Description] => TEST - NEW SALES [TaxType] => BASEXCLUDED ) [_dirty:protected] => Array ( [LineAmount] => 1 ) ) ) [Date] => DateTime Object ( [date] => 2015-06-04 00:00:00 [timezone_type] => 3 [timezone] => Australia/Brisbane ) [LineAmountTypes] => Inclusive [Status] => POSTED [ShowOnCashBasisReports] => 1 [HasAttachments] => ) [_dirty:protected] => Array ( ) )
```

**Comment by calcinai** [comment]
Objects are always passed by reference in PHP unless explicitly cloned.  Do you ha et XML that is being generated?

**Comment by sn0rcha** [comment]
Hey Calcinai,

Is there a way to output the XML generated by the module on save?

**Comment by calcinai** [comment]
You can look at a particular object's xml with something like 

```php
$object_data = array($object::getRootNodeName() => $object->toStringArray());
$xml = Helpers::arrayToXML($object_data);
```

There's no direct accessor for it, but this is how it's internally generated.

**Comment by sn0rcha** [comment]
Thanks, interesting when I check if the object is dirty, it's telling me it's not ```if($object->isDirty())```... Any idea why that would not be? From that output I posted earlier it's picking up it's dirty or am I reading that wrong?

**Comment by sn0rcha** [comment]
I can confirm that with the method I am using, a request is never made to update the journal, am I doing something with the way I'm updating the $journal object?

**Comment by sn0rcha** [comment]
Sorry for the continious postings.. But I think I've found a bug.. If I use my method above AND do a $journal->setNarration('something different') - the update always triggers and things work as they should, however if I just update the line items, the update will never get triggered.

**Comment by calcinai** [comment]
That seems about right actually, are you changing the actual LineItem itself, not adding/removing one?

**Comment by calcinai** [comment]
I'm going to close this and shift to #30 to make it more clear what's going on.

**Comment by calcinai** [comment]
FYI, have updated #30.
