### ISSUE TITLE
Refund Payment / Update Payment Status

### ISSUE THREAD

**Issue by david741258** [calcinai/xero-php#283]
Hi, Can anyone help me how to update payment status or delete payment for better ? I can't find any method to delete payment which I need to make refund. 

Thanks

**Comment by williamrenfrew** [comment]
Hi David

Here's a simplified excerpt of what we do to delete payments that have been applied to Sales Invoices:

`$check_payment = $xero->loadByGUID('Accounting\\Payment', $xero_payment_guid);
            if ($check_payment->getStatus() == \XeroPHP\Models\Accounting\Payment::PAYMENT_STATUS_AUTHORISED) {
                $xero_payment = new \XeroPHP\Models\Accounting\Payment();
                $xero_payment->setGUID($xero_payment_guid);
                $xero_payment->setStatus(\XeroPHP\Models\Accounting\Payment::PAYMENT_STATUS_DELETED);
                $xero->save($xero_payment);
            }`

**Comment by david741258** [comment]
Thanks so much for all the help !!!

**Comment by calcinai** [comment]
Thanks guys
