### ISSUE TITLE
Could not filter the Purchase Order results using where condition.

### ISSUE THREAD

**Issue by srphpprogrammer** [calcinai/xero-php#284]
I'm getting the response  well but I'm unable to filter the data. I tried various ways as documented on the the readme(https://github.com/calcinai/xero-php/blob/master/README.md) file like this 
Search for objects meeting certain criteria
```

$xero->load('Accounting\\Invoice')
    ->where('Status', \XeroPHP\Models\Accounting\Invoice::INVOICE_STATUS_AUTHORISED)
    ->where('Type', \XeroPHP\Models\Accounting\Invoice::INVOICE_TYPE_ACCREC)
    ->execute();
or

$xero->load('Accounting\\Invoice')->where('
    Status=="' . \XeroPHP\Models\Accounting\Invoice::INVOICE_STATUS_AUTHORISED . '" AND
    Type=="' . \XeroPHP\Models\Accounting\Invoice::INVOICE_TYPE_ACCREC . '"
')->execute();
```

but no matter what I did it is still giving me an unfiltered result set. I've also tried 'DELETED'. What could be the problem?

Here's the code I've used to get the Purchase Orders.
```
$ordersData = $xero->load('Accounting\\PurchaseOrder')->where('status, 'Deleted')->execute();

```
@calcinai I'm using the latest stable version. Is there an issue with the library?

**Comment by calcinai** [comment]
I'm not sure what the issue might be here - that looks correct to me.  By unfiltered, do you mean just all invoices in Xero?

**Comment by glaing** [comment]
> $ordersData = $xero->load('Accounting\\PurchaseOrder')->where('status, 'Deleted')->execute();

@srphpprogrammer did you manage to get this to work for Purchase Orders?

I'm trying to get this working for a project where I want to only get Approved Purchase Orders returned, but I always get all Purchase Orders returned.

$xero_purchase_orders = $xero->load('Accounting\\PurchaseOrder')->where('status', 'Approved')->execute();

Any help would be greatly appreciated :)

Thanks,
George

**Comment by timacdonald** [comment]
I can't test this live right now, but I can confirm that command produces the following request from the library...

```php
[
  "method" => "GET",
  "body" => null,
  "headers" => [
    0 => "Accept: text/xml",
  ],
  "url" => "https://api.xero.com/api.xro/2.0/PurchaseOrders",
  "query_string" => "where=status%3D%3D%22AUTHORISED%22",
]
```

which results in the full url being...

```
https://api.xero.com/api.xro/2.0/PurchaseOrders?where=status%3D%3D%22AUTHORISED%22
```

which looks correct to me.

**Comment by timacdonald** [comment]
Although looking at their docs 🤦‍♂️ ...

```
Filter by purchase order status (e.g. GET https://.../PurchaseOrders?status=DRAFT)
```

**Comment by timacdonald** [comment]
Try this instead of using the `where` method...

```php
$xero_purchase_orders = $xero->load('Accounting\PurchaseOrder')->setParameter('status', 'AUTHORISED')->execute();
```

**Comment by glaing** [comment]
@timacdonald Thank you very much - that works perfectly!!

**Comment by l1ngoman** [comment]
@timacdonald Any idea on how to do more than one status at a time? I'm trying to get all purchase orders except those that have been deleted.

Thanks!

**Comment by timacdonald** [comment]
Haven't tested, but I believe you can comma seperate them...

```php
$xero_purchase_orders = $xero->load('Accounting\PurchaseOrder')->setParameter('status', 'AUTHORISED,VOIDED')->execute();
```
