### ISSUE TITLE
Pulling reports

### ISSUE THREAD

**Issue by jwatkins0101** [calcinai/xero-php#29]
how do you pull a report I don't see a model for it?

**Comment by calcinai** [comment]
You may notice in [the generator](https://github.com/calcinai/xero-php/blob/master/generator/generate#L52) that reports are skipped as they don't follow a uniform format.  

You can still use the api/parser manually, e.g.

```php
$url = new URL($xero, 'Reports/AgedPayablesByContact');
$request = new Request($xero, $url, Request::METHOD_GET);
$request->setParameter('contactID', 'xxx');
$request->send();

$elements = $request->getResponse()->getElements();
```

**Comment by jwatkins0101** [comment]
Thanks.
