### ISSUE TITLE
Return Type loadByGUID()

### ISSUE THREAD

**Issue by kashifau** [calcinai/xero-php#293]
What is value return by \XeroPrivate::loadByGUID('Accounting\Invoice', $invoice->id) if the Invoice ID does not exist and how can I handle the exception?

**Comment by Josh-G** [comment]
If you are requesting a non-existent invoice when calling loadByGUID, xero-php will throw a `XeroPHP\Remote\Exception\NotFoundException` as seen [here](https://github.com/calcinai/xero-php/blob/e270e09e521ab6cf542ce592458d5264793bd3aa/src/XeroPHP/Remote/Response.php#L91):
```
            case Response::STATUS_NOT_FOUND:
                throw new NotFoundException();
```

**Comment by kashifau** [comment]
Thanks! that's helpful.
