### ISSUE TITLE
PayrollAU TaxDeclaration can't be used as is.

### ISSUE THREAD

**Issue by Healyhatman** [calcinai/xero-php#295]
I needed to add a setTaxDeclaration method to PayrollAU/Employee. Can't do TaxDecl->save() and there was nothing in there to use.

Using setEmployeeID in TaxDeclaration, adding the TaxDeclaration to the Employee object and saving gives "EmployeeID is not a valid element in TaxDeclaration" in the History (nothing in the code) - can you not just append the response text to the exception somehow? 

Anyway, after adding my methods and whatnot I was able to save an employee's tax declaration. Hooray for me.

**Comment by Healyhatman** [comment]
Alsoalso, several of the properties have type String, but they should be Booleans - TaxFreeThresholdClaimed, AustralianResidentForTaxPurposes, Has(HELPDebt, SFSSDebt, TSLDebt,TradeSupportLoanDebt)

And TSL stands for TradeSupportLoan so not sure why they're both properties.

**Comment by timacdonald** [comment]
Hey @Healyhatman awesome that you got it going! I'm sure @calcinai would love you to send a Pull Request with the fixes if you can - might help out other in the future with the same issue.

**Comment by Healyhatman** [comment]
@timacdonald sure I'd love to. No idea how though so I'll have to look into it :)

**Comment by timacdonald** [comment]
If ya just stating out with GIT and contributing - I found [GitHub desktop](https://desktop.github.com) a big help when I was trying to work out how it all came together. If you need any pointers - let me know! More than happy to point you in the right direction.

**Comment by Healyhatman** [comment]
@timacdonald I submitted the pull request, hopefully I did it right. I included some of the other things I changed / fixed.

**Comment by timacdonald** [comment]
Nice one!

**Comment by timacdonald** [comment]
Looks right to me - congrats! Whether it's accepted or rejected - awesome work getting your first contribution going - and don't be put off by a few rejections - doesn't mean you should continue to send things thought to try and help everyone out! It gets addictive and is a great way to get to code with others.
