### ISSUE TITLE
Cannot access private key for signing: openssl_pkey_get_private

### ISSUE THREAD

**Issue by mrdigitalau** [calcinai/xero-php#296]
Hi, I wasn't sure where to post this but hopefully it's ok to do it here. I would really appreciate an idea what i'm doing wrong, I've been pulling my hair out for the past few hours.

I am creating a private application.

I am using XAMPP on Windows 10 and have OPENSSL and CURL enabled, running PHP7.

I installed the project via composer and then created an index.php file in my project.
I've got my certificates in a separate folder called "certs". My folder structure is like this.

- index.php
- /certs/
- /vendor/

**When I try and run index.php, I always receive this error:**

There error I receive when running index.php is:
`Fatal error: Uncaught XeroPHP\Remote\OAuth\Exception: Cannot access private key for signing: openssl_pkey_get_private('/certs/privatekey.pem') returned false in C:\xampp\htdocs\tutorials\vendor\calcinai\xero-php\src\XeroPHP\Remote\OAuth\SignatureMethod\RSASHA1.php:13 Stack trace: #0 C:\xampp\htdocs\tutorials\vendor\calcinai\xero-php\src\XeroPHP\Remote\OAuth\Client.php(150): XeroPHP\Remote\OAuth\SignatureMethod\RSASHA1::generateSignature(Array, 'GET&https%3A%2F...', 'LV2AZPSIUJJEME3...') #1 C:\xampp\htdocs\tutorials\vendor\calcinai\xero-php\src\XeroPHP\Remote\OAuth\Client.php(68): XeroPHP\Remote\OAuth\Client->getSignature() #2 C:\xampp\htdocs\tutorials\vendor\calcinai\xero-php\src\XeroPHP\Remote\Request.php(68): XeroPHP\Remote\OAuth\Client->sign(Object(XeroPHP\Remote\Request)) #3 C:\xampp\htdocs\tutorials\vendor\calcinai\xero-php\src\XeroPHP\Remote\Query.php(272): XeroPHP\Remote\Request->send() #4 C:\xampp\htdocs\tutorials\index.php(25): XeroPHP\Remote\Query->execute() #5 {main} thrown in C:\xampp\htdocs\tutorials\vendor\calcinai\xero-php\src\XeroPHP\Remote\OAuth\SignatureMethod\RSASHA1.php on line 13
`

My code is as below, the private and public keys are definitely the correct name in the /certs/ folder.

My index.php looks like this:

`<?php 
use XeroPHP\Application\PrivateApplication;

require 'vendor/autoload.php';

$config = [
    'oauth' => [
        'callback'         => 'http://tutorials.dev/',
        'consumer_key'     => '3AU7LOEAR4PBXOARPYDYWW3UPKPQ4N',
        'consumer_secret'  => 'LV2AZPSIUJJEME3ZCP1HQQV4AQ67V1',
        'rsa_private_key'  => '/certs/privatekey.pem',
        'rsa_public_key'  => '/certs/publickey.cer',
    ],
];

$xero = new PrivateApplication($config);

$contacts = $xero->load('Accounting\\Contact')->execute();
foreach ($contacts as $contact) {
    print_r($contact);
}`

Do you have any idea what I might be doing wrong here?
Any help would be much appreciated :)

Thank you

**Comment by mrdigitalau** [comment]
Hi 

Just an update, I got it working by adding in the certificates directly into the $config array.
So basically copied them from their respective files and pasted them in directly, which worked.

Cheers

**Comment by mrdigitalau** [comment]
Hi Just another update,

I ended up doing it this way as FILE:// didn't seem to want to work for me.

`
$privatekey = file_get_contents('certs/privatekey.pem');
$publickey = file_get_contents('certs/publickey.cer');

require 'vendor/autoload.php';

$config = [
    'oauth' => [
        'callback'         => 'http://tutorials.dev/',
        'consumer_key'     => '3AU7LOEAR4PBXOADSYWW3UPKPQ4N',
        'consumer_secret'  => 'LV2AZPSIUJJEME3ZD1HQQV4AQ67V1',
        'rsa_private_key'  =>  $privatekey,

       'rsa_public_key'  => $publickey,
    ],
];

$xero = new PrivateApplication($config);


`

**Comment by alvinnguyen** [comment]
Confirm having the same issue and has to do file_get_content as mrdigitalau suggested above.
