### ISSUE TITLE
Generating models

### ISSUE THREAD

**Issue by paulsschwarz** [calcinai/xero-php#3]
So far I haven't noticed any issues with the generated models. I was just thinking, this might be a more robust source of truth.
https://github.com/XeroAPI/XeroAPI-Schemas/blob/master/v2.00/Invoice.xsd

**Comment by calcinai** [comment]
It probably would be, but their shemas only contain the Accounting API, not either Payroll or the Files one.

It would be nice to move to that eventually - I'm told it's pretty easy to generate those from .net apps so hopefully it's not too far away.

The docs are terribly inconsistent and I've had to build in a lot of complex testing logic to parse what it is most likely to be.

**Comment by calcinai** [comment]
I'm going to close this.  At the point where there is a complete set of xsd's, I'll definitely make the switch.
