### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by gkavaliu** [calcinai/xero-php#300]
Hello,

Is there any plan to add support Setup or can I just not find it?

https://api.xero.com/api.xro/2.0/Setup

Thank You,
Glen

**Comment by calcinai** [comment]
Is that documented anywhere?

**Comment by gkavaliu** [comment]
https://developer.xero.com/documentation/api-guides/conversions

**Comment by calcinai** [comment]
Didn't even know that existed! You could manually create the URL and request without too much trouble..

```php
$url = new \XeroPHP\Remote\URL($xero, 'Setup');
$request = new \XeroPHP\Remote\Request($xero, $url, \XeroPHP\Remote\Request::METHOD_POST);

$data = [
    'Accounts' => [
        'Account' => [
            'Code' => 200,
            'Name' => 'Sales',
            'Type' => 'SALES',
            'ReportingCode' => 'REV.TRA.GOO'
        ]
    ]
];

$request->setBody(\XeroPHP\Helpers::arrayToXML($data));
$request->send();
```

It might make sense to make a helper function for this for others

**Comment by gkavaliu** [comment]
Wow thanks. I am still learning all of what this can do :)

**Comment by gkavaliu** [comment]
Sorry so adding another account would look like this?

$data = [
    'Accounts' => [
        'Account' => [
            'Code' => 200,
            'Name' => 'Sales',
            'Type' => 'SALES',
            'ReportingCode' => 'REV.TRA.GOO'
        ]
        'Account' => [
            'Code' => 201,
            'Name' => 'Sales2',
            'Type' => 'SALES',
            'ReportingCode' => 'REV.TRA.GOO'
        ]
    ]
];

**Comment by calcinai** [comment]
Is there a reason you can't use https://developer.xero.com/documentation/api/accounts?

**Comment by gkavaliu** [comment]
Good point. I am more looking at this for the 

<Setup>
  <ConversionDate>
      <Month>1</Month>
      <Year>2014</Year>
  </ConversionDate>
  <ConversionBalances>
      <ConversionBalance>
        <AccountCode>200</AccountCode>
        <Balance>-5000.00</Balance>
      </ConversionBalance>
      <ConversionBalance>
        <AccountCode>400</AccountCode>
        <Balance>2000.00</Balance>
      </ConversionBalance>
      <ConversionBalance>
        <AccountCode>610</AccountCode>
        <Balance>5000.00</Balance>
      </ConversionBalance>
       <ConversionBalance>
        <AccountCode>800</AccountCode>
        <Balance>-2000.00</Balance>
      </ConversionBalance>
  </ConversionBalances>
</Setup>
