### ISSUE TITLE
Feature Request: Filter by list of ID's

### ISSUE THREAD

**Issue by rohanrichards** [calcinai/xero-php#310]
Forgive me if this exists but I can't find it in the source.
Basically I have a list of GUID's and would just like to fetch all of the invoice objects from Xero without doing individual API calls. Seems like the API has this as an option:

```
Filter by a comma-separated list of InvoicesIDs, InvoiceNumbers, ContactIDs or Statuses. For faster response times we recommend using these explicit parameters instead of passing OR conditions into the Where filter.
e.g. GET https://.../Invoices?Statuses=DRAFT,SUBMITTED
```

Just some way to make use of the filters other than the WHERE attribute.

**Comment by rohanrichards** [comment]
Toying around with this but getting UnauthorizedException: Failed to validat signature. I might just be out of my depth hehehe
```
    public function loadByGUIDs($model, $guids)
    {
        /**
         * @var Remote\Object $class
         */
        $class = $this->validateModelClass($model);

        $uri = sprintf('%s?InvoicesIDs=%s', $class::getResourceURI(), $guids);
        $api = $class::getAPIStem();

        $url = new URL($this, $uri, $api);
        $request = new Request($this, $url, Request::METHOD_GET);
        $request->send();

        return $request;
    }
```

**Comment by calcinai** [comment]
Hey, yeah it's not implemented anywhere, but you should be able to do it with the `->setParameter()` method for invoiceIDs, that way the parameters will be handled properly during OAuth signing.

**Comment by rohanrichards** [comment]
hmmm, I understand now what ->setParameter() does on the request object, and I seem to be getting a response. What I'm not sure about now is how to get this into a Collection like a regular query does. I've tried copying and modifying a Query->execute() foreach loop to mimic the loadByGUID method, but it just hangs on ->fromStringArray 

```
        $request->setParameter("InvoiceIDs", $guids);
        $request->send();

        $elements = new Collection();
        foreach ($request->getResponse()->getElements() as $element) {
            /**
             * @var Remote\Object $object
             */
            $object = new $class($this);
            $object->fromStringArray($element);
            $elements->append($object);
        }

        return $elements;
```

Any more hints? 😄
