### ISSUE TITLE
`oauth_callback` does nothing in Private Application

### ISSUE THREAD

**Issue by DrRoach** [calcinai/xero-php#314]
I've just had a look through the code and found that everything still works even when the `oauth_callback` is removed from the application. What is the use for this? And would it be plausible to remove it? It seems strange to have this if it doesn't do anything.

**Comment by calcinai** [comment]
Yeah you're right, it doesn't seem to, but as per the [OAuth 1.0a Spec](https://oauth.net/core/1.0a/#rfc.section.6.1.1)

> If the Consumer is unable to receive callbacks or a callback URL has been established via other means, the parameter value MUST be set to oob (case sensitive), to indicate an out-of-band configuration.
