### ISSUE TITLE
saveAll() pointing to wrong URI for payroll endpoints

### ISSUE THREAD

**Issue by yiyang00171** [calcinai/xero-php#318]
When doing bulk create/update on Payroll API endpoints using `saveAll()`, the code always gets 404 in response. 

Dig into it and found out the request URL is wrong. For example when bulk updating payslips, request is being sent to `https://api.xero.com/api.xro/2.0/Payslip`, however base on XERO documentation it should be sent to `https://api.xero.com/payroll.xro/1.0/Payslip`.

Problem is in the main `Application::saveAll()` line 262.
```
$url = new URL($this, $type::getResourceURI());
```  
Missing 3rd param `$api` will build `URL` using default API and version `api.xro/2.0`.

**Comment by yiyang00171** [comment]
Notice this has been fixed on master, but not available on v1.5.0 yet.

**Comment by wbercx** [comment]
+1. A new release would be nice.

**Comment by calcinai** [comment]
Why not!

**Comment by calcinai** [comment]
I've bumped the version to 1.6 since there are arguably some changes that aren't completely bc.

**Comment by wbercx** [comment]
That was swift. Thank you!
