### ISSUE TITLE
Service Provider

### ISSUE THREAD

**Issue by empsean** [calcinai/xero-php#319]
Wondering if anyone has made a service provider, or guide me in making a service provider for this?

Ask as this is the first package where there isn't a config and facade to just use it out of the box, and don't want to call the config everytime I need to use this.

Thanks!

**Comment by calcinai** [comment]
What specifically are you looking for a service provider for? Something like Silex/Symfony?

**Comment by empsean** [comment]
Well usually a package would have a config file that you can enter the details into, but this package does not and the readme has no information on how to add the configuration information and not have to load it every-time you want to use it.

**Comment by leith** [comment]
@empsean From your [SO post](https://stackoverflow.com/questions/46841446/calcinai-xero-php-pass-config-once) I think the one you're after is https://github.com/amochohan/xerolaravel
