### ISSUE TITLE
Uploading attachments

### ISSUE THREAD

**Issue by drawmyattention** [calcinai/xero-php#32]
Given I have an existing invoice, how would I add an attachment to that invoice?

There is no attachment model, and looking at the ```Save()``` method on the ```Application``` class, there's no way for the file to be saved that I can determine.

**Comment by drawmyattention** [comment]
My issue isn't relating to downloading PDFs, or other existing invoice attachments. I'm referring more to the ability to POST a brand new attachment to the Attachments endpoint as per http://developer.xero.com/documentation/api/attachments/

**Comment by calcinai** [comment]
Yep - I'm about to push a fix for both.

**Comment by calcinai** [comment]
You can use it like this:

```php
$attachment = \XeroPHP\Models\Accounting\Attachment::createFromLocalFile('image.jpg');
$invoice = $xero->loadByGUID('Accounting\\Invoice', '[GUID]');
$invoice->addAttachment($attachment);
```

and fetch them like:
```php
$invoice = $xero->loadByGUID('Accounting\\Invoice', '[GUID]');
$attachments = $invoice->getAttachments();
...
$attachment->getContent(); //Will contain the binary content of the file.
```

Let me know if you fun into any issues.

**Comment by drawmyattention** [comment]
Just checked out the latest version, and having an issue with the file that gets created within Xero.

Using the exact same code that you've posted above, I can see the file gets created in Xero as can see it is listed along with the invoice that I've associated it to. 

However, when I try to view the attachment (via the code above, or even directly within Xero) I get either a blank white document, or 'Failed to load PDF document'.

I've tried three different PDF documents, each from different sources.

**Comment by calcinai** [comment]
Hey,

I've just been doing some testing too, and I'm getting the same thing.  The ```->getContent()``` method seems to contain the correct data, as if I set the content-type header in my test script and echo it, it shows.  I'm just about to do a diff and see where the discrepancy is.

**Comment by drawmyattention** [comment]
Whilst trying to debug what may be going on, I noticed the '?IncludeOnline=true' flag:

> You can set an attachment to be included with the invoice when viewed online (through Xero). This functionality is available for accounts receivable invoices and accounts receivable credit notes. To enable an attachment to be viewed with the online invoice add the parameter IncludeOnline=true to the end of your request.

However, when appending that to the endpoint url the request throws an Exception ```Failed to validate signature```.

The ```addAttachment()``` method sends the request twice, was this intentional?

**Comment by calcinai** [comment]
No, (neither is the print_r in there!).  No idea how that slipped through, I think it's to do with the content-encoding - it's uploading it as UTF-8, when it's binary.

**Comment by calcinai** [comment]
>However, when appending that to the endpoint url the request throws an Exception Failed to validate signature.
You need to use ```$request->addParameter()``` as the query string params are signed in the oath token.

**Comment by calcinai** [comment]
I've tried now using the file handle directly as ```CURLOPT_INFILE``` with no luck either.  Will keep digging.  Aside from the obvious (print_r & double send) the only problem seems to be the content encoding curl uses to send the file..

**Comment by drawmyattention** [comment]
How are you setting the headers? Within ```Request```, in the ```send()``` method I've tried adding:

```$this->setHeader('Content-type', 'multipart/form-data');

before the ```$header_array``` variable is built, but this results in ```Undefined index: message``` in the response.
