### ISSUE TITLE
Public oauth working for demo company, but not a live company

### ISSUE THREAD

**Issue by mogilvie** [calcinai/xero-php#324]
Hi, 
I'm not sure if this is a xero-php issue or a xero issue or my own!

My public oauth process works fine for the demo company, but fails with "Failed to validate signature" on any other live company.

I'm at a loss to understand why. The requests are identical except for the oauth_token, oauth_verifier and org.

This is successfull (when authorising the Demo organisation);

Request {#412 ▼
  -app: PublicApplication {#404 ▼
    #config: array:3 [▼
      "xero" => array:6 [▼
        "site" => "https://api.xero.com"
        "base_url" => "https://api.xero.com"
        "core_version" => "2.0"
        "payroll_version" => "1.0"
        "file_version" => "1.0"
        "model_namespace" => "\XeroPHP\Models"
      ]
      "oauth" => array:8 [▼
        "signature_method" => "HMAC-SHA1"
        "signature_location" => "header"
        "authorize_url" => "https://api.xero.com/oauth/Authorize"
        "request_token_path" => "oauth/RequestToken"
        "access_token_path" => "oauth/AccessToken"
        "callback" => "http://localhost:8001/xerotaxrate/select?oauth_token=NXYVZWE6QJYPJLN01YKUW7JXUMFO24&oauth_verifier=2217428&org=Dz4t6VbpZqownF4-XiM8Om"
        "consumer_key" => "MYAPPCONSUMERKEY"
        "consumer_secret" => "MYAPPCONSUMERSECRET"
      ]
      "curl" => array:9 [▼
        10018 => "Parolla Tools Test App"
        78 => 30
        13 => 20
        64 => 2
        81 => 2
        52 => false
        10004 => false
        10006 => false
        10102 => ""
      ]
    ]
    #oauth_client: Client {#413 ▼
      -config: array:9 [▼
        "signature_method" => "HMAC-SHA1"
        "signature_location" => "header"
        "authorize_url" => "https://api.xero.com/oauth/Authorize"
        "request_token_path" => "oauth/RequestToken"
        "access_token_path" => "oauth/AccessToken"
        "callback" => "http://localhost:8001/xerotaxrate/select?oauth_token=NXYVZWE6QJYPJLN01YKUW7JXUMFO24&oauth_verifier=2217428&org=Dz4t6VbpZqownF4-XiM8Om"
        "consumer_key" => "MYAPPCONSUMERKEY"
        "consumer_secret" => "MYAPPCONSUMERSECRET"
        "token" => "NXYVZWE6QJYPJLN01YKUW7JXUMFO24"
      ]
      -request: null
      -oauth_params: null
      -token_secret: "TOWZ7HUYLJUK0HM09OELOH9VKFZWIN"
      -verifier: "2217428"
    }
  }
  -url: URL {#396 ▼
    -base_url: "https://api.xero.com"
    -endpoint: "AccessToken"
    -is_oauth: true
    -path: "oauth/AccessToken"
  }
  -method: "GET"
  -headers: array:1 [▼
    "Accept" => "text/xml"
  ]
  -parameters: []
  -body: null
  -response: null
}

============================
This is unsuccessful when authorising my Ogilvie Consulting Ltd organisation.

Request {#412 ▼
  -app: PublicApplication {#404 ▼
    #config: array:3 [▼
      "xero" => array:6 [▼
        "site" => "https://api.xero.com"
        "base_url" => "https://api.xero.com"
        "core_version" => "2.0"
        "payroll_version" => "1.0"
        "file_version" => "1.0"
        "model_namespace" => "\XeroPHP\Models"
      ]
      "oauth" => array:8 [▼
        "signature_method" => "HMAC-SHA1"
        "signature_location" => "header"
        "authorize_url" => "https://api.xero.com/oauth/Authorize"
        "request_token_path" => "oauth/RequestToken"
        "access_token_path" => "oauth/AccessToken"
        "callback" => "http://localhost:8001/xerotaxrate/select?oauth_token=JVYI9D95PON8LPQROK71GQUAEQTWNT&oauth_verifier=5055671&org=NcvQs%24sSIaklS7Xr-R2thG"
        "consumer_key" => "MYAPPCONSUMERKEY"
        "consumer_secret" => "MYAPPCONSUMERSECRET"
      ]
      "curl" => array:9 [▼
        10018 => "Parolla Tools Test App"
        78 => 30
        13 => 20
        64 => 2
        81 => 2
        52 => false
        10004 => false
        10006 => false
        10102 => ""
      ]
    ]
    #oauth_client: Client {#413 ▼
      -config: array:9 [▼
        "signature_method" => "HMAC-SHA1"
        "signature_location" => "header"
        "authorize_url" => "https://api.xero.com/oauth/Authorize"
        "request_token_path" => "oauth/RequestToken"
        "access_token_path" => "oauth/AccessToken"
        "callback" => "http://localhost:8001/xerotaxrate/select?oauth_token=JVYI9D95PON8LPQROK71GQUAEQTWNT&oauth_verifier=5055671&org=NcvQs%24sSIaklS7Xr-R2thG"
        "consumer_key" => "MYAPPCONSUMERKEY"
        "consumer_secret" => "MYAPPCONSUMERSECRET"
        "token" => "JVYI9D95PON8LPQROK71GQUAEQTWNT"
      ]
      -request: null
      -oauth_params: null
      -token_secret: "P9HIDB8FW19ZDUWH09ZMLSVHH3LSDG"
      -verifier: "5055671"
    }
  }
  -url: URL {#396 ▼
    -base_url: "https://api.xero.com"
    -endpoint: "AccessToken"
    -is_oauth: true
    -path: "oauth/AccessToken"
  }
  -method: "GET"
  -headers: array:1 [▼
    "Accept" => "text/xml"
  ]
  -parameters: []
  -body: null
  -response: null
}
 

The only difference I can see is the oauth token, verifier and org. So I am at a loss as to why one request works and the other fails.

**Comment by mogilvie** [comment]
Turns out i needed to uncomment signature_location in the config.
Not sure why, but it works now.

**Comment by calcinai** [comment]
Ah, now you mention that, I think someone else had an issue with this in the past.  By default the signature goes in the query string, but the spec says it can be in the header (but that doesn't always work)
