### ISSUE TITLE
Checking for error messages when recording payment to invoice?

### ISSUE THREAD

**Issue by ashleydance** [calcinai/xero-php#325]
Hi, I'm currently building an application that takes payments from Stripe and then marks the payment against the invoice in Xero.

Currently, my application is working fine, but I want to include some try catch statements to check for errors.

How would I go about checking the invoice has been successfully marked as paid with the code below?

        $invoice = XeroPrivate::loadByGUID("Accounting\\Invoice", $request->input("inv-reference") );
        $account = XeroPrivate::loadByGUID("Accounting\\Account", env("XERO_BANK_ID") );

        $dateInstance = new \DateTime();

        // Create a new payment in Xero
        $newPayment = new \XeroPHP\Models\Accounting\Payment();
        $newPayment
            ->setInvoice($invoice)
            ->setAccount($account)
            //->setDate($dateInstance)
            ->setAmount( $request->input('inv-amount') )
            ->setIsReconciled(true)
            ->setReference( 'Sixth Story - ' . $request->input('inv-reference') );

        // Save the payment in Xero
        $posted_payment = XeroPrivate::save($newPayment);

**Comment by williamrenfrew** [comment]
We only push using saveAll as we bulk them through, but you may find something like the below helpful/point you in the right direction:

```php $responses = $xero->saveAll($sendPayments);
foreach ($responses->getElements() as $key => $posted_payment) {
 if (isset($posted_payment['ValidationErrors']) && is_array($posted_payment['ValidationErrors'])) {
 // Payment failed and the error is in $posted_payment['ValidationErrors']
 } 
} `

In your case, $posted_payment may have the returned $posted_payment['ValidationErrors'], I can't remember the save() syntax off top of my head.

**Comment by Healyhatman** [comment]
`
            $response = $xero->saveAll($invoices, true, true);
            $errors = $response->getElementErrors();`

$errors will be an array, and the index will match the index you passes in save all. So if invoices is `[$badInvoice, $goodInvoice, $badInvoice]` then errors will be `[0 => $error, 2 => $anotherError]`

**Comment by calcinai** [comment]
Thanks @Healyhatman
