### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by stralytic** [calcinai/xero-php#326]
Use of the keyword "object" is not allowed in any case in PHP 7.2, which prevents the use of XeroPHP with this version of PHP.

`Compile Error: Cannot use 'XeroPHP\Remote\Object' as class name as it is reserved`

**Comment by circle314** [comment]
Good catch @stralytic , I imagine the circumstances around finding this were unfortunate. I would have encountered it myself but for the fact that our codebase won't immediately benefit from 7.2, and I planned on moving to 7.3 instead once that's out.

The comments on the class mention the following:

> todo - at 2.x, move this into the root of the project and refer to it as a model

@calcinai how far off is 2.x? Given this is a showstopper for anyone on PHP7.2 (and they're already working on PHP7.3) could this change be implemented in a v1.7 as a stopgap?

**Comment by calcinai** [comment]
I *think* so, but it might be prudent to keep a class called `Object` in there extending whatever it is renamed to unless there is some type hinting somewhere on others' code.  Thoughts?

I had a chat to Xero a couple of days ago about moving forward - it looks like they're wanting to allocate a bit of response to this project, so watch this space. We went through a rough plan of where things are headed.

**Comment by calcinai** [comment]
What was I thinking calling it `Object` anyway! It's hardly descriptive.

**Comment by circle314** [comment]
Leaving it in there is fine, only so long as your composer.json file requires PHP <=7.1.*, though I would think that a safety measure rather than a future ready requirement. I've had the same problems with code I've written, sudden unexpected reserved word Colossians that is. It's gut wrenching :(

**Comment by ilijastuden** [comment]
Now that PHP 7.2 is stable, this issue is causing brave souls that upgraded. What is the more descriptive name that you wanted to use? Maybe we can contribute a fix.

**Comment by calcinai** [comment]
I think I'd thought to call it `Model` based on comments in the code! If you could submit a PR I'd happily review and merge it.

**Comment by nigel-binaryio** [comment]
Thanks mattmcardle, appreciate your work here

**Comment by ilijastuden** [comment]
Hi @calcinai 

I went to the mountains and brought only iPad, so I could not prepare and send a fix. When do you expect to have @nigel-binaryio's MR merged?

**Comment by graphem** [comment]
Any news on this? Active Collab self hosted is broken on PHP 7.2 because of this. Thanks for all your work!!

**Comment by calcinai** [comment]
Will test this afternoon and merge! Sorry for the delay
