### ISSUE TITLE
Contact - property 'Website' is not set

### ISSUE THREAD

**Issue by neeon-li** [calcinai/xero-php#329]
I found a strange case, but I haven't found the reason yet.

The code is:
```
$contact = new \XeroPHP\Models\Accounting\Contact($xero);
$contact->setName($companyName);
$contact->setWebsite('www.google.com');
$contact->save();

// ------------------------------------
// Test cahce
$websiteInCache = $contact->getWebsite();
echo websiteInCache."<br>";

// ------------------------------------
// Test Xero
$createdContact = $xeroconnection->loadByGUID(
    'Accounting\\Contact', $contact->getContactID());
$nameInXero = $createdContact->getName();
$websiteInXero = $createdContact->getWebsite();
echo $nameInXero."<br>";
echo $websiteInXero."<br>";
```

The value of $websiteInCache is correct, but the $websiteInXero is empty.

**Comment by calcinai** [comment]
That's a strange one.  Do you know if it's actually saving it in Xero? 

i.e. by logging into the Xero UI

**Comment by neeon-li** [comment]
In Xero, at the detail page of contact (https://go.xero.com/Contacts/View/<CONTACT_UUID>), the HTML code in 'Contact Details' as
```
<div class="field website"><span><a class="xbtn exclude external doNotDisable doNotDisableOthers" id="externalLinkWebsite" href="http://www.google.com" target="_blank">http://www.google.com<span>&nbsp;</span></a></span></div>
```

Also at the edit page (https://go.xero.com/Contacts/Edit.aspx?contactID=<CONTACT_UUID>)
```
<input autocomplete="off" type="text" id="Website" name="Website" maxlength="200" value="http://" placeholder="http://www.website.com" style="width:222px;">
```

And then when submitting edited value with POST request, the body shows that it uses 'Website' as the key name.
![screen shot 2017-12-15 at 9 10 03 am](https://user-images.githubusercontent.com/25143608/34022372-d3657ea4-e179-11e7-9f39-47e92b8c8482.png)
By this 3 point, the key name `Website` should be correct.


Also, I tried to change `Contact.php` from `Website` to `website` with no success.
```
    /**
     * @return string
     */
    public function getWebsite()
    {
        return $this->_data['website'];
    }

    /**
     * @param string $value
     * @return Contact
     */
    public function setWebsite($value)
    {
        $this->propertyUpdated('website', $value);
        $this->_data['website'] = $value;
        return $this;
    }
```

**Comment by neeon-li** [comment]
I think this should be the reason.

The Contacts section in [Xero API Docs](https://developer.xero.com/documentation/api/contacts) mention `Website` exist in `GET Contacts` (GET method) but not exist in `POST Contacts` (POST method).

Therefore `Website` is not available to update through the API.

**Comment by neeon-li** [comment]
I think to use the `SkypeUserName` is a way of replacing `Website`, although it is odd to do this.

Sadly this case is already mentioned in [User Voice](https://xero.uservoice.com/forums/5528-xero-accounting-api/suggestions/3366184-website-url-in-api-feed) at 2012. And still not fix this problem.
