### ISSUE TITLE
Exception when trying to use attachments

### ISSUE THREAD

**Issue by jammin88** [calcinai/xero-php#330]
We're getting a `Uncaught exception 'XeroPHP\Remote\Exception\UnauthorizedException' with message 'Failed to validate signature'`

When trying to add attachments.  Tried with/without MIME type set manually, tried using binary method... always receive this exception?

```
$attachment = new XeroPHP\Models\Accounting\Attachment($xero);

$attachment->createFromLocalFile("images/logo.jpg","image/jpg");

//$attachment->createFromBinary("data,test,test", "filename.csv","text/csv");

$spend->addAttachment($attachment);
```

**Comment by calcinai** [comment]
That's interesting. Have you looked in the API history for the specific request/response? This could shed some more light on it

**Comment by jammin88** [comment]
Doesn't show in the API history.... guessing because it doesn't send it as it can't validate the signature...?

**Comment by jammin88** [comment]
Here's the full trace... think this may help a bit more!

`Fatal error: Uncaught exception 'XeroPHP\Remote\Exception\UnauthorizedException' with message 'Failed to validate signature' in /var/www/vhosts/xx.co.uk/orders/vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php:85

Stack trace: 

#0 /var/www/vhosts/xx.co.uk/orders/vendor/calcinai/xero-php/src/XeroPHP/Remote/Request.php(109): XeroPHP\Remote\Response->parse() 

#1 /var/www/vhosts/xx.co.uk/orders/vendor/calcinai/xero-php/src/XeroPHP/Traits/AttachmentTrait.php(27): XeroPHP\Remote\Request->send() 

#2 /var/www/vhosts/xx.co.uk/orders/xero/xeroPost.php(217): XeroPHP\Models\Accounting\BankTransaction->addAttachment(Object(XeroPHP\Models\Accounting\Attachment)) 

#3 /var/www/vhosts/xx.co.uk/orders/xero/xeroPost.php(45): postReceiveMoneyToXero(Object(XeroPHP\Application\PrivateApplication), '16DCB6809BD44F5...', 4001, 0.01, 'testing', '16d1045b-55f9-4...') 

#4 {main} thrown in /var/www/vhosts/xx.co.uk/orders/vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php on line 85`

**Comment by jammin88** [comment]
Ok, some more digging...

Looks like the `$this->getGUID()` call on line 17 of the AttachmentTrait class is returning an empty string... so the request is being sent to:

`https://api.xero.com/api.xro/2.0/BankTransactions//Attachments/logo.jpg` 

Note the double slash, which should contain the GUID of the associated bank transaction we're attaching this to.

**Comment by jammin88** [comment]
Resolved... There is (obviously..) no GUID on the transaction until it's been saved.

Need to call ->save() on the transaction, then add the attachment. Makes sense when brain engaged!
