### ISSUE TITLE
Adding new reports

### ISSUE THREAD

**Issue by michael-capitalbay** [calcinai/xero-php#332]
Hi, 

how can I add new reports.
For example I want to generate the AgedReceivables report, which requires customerId as a parameter. how do I add a report like that?

I am using laravel 5.5 as my framework.

Thanks :)

**Comment by calcinai** [comment]
You might need to look in the https://github.com/calcinai/xero-php/tree/master/src/XeroPHP/Models/Accounting/Report folder to get an idea how the existing ones work. How is the `customerId` passed? Is it possible to overload the request?

**Comment by michael-capitalbay** [comment]
Thanks a lot for your reply.
Turns out it was actually a "stupid developer" error - the parameter is ContactID not CustomerID.
Once I figured out that I need new glasses and changed to the right parameter everything worked ok :)
Thanks
