### ISSUE TITLE
Replacing cURL with Guzzle

### ISSUE THREAD

**Issue by Josh-G** [calcinai/xero-php#333]
Currently the library is using cURL to make requests to Xero, would there be any push back if I was to send a pull request to use [guzzlehttp/guzzle](https://github.com/guzzle/guzzle) under the hood instead?

Having the library support Guzzle would bring some benefits to our application in particular (as an example) as we would be able to add middlewares, which would be a huge gain for us. In particular, we would be able to add a retry middleware, debug middlewares etc

Our biggest use case for this would absolutely be a retry middleware. We've currently added our own retry functionality by extending some of the library classes and redirecting some method calls, but it's a very unwieldy hack.

**Comment by calcinai** [comment]
This is a great idea, would you be interested in helping with the next major?

**Comment by calcinai** [comment]
Have you seen #4? I think most of the issues there are no longer a problem

**Comment by Josh-G** [comment]
Absolutely 👍  glad to see there has already been interest in this. I will start looking to prepare a pull request as soon as I can.

**Comment by calcinai** [comment]
I'm going to close this one in favour of #4
