### ISSUE TITLE
TLS 1.0 Deprecation

### ISSUE THREAD

**Issue by edegaudenzi** [calcinai/xero-php#340]
Hi Calcinai, 

Just received from Xero the advice for TLS 1.0 deprecation. [Official doc here](https://developer.xero.com/tls1-deprecation?mkt_tok=eyJpIjoiTVRjMllURTJNamcyWTJKbSIsInQiOiJ2d015YkRnMUJmdStaZGdGNEg4YzhuN1R4aTFZVTNzUHRsQTZFQ0xKeEc1YVd0NXU4S0ExVUdaUEhWc3hvTjhxazJzWHVKazFNWWdZSFQ3dFBmdmZcL1RIOVBBeUR5QTloTVQzXC9OdHZDd051Sk9zcWloS2NWUEQzOFdVdlhHeno4In0%3D)

is xero-php already ready to go or does it need this implementation?

**Comment by calcinai** [comment]
Haha, I heard from them a few days ago that this was going to happen, but as I said to them, it's going to come down to the version of OpenSSL you have installed.  Support for TLS 1.1 came in OpenSSL 1.0.1 (circa 2012), so it'll come down to specific deployments.

I understand that they're going to set up a test endpoint (with no TLS 1.0 support) to test, like they did for the SSL migration a couple of years ago.  Once that's up, you'll be able to test your deployment against that.

I'll leave this open in case someone else is looking for info over the next little while.

**Comment by edegaudenzi** [comment]
Quick and explainful, tx man!

**Comment by joshbenham** [comment]
Hey @calcinai just so I understand. If my server already has TLS 1.1 and 1.2 installed should this package work automatically?

Or is there more to it?

**Comment by calcinai** [comment]
@joshbenham you should be fine.

Depending on your environment (if it's *nix) you could do something like `php -i | grep -i 'OpenSSL \d\.\d\.\d\w'` to see the version

**Comment by edegaudenzi** [comment]
Thanks for the command @calcinai! Here I anyway propose a command that explicitly tells you what version your server is using (taken from [here](https://stackoverflow.com/questions/27430158/how-to-find-out-the-supported-ssl-tls-versions-for-specific-openssl-built)):

`openssl ciphers -v | awk '{print $2}' | sort | uniq`

Hope it is helpful!

**Comment by calcinai** [comment]
@edegaudenzi thanks for that. I’m happy to be corrected, but is it possible that there could be a different binary linked to the php install?

**Comment by joshbenham** [comment]
Hey @calcinai 

Unfortunately this environment is a tiny bit old and runs 5.6 PHP

`
[~/project/website]# /usr/local/bin/php -i | grep 'OpenSSL [^\s]'
OpenSSL Library Version => OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL Header Version => OpenSSL 1.0.1e-fips 11 Feb 2013
`

However the other command showed

`
[~/project/website]# openssl ciphers -v | awk '{print $2}' | sort | uniq
SSLv3
TLSv1.2
`

So I am a tiny bit confused here.

**Comment by calcinai** [comment]
@joshbenham the first command is showing the OpenSSL version linked to PHP, `1.0.1e`

If you look at the OpenSSL [changelog](https://web.archive.org/web/20150120120428/https://www.openssl.org/news/openssl-1.0.1-notes.html), you'll see that **TLS 1.2/1.2 support came from OpenSSL 1.0.1 onward**, so you've got support and the various TLS bug fixes that followed.

Obviously the newer version the better, bearing in ming that [Heartbleed](http://heartbleed.com) was only patched at `1.0.1g`, which is obviously not great on a webserver.

**Comment by Josh-G** [comment]
To check exactly which version of OpenSSL that your cURL was built against, you should run the following: `php -r "echo curl_version()['ssl_version'];"` as this can differ from the version that PHP was built against.

For example, one of our production servers has:
OpenSSL Library Version => OpenSSL 1.1.0g  2 Nov 2017
OpenSSL Header Version => OpenSSL 1.1.0g  2 Nov 2017
but cURL was built against:
```
$ php -r "echo curl_version()['ssl_version'];"
OpenSSL/1.0.2g
```

**Comment by calcinai** [comment]
@Josh-G awesome, thanks for that.
