### ISSUE TITLE
Should getSalesDetails by Sale[] or just Sale

### ISSUE THREAD

**Issue by bretto36** [calcinai/xero-php#342]
https://github.com/calcinai/xero-php/blob/8ad5cf1ace1dc42075ac03d9376217606cb2dfe3/src/XeroPHP/Models/Accounting/Item.php#L73

From the Docs $item->getSalesDetails() should return a single object, not a collection. 

      "SalesDetails": {
        "UnitPrice": 40.0000,
        "AccountCode": "200",
        "TaxType": "OUTPUT2"
      },

The type hint indicates it's returning an array of Sale objects. Should we change the type hinting on both the getSalesDetails and the property at the line specified above?

**Comment by calcinai** [comment]
This has been fixed
