### ISSUE TITLE
Invoice not creating after set DueDate in invoice

### ISSUE THREAD

**Issue by mayankvadiya** [calcinai/xero-php#343]
I am trying to create new invoice into xero with 'AUTHORISED' status, but after set status 'AUTHORISED' it require DueDate, when I set DueDate it will not working. My code is looks like as below.
 
```
         $xeroInvoice = new Invoice($xero);
         $xeroInvoice->setType(Invoice::INVOICE_TYPE_ACCREC);
         $xeroInvoice->setStatus(Invoice::INVOICE_STATUS_PAID);
         $xeroInvoice->setDueDate('2018-09-20');
         $xeroInvoice->setLineAmountType(Invoice::LINEAMOUNT_TYPE_EXCLUSIVE);
	 $contact = $xero->loadByGUID('Accounting\\Contact', '30a67a6e-109f-4462-896b-335058926e7f');
	 $xeroInvoice->setType('ACCREC')->setContact($contact)->setReference('123456');
	$xeroLineItem = new LineItem($xero);
	$xeroLineItem->setQuantity(1);
	$xeroLineItem->setDescription('Test Item1');
	$xeroLineItem->setUnitAmount('1000.00');

	$xeroInvoice->addLineItem($xeroLineItem);

	$xeroInvoice->save();
```
`
I have set YYYY-MM-DD format as per document, still its not working

**Comment by calcinai** [comment]
What's the error you're getting? I suspect it's because you're not passing a `DateTime` object in.

**Comment by mayankvadiya** [comment]
@calcinai  I have solved out this error but now i can't access `status` key of response, like something as below
```
$response=$xeroInvoice->save();
echo $response->status;
```

It will fire an exception like **Cannot access private property XeroPHP\Remote\Response::$status**

**Comment by calcinai** [comment]
@mayankvadiya That's what I'd expect; have you had a look at the `Response` class?  In there you'll see which methods are available.
