### ISSUE TITLE
Can't update existing employee

### ISSUE THREAD

**Issue by Healyhatman** [calcinai/xero-php#346]
I'm trying to update an employee - the Xero documentation on PayrollAU/Employee says 
`

> Use this method to create, update or delete one or more payroll employee items.

`

but I can't figure it out. 

What I'm trying to do is to get all the employees in a group (which works), loop through them (works) and give them a new Pay Template. When I do $employee->save() though I get "XeroPHP\Models\PayrollAU\Employee::$HomeAddress is mandatory and is either missing or empty."

If I instead get all the employees in the group and then for each one do loadByGuid($employee->getEmployeeId()), set the new pay template, and then save(), I get "A validation exception occurred (The superannuation fund is required)". 

As far as I can tell in either case it's trying to add the employee as a NEW employee? Maybe? No idea.

**Comment by calcinai** [comment]
That first exception is generated client-side - if you change the Employe:: $HomeAddress property to be not required in the model, does that help?

**Comment by Healyhatman** [comment]
"A validation exception occurred (The superannuation fund is required)" it went back to

**Comment by Healyhatman** [comment]
One thing though - when you search for an employee by name as in 
`$xero->load('\\XeroPHP\\Models\\PayrollAU\\Employee')->where("FirstName", $firstName)->execute();`
It doesn't actually GET everything - for example the PayTemplate is blank. You instead have to search for the employee as above, then do getEmployeeId(), and THEN do $xero->loadByGuid.

**Comment by Healyhatman** [comment]
OK so to update the employee with the new Pay Template this is what I have had to do.

1. Get the employee by searching for them by name
2. Use getEmployeeId, and then get the employee again using loadbyguid
3. Set the new pay template, using addSuperLine with the superLine from the old PayTemplate
4. Save


Still  a bit weird I have to use loadbyguid to be able to get ALL the properties though.
