### ISSUE TITLE
Payslip PayRunID not set

### ISSUE THREAD

**Issue by JimboM4CK** [calcinai/xero-php#348]
PayrollAU
When trying to create a payslip, you have to post the Employee ID and the Pay Run ID.
The payslip model doesn't have a method to set the Pay Run ID.

**Comment by jeremyj11** [comment]
I just encountered the same issue.

Fixed by adding to Payslip.php:
`/**
     * @param string $value
     * @return Payslip
     */
    public function setPayRunID($value)
    {
        $this->propertyUpdated('PayRunID', $value);
        $this->_data['PayRunID'] = $value;
        return $this;
    }`

**Comment by jeremyj11** [comment]
pull request #359
