### ISSUE TITLE
PayrollAU Payslip line items

### ISSUE THREAD

**Issue by JimboM4CK** [calcinai/xero-php#349]
All line items that have NumberOfUnits are trying to set and return a collection. This is supposed to be a float value. 

The current method is **addNumberOfUnit** whereas it should be **setNumberOfUnits**.

**Comment by jeremyj11** [comment]
Fixed by changing addNumberOfUnits to:
`public function setNumberOfUnits($value)
    {
        $this->propertyUpdated('NumberOfUnits', $value);
        $this->_data['NumberOfUnits'] = $value;
        return $this;
    }`

and line 98 getProperties to:
` 'NumberOfUnits' => [false, self::PROPERTY_TYPE_FLOAT, null, false, false],`

**Comment by jeremyj11** [comment]
pull request #359
