### ISSUE TITLE
Webhook returns false on validate.

### ISSUE THREAD

**Issue by adriandrozdz** [calcinai/xero-php#351]
I have been trying to validate webhook with ITR on developer.xero.com as it it required to use a webhook. 

I grabbed a Webhook.php file (as this hasn't been released yet) and used it as a Helper in my Laravel project. Unfortunately the hash differes from x-xero-signature by one character whenever I sent an ITR.
Here's an example:

    HTTP_X_XERO_SIGNATURE = 8Ub1A/mg0apZUkyc3yoi+3Yap/AMLO20wvNkVC0Go2s=
    HASHED PAYLOAD = 8Ub1Anmg0apZUkyc3yoi+3Yap/AMLO20wvNkVC0Go2s=
    PAYLOAD = {"events":[],"firstEventSequence": 0,"lastEventSequence": 0, "entropy": "WXUAMNYXPMQEDHQLSISU"}

I am testing this on my local vagrant environment using ngrok app to tunnel reguests from xero webhook.

Do you happen to know why this might be the case? I am using vagrant with PHP 7.1.14

**Comment by williamrenfrew** [comment]
Xero will do this to test your ITR is working correctly and responding with the correct status so ensure that you are responding with the correct status header.

More info: https://developer.xero.com/documentation/webhooks/configuring-your-server#intent

**Comment by adriandrozdz** [comment]
@williamrenfrew so you are saying that Xero is sending a wrong xero-signature in the header intentionally so that they now I am responding with 401 in this case? 

This happens for most requests from xero so I do not this this is intentional.

**Comment by Josh-G** [comment]
About 3 of 4 requests in the ITR are purposefully invalid by a single character. If that's what you're observing, you must correctly return 401 otherwise Xero will mark the ITR as failed.

**Comment by adriandrozdz** [comment]
I understand and didn't know about it thanks for the response.

**Comment by Josh-G** [comment]
@adriandrozdz just fyi, webhooks have been released now:
https://github.com/calcinai/xero-php/releases/tag/v1.7.1
