### ISSUE TITLE
Rate Limit Counter

### ISSUE THREAD

**Issue by olimortimer** [calcinai/xero-php#352]
I'm struggling with the Xero Rate Limit, and unsure why as I'm not querying often enough to hit their limit.  Is there anything built into Xero-PHP to allow me to output the rate that I am querying at?  Ie a counter etc.

**Comment by mogilvie** [comment]
Not that I am aware of.
You could create a log on each of your query execution, or more quickly, you view your endpoint history in the Xero developer portal.
Regards,
Mark

**Comment by olimortimer** [comment]
Cheers @mogilvie

**Comment by olimortimer** [comment]
Xero include a X-Rate-Limit-Problem in the HTTP headers, which would be good to retrieve back for more information on the rate limiting.

For example; `X-Rate-Limit-Problem: Daily` or `X-Rate-Limit-Problem: Minute`

I have a solution to output this, but it's messy...
