### ISSUE TITLE
Why classes are not autoloaded?

### ISSUE THREAD

**Issue by esafwan** [calcinai/xero-php#355]
I am trying to get the basic example running. I added all my information to the example private.php. My private.php file looks as below: 

```
<?php
namespace XeroPHP;

use XeroPHP\Application\PrivateApplication

// //These are the minimum settings - for more options, refer to examples/config.php
$config = [
    'oauth' => [
        'callback'         => 'oob',        
        'consumer_key'      => 'key,
        'consumer_secret'   => 'secret',        
        'rsa_private_key'  => 'file://certs/private-key.cer',
    ],
];

$xero = new PrivateApplication($config);

 print_r($xero->load('Accounting\\Organisation')->execute());

```

**I am getting the below error:**

> Fatal error: Class 'XeroPHP\Application' not found in /Users/safwan/Code/Acquia/devdesktop/xero/xero-php2/src/XeroPHP/Application/PrivateApplication.php on line 7

**I have done the following:**

1.  I have ran `composer install` command in the root of repo.
2. I have kept the private.php file in the XeroPHP root folder. 

I am not well versed with using composer and autoloader. So chances are am not doing it the right way. Any idea where I may have gone wrong?

**Comment by calcinai** [comment]
@esafwan Classes will only be autoloaded if you require the autoloader. 

Try `include 'vendor/autoload.php';`

**Comment by calcinai** [comment]
Also, you shouldn't be using the `XeroPHP` namespace for your project files.

**Comment by esafwan** [comment]
Thanks, it's working now.
