### ISSUE TITLE
Get Timesheets by EmployeeID

### ISSUE THREAD

**Issue by jeremyj11** [calcinai/xero-php#356]
I seem unable to get timesheets with a where filter for EmployeeID. The following result in a 400 BadRequest:

$this->xero->load('PayrollAU\\Timesheet')
            ->where("EmployeeID=='295241fd-63f8-4316-b7fa-bb05d27119a9'")
            ->execute();

$this->xero->load('PayrollAU\\Timesheet')
            ->where('EmployeeID','295241fd-63f8-4316-b7fa-bb05d27119a9')
            ->execute();

Any advice anyone?

**Comment by jeremyj11** [comment]
OMG after hours or searching I found out what was wrong. This works:

$ts = $this->xero->load('PayrollAU\\Timesheet')
            ->where('EmployeeID==GUID("295241fd-63f8-4316-b7fa-bb05d27119a9")')
            ->execute();

Hope it helps someone else.

**Comment by calcinai** [comment]
@jeremyj11 - It should be automatic.

There's a method `->loadByGUID()` that you probably want to be using.

**Comment by calcinai** [comment]
Sorry, just saw you're loading by the EmployeeID.  Not sure why that wasn't happing automatically, did you dig into it at all?

**Comment by jeremyj11** [comment]
Didn't dig into it deeply.

In Models/Timesheet.php line 118 getProperties() both EmployeeID and TimesheetID are specified as PROPERTY_TYPE_STRING. Changing this to PROPERTY_TYPE_GUID made no difference.
