### ISSUE TITLE
Create PayrollAU/Employee with non-existant payrollCalendarID results in undefined index

### ISSUE THREAD

**Issue by jeremyj11** [calcinai/xero-php#357]
As in title..

Create a PayrollAU/Employee with a non existant PayrollCalendarID.
Upon calling save() on newly created Employee the following error is uncaught:

Undefined index: message

**Comment by jeremyj11** [comment]
This can be fixed by changing line 73 of Remote/Response.php from:

if (isset($this->root_error)) {

to:

if (isset($this->root_error) && isset($this->root_error['message'])) {

**Comment by calcinai** [comment]
@jeremyj11 what version of the library are you using - look at [this](https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/Response.php#L73)

**Comment by jeremyj11** [comment]
1.7
weird, I just did a composer update, I don't get that fix
