### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by gerrywastaken** [calcinai/xero-php#36]
This looks like a typo as it's the same check on both sides of the ||. However I'm not sure what it should be:

https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/Request.php#L95

**Comment by calcinai** [comment]
Good spotting.  I think cURL is smart enough to set that flag if you do a PUT anyway..

**Comment by gerrywastaken** [comment]
:+1:
