### ISSUE TITLE
Property  TypeOfUnits of LeaveType should be a string

### ISSUE THREAD

**Issue by omgwhatuser** [calcinai/xero-php#360]
Hi,

On line 123 of Models/PayrollAU/PayItem/LeaveType.php you have

`            'TypeOfUnits' => [true, self::PROPERTY_TYPE_FLOAT, null, true, false],
`

But as per Xero API docs it returns a string (ie. "Hours"), see JSON response excerpt below (extracted from https://developer.xero.com/documentation/payroll-api/payitems)

`
...
<LeaveType>
      <LeaveTypeID>f3a5f2f8-c14e-4223-ab58-4e779e0f6f2c</LeaveTypeID>
      <Name>Carer's Leave (unpaid)</Name>
     <TypeOfUnits>Hours</TypeOfUnits>
      <IsPaidLeave>false</IsPaidLeave>
      <ShowOnPayslip>false</ShowOnPayslip>
      <UpdatedDateUTC>2013-04-09T23:45:25</UpdatedDateUTC>
    </LeaveType>
...`

Is there any reasons a float[] was used for this property?

Regards,
Rafael

**Comment by calcinai** [comment]
All of these models were generated using a doc scraper, feel free to update and make a PR!
