### ISSUE TITLE
Operator '==' incompatible with operand types 'Guid?' and 'String'

### ISSUE THREAD

**Issue by Healyhatman** [calcinai/xero-php#364]
Trying to get a timesheet by EmployeeID using $xero->load. The following works:

`	$url = new \XeroPHP\Remote\URL($xero, "Timesheets", \XeroPHP\Remote\URL::API_PAYROLL);
	$request = new \XeroPHP\Remote\Request($xero, $url);
	$request->setParameter("where", 'EmployeeID=GUID("5e8464e8-4e6e-4b3c-ae6b-cd58079a31a4")');
	$request->send();`

But having trouble with the syntax converting that to a shorthand $xero-load. Probably a stupidly easy answer again!

**Comment by calcinai** [comment]
It will detect if it needs to be a GUID if the name matches i.e `Employee.EmployeeID` [here](https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/Query.php#L102), but this is not correct.  I think it should be more eager, instead accepting just `EmployeeID` and a GUID for the parameter.

Thoughts?

**Comment by Healyhatman** [comment]
I don't know why I couldn't get it before, but the following works.

`$result = $xero->load("\\XeroPHP\\Models\\PayrollAU\\Timesheet")->where('EmployeeID=GUID("' . $id . '")')->execute();`

**Comment by phena109** [comment]
@calcinai I read the code you provided. With the change you suggest it should fix the issue. But what I don't understand is why did you have that in the first place?

If I don't know the original intend or you have valid reason things should be done that way (to have the `EmployeeID.` part), I would at least change the regex to something like `/^([a-z]+\.\1)?ID$/i` to serve both sides' need.

**Comment by calcinai** [comment]
It's hard to say why I did that. It is probably safe to change.

**Comment by tonexv** [comment]
I get the same error. I wonder how to make it work when working with bank transactions? These 2 tries fail:

`$xero->load('Accounting\\BankTransaction')
   ->where('BankTransactionID', 'someidhere')
   ->execute();`

`$xero->load('Accounting\\BankTransaction')
   ->where('BankTransactionID=GUID("' . 'someidhere' . '")')
   ->execute();`

**Comment by atf2** [comment]
I have just run into the same problem, in my case trying to query on ContactID.  I have worked around the problem using tonexv's second solution but would prefer it if you could get the 2-argument version working.  The proposed regex /^([a-z]+)(\.\1)?ID$/i suffers from recognising elements such as "AmountPaid" but I guess that is mitigated by also insisting the second argument looks like a GUID.  Assuming that all GUID elements end in upper case ID there would be a small benefit in changing the regex to /^([a-zA-Z]+)(\.\1)?ID$/.

**Comment by StoyanPenev** [comment]
Hi there,
I would suggest ``` /^[a-z]+(.[a-z]+)?ID$/i ``` regex as it will catch
```Contact.ContactID, InvoiceId, EmployeeID``` etc.

The current regex ``` /^([a-z]+)\\.\\1ID$/i ``` will catch **only strings with dots** like 
Contact.ContactID also putting constraint on the string after the dot ```ContactID``` to be the same as the one before the dot but with ID at the end (due to the ```\\1``` part) but will fail for all others. If for some reason Xero has Contact.EmployeeID it will fail.

So the only change needed to fix this for all guids is to update
 ``` /^([a-z]+)\\.\\1ID$/i ``` to ``` /^[a-z]+(.[a-z]+)?ID$/i ``` if we want to remove the constraint I mentioned above or
 ``` /^([a-z]+)\\.\\1ID$/i ``` to ```/^([a-z]+)(\\.\\1)?ID$/i``` to preserve that constraint but allow for guids without dot notation like InvoiceID.

@calcinai I can open a pull request if this will accelerate the issue being fixed :)

**Comment by calcinai** [comment]
@StoyanPenev I've done  search of all the models and I can't see anything that's using this format that's not a uuid.

Fee free to make a PR.  Thanks!
