### ISSUE TITLE
Deleting Payment

### ISSUE THREAD

**Issue by waqashassan98** [calcinai/xero-php#365]
Hi

I am trying to delete a payment by GUID (Authorised), but I am getting this error:
Uncaught XeroPHP\Remote\Exception\BadRequestException: A validation exception occurred (Only Status accepted for updates)
Validation errors:
Only Status accepted for updates. in /home/xaizarco/public_html/xero-op/vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php:76

Here is my code:
```
$payment = $xero->loadByGUID('Accounting\\Payment', $transaction["xero_payment_id"]);
$payment->setStatus('DELETED');
//$payment->setStatus(\XeroPHP\Models\Accounting\Payment::PAYMENT_STATUS_DELETED);
$payment->save();
```

**Comment by williamrenfrew** [comment]
Here is what we use. The two differences appear to be that we instantiate a new Xero payment and use the static variable rather than a string for the new status, but I see you've commented that out at line 3 so have tried that.

```php 
$check_payment = $xero->loadByGUID('Accounting\\Payment', $payment_guid);
if ($check_payment->getStatus() == \XeroPHP\Models\Accounting\Payment::PAYMENT_STATUS_AUTHORISED) {
   $xero_payment = new \XeroPHP\Models\Accounting\Payment();
   $xero_payment->setGUID($payment_guid);
   $xero_payment->setStatus(\XeroPHP\Models\Accounting\Payment::PAYMENT_STATUS_DELETED);
   $xero->save($xero_payment);
}

**Comment by waqashassan98** [comment]
Thanks @williamrenfrew 
Let me try that

**Comment by waqashassan98** [comment]
Great That is working
