### ISSUE TITLE
Undefined index: InvoiceID

### ISSUE THREAD

**Issue by pjw345** [calcinai/xero-php#368]
/vendor/calcinai/xero-php/src/XeroPHP/Models/Accounting/Invoice.php on line 680

The loadInvoice function is a function that performs a remote query based on the InvoiceNumber 

* @var \XeroPHP\Models\Accounting\Invoice $i */
$i = $xero->loadInvoice($invoice->getIncrementId());
if ($i && $i->getInvoiceID() && $i->getStatus() == \XeroPHP\Models\Accounting\Invoice::INVOICE_STATUS_PAID) {
                        $paid = true;
}

Surely if an invoice exists in Xero it should have an InvoiceID but regardless shouldn't the getter perform an isset?

**Comment by calcinai** [comment]
It absolutely should - no idea why I thought it was a good idea - maybe I was aiming it would always have all the keys?

Moving forward, I'll make a not of this to add (obviously a lot of work to add to all properties of all models), but you can still do an `isset($invoice->InvoiceID)`.  I know not the most elegant..
