### ISSUE TITLE
Wrong Sale class used in Item

### ISSUE THREAD

**Issue by jrmadsen67** [calcinai/xero-php#37]
https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Models/Accounting/Item.php

should use:

use XeroPHP\Models\Accounting\Item\Sale;
(not Organization)

and line 112:
change to:
'SalesDetails' => array (false, self::PROPERTY_TYPE_OBJECT, 'Accounting\\Item\\Sale', true, false)

if I get a change, will do a PR, but to get the knowledge out for now

**Comment by jrmadsen67** [comment]
I think this was mistakenly closed? I don't see the file I mentioned among the 6 modified

**Comment by calcinai** [comment]
50fd08e was the generate update to correctly parse properties
6be314c were the resulting models

**Comment by jrmadsen67** [comment]
there they are - sorry!

Thanks for all the work on this, btw! Great job!

**Comment by calcinai** [comment]
Sweet as.
