### ISSUE TITLE
Different endpoints returning dates as different timezones

### ISSUE THREAD

**Issue by Healyhatman** [calcinai/xero-php#371]
My mission for pretty much the last DAY AND A HALF has been trying to get the dates on my timesheet entry system working and I just can't figure it out, let alone figure it out in a way that I know won't break when my back is turned...

I load all the payroll calendars from Xero, and all their startdates are in Australia/Sydney timezone, like this
```
DateTime Object
(
    [date] => 2018-05-01 00:00:00.000000
    [timezone_type] => 3
    [timezone] => Australia/Sydney
)
```

I get timesheets from the last 2 weeks for a selection of workers, and THEIR dates are in Zulu, like this
```
DateTime Object
(
    [date] => 2018-05-01 00:00:00.000000
    [timezone_type] => 2
    [timezone] => Z
)
```

Obviously this makes comparing them a nightmare when trying to see if a recent timesheet exists already for the current calendar period. But even worse is trying to update that existing timesheet with new information. Keeps telling me 

> A validation exception occurred (Provided period doesn't correspond with a pay period) Validation errors: Provided period doesn't correspond with a pay period

What am I missing here, what am I doing wrong?

**Comment by Healyhatman** [comment]
Any tips @calcinai ? I've been stuck at this point for two days now and unsure how to proceed.

**Comment by calcinai** [comment]
Are you able to pose the relevant XML?

**Comment by Healyhatman** [comment]
Request
`<Timesheets><Timesheet><EmployeeID>79e3c545-b16d-4226-8cd6-4f3c4477ac54</EmployeeID><StartDate>2018-05-01</StartDate><EndDate>2018-05-07</EndDate><TimesheetLines><TimesheetLine><EarningsRateID>4d71d176-4362-4946-958a-d19562535875</EarningsRateID><NumberOfUnits><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>5</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit></NumberOfUnits></TimesheetLine><TimesheetLine><EarningsRateID>a052c1b7-f09f-4830-93dc-be244be40cc6</EarningsRateID><NumberOfUnits><NumberOfUnit>2</NumberOfUnit><NumberOfUnit>2</NumberOfUnit><NumberOfUnit>2</NumberOfUnit><NumberOfUnit>2</NumberOfUnit><NumberOfUnit>2</NumberOfUnit><NumberOfUnit>6</NumberOfUnit><NumberOfUnit>2</NumberOfUnit></NumberOfUnits></TimesheetLine></TimesheetLines><TimesheetID>162760e3-9b9f-4162-b50d-a992419139a3</TimesheetID></Timesheet><Timesheet><EmployeeID>fe1bb1cd-197a-4585-ae89-a9b22dfcda29</EmployeeID><StartDate>2018-05-01</StartDate><EndDate>2018-05-07</EndDate><TimesheetLines><TimesheetLine><EarningsRateID>4d71d176-4362-4946-958a-d19562535875</EarningsRateID><NumberOfUnits><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>5</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit></NumberOfUnits></TimesheetLine></TimesheetLines><TimesheetID>162760e3-9b9f-4162-b50d-a992419139a3</TimesheetID></Timesheet></Timesheets>`

Response
`<Response xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Id>a9fe9a8a-be3c-4d6b-9756-9d1e804a351c</Id><ProviderName>Onboarding</ProviderName><ErrorNumber>10</ErrorNumber><Type>ValidationException</Type><Message>A validation exception occurred</Message><Timesheets><Timesheet><TimesheetID>162760e3-9b9f-4162-b50d-a992419139a3</TimesheetID><EmployeeID>79e3c545-b16d-4226-8cd6-4f3c4477ac54</EmployeeID><StartDate>2018-05-01T00:00:00</StartDate><EndDate>2018-05-07T00:00:00</EndDate><TimesheetLines><TimesheetLine><EarningsRateID>4d71d176-4362-4946-958a-d19562535875</EarningsRateID><NumberOfUnits><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>5</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit></NumberOfUnits></TimesheetLine><TimesheetLine><EarningsRateID>a052c1b7-f09f-4830-93dc-be244be40cc6</EarningsRateID><NumberOfUnits><NumberOfUnit>2</NumberOfUnit><NumberOfUnit>2</NumberOfUnit><NumberOfUnit>2</NumberOfUnit><NumberOfUnit>2</NumberOfUnit><NumberOfUnit>2</NumberOfUnit><NumberOfUnit>6</NumberOfUnit><NumberOfUnit>2</NumberOfUnit></NumberOfUnits></TimesheetLine></TimesheetLines></Timesheet><Timesheet><ValidationErrors><ValidationError><Message>Provided period doesn't correspond with a pay period</Message></ValidationError></ValidationErrors><TimesheetID>162760e3-9b9f-4162-b50d-a992419139a3</TimesheetID><EmployeeID>fe1bb1cd-197a-4585-ae89-a9b22dfcda29</EmployeeID><StartDate>2018-05-01T00:00:00</StartDate><EndDate>2018-05-07T00:00:00</EndDate><TimesheetLines><TimesheetLine><EarningsRateID>4d71d176-4362-4946-958a-d19562535875</EarningsRateID><NumberOfUnits><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>5</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit><NumberOfUnit>1</NumberOfUnit></NumberOfUnits></TimesheetLine></TimesheetLines></Timesheet></Timesheets></Response>`

**Comment by Healyhatman** [comment]
Here's the relevant payroll calendar

PayrollCalendarID: 3d55a5c5-3628-4d3f-b26b-9e2e525f33bf
Name: Weekly Tuesday Payroll
CalendarType: WEEKLY
StartDate: DateTime Object
(
    [date] => 2018-05-01 00:00:00.000000
    [timezone_type] => 3
    [timezone] => Australia/Sydney
)

PaymentDate: DateTime Object
(
    [date] => 2018-05-08 00:00:00.000000
    [timezone_type] => 3
    [timezone] => Australia/Sydney
)

**Comment by calcinai** [comment]
The problem is that there are no timezones in those dates, but the PHP date time needs a time zone. You could try stripping the one out and taking the literal date?

Here's a function I've used for similar purposes:

    public static function replaceTimezone(\DateTimeInterface $dateTime, \DateTimeZone $timeZone)
    {
        static $format = 'Y-m-d H:i:a';
        return \DateTime::createFromFormat($format, $dateTime->format($format), $timeZone);
    }

May or may not be of any use!

**Comment by Healyhatman** [comment]
And start and end dates of the timesheet entry I'm trying to edit
DateTime Object
(
    [date] => 2018-05-01 00:00:00.000000
    [timezone_type] => 2
    [timezone] => Z
)
DateTime Object
(
    [date] => 2018-05-07 00:00:00.000000
    [timezone_type] => 2
    [timezone] => Z
)

**Comment by Healyhatman** [comment]
Sorry so how would I use that function?

**Comment by calcinai** [comment]
So you can use that to strip/replace the timezone so comparison functions work? I'm not sure I completely understand the issue, less so why you're getting mixed timezones..

**Comment by Healyhatman** [comment]
I'll email you my horrible messy code so you can see what I'm trying to do. Ignore the 50 or so "debugPrint" and echo's where I'm trying to track wtf is happening.

**Comment by Healyhatman** [comment]
I'm able to compare the dates, even though the comparison looks terribly ugly. Now I'm just trying to save the timesheets.
