### ISSUE TITLE
Failed to validate signature, using example for public application

### ISSUE THREAD

**Issue by thelmaria** [calcinai/xero-php#373]
Using the [example for public applications](https://github.com/calcinai/xero-php/blob/master/examples/public.php), I'm getting an exception: 

> Fatal error: Uncaught XeroPHP\Remote\Exception\UnauthorizedException: Failed to validate signature 

thrown when I try to request an `OAUTH_ACCESS_TOKEN`: 

```
 if (isset($_REQUEST['oauth_verifier'])) {
     $xero->getOAuthClient()->setVerifier($_REQUEST['oauth_verifier']);
     $url = new URL($xero, URL::OAUTH_ACCESS_TOKEN);
     $request = new Request($xero, $url);
     $request->send(); // Exception throws here. 
```

My keys are correct, and this is a straight copy-paste from the example. I'm not sure where to go from here -- is this an issue with the example code, or a xero-side problem?

**Comment by calcinai** [comment]
I'm sorry to say I can't see anything immediately wrong with that, assuming you're following the flow in the example.  Can you triple check your key/secret and callback domain?

**Comment by thelmaria** [comment]
Thanks for the reply! :) 
Triple-checked secret/key and callback domains, they look correct. I'm stumped as to where to look for problems.

**Comment by thelmaria** [comment]
Looking at [this one](https://github.com/calcinai/xero-php/issues/92), I've fixed it -- setting the signature location seems to work. Thanks!

**Comment by calcinai** [comment]
Ah yes - that was a long time ago but it does ring a bell! Well done for finding that, glad it's working fo you.
