### ISSUE TITLE
Is there any integration with emailing invoices out?

### ISSUE THREAD

**Issue by shabaz-ejaz** [calcinai/xero-php#374]
Xero have a way of emailing an invoice to a customer through the API: https://developer.xero.com/documentation/api/invoices?emailbeta=true#emailing

Although it is in Beta mode at the moment, I sent them an email asking them to authorise my app to email invoices and they've enabled access for my app now.

So is there any integration with this feature yet?

Great package by the way 👍 

Many Thanks

**Comment by Josh-G** [comment]
If you'd like to access this feature using the library in its current state, something like this should work well for you. I've not tried it but it should be fine:

```php
use XeroPHP\Remote\Request;
use XeroPHP\Remote\URL;

class Invoice extends \XeroPHP\Models\Accounting\Invoice
{
    public function sendEmail()
    {
        $uri = sprintf('%s/%s/Email', $this::getResourceURI(), $this->getGUID());
        $url = new URL($this->_application, $uri);
        $request = new Request($this->_application, $url, Request::METHOD_POST);
        $request->send();
        
        return true;
    }
}
```

**Comment by shabaz-ejaz** [comment]
Sorry to be a pain but do you have any idea on how we can attach the invoice PDF to the email? Xero lets you do this easily from the website but not sure if its possible through the API?

**Comment by calcinai** [comment]
@Josh-G whoa what!? I had no idea Xero had started supporting this awesome!

@shabaz-ejaz Given Xero are sending the email in that request, not sure how you'd alter its content. I can't see anything in the docs either unfortunately.

**Comment by Josh-G** [comment]
@calcinai yep! They've sneaked some good stuff in recently. The exciting/useful one for us was the invoice history retrieval :)
