### ISSUE TITLE
Strings can't contain certain characters, need to be urlencode()d

### ISSUE THREAD

**Issue by Healyhatman** [calcinai/xero-php#377]
Encountered in: Employee

Only came across this when I had a worker with an Irishy last name, like O'Dogherty or something. The apostrophe broke poor old Xero. Probably this would come up in other situations but this is the one I encountered it in. 

Fix: use urlencode() on your strings first.

**Comment by calcinai** [comment]
Interesting. I thought that this was already being done..

**Comment by calcinai** [comment]
Can you please give an example of this? Also check the XML that's being generated.

**Comment by Healyhatman** [comment]
To be fair it may have been on my 2-months-out-of-date version. I'll check hang on.

**Comment by Healyhatman** [comment]
OKAY ummmmm never mind 

<Employee><FirstName>O&apos;Neill</FirstName><LastName>O&apos;Neill

It seems to be working at present. A few weeks / a month back I had a user onboarding with the last name O'Neill and it didn't work properly, and I had to explicitly urlencode the string but now apparently all is well?
