### ISSUE TITLE
BankTransactions LineItems are not returned

### ISSUE THREAD

**Issue by tonexv** [calcinai/xero-php#379]
It seems that the LineItems of the BankTransactions response is not being returned. (I need them.) Here's the code I used:

`$trans = $xero->load('Accounting\\BankTransaction')
      ->where('BankTransactionID=GUID("' . 'someguidhere' . '")')
    ->execute();

    foreach ($trans as $tran) {
        print_r($tran);
    }`

If you read the response, there is no LineItems object collection being returned .

Maybe there's another way of retrieving them using the BankTransactionID in the where clause? Can you guys help?

**Comment by calcinai** [comment]
Xero's API reacts differently if you search for an object as opposed to requesting it directly.  Have you tried using the `$xero->loadByGUID()` method?

**Comment by tonexv** [comment]
Yes, I did. No error, but no response either. Hold on, let me paste the code.

**Comment by tonexv** [comment]
`$guid = 'someguidhere';
$trans = $xero->loadByGUID('Accounting\\BankTransaction', $guid);
foreach ($trans as $tran) {
    print_r($tran);
}`

**Comment by calcinai** [comment]
`loadByGUID()` is only going to return one object (or throw a 404) because it's, you know, a _guid_!

What does `$trans` contain in the above code?

**Comment by tonexv** [comment]
LOL. I'm dumb. How should I reference the returned single object?

**Comment by calcinai** [comment]
If you're not getting any exceptions, `$trans` should be an instance of `BankTransaction`

**Comment by tonexv** [comment]
That's what I thought. And I should then reference that instance, say a simple:

`echo $trans->Contact->Name;`

...but no output is shown.

**Comment by tonexv** [comment]
hold on.. I got it!

**Comment by calcinai** [comment]
Have you got error reporting enabled?

**Comment by tonexv** [comment]
I forgot to comment out a closing bracket :)

the loadByGUID works. Thanks calcinai. You're awesome :P

**Comment by ziming** [comment]
You can try ->page($num) as well. Seem to make the line items appear too
