### ISSUE TITLE
InternalErrorException

### ISSUE THREAD

**Issue by kashifau** [calcinai/xero-php#384]
Hi I am getting this error:

"[XeroPHP\Remote\Exception\InternalErrorException]. An unhandled error with the Xero API. Contact the Xero API team if problems persist."

Any idea what is causing this?

**Comment by calcinai** [comment]
Can you have a look in the developer console and you may get a more verbose message.

**Comment by kashifau** [comment]
It fixed on its own. Not sure what caused it.

**Comment by calcinai** [comment]
Have a look in [https://developer.xero.com/myapps/](https://developer.xero.com/myapps/) and it will show you the request and response.

**Comment by kashifau** [comment]
Thanks!
