### ISSUE TITLE
"Contains" and "StartsWith" ?

### ISSUE THREAD

**Issue by Healyhatman** [calcinai/xero-php#385]
Is there a way to get element using .Contains or .StartsWith, etc?

As in the examples shown on https://developer.xero.com/documentation/api/requests-and-responses

**Comment by calcinai** [comment]
You can do any string-based query by just passing one parameter to the `-where()` function. If you'd like to make a helper function to do this, feel free!

**Comment by Healyhatman** [comment]
Yep thanks, didn't know that.

If anyone needs to know: 

`$result->where('FirstName.Contains("' . $firstName . '")');`

The query needs to have the double quotation marks around the string you're checking.

**Comment by FrankEBailey** [comment]
Yes, this helped me, thanks for putting the solution in! :)
