### ISSUE TITLE
The consumer was denied access to this resource.

### ISSUE THREAD

**Issue by seivad** [calcinai/xero-php#395]
Hey man, trying to follow your public.php example file and convert to work with Laravel 5.6. 

I've got most of it but now receive the error: "The consumer was denied access to this resource." after returning the oauth_token, oauth_verifier and org when accepting the app to use my data for the next 30 minutes. 

I can't track down why it is failing and I don't understand what the consumer is when the same consumer credentials worked to get to the authorisation page. Gist below so you can see the test controller i'm trying to get this to work in.

https://gist.github.com/seivad/a54901974ec4064f8fe6665e11a86598

**Comment by calcinai** [comment]
@seivad sorry for the delay in getting back to you. Those examples are old and (although should still work) are not the greatest.  Have a look at https://github.com/XeroAPI/xero-php-sample-app for a complete running app. You can see the auth flow for a public app.

**Comment by seivad** [comment]
thanks @calcinai - sorry for the delay too, it was enough to put me off looking at Xero for 3 weeks! I'll check out the other repo and see those examples. Much appreciated!
