### ISSUE TITLE
Uncaught Error: Class 'xero' not found

### ISSUE THREAD

**Issue by benjaminschneider1994** [calcinai/xero-php#396]
I am trying to setup an application and I dont understand how to do it and I am getting the error Uncaught Error: Class 'xero' not found? 

Thanks

**Comment by calcinai** [comment]
Can you please provide a little more information?

**Comment by benjaminschneider1994** [comment]
Hi Michael,

Sorry for the delay, I don't understand how to use the code in my PHP application. I have downloaded the sample application but that appears to be for a public app and not private?

Ben

**Comment by calcinai** [comment]
@benjaminschneider1994 have you had a look at the setup/usage instructions in the readme?

**Comment by benjaminschneider1994** [comment]
Hi Michael

I have but I dont know where to begin? Where do I put the code: $xero = new \XeroPHP\Application\PrivateApplication($config);

I tried putting it in a PHP file after downloading the code but I get the class error?

Ben

**Comment by calcinai** [comment]
Have a look in the `examples` folder of this repository.

**Comment by benjaminschneider1994** [comment]
Hi

 

I have had a look but cannot see anything that will help me?

 

Ben
