### ISSUE TITLE
Batch Saving Invoices

### ISSUE THREAD

**Issue by kashifau** [calcinai/xero-php#399]
Hi. Is it possible to batch save invoices? I want to push multiple invoices to xero with one call. I have seen a method saveAll() in docs and an example showing it how to apply it to batch save contacts? How can I do the same with invoices?

**Comment by calcinai** [comment]
You should be able to use `saveAll` with almost any endpoint exactly the same as the contacts example

**Comment by kashifau** [comment]
Got it. Thanks!
