### ISSUE TITLE
Retrieve Multiple Invoices

### ISSUE THREAD

**Issue by kashifau** [calcinai/xero-php#400]
How can I retrieve multiple invoices using one API call?

**Comment by FrankEBailey** [comment]
Load collection of objects, for a single page, and loop through them 

$contacts = $xero->load(Contact::class)->page(1)->execute();

foreach ($contacts as $contact) {
    print_r($contact);
}

**Comment by williamrenfrew** [comment]
We use something similar to this for pagination;

```php
<?php
$page = 1;
$xero = new \XeroPHP\Application\PrivateApplication($config);
while ($page) {
  $invoices = $xero->load(Invoice::class)
    ->where('Status', Invoice::INVOICE_STATUS_AUTHORISED)
    ->where('Type', Invoice::INVOICE_TYPE_ACCREC)
    ->page($page)
    ->execute();

  // Do something with $invoices
  $page++;
}
```

**Comment by kashifau** [comment]
Thanks. It is really helpful.
