### ISSUE TITLE
Query by GUID Problematic

### ISSUE THREAD

**Issue by markwoods241** [calcinai/xero-php#402]
When attempting to query by GUID (for example, lets say I want to search for a particular contact by id but only where IsCustomer is also true, or i want to query a list of multiple contact GUIDs), it is only possible by conforming to the regex in Query.php, using the format:

    ->where('Contact.ContactID', $guid)

Which results in the following in the request:

    Contact.ContactID==GUID("[guid]")

Xero response is then:

    No property or field 'Contact' exists in type 'Contact'

Since they are not expecting the Contact prefix, i.e.:

    ContactID==GUID("[guid]")

Can the handling for GUID in Query.php be updated to fix this, and not expect the prefix?

            elseif (preg_match('/^([a-z]+)\.\1ID$/i', $args[0])
                && preg_match(
                    '/^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$/i',
                    $args[1]
                )
            ) {
                $this->where[] = sprintf('%s=Guid("%s")', $args[0], $args[1]);
            }

could be something like this instead, to make the "Contact." prefix optional?

            elseif (preg_match('/^([a-z]+)(\.\1)?ID$/i', $args[0])
                && preg_match(
                    '/^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$/i',
                    $args[1]
                )
            ) {
                $this->where[] = sprintf('%s=Guid("%s")', $args[0], $args[1]);
            }

I'm quite new to working with the Xero API, so thought best to raise as an issue instead of make a pull request, since i'm not sure on the wider implications of this.

One also thing to note - finding out how to utilize the GUID based query functionality required me to dig through the code after running into errors - it would be ideal if this feature could be documented more clearly.

Kind Regards,

Mark

**Comment by markwoods241** [comment]
Apologies, just noticed that this may be a duplicate of issue #364 

The fix proposed in there appears to be in line with what I have suggested above, so hopefully that can be rolled into the next release?

For now, I'll condense it down to a single argument as also suggested in that ticket, to get past the issue for now.

**Comment by calcinai** [comment]
You're correct, this had been visited before.  I think it might be best to get this regex changed and bump the minor v.
