### ISSUE TITLE
Operation Time Out

### ISSUE THREAD

**Issue by kashifau** [calcinai/xero-php#403]
How can I change the operation time out CURLOPT_TIMEOUT ?

**Comment by Josh-G** [comment]
Have a look here https://github.com/calcinai/xero-php/blob/master/examples/config.php#L28
Add a new key CURLOPT_TIMEOUT and set it to your desired value

**Comment by calcinai** [comment]
That's in the curl options of the config.  https://github.com/calcinai/xero-php/blob/master/examples/config.php

**Comment by calcinai** [comment]
@Josh-G snap

**Comment by kashifau** [comment]
Getting the following error:
 [Symfony\Component\Debug\Exception\FatalThrowableError]
  Parse error: syntax error, unexpected ''curl'' (T_CONSTANT_ENCAPSED_STRING)
  , expecting ']'

**Comment by kashifau** [comment]
Thanks! It's working.
