### ISSUE TITLE
Payroll Settings Return Null after API returns correct values.

### ISSUE THREAD

**Issue by nzbenny** [calcinai/xero-php#406]
Hi,

Apologies if I am doing something dumb, but I am not sure how to make sense of this. I'm using AU Payroll and just want to check if the tracking code is set in the payroll settings...but when I call the API, the response comes back as NULL for all settings, even though I can see the response from the API is ok and makes sense. 

All I am doing is a 
```
load('PayrollAU\\Setting')->execute();
```
You can see the data tucked way in 3 arrays way down in the response, but I can't even figure out how to get it from there :(

Can anyone potentially see what may be causing this and give me a hand? It would be much appreciated - I've been looking at it for ages but getting a totally lost!

Thank you, thank you, thank you...

```
Collection {#305 ▼
  #_associated_objects: null
  flag::STD_PROP_LIST: false
  flag::ARRAY_AS_PROPS: false
  iteratorClass: "ArrayIterator"
  storage: array:3 [▼
    0 => Setting {#308 ▼
      #_data: array:3 [▼
        "Accounts" => null
        "TrackingCategories" => null
        "DaysInPayrollYear" => null
      ]
      #_dirty: []
      #_associated_objects: []
      #_application: PublicApplication {#287 ▶}
    }
    1 => Setting {#306 ▼
      #_data: array:3 [▼
        "Accounts" => null
        "TrackingCategories" => null
        "DaysInPayrollYear" => null
      ]
      #_dirty: []
      #_associated_objects: []
      #_application: PublicApplication {#287 ▶}
    }
    2 => Setting {#302 ▼
      #_data: array:3 [▼
        "Accounts" => null
        "TrackingCategories" => null
        "DaysInPayrollYear" => null
      ]
      #_dirty: []
      #_associated_objects: []
      #_application: PublicApplication {#287 ▼
        #config: array:3 [▶]
        #oauth_client: Client {#291 ▼
          -config: array:11 [▶]
          -request: Request {#294 ▼
            -app: PublicApplication {#287}
            -url: URL {#293 ▶}
            -method: "GET"
            -headers: array:2 [▶]
            -parameters: []
            -body: null
            -response: Response {#295 ▼
              -request: Request {#294}
              -status: 200
              -content_type: "text/xml"
              -response_body: "<Response xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Id>6c1d6a1d-cf95-4dde-b5e3-0b078d9e55b0</Id><Status>OK</Status><ProviderName>ximport</ProviderNam ▶"
              -oauth_response: null
              -elements: array:3 [▼
                0 => array:6 [▼
                  0 => array:4 [▼
                    "AccountID" => "13918178-849a-4823-9a31-57b7eac713d7"
                    "Type" => "BANK"
                    "Code" => "090"
                    "Name" => "Business Bank Account"
                  ]
                  1 => array:4 [▶]
                  2 => array:4 [▶]
                  3 => array:4 [▶]
                  4 => array:4 [▶]
                  5 => array:4 [▶]
                ]
                1 => array:2 [▼
                  "EmployeeGroups" => array:2 [▶]
                  "TimesheetCategories" => array:2 [▶]
                ]
                2 => []
              ]
              -element_errors: []
              -element_warnings: []
              -root_error: []
            }
          }
          -token_secret: "NWU71FMHNVYW2MZXYDRGAOAAQD4HGN"
          -verifier: null
        }
      }
    }
  ]
}
```

**Comment by calcinai** [comment]
This could be the model/relationship definition not being correct.  Have you checked the mappings?

At the end of the day, you can still just make a manual request ie `new Request()` etc, and manually process the JSON from there.

**Comment by nzbenny** [comment]
Hi - thanks for your quick response - and also for your great work on this...this is the only bump I have hit :)

I was digging into the Model/Relationship but couldn't see anything glaring, though I will take another look =and see if I can find anything. I wasn't sure if I was just doing something silly to start with, so kind of needed a jolt in the right direction.

Thanks also for the tip on making a manual request, I think I know what you mean, so will have a crack if I can't figure it out.

**Comment by calcinai** [comment]
No worries.

It's entirely possible you're the first person to try and hit this endpoint.  It could be something like being defined as an array when it's expecting an object somewhere.  Sorry I don't have time to investigate at the moment.

Re the manual request, yes, just as in the `load()` method. Like this:

    $url = new URL($xero, PayrollAU\Setting::getResourceURI(), PayrollAU\Setting::getAPIStem());
    $request = new Request($xero, $url, Request::METHOD_GET);
    $request->send();

    $elements = $request->getResponse()->getElements()

**Comment by nzbenny** [comment]
Yeah, I figured I may be the first! Been using it a while, but didn't need the settings until now.

Cheers for the details on the manual request - I'll let you know how I get on.

Thanks again!

**Comment by nzbenny** [comment]
So... I couldn't see anything glaring that was out of line with the model, but there must be something. I will try and revisit it when I get some time. If I figure it out I'll update this.

The code you gave me to do a manual request has solved my immediate issue (as it should if anyone else hits this problem) and saved me a ton of time, so very much appreciated. So glad you could help :)

Thanks again!
