### ISSUE TITLE
PayrollAU Payslip getTimesheetEarningsLines() returns zero lines

### ISSUE THREAD

**Issue by JimboM4CK** [calcinai/xero-php#407]
Timesheet earnings lines allocation issue. 
The data is included in the initial response from the Xero API. 

I think I've narrowed it down to the fromStringArray function, the xero response has the earnings lines wrapped in an array called 'EarningsLine' which I believe is causing the issue.

It also seems to be returning 'NumberOfUnits' instead of 'Amount'.

**Comment by calcinai** [comment]
This is quite possible. Are you able to propose a PR to make the models correctly reflect the data structure?

**Comment by jmack111** [comment]
Looks like it might be from Xero's end. They are only returning the last TimesheetEarningsLine instead of all of them. Example: 

[TimesheetEarningsLines] => Array (
  [EarningsLine] => Array (
    [EarningsRateID] => a2cf28fb-24ce-4eb2-a292-d14ta4af9617
    [RatePerUnit] => 0.000000
    [NumberOfUnits] => 5.0000
  )
)
Note, EarningsLine should be a numeric array.

**Comment by jmack111** [comment]
See PR #408

**Comment by rodjsta** [comment]
@calcinai, the solution proposed in #408 does work, but do you have any idea if there's a more appropriate way?
