### ISSUE TITLE
How to create a new Invoice?

### ISSUE THREAD

**Issue by yashtiwari** [calcinai/xero-php#409]
Hey man, can you please explain a process to create a new invoice on Xero using "calcinai/xero-php
" library.

**Comment by calcinai** [comment]
All of the models behave basically the same way, so the example for creating a contact in the readme or [here](https://github.com/calcinai/xero-php/wiki/Usage-by-example%3A-Accounting%5CContact) should give you a fair idea of how it works.

I'd recommend either using a smart IDE or looking at the Xero documentation to see which parameters you need to set on the invoice to create it.

**Comment by reggieds** [comment]
I got this error when using code from [:](https://github.com/calcinai/xero-php/wiki/Usage-by-example%3A-Accounting%5CContact)

Fatal error: Uncaught Error: Class 'Address' not found in D:\WinNMP\www\xero-php\examples\private.php:47 Stack trace: #0 {main} thrown in D:\WinNMP\www\xero-php\examples\private.php on line 47

**Comment by timacdonald** [comment]
Hey,

The file you are referencing does not contain that class: https://github.com/calcinai/xero-php/blob/master/examples/private.php

I'd say you have made your own changes to the file. Make sure you import the fully qualified namespace before you use the `Address` class, i.e.

```php
use XeroPHP\Models\Accounting\Address;

$address = new Address;

// etc...
```

**Comment by reggieds** [comment]
Is there any real example (full code) to add new invoice?

**Comment by calcinai** [comment]
Try something like 

`
use XeroPHP\Models\Accounting\Invoice;

$invoice = new Invoice($xero);
$invoice->setDate(new DateTime())
    ->setDueDate(new DateTime());

$lineItem = new Invoice\LineItem();
$lineItem->setDescription([description])
    ->setQuantity([quantity])
    ->setAccountCode([account])
    ->setUnitAmount([amount]);

$invoice->addLineItem($lineItem)
    ->save();
`

Have a look at the model to see all the properties or look at the Xero docs

**Comment by reggieds** [comment]
How to combine with existing contact or new contact?

I got this error:
`Fatal error: Uncaught XeroPHP\Remote\Exception: XeroPHP\Models\Accounting\Invoice::$Contact is mandatory and is either missing or empty.`

My Code:
`<?php
require '../vendor/autoload.php';

use XeroPHP\Application\PrivateApplication;

$config = [
    'oauth' => [
        'callback' => 'http://localhost/',
        'consumer_key' => 'k',
        'consumer_secret' => 's',
        'rsa_private_key' => 'file://certs/private.pem',
    ],
];

$xero = new PrivateApplication($config);

use XeroPHP\Models\Accounting\Invoice;

$invoice = new Invoice($xero);

$invoice->setDate(new DateTime())
    ->setDueDate(new DateTime())
    ->setType('ACCPAY');

$lineItem = new Invoice\LineItem();
$lineItem->setDescription('Item AA')
    ->setQuantity('1')
    ->setAccountCode('200')
    ->setUnitAmount('50');

$invoice->addLineItem($lineItem)
    ->save();

`

**Comment by Godwin-Richard** [comment]
i tried to Create new invoice using the above code but it gives me following Error


Fatal error: Uncaught exception 'XeroPHP\Remote\Exception' with message 'XeroPHP\Models\Accounting\Invoice::$Type is mandatory and is either missing or empty.' 


$invoice = new Invoice($xero);
$invoice->setDate(new DateTime())
    ->setDueDate(new DateTime());

$lineItem = new Invoice\LineItem();
$lineItem->setDescription(['Test Invoice'])
    ->setQuantity(['11'])
    ->setAccountCode(['1213'])
    ->setUnitAmount(['2132']);

$invoice->addLineItem($lineItem)->save();

**Comment by timacdonald** [comment]
> Fatal error: Uncaught exception 'XeroPHP\Remote\Exception' with message 'XeroPHP\Models\Accounting\Invoice::$Type is mandatory and is either missing or empty.'

The error message here is letting you know the issue. Specifically 

```
XeroPHP\Models\Accounting\Invoice::$Type is mandatory and is either missing or empty.
```

**Comment by SShalini** [comment]
how to update an existing invoice?

**Comment by SShalini** [comment]
can you please explain a process to  edit an existing invoice on Xero using "calcinai/xero-php
" library.
