### ISSUE TITLE
Case sensitive search

### ISSUE THREAD

**Issue by grepollo** [calcinai/xero-php#416]
Hi, 

I cannot get a response from query of 'Accounting\Item' by where clause. 

An example is Code = 'DevD', and my query is 'devd', i always got empty response. And when I insert it, i got an error that product already exist. 

Is there a way we can search it in case sensitive?

Thanks.

**Comment by calcinai** [comment]
@grepollo I'm not sure to be honest. Have you looked at the API docs?

**Comment by grepollo** [comment]
Hi, 

I've scanned their docs, but no mention on this kind of scenario on query. What i did is query all the items and put it in cache, then do a search on the whole array. I know not a good solution though.

**Comment by calcinai** [comment]
@grepollo [This](https://community.xero.com/developer/discussion/64412940) suggests it's not possible, it might be worth contacting them directly.

**Comment by grepollo** [comment]
Hi, 

Just in case someone has the same issue, the Xero team suggest to use ToLower in where clause

```
->where('Code.ToLower().Equals("'.strtolower($code).'")')
```

It works perfectly.

**Comment by calcinai** [comment]
@grepollo does this work with items? I saw this example for contacts, but then the link above specifically stating it's not possible..
