### ISSUE TITLE
"Class does not exist" error

### ISSUE THREAD

**Issue by mattnico** [calcinai/xero-php#419]
When I create a new private application instance and then attempt to use it I get a persistent error:

`Class does not exist [XeroPHP\Models\Invoice]`

It doesn't matter what class I attempt to work with: Invoice, Contact, you name it.

Here's my code:

```
use \XeroPHP\Application\PrivateApplication;

$xero_config = [
            'oauth' => [
                'callback'    => 'oob',
                'consumer_key'      => 'k', //Yes, I have my real key in the actual code
                'consumer_secret'   => 's',
                'rsa_private_key'  => '/path/to/key',
                'rsa_public_key'   => '/path/to/key'
            ]
        ];

$xero = new PrivateApplication($xero_config);

try {
	$xero->load(Invoice::class)
    ->where('Status', Invoice::INVOICE_STATUS_AUTHORISED)
    ->where('Type', Invoice::INVOICE_TYPE_ACCREC)
    ->execute();
} catch (\Exception $e) {
	echo $e->getMessage();
}
```

It doesn't matter what I put in my `try` I get the same result. Ideas?

**Comment by calcinai** [comment]
Whoops, have you tried adding he relevant `use` statement?

**Comment by mattnico** [comment]
D'oh, that was it. Amazing how something so simple can elude me for hours...
