### ISSUE TITLE
Updating Inventory Price

### ISSUE THREAD

**Issue by ashwaniBT** [calcinai/xero-php#422]
This is how I have set the prices

$purchase = new Purchase();
$item->addPurchaseDetail($purchase->setUnitPrice($inventory['Inventory']['purchase_unit_price']));
$sale = new Sale();
$item->addSalesDetail($sale->setUnitPrice($inventory['Inventory']['list1']));

but the item prices are not updated in Xero.
can you please help me pointing out the issue here 
Thanks & Regards,
Ashwani

**Comment by calcinai** [comment]
Are you saving `$item`?

**Comment by ashwaniBT** [comment]
Yes
