### ISSUE TITLE
How to start... 

### ISSUE THREAD

**Issue by iampapagray** [calcinai/xero-php#423]
Ive been going round and round within the documentation and gitbub repo to find a way to begin to use the API on a private app. I used composer to load in the API files and now i dont know to add it into my app and use it whatever i try fails. Its been really stressful finding a way to start here. Someone please help.

**Comment by calcinai** [comment]
Can you please be more specific about what you've tried, and what's failed?  Have a look at t[he examples](https://github.com/calcinai/xero-php/tree/master/examples) and see how you get on

**Comment by iampapagray** [comment]
I am trying to build a private app. so i followed the instructions on getting started and used composer to setup. so i have a in my vendor folder calcinai/xero-php/... . Now i created an index to php in my project root directory and then copied the content of the private.php file in the examples folder. I also modified it with the consumer_secret and consumer_key i got when i created the app on the xero site. i created a dir in the root dir and called certs to hold the certs generated. 

When i load the app in my browser i get 500 server error. Im not sure whats wrong. Could it be the file structure ?
I appreciate your response, please help.

**Comment by calcinai** [comment]
That all sounds about right.

A 500 could be any server error.  WHat's the actual error message?

**Comment by iampapagray** [comment]
that all i get with firefox. Is there a way to get the actual error message.
Thanks for your help

**Comment by calcinai** [comment]
Standard php error reporting should do it:

```
ini_set('display_errors', '1');
error_reporting(E_ALL);
```

**Comment by iampapagray** [comment]
Fatal error: Uncaught Error: Class 'XeroPHP\Application\PrivateApplication' not found in xeroApp/index.php:22

**Comment by iampapagray** [comment]
This is my file structure:
--rootDir
----certs
------privatekey.pem
------publickey.cer

----vendor
------calcinai
--------xero-php (other files within here)
------composer (composer files)

----index.php

**Comment by calcinai** [comment]
Ok, are you including the `vendor/autoload` file as per the examples?

**Comment by iampapagray** [comment]
No i didnt see that in the example
Will try that out
Thanks again

**Comment by iampapagray** [comment]
Fatal error: Uncaught XeroPHP\Remote\OAuth\Exception: Cannot access private key for signing: openssl_pkey_get_private('certs/privatekey.pem') returned false in /var/www/html/forhey.lan/public_html/xero/vendor/calcinai/xero-php/src/XeroPHP/Remote/OAuth/SignatureMethod/RSASHA1.php:13 Stack trace: #0 /var/www/html/forhey.lan/public_html/xero/vendor/calcinai/xero-php/src/XeroPHP/Remote/OAuth/Client.php(144): XeroPHP\Remote\OAuth\SignatureMethod\RSASHA1::generateSignature(Array, 'GET&https%3A%2F...', 'RXJ5PITKHZQNIA3...') #1 /var/www/html/forhey.lan/public_html/xero/vendor/calcinai/xero-php/src/XeroPHP/Remote/OAuth/Client.php(61): XeroPHP\Remote\OAuth\Client->getSignature(Object(XeroPHP\Remote\Request)) #2 /var/www/html/forhey.lan/public_html/xero/vendor/calcinai/xero-php/src/XeroPHP/Remote/Request.php(68): XeroPHP\Remote\OAuth\Client->sign(Object(XeroPHP\Remote\Request)) #3 /var/www/html/forhey.lan/public_html/xero/vendor/calcinai/xero-php/src/XeroPHP/Remote/Query.php(287): XeroPHP\Remote\Request->send() #4 /var/www/html/forh in /var/www/html/forhey.lan/public_html/xero/vendor/calcinai/xero-php/src/XeroPHP/Remote/OAuth/SignatureMethod/RSASHA1.php on line 13

This is the error i get now.

My index.php
require_once('vendor/autoload.php');
use XeroPHP\Application\PrivateApplication;
	$config = [
			    'oauth' => [
			        'callback'         => 'http://localhost/',
			        'consumer_key'     => 'my_key',
			        'consumer_secret'  => 'my_secret',
			        'rsa_private_key'  => 'certs/privatekey.pem',
			    ],
			];

			$xero = new PrivateApplication($config);
			print_r($xero->load('Accounting\\Organisation')->execute());

**Comment by calcinai** [comment]
> Cannot access private key for signing: openssl_pkey_get_private('certs/privatekey.pem') returned false

I'd suggest that you need to use an absolute path to your certificate.

**Comment by wiki99** [comment]
<?php

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
ini_set('display_errors',1);

require 'vendor/autoload.php';

$xero = new \XeroPHP\Application\PrivateApplication($config);


	//print_r($Contactobj);
//$contacts = $xero->load(Contact::class)->execute();
echo "<pre>";

//print_r($accounts);

//$contacts =$xero->load('Accounting\\Contact')->execute();

    
  
	$address=$xero->load('Accounting\\Address')->execute();


foreach ($address as $add)

{
	
	
	print_r($add);
}

**Comment by AndyTurff** [comment]
Hi wiki99, I had a similar problem, below is what worked for me. It is deliberately long winded to show you different options. Hope it helps...
`
use XeroPHP\Application\PrivateApplication;

require 'autoload.php';
include ('config.php');

$xero = new PrivateApplication($config);

$contacts = $xero->load('Accounting\\Contact'::class)
	//->where('UpdatedDateUTC >= DateTime(2019, 02, 10) && UpdatedDateUTC < DateTime(2019, 02, 21)')
	->execute();

foreach ($contacts as $contact) {
    //print_r($contact);
	   
	//print_r($contact->toStringArray()); 

			$company = $contact->Name;
			$FirstName = $contact->FirstName;
			$emailaddress = $contact->EmailAddress;
			$contactId = $contact->ContactID;
			$ContactNumber = $contact->ContactNumber;
			$ln = $contact->LastName;
			$contactStatus = $contact->ContactStatus;
			$UpdatedDateUTC = $contact->UpdatedDateUTC;
			$Website = $contact->Website;
			$DefaultCurrency = $contact->DefaultCurrency;
			$discount = $contact->Discount;
			
			$addresses = $contact->getAddresses(0);	
			
			$addressType = $addresses[0]->getAddressType();			
			$AddressLine1 = $addresses[0]->getAddressLine1();			
			$AddressLine2 = $addresses[0]->getAddressLine2();
			$city = $addresses[0]->getCity();
			$Region = $addresses[0]->getRegion();			
			$PostalCode = $addresses[0]->getPostalCode();
			$country = $addresses[0]->getCountry();
			
			$addressTypex = $addresses[1]->getAddressType();			
			$AddressLine1x = $addresses[1]->getAddressLine1();			
			$AddressLine2x = $addresses[1]->getAddressLine2();
			$cityx = $addresses[1]->getCity();
			$Regionx = $addresses[1]->getRegion();			
			$PostalCodex = $addresses[1]->getPostalCode();
			$countryx = $addresses[1]->getCountry();
			
			$phones = $contact->getPhones(0);
			$phoneTypeDDI = $phones[0]->getPhoneType();			
			$phoneNumberDDI = $phones[0]->getPhoneNumber();
			$phoneAreaCodeDDI = $phones[0]->getPhoneAreaCode();
			$phoneCountryCodeDDI = $phones[0]->getPhoneCountryCode();

			$phoneTypeDefault = $phones[1]->getPhoneType();
			$phoneNumberDefault = $phones[1]->getPhoneNumber();
			$phoneAreaCodeDefault = $phones[1]->getPhoneAreaCode();
			$phoneCountryCodeDefault = $phones[1]->getPhoneCountryCode();

			$phoneTypeFax = $phones[2]->getPhoneType();
			$phoneNumberFax = $phones[2]->getPhoneNumber();
			$phoneAreaCodeFax = $phones[2]->getPhoneAreaCode();
			$phoneCountryCodeFax = $phones[2]->getPhoneCountryCode();

			$phoneTypeMobile = $phones[3]->getPhoneType();
			$phoneNumberMobile = $phones[3]->getPhoneNumber();
			$phoneAreaCodeMobile = $phones[3]->getPhoneAreaCode();
			$phoneCountryCodeMobile = $phones[3]->getPhoneCountryCode();


			echo"<br> <b>".$company;			
			echo"</b><br> ".$FirstName." ".$ln;

			echo"<br> ".$addressType;
			echo"<br> ".$AddressLine1;
			echo"<br> ".$AddressLine2;
			echo"<br> ".$city;			
			echo"<br> ".$Region;
			echo"<br> ".$PostalCode;			
			echo"<br> ".$country;			
			echo"<br> Email-".$emailaddress;

			echo"<br><br> ".$addressTypex;
			echo"<br> ".$AddressLine1x;
			echo"<br> ".$AddressLine2x;
			echo"<br> ".$cityx;			
			echo"<br> ".$Regionx;
			echo"<br> ".$PostalCodex;			
			echo"<br> ".$countryx;			
			//echo"<br> Email-".$emailaddressx;
			
			echo"<br><br> Phone Type-".$phoneTypeDDI;			
			echo"<br> Country Code-".$phoneCountryCodeDDI;
			echo"<br> Area Code-".$phoneAreaCodeDDI;
			echo"<br> Phone Number-".$phoneNumberDDI;
			
			echo"<br><br> Phone Type-".$phoneTypeDefault;			
			echo"<br> Country Code-".$phoneCountryCodeDefault;
			echo"<br> Area Code-".$phoneAreaCodeDefault;
			echo"<br> Phone Number-".$phoneNumberDefault;
			
			echo"<br><br> Phone Type-".$phoneTypeFax;
			echo"<br> Country Code-".$phoneCountryCodeFax;
			echo"<br>Fax Number: ".$phoneAreaCodeFax." ".$phoneNumberFax;

			echo"<br><br> Phone Type: ".$phoneTypeMobile;			
			echo"<br> Country Code: ".$phoneCountryCodeMobile;
			echo"<br>Number: ".$phoneAreaCodeMobile." ".$phoneNumberMobile;

			echo"<br><br>DefaultCurrency-".$DefaultCurrency; 
			echo"<br>Discount-".$discount; 
			echo"<br>Website-".$Website;
			echo"<br>ContactID-".$contactId; 
			echo"<br>Contact Number-".$ContactNumber;
			echo"<br>Contact Status-".$contactStatus . "<br>";
			print_r($UpdatedDateUTC);
			echo"<br><br>";
		}`
