### ISSUE TITLE
Trying to get a simple list of payment details starting from a date

### ISSUE THREAD

**Issue by iboulard** [calcinai/xero-php#424]
Hello, 
Newby question, is there a simpler alternative to the "Payment load" that this is returning a huge amount of data:

$payments = $xero->load('Accounting\\Payment')->execute();
foreach ($payments as $payment) {
    print_r($payment);
}

I would like to retrieve a list of payment details similar to this list below instead, with a ->where('Date>"2018-01-01"')  Is there a class that I can use or do I have to loop thru the arrays returned by the "Payment load" returned above?

						(
                                                    [PaymentID] =&gt; e08362f1-e013-4917-93c3-xyz123
                                                    [Date] =&gt; 2018-08-31T00:00:00
                                                    [BankAmount] =&gt; 0.01
                                                    [Amount] =&gt; 0.01
                                                    [Reference] =&gt; 12345
                                                    [CurrencyRate] =&gt; 1.000000
                                                    [PaymentType] =&gt; ACCRECPAYMENT
                                                    [Status] =&gt; AUTHORISED
                                                    [UpdatedDateUTC] =&gt; 2018-09-21T15:28:04.927
                                                    [IsReconciled] =&gt; false
                                                    [Account] =&gt; Array
                                                        (
                                                            [AccountID] =&gt; f77dce03-701b-47ea-ab6c-xyz123
                                                            [Code] =&gt; 1100
                                                        )

                                                    [Invoice] =&gt; Array
                                                        (
                                                            [Contact] =&gt; Array
                                                                (
                                                                    [ContactID] =&gt; bce7dc20-a3a5-4d76-9939-12345
                                                                    [ContactNumber] =&gt; abc
                                                                    [Name] =&gt; ABC 123
                                                                )

                                                            [CurrencyCode] =&gt; USD
                                                            [Type] =&gt; ACCREC
                                                            [InvoiceID] =&gt; ae2abe8b-2140-4bbb-893f-xyz123
                                                            [InvoiceNumber] =&gt; 1234567
                                                        )

                                                )

Thank you for your help!!!
Isabelle

**Comment by calcinai** [comment]
What happens if you add that `where()` clause?

**Comment by iboulard** [comment]
Hi, I found from another post how to filter the date and simple result, just sharing for anybody else struggling with the same issue as I did:

	$startDateString = date('Y, m, d');
        $endDateString = date('Y, m, d', strtotime('2018-08-01'));
	$paymenttype = "ACCRECPAYMENT";
	
	$payments = $xero->load('Accounting\\Payment')->where('PaymentType=="'.$paymenttype.'"')->where(sprintf('Date >= DateTime(%s) && Date < DateTime(%s)', $endDateString, $startDateString))->execute();

foreach ($payments as $payment) {

	$amount = $payment-> Amount;
	$status = $payment-> Status;
	$account_code = Account-> Code;
	$customer_no = $payment-> Invoice -> Contact-> ContactNumber;
	
	
}
