### ISSUE TITLE
Not Returning ContactID or ContactStatus on new invoices

### ISSUE THREAD

**Issue by tymolls** [calcinai/xero-php#425]
Hi,

If I save the contact during the invoice creation process, $xeroContact below returns the Contact ID. E.g.
`
$xeroContact = new Contact($xero);
$xeroContact->setName($contact->name)
->setEmailAddress($contact->email);
$xeroContact->save();
$xeroInvoice = $invoice->setContact($xeroContact)
`

However, if I do not save the contact ($xeroContact), then just attach the contact to the invoice, it saves, but it does not return the Contact ID. Only the name and email (that I set) are returned.

I checked the API previewer in Xero, and it's meant to return ContactID, Contact Status etc. But I'm unable to access it.

**Comment by calcinai** [comment]
Are you using the current version of the library? For some reason I thought this issue was already fixed...

**Comment by tymolls** [comment]
> Are you using the current version of the library? For some reason I thought this issue was already fixed...

Yes, currently using v1.8.3

Saving first means it returns an error if it finds an existing contact with the same name. So I'm having to first query Xero to see if the contact exists, then creating a contact if it doesn't.

```
	        $checkContact = $xero->load(Contact::class)
					    ->where('Name', $contact->name)
					    ->execute();

			if (sizeof($checkContact)  > 0) {
				
				$xeroContact = $checkContact[0];

			} else {

				$xeroContact = new Contact($xero);

				$xeroContact->setName($contact->name)
				    		->setEmailAddress($contact->email);

				$xeroContact->save();

			}
```

If my original code returned the ContactID, then I can just setContact with a name and email to a new invoice, and save the ContactID returned against the user's record.

**Comment by tymolls** [comment]
@calcinai - could you kindly help with above issue.

Thanks,

**Comment by tymolls** [comment]
This works great. Thank You
