### ISSUE TITLE
Adding an Item with purchase and sales account codes? 

### ISSUE THREAD

**Issue by FrankEBailey** [calcinai/xero-php#426]
I'm encountering an odd issue (well, odd to me anyway) when adding an Item through the Xero API using the Calcinai XeroPHP library. Omitting the purchase and sales account codes seems to cause the item to default to the old 14% VAT rate (here in South Africa VAT rose to 15% in April of this year).

So I'm hoping to stop this issue by specifying the purchase and sale account codes when creating an Item via the API, however I'm not 100% sure of the syntax to use.

The syntax I've used thus far is

```
$item = $xero->load(Accounting\Item::class)->where('Code', 'MYITEMCODE')->execute();

if(@!$item) {
$nu = new XeroPHP\Models\Accounting\Item($xero);
$nu->setCode('ItemCode')
->setName('ItemName')
->setPurchaseDescription('ItemName')
->setDescription('ItemName')
->setIsSold(true)
->setIsPurchased(true);
$nu->save();
}
```

If someone could assist me with the correct syntax to create an Item in XeroPHP, incorporating the Unit Price and AccountCode / COGSAccountCode, I would really appreciate it.

**Comment by calcinai** [comment]
@FrankEBailey have you been able to get this using the API previewer? An example of the correct XML would help to see where the library is going wrong..

**Comment by FrankEBailey** [comment]
I don't know that the library is going wrong, I'm just unable to locate an example of adding an item that has an account code and an amount for purchase and sale.

The XML is pretty straightforward, but I'm probably just too dense to figure out how to structure the XeroPHP call.

<Items>
  <Item>
    <ItemID>493bb21e-742c-45a9-aa07-61b83cf33f41</ItemID>
    <Description>Short Black</Description>
    <Code>CAFE001</Code>
    <UpdatedDateUTC>2011-01-19T05:24:55.55</UpdatedDateUTC>
    <SalesDetails>
      <UnitPrice>3.50</UnitPrice>
      <TaxType>OUTPUT</TaxType>
      <AccountCode>200</AccountCode>
    </SalesDetails>
    <PurchaseDetails>
      <UnitPrice>2.00</UnitPrice>
      <TaxType>INPUT</TaxType>
      <AccountCode>428</AccountCode>
    </PurchaseDetails>	
  </Item>
</Items>
