### ISSUE TITLE
Optional parameters for GET TrackingCategories

### ISSUE THREAD

**Issue by glaing** [calcinai/xero-php#431]
I am working on a project that needs to check if a Tracking Category Option exists before submitting invoices.

I've managed to pull a list of 'Event' tracking options:

```
 $xero_tracking_categories = $xero->load('Accounting\\TrackingCategory')->execute();
   
   
foreach ( $xero_tracking_categories as $tracking_categories )  {
    $category_name = $tracking_categories->getName();
  
    if ($category_name == "Event") {
        $category_event_options = $tracking_categories->getOptions();
        
        foreach ( $category_event_options as $tracking_event ) {
        
        print_r( $tracking_event->getName() );
        echo ' (';
        print_r( $tracking_event->getStatus() );
        echo ')';
        echo '<br />';
        
        }

    }
     
}
```

But I can't seem to get any options that have been archived.

Xero's API Documentation states that you can include optional parameters in the request to include archived options, but I am not sure if that is supported by this library, or if it is, how I might go about including it.

> includeArchived | e.g. includeArchived=true - Categories and options with a status of ARCHIVED will be included in the response

Has anyone managed to do this in the past? Or does anyone have any pointers on similar situations that I can use to figure this out?

Many Thanks,
George

**Comment by calcinai** [comment]
I'm pretty sure you can just chain in `->includeArchived()` like:

    $xero_tracking_categories = $xero->load('Accounting\\TrackingCategory')
      ->includeArchived()
      ->execute();

**Comment by glaing** [comment]
That worked perfectly - thank you!
