### ISSUE TITLE
Unable to Allocate Credit Note without Exception

### ISSUE THREAD

**Issue by April-MD-Limited** [calcinai/xero-php#438]
The only way I can see to allocate a credit note to an invoice results in an exception.

Firstly, `saveAll` doesn't seem to work in that you can add the allocation when the credit note is created but it just ignores you. I would either expect it to work, as in allocate, or throw an exception to say you can't allocate at the point of credit note creation.

Then, if I try to use `save` to create a credit note including an allocation it throws a 'Failed to validate signature' error. I know the signature is fine because if I create a credit note without an allocation it creates it just fine. So the error message is very misleading.

However, if I attempt to allocate the credit note to an invoice it's not dirty when I try and save:

>
    use XeroPHP\Exception as XeroException;
    use XeroPHP\Models\Accounting\CreditNote as XeroCreditNote;
    use XeroPHP\Models\Accounting\CreditNote\Allocation as XeroCreditNoteAllocation;
    use XeroPHP\Models\Accounting\Invoice as XeroInvoice;

    ...

    $xeroCreditNoteAllocation = new XeroCreditNoteAllocation($this->xero);
    $xeroInvoice = new XeroInvoice();
    $xeroInvoice->setInvoiceID($accountingEntity->getXeroUuid());
    $xeroCreditNoteAllocation->setInvoice($xeroInvoice);
    $xeroCreditNoteAllocation->setAppliedAmount((float)($totalAmount+$totalVat) / 100.0);
    $xeroCreditNoteAllocation->setDate($requestedAt);
    $xeroCreditNote->setCreditNoteID($xeroCreditNoteUuid);
    $xeroCreditNoteAllocation->addAssociatedObject('CreditNote', $xeroCreditNote);
    ResourceLoader::logDebug('isDirty: '.($xeroCreditNoteAllocation->isDirty()?'T':'F'));
    $response = $xeroCreditNoteAllocation->save();

it results in:
>    Core.DEBUG: isDirty: F 

So that when I save nothing happens and the `$response` is null. If I try to make it dirty prior to the save I just get an exception stating:
>Failed to allocate credit XeroPHP\Models\Accounting\CreditNote\Allocation doesn't support [POST] via the API

However, if I add the allocation to a credit note as follows:
>
    ...

    $xeroCreditNote = new XeroCreditNote($this->xero);
    $xeroCreditNote->addAllocation($xeroCreditNoteAllocation);
    try {
        $response = $xeroCreditNote->save();
    } catch (XeroException $ex) {
        ResourceLoader::logError('Failed to allocate credit: ', $ex);
    }
 
it results in:
>    Core.ERROR: Failed to allocate credit: A validation exception occurred (This document cannot be edited as it has a payment or credit note allocated to it)

and when I look in the application history of Xero I get two requests as follows:

>Created Date (UTC) | Endpoint | Method | Response | User Agent
2018 Oct 30 11:33 | /api.xro/2.0/CreditNotes/_uuid_ | POST | 400 | XeroPHP | View
2018 Oct 30 11:33 | /api.xro/2.0/CreditNotes/_uuid_/Allocations | PUT | 200 | XeroPHP

Please note that the _uuid_'s are the same, but I've just removed/obscured them. Also, they are in descending chronological order so the PUT is sent before the POST.

When I now look in the Xero front end the credit note is allocated to the correct invoice and as I want it to be, but that the exception has been thrown. I understand why the exception is thrown as the POST is attempting to change things after they have been allocated.

My question is how do I allocate a credit note without the second call, i.e. how can I do the PUT without the POST?

**Comment by April-MD-Limited** [comment]
Hi, is there any update on this please?

If there's a better way if doing allocating credit notes, or you have a working example it would be much appreciated. The simple requests are fairly obvious but as this is more complex I can't see how to do it other than above. I tried lots of alternatives all to no avail. I know exactly what to send to the API but not how to get xero-php to send it. Any assistance with this and how to progress it would be gratefully received.

**Comment by April-MD-Limited** [comment]
Is this repo still supported?

Please can you at least acknowledge this, it's rather unprofessional to just ignore it - or am I being unreasonable in expecting a response?

Again, if I'm doing something wrong please let me know and/or provide an example of how to do it. If you require more time to investigate just let me know. Conversely, if you're not going to do anything then please have the decency to let me know that too.

**Comment by calcinai** [comment]
@April-MD-Limited Sorry for the delay, I've been flat out at work.  Unfortunately, at Xero there's not really a PHP resource for maintaining this library, so often the community have to get their hands a little dirty to diagnose the issues/make fixes.  

Looking at your issues, I think the first thing to do is see if you can make these actions work using the [API previewer](https://app.xero.com/Previewer), using the docs.  If that's working as expected, I'd suggest seeing what XML is being generated here, and what's different. If it's a parsing/encoding issue, that makes it much easier to fix (rather than me trying to replicate your issue with test data).

Hopefully that gives some direction and if you're still stuck next week, I should have a bit of time where I can have a look for you.

**Comment by calcinai** [comment]
@April-MD-Limited how are you getting on?

**Comment by April-MD-Limited** [comment]
@calcinai thanks for the reply, and sorry for the delay - I've been away for a while. I've no problem getting my hands dirty! The API Previewer works fine, and I don't believe it's a parsing/encoding issue either as xero-php is actually sending the correct xml and working. The problem is that the only way I can get it to send the correct request also results in it sending an incorrect request afterwards!

From my investigations it looks like `savePropertiesDirectly` in `Application.php` is sending the correct allocation request, but only if I add the allocation to a credit note and then save the credit note. However the actual credit note save fails.

So how do I save the properties (i.e. the `CreditNoteAllocation`) without actually saving the `CreditNote` itself?

**Comment by calcinai** [comment]
Ok, I think I understand!

What is in the `_dirty` array of the credit note when you're saving it? From what I can see, it looks like the allocation should save directly, then set that property clean, then return null if there's nothing else dirty.

`Application.php:271`

    $this->savePropertiesDirectly($object);

    if (!$object->isDirty()) {
        return null;
    }
