### ISSUE TITLE
The save() function returns null in some instances, causing higher-level try/catches to be problematic

### ISSUE THREAD

**Issue by ok200paul** [calcinai/xero-php#443]
https://github.com/calcinai/xero-php/blob/39b56e03a0288cd543a239d45d5a6d70fabb175d/src/XeroPHP/Application.php#L272

Hi all, is there a reason why the `return null` is used in this conditional? We have a try/catch up at the application level for `save()` and the null return isn't being caught by it. Shouldn't it fire some kind of Exception indicating that the data has not changed, so the `save()` function hasn't been fired to the Xero API? I might be misunderstanding here, but higher try/catches are quietly failing in some circumstances.

Here's what we're doing:
```
$results      = XeroPrivate::save($contact, true);
$resultsArray = $results->getElements(); // .. $results is null if no data has changed

 // .. and so on
```

Cheers - PG

**Comment by calcinai** [comment]
@ok200paul Is there a reason you're using it like that and not just `$contact->save()`? 

I'm not sure it's appropriate to throw an exception if the data hasn't changed, for instance, if you've updated a name with user data and they don't change anything... Thoughts?

**Comment by ok200paul** [comment]
Hey @calcinai - thanks for the quick response. I can't recall why it's like that - I see what you mean on it though, will get it refactored to be more fluent. Might be because it's not being injected or some such, my memory is a little foggy there

Valid point on the exception aspect - just after I posted, my eyes raised to the docblock mentioning the null possibility:
```
* @return Remote\Response|null
```
.. which indicated to me that it's intentional. My higher-up function needs to respect a potential null response. I feel some refactoring coming on! This can be closed - thanks again.
