### ISSUE TITLE
LineItems no longer honour line breaks in the description

### ISSUE THREAD

**Issue by LucidNinja** [calcinai/xero-php#447]
Recently, line items stopped honouring a carriage return in my description. The whole description is now being generated on one line. No code was changed as far as I can tell - is this a change with Xero's API?? Or is there a better way to achieve this?

Eg. This is my line item, which now is on one line instead of 6 (still one line item, but no line breaks inside description)

```
 $lineItems['System']['Description'] = 'Quoted Price: $' . $salePrice . '.
    Supply and Installation of:
    ' . $systemSize . 'kW Solar System. 
    ' . $panelAmount . ' x ' . $panelWattage . 'W ' . $panelSeriesModel . ' solar panels. 
    ' . $componentDetails . '. 
    1x ' . $systemSize . 'kW Solar Mounting kit.'; // This will contain variables
```

**Comment by calcinai** [comment]
Any updates on this @LucidNinja

**Comment by LucidNinja** [comment]
Hey @calcinai - this just started working again with no changes to the codebase on my end. I feel like perhaps there was a brief change to the Xero API? Let's just mark this as resolved for now and reopen if it happens again.
