### ISSUE TITLE
[QUESTION] get xml response from XERO

### ISSUE THREAD

**Issue by link08** [calcinai/xero-php#454]
Hello,
is it possible update the package with the possibility to get the raw XML response from XERO without parsing that?
Or can you tell me how can I do that?

I've saw that in the file 'xero-php/src/XeroPHP/Remote/Request.php', in the method send() there isn't any way to skip the parsing.

rows:
```
126. $this->response = new Response($this, $response, $info, $headers);
127. $this->response->parse();
128.  
129.  return $this->response;
```

Thanks in advance,
Loris.

**Comment by calcinai** [comment]
You can't stop the parsing, but there is a `getResponseBody()` method on the response object that's returned.
