### ISSUE TITLE
PSR-2 Coding Standard

### ISSUE THREAD

**Issue by mhlavac** [calcinai/xero-php#46]
Is anyone opened to use PSR-2 coding standard?

http://www.php-fig.org/psr/psr-2/

**Comment by calcinai** [comment]
Definitely not a bad idea to pick a standard. I previously used PHPStorms auto-format I've the whole project. 

I might have to get used to opening function brackets on new lines!

**Comment by mhlavac** [comment]
@calcinai this can help a lot http://cs.sensiolabs.org/ ;-)

**Comment by gerrywastaken** [comment]
Indeed I hate the psr standards as they use votes instead of solid reasoning behind their decisions, but unfortunately it's been adopted by the PHP community in general so there is really no escaping it.

@calcinai I hate the opening bracket thing too.

I've used the cs fixer tool mentioned by @calcinai and it's actually very good so long as you haven't got inconsistent indenting anywhere.

**Comment by mhlavac** [comment]
@calcinai @gerrywastaken PSR standards are not so bad. There are a lot of discussions going on before voting starts, it's same as PHP RFC a long discussions and then it finally goes down to votes, because there is always someone who doesn't like the final solution and discussions could go on forever.

I was also against spaces and opening brackets on new line, but I got used to it and have no problem with it anymore. I try to respect standard syntax for different languages, because it's easier to contribute that way.

**Comment by gerrywastaken** [comment]
@mhlavac I disagree that it's not so bad. But I do agree that it's a good idea to follow it.

**Comment by calcinai** [comment]
That sounds like a decision..

**Comment by gerrywastaken** [comment]
@calcinai Well it's your repo. I can't make the decision. But if it's a yes then I think this issue can be closed and we can all start coding to it (right @mhlavac?). :)

**Comment by mhlavac** [comment]
@calcinai @gerrywastaken right. I can open PR later this week with reformatted code to PSR2. Good thing is that cs fixer can be used on generated methods as well ;-)

**Comment by calcinai** [comment]
I think it'd be better to fix the generator templates to conform, otherwise, every time we generate it'll put a whole lot of rubbish in the git history.

**Comment by calcinai** [comment]
But yes, let's do it for the rest of the code.  Why not!
