### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by darkwind77** [calcinai/xero-php#461]
I've uploaded all the files to my server.

I'm trying the below code:
```
$config = [
    'oauth' => [
        'callback'         => 'oob',        
        'consumer_key'      => 'key,
        'consumer_secret'   => 'secret',        
        'rsa_private_key'  => 'file://certs/private-key.cer',
    ],
];

$xero = new PrivateApplication($config);

print_r($xero->load('Accounting\\Organisation')->execute());
```

but I'm getting this error:
`Fatal error: Uncaught Error: Class 'XeroPHP\Application\PrivateApplication' not found`

**Comment by timacdonald** [comment]
Hey @darkwind77 do you now if you are using an Autoloader? Perhaps [Composer](https://getcomposer.org) ?

Sounds to me like the files have not been [included](https://secure.php.net/manual/en/function.include.php) so PHP does not know where to find that file.

**Comment by darkwind77** [comment]
I'm not using composer. I've just downloaded the master file, uploaded it to me server and tried the code I mentioned.

I'm stuck.

**Comment by calcinai** [comment]
Hi @darkwind77, the preferred method is using Composer, as @timacdonald mentioned.  If your project isn't using composer, the namespaces are [PSR-4](https://www.php-fig.org/psr/psr-4/) compliant, so you can add it to an existing autoloader.

If you don't have an autoloader in your project, unfortunately you'll need to write one, or manually `include` all of the files in the project.

I'd strongly recommend using Composer, as it's now very much the standard and the vast majority of PHP code now uses it for dependency management and autoloading.

**Comment by darkwind77** [comment]
ah. unfortunately I don't have autoloader on the project.

Manually include meaning using the `include` function, correct?

So `include` each file of each folder?

**Comment by calcinai** [comment]
@darkwind77 yes that's what you'll need to do.  

If you really can't use Composer (please try, it'll make every day of your life easier), you could use something like this from [php-fig](https://www.php-fig.org/psr/psr-4/examples/)

```
spl_autoload_register(function ($class) {

    // project-specific namespace prefix
    $prefix = 'XeroPHP\\';

    // base directory for the namespace prefix
    $base_dir = __DIR__ . '/xero-php/';

    // does the class use the namespace prefix?
    $len = strlen($prefix);
    if (strncmp($prefix, $class, $len) !== 0) {
        // no, move to the next registered autoloader
        return;
    }

    // get the relative class name
    $relative_class = substr($class, $len);

    // replace the namespace prefix with the base directory, replace namespace
    // separators with directory separators in the relative class name, append
    // with .php
    $file = $base_dir . str_replace('\\', '/', $relative_class) . '.php';

    // if the file exists, require it
    if (file_exists($file)) {
        require $file;
    }
});

```
