### ISSUE TITLE
Use scrutinizer to run additional checks

### ISSUE THREAD

**Issue by mhlavac** [calcinai/xero-php#47]
https://scrutinizer-ci.com/ can be used for free on open source projects like this.

It does a lot of things https://scrutinizer-ci.com/tour/all-features-in-one-glance

**Comment by gerrywastaken** [comment]
:+1: linting tools.

I think it's a great idea. It's essentially removing work when checking over pull requests. It means that instead of trying to justify why you won't merge messy code, you can just point to the results of these checks.

**Comment by calcinai** [comment]
Should we be using one or both of this and #48?

**Comment by gerrywastaken** [comment]
Are there downsides to using both?

**Comment by calcinai** [comment]
I've never used either, let alone them together!

**Comment by gerrywastaken** [comment]
Hmmm... I just tried signing up for https://scrutinizer-ci.com/. They require read and write access not just to public repositories, but also to any organisations I have access to before letting me proceed. This really sucks.

**Comment by calcinai** [comment]
Yes - I did the same.  Makes me feel a little uneasy!
