### ISSUE TITLE
Could not resolve host: api.xero.com 

### ISSUE THREAD

**Issue by Mutondi** [calcinai/xero-php#473]
Hi there I am getting a could not resolve host error when I try to post an invoice to the xero api

**Comment by timacdonald** [comment]
Sounds like you machine is unable to communicate with the Xero API endpoint.

What happens if you open up a web browser and try to visit: https://api.xero.com ?

**Comment by Mutondi** [comment]
When I do that. it leads me to the xero accounting login page. been trying to trouble shoot the solution to no luck , it has been communicating and posting fine all week. I guess this is a network issue ?

**Comment by Mutondi** [comment]
`<br />
<b>Fatal error</b>:  Uncaught XeroPHP\Remote\Exception: Curl error: Failed to connect to api.xero.com port 443: Timed out in C:\xampp2\htdocs\helloapi\src\XeroPHP\Remote\Request.php:125
Stack trace:
#0 C:\xampp2\htdocs\helloapi\src\XeroPHP\Remote\Query.php(287): XeroPHP\Remote\Request-&gt;send()
#1 C:\xampp2\htdocs\helloapi\private.php(71): XeroPHP\Remote\Query-&gt;execute()
#2 C:\xampp2\htdocs\helloapi\private.php(201): SearchCustomer('SUP002')
#3 {main}
  thrown in <b>C:\xampp2\htdocs\helloapi\src\XeroPHP\Remote\Request.php</b> on line <b>125</b><br />`

**Comment by Mutondi** [comment]
![image](https://user-images.githubusercontent.com/28397181/51652816-a29a7680-1f99-11e9-9ac2-2db1dc51745a.png)
this what i see : Ping request could not find host api.xero.com. Please check the name and try again.

**Comment by calcinai** [comment]
@Mutondi you should expect something like 

```
$ ping api.xero.com
PING e11670.x.akamaiedge.net (23.73.188.177): 56 data bytes
64 bytes from 23.73.188.177: icmp_seq=0 ttl=56 time=167.612 ms
64 bytes from 23.73.188.177: icmp_seq=1 ttl=56 time=173.314 ms
64 bytes from 23.73.188.177: icmp_seq=2 ttl=56 time=173.081 ms
```

What that looks like is your DNS lookup is failing.  Have you got non-standard DNS configured on your computer/network?

**Comment by Mutondi** [comment]
Thanks Gentlemen, I resolved the issue. DNS was the issue. Thanks for this awesome tool!
