### ISSUE TITLE
unable to fetch Address And phone 

### ISSUE THREAD

**Issue by wiki99** [calcinai/xero-php#474]
Hi calcinai
 I am getting problem in Xero php sdk library  regarding address and phone and i am unable to create Address and phone object can you help me out from this issue how fetch address and phone from sdk xero api

**Comment by wiki99** [comment]
on get address it return phone object and on phone it return address obj how use it?

**Comment by timacdonald** [comment]
Can you post a full code snippet? The above seems like it has been cut off.

**Comment by wiki99** [comment]
it dosent return object of address and phone i simply tried to get object property of address 
by using  
$contacts =$xero->load('Accounting\\Address')->execute();
foreach($contacts as $contact)
{
print_R($contact);

}

**Comment by timacdonald** [comment]
What do you get if you dump the `$contacts` variables?

```php
$contacts = $xero->load('Accounting\Address')->execute();

var_dump($contacts);
die;
```

**Comment by wiki99** [comment]
it return blank

**Comment by timacdonald** [comment]
Sounds like you have not set the address in Xero.

Can you please paste the result of the following code so we can see what is happening...

```php
$contacts = $xero->load('Accounting\Address')->execute();

var_dump($contacts->getAddresses());
die;
```

**Comment by wiki99** [comment]
ok

**Comment by wiki99** [comment]
/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:11:string 'Number of contacts: 4' (length=21)

/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:14:string 'Number of addresses for this contact: 2' (length=39)

/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:14:string 'Number of addresses for this contact: 2' (length=39)

/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:14:string 'Number of addresses for this contact: 2' (length=39)

/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:14:string 'Number of addresses for this contact: 2' (length=39)

**Comment by wiki99** [comment]
it display like this

**Comment by timacdonald** [comment]
Great!

Now lets see what is happening with the following code.

```php
$contacts = $xero->load('Accounting\\Contact')->execute();

foreach ($contacts as $contact) {
    $addresses = $contact->getAddresses();
    var_dump('First address type: '.$addresses[0]->getAddressType());
    var_dump('Second address type: '.$addresses[1]->getAddressType());
}
```

**Comment by wiki99** [comment]
now it return

**Comment by wiki99** [comment]
/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:13:string 'First address type: STREET' (length=26)

/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:14:string 'Second address type: POBOX' (length=26)

/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:13:string 'First address type: STREET' (length=26)

/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:14:string 'Second address type: POBOX' (length=26)

/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:13:string 'First address type: STREET' (length=26)

/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:14:string 'Second address type: POBOX' (length=26)

/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:13:string 'First address type: STREET' (length=26)

/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:14:string 'Second address type: POBOX' (length=26)

**Comment by timacdonald** [comment]
So looks like it is working now?

This code is looping though all the customers. For each customer it is looping through their addresses and outputting information about the address.

**Comment by wiki99** [comment]
how i used street address and pobox address differently  in same file

**Comment by timacdonald** [comment]
You need to check what type of address it is. You can do this as follows (just a quick example):

```php

use XeroPHP\Models\Accounting\Address;

$contacts = $xero->load('Accounting\\Contact')->execute();

foreach ($contacts as $contact) {

    $address = $contact->getAddresses()[0];

    if ($address[0]->getAddressType() === Address::ADDRESS_TYPE_POBOX) {
        var_dump('this is a PO Box');
    }

    if ($address[0]->getAddressType() === Address::ADDRESS_TYPE_STREET) {
        var_dump('this is a Street address');
    }


    if ($address[0]->getAddressType() === Address::ADDRESS_TYPE_DELIVERY) {
        var_dump('this is a delivery address');
    }
}
```

**Comment by wiki99** [comment]
ok thanks Timac its working fine great

**Comment by timacdonald** [comment]
awesome
