### ISSUE TITLE
Unable to use for Public applications

### ISSUE THREAD

**Issue by PrakharSambhav1** [calcinai/xero-php#475]
"Token has not been provided" Error is displayed when ever i try to execute. Please make a CRUD example for public examples if possible.
exception:"XeroPHP\Remote\Exception\UnauthorizedException"
file:"/var/www/html/hoops-crm/dev/backend/vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php"
message:"Token has not been provided"

**Comment by wiki99** [comment]
hii 
did you try this file:///var/www/html/xerophp/foldername/publickey.pem kindly make absolute path for your unix system
