### ISSUE TITLE
Address not display on account/contact

### ISSUE THREAD

**Issue by wiki99** [calcinai/xero-php#476]
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
ini_set('display_errors',1);
require 'vendor/autoload.php';
$xero = new \XeroPHP\Application\PrivateApplication($config);
	
echo "<pre>";
$contacts =$xero->load('Accounting\\Contact')->execute();

foreach($contacts as $contact)
{

	$add=$xero->load(Address::class)->execute();
	print_r($contact->getAddresses($add->getAddressLine1()->$add->getCity()));
		
}

**Comment by timacdonald** [comment]
@wiki99 you've already open an issue about this: https://github.com/calcinai/xero-php/issues/474

Please close this issue.

**Comment by wiki99** [comment]
ok
