### ISSUE TITLE
unable to retreive website

### ISSUE THREAD

**Issue by wiki99** [calcinai/xero-php#477]
Hi 

i am unable to get website please help me out how we fetch website from sdk library 

$xero = new \XeroPHP\Application\PrivateApplication($config);
	$contacts = $xero->load('Accounting\\Contact')->execute();  
foreach($contacts as $contact)
{
$contact->getWebsite();
var_dump($contact);
}

**Comment by wiki99** [comment]
output is 
/var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:28:null

**Comment by wiki99** [comment]
yes its return string but when i am echo $contact->getWebsite(); it return blank white page why but on var_dump its return /var/www/html/suitexero/custom/entrypoints/xero-php/tests/sendAccountToXero.php:29:string 'Contact website is: ' (length=20)

**Comment by wiki99** [comment]
i face same issue in getting invoice due date my  code are
 $xero = new \XeroPHP\Application\PrivateApplication($config);
	$Invoice = $xero->load('Accounting\\Invoice')->execute();
foreach ($Invoice as $invoice)
{
$get=$invoice->getDueDate();
			var_dump($get);
}

**Comment by wiki99** [comment]
output is : /var/www/html/suitexero/custom/entrypoints/xero-php/tests/getXeroInvoices.php:30:null

/var/www/html/suitexero/custom/entrypoints/xero-php/tests/getXeroInvoices.php:30:
object(DateTime)[65]
  public 'date' => string '2019-01-31 00:00:00.000000' (length=26)
  public 'timezone_type' => int 3
  public 'timezone' => string 'Asia/Colombo' (length=12)
 but uanble to fetch duedate and when echo it display nothing on removing var_dump(); how use datetime

**Comment by timacdonald** [comment]
I believe these issues are outside the scope of this library.

The website issue seems like there is not a website set at Xero's end.

Regarding the datetime "issue", the PHP docs have information on the DateTime object: https://secure.php.net/manual/en/class.datetime.php

You will need to learn how to utilise the DateTime class to be able to work with it in your app.

**Comment by wiki99** [comment]
ok sure thanks
