### ISSUE TITLE
Blank Line Item

### ISSUE THREAD

**Issue by DPineault** [calcinai/xero-php#479]
When using the UI, it is possible to create blank/empty line items in an Invoice.  This can be used for instance as a separator.

That said, from my experience with this extension, this does not seem possible as Description requires a value.  Is there any way to do this?  Am I missing something?

Thank you.

**Comment by calcinai** [comment]
@DPineault this could be related to #447, have you tested it recently?

Does the API previewer allow you  to submit empty lines?
