### ISSUE TITLE
Use Sensiolabs insights

### ISSUE THREAD

**Issue by mhlavac** [calcinai/xero-php#48]
Additional checks can be done with https://insight.sensiolabs.com/ it's free for open source projects

**Comment by gerrywastaken** [comment]
@calcinai OK so while Sensio has the same excessive permissions issue as Scrutinizer, you can work around issue.

During the login with github step you need to modify the url that they send you to removed the contents of the scope argument. This sets their permissions to only public repos. see: https://developer.github.com/v3/oauth/#scopes

Then when it tries to connect to a repository it can't and says you can manually add a deploy key. Doing this allows you to give read only access to a single repository.

There was a problem though, it seems to think my version of this repository is private as so limits the account. I'm not sure if the same will happen for you given that you have the root repository.
