### ISSUE TITLE
setIsTrackedAsInventory does not appear to work when creating an Item

### ISSUE THREAD

**Issue by FrankEBailey** [calcinai/xero-php#498]
I am creating Items in Xero via the API prior to adding a draft invoice.

My code is as follows:

			$nu = new XeroPHP\Models\Accounting\Item($xero);
			$salesdetails = new XeroPHP\Models\Accounting\Item\Sale($xero);
				$salesdetails->setAccountCode($linePart['SalesAccount'])
				->setUnitPrice($linePart['SalesUnitPrice'])
				->setTaxType('OUTPUT3');
			$nu->setCode($linePart['ItemCode'])
				->setName($linePart['ItemName'])
				->setPurchaseDescription($linePart['ItemName'])
				->setDescription($linePart['ItemName'])
				->setIsSold(true)
				->setIsPurchased(true)
				->setIsTrackedAsInventory(true)
				->addSalesDetail($salesdetails);
			$nu->save();

When I go into the created item in the Xero system, the "I track this item" checkbox is unchecked. 

I have checked that the Item did not already exist and have transactions against it. The item was brand new, created by the above code, but the ->setIsTrackedAsInventory(true) command appears to have no effect. 

Any assistance on this would be greatly appreciated.

**Comment by timacdonald** [comment]
I don't believe you set that attribute directly - instead you pass other information for Xero to determine if that is supposed to be true.

Take a look at the docs: https://developer.xero.com/documentation/api/items

> InventoryAssetAccountCode: The inventory asset account for the item. The account must be of type INVENTORY. The COGSAccountCode in PurchaseDetails is also required to create a tracked item

**Comment by FrankEBailey** [comment]
Hi again Tim. Yes, what you're saying makes sense in the context of a careful re-read of the docs. Up to now I've only been passing sales info with no purchase info, but not being able to track an item if you don't have a record of the purchase of that item is a perfectly sensible limitation.
