### ISSUE TITLE
Unable to load a specific Purchase Order line item by LineItemID

### ISSUE THREAD

**Issue by FrankEBailey** [calcinai/xero-php#499]
I'm not sure if the library supports what I'm trying to do. If a line item with a known LineItemID exists, it should be updated, otherwise it should be added.

My call is 

$lineitem = $xero->load(Accounting\PurchaseOrder\LineItem::class)->where('LineItemID', 'af6e6e41-ca02-4b8e-b79b-06ef071f56d1')->execute();

However this doesn't return anything. Can a line item even be LOADed in this way, or perhaps I'm using incorrect syntax?

**Comment by timacdonald** [comment]
Maybe try the `loadByGUID ` method and see if that works.

```php
$lineitem = $xero->loadByGUID('Accounting\PurchaseOrder\LineItem', 'af6e6e41-ca02-4b8e-b79b-06ef071f56d1')->execute();
```

**Comment by FrankEBailey** [comment]
Tim, you are a God among men. That did the trick. Thank you so much!

While you're here, do I need to save updates to the line items as I iterate through them, or will any updates I make be saved when I save the Purchase Order as a whole?

**Comment by FrankEBailey** [comment]
Drat, that didn't work, I was hopeful for a second there, but unfortunately it doesn't return anything. I get

Uncaught XeroPHP\Remote\Exception\NotFoundException: Resource Not Found

I'm beginning to worry that getting a LineItem isn't supported in the way I'd hoped...

Thanks for trying Tim!

**Comment by timacdonald** [comment]
You know what - I didn't even look at the docs before posting my first comment - but scanning now I don't think you can load the line items individually.

Gotta get the parent invoice and then scan through the line items by the looks of it.

...which no doubt is where your thinking is going as well.

**Comment by FrankEBailey** [comment]
Yeah, very much so. My thought right now is to do something like this:

$searchedValue = 'af6e6e41-ca02-4b8e-b79b-06ef071f56d1';
$neededObject = array_filter(
	(array)$po->LineItems,
	function ($e) use ($searchedValue) {
		return $e->LineItemID == $searchedValue;
	}
);

$lineItem = $neededObject[0];

That gives me the matching LineItem object, if it exists. 

I need to do some testing now to see whether I can update that object, pass it back to the PurchaseOrder object, then save the PurchaseOrder, and have my changes saved to Xero.

Crossing fingers... I wouldn't've thought that updating existing line items in a Purchase Order would prove to be this tricky.
