### ISSUE TITLE
Xml for post data was invalid, Reference to undeclared entity 'aacute'.

### ISSUE THREAD

**Issue by paulsschwarz** [calcinai/xero-php#5]
I think I'm hitting this issue. I've read the thread but I'm unclear on the best way to solve this.
https://community.xero.com/developer/question/32311

**Comment by calcinai** [comment]
Ideally, it'd use DOMDocument here.  At the time of implementation I wouldn't justify it as it's build recursively on a per-node basis.  Maybe now I can!

**Comment by paulsschwarz** [comment]
I'm not familiar enough with the code yet to appreciate what you're talking about. Is there a workaround? or is there something we can fix here?

**Comment by calcinai** [comment]
I've just released a fix for this. v1.1.1

**Comment by paulsschwarz** [comment]
:)
