### ISSUE TITLE
composer.json autoload entry needs correcting

### ISSUE THREAD

**Issue by judgej** [calcinai/xero-php#50]
The PSR-0 autoload entry is as follows:

    "psr-0": { "": "src/" }

This will catch ALL namespaces and even classes without namespaces. This can slow an application down with additional filesystem checks that are not necessary. The entry should look like this:

    "psr-0": { "XeroPHP": "src/" }

or even:

    "psr-4": { "XeroPHP": "src/XeroPHP/" }

or use both of these at the same time.

If the namespace is changed as per ticket #45 I would recommend dropping PSR-0 support and just going for PSR-4:

    "psr-4": { "Calcinai\\XeroPHP": "src/" }

In this case the `XeroPHP` directory under `src` would be dropped, and `Application.php` and friends would go straight into `src`. You don't *have to* drop that directory for PSR-4, but you *can* so you might as well.

**Comment by calcinai** [comment]
Sorted.
