### ISSUE TITLE
Any examples of the OAuth callback?

### ISSUE THREAD

**Issue by judgej** [calcinai/xero-php#51]
When acting as a partner application, OAuth kicks in the first time and results in the OAuth callback being called. Are there any examples of what this callback handler would look like?

**Comment by mhlavac** [comment]
@judgej I think it's this part https://github.com/calcinai/xero-php/blob/master/examples/partner.php#L78 that is responsible for what you need.

Xero redirects you to your callback with oauth_verifier value passed via get.

**Comment by judgej** [comment]
So it should redirect back to itself to complete the authorisation process?

I'm coming back to the page with `oauth_verifier` and a few other parameters set, but it's still giving me the "Click here to Authorize" link rather than printing the account details. Do I perhaps need to make sure I start the session for the (demo) storage?

The private application example works, authorised against a single, pre-selected test Xero account.

**Comment by judgej** [comment]
I think Xero has blocked me now. I'll give it another try later on, when the blocking has hopefully been lifted.

**Comment by judgej** [comment]
I'm trying the public application example, also with no luck. The session keeps getting an empty array added to it:

~~~php
array(1) {
  ["oauth"]=>
  array(3) {
    ["token"]=>
    NULL
    ["token_secret"]=>
    NULL
    ["expires"]=>
    NULL
  }
}
~~~

which results in an error:

~~~
Fatal error: Uncaught exception 'XeroPHP\Remote\Exception\UnauthorizedException' with message 'Token has not been provided' in /var/www/vhosts/mysite.com/httpdocs/xero/vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php:85
Stack trace:
#0 /var/www/vhosts/mysite.com/httpdocs/xero/vendor/calcinai/xero-php/src/XeroPHP/Remote/Request.php(106): XeroPHP\Remote\Response->parse()
#1 /var/www/vhosts/mysite.com/httpdocs/xero/vendor/calcinai/xero-php/src/XeroPHP/Remote/Query.php(106): XeroPHP\Remote\Request->send()
#2 /var/www/vhosts/mysite.com/httpdocs/xero/public.php(69): XeroPHP\Remote\Query->execute()
#3 {main}
  thrown in /var/www/vhosts/mysite.com/httpdocs/xero/vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php on line 85
~~~

I'm stumped how to debug this.

**Comment by judgej** [comment]
The URL it tries to get the token from is `https://api.xero.com/oauth/RequestToken`

The response to sending that (`$oauth_response = $request->getResponse()->getOAuthResponse();`) is "Bad Request" with a code of 400.

The public application does not have a `die()` in the exception raised by the bad request to get the OAUTH_REQUEST_TOKEN so that explains the empty array in the session.

**Comment by judgej** [comment]
Ah, "Callback url is not in the registered callback domain".

That has been left blank on my application. It is supposed to be optional. I set the callback domain (labelled "optional" in nice italic letters) in my public application, and it now works.

**Comment by gerrywastaken** [comment]
@judgej I think it would be good to add a comment to https://github.com/calcinai/xero-php/blob/master/examples/partner.php#L13 (and the other examples) stating that the "localhost" domain (or whatever domain is specified as the callback) must be specified in the appropriate callback config on https://app.xero.com/Application.

**Comment by mhlavac** [comment]
@gerrywastaken @judgej in example session_start is used already. We could add first page where you can set up Application config via simple form and save entered data to session.

That would make test really easy, because you would just open the page, enter data in those fields and you can make your requests.

Additionally callback domain could be auto prefilled by really simple javascript or from $_SERVER values..

What do you think?

**Comment by gerrywastaken** [comment]
@mhlavac If I understand you correct you are suggesting making a config generator for xero-php. That sounds interesting but I'm not sure if it adds unnecessary bloat. I think the existing system is already quite simple and appropriate. But I don't feel strongly either way.

I think they problem @judgej  was having was that he hadn't filled in the correct value on https://app.xero.com/Application.

**Comment by calcinai** [comment]
Yeah, I think that use of this will always require a _basic_ understanding of OAuth.  Xero try to hold your hand a bit when you set up your application, so maybe it can just be left at that.

I really don't know how to approach those examples that use the session - it was purely an example using the easiest way to maintain state between page loads.  I'm unsure of a simple alternative.

**Comment by gerrywastaken** [comment]
Yeah unfortunatly PHP doesn't have something like [pstore](http://ruby-doc.org/stdlib-1.9.2/libdoc/pstore/rdoc/PStore.html) or [shelve](https://docs.python.org/2/library/shelve.html)

But maybe something like this might be a better alternative to using sessions.

```php
<?php
// You should probably replace this with a more robust form of persistent storage, such as a database
function pstore($data=null){
  $filename = '/tmp/pstore.dat';

  if($data !== null){
    $returnVal = file_put_contents($filename, serialize($data));
  }
  else{
    $returnVal = unserialize(file_get_contents($filename, $data));
  }

  return $returnVal;
}

$xeroSession = [
  'token' => 'tdfahsjkhfdja',
  'token_secret' => 'dkjfkdlsjfa'
];


// Store
pstore($xeroSession);

// Fetch
$xeroSession2 = pstore();

var_dump($xeroSession2);
```

**Comment by judgej** [comment]
TBH the session is fine. I just forgot to copy that line from the example code, and once I had, it all worked fine.

Storing the keys in the session (for example only) works with OAauth because there are no back-channels - everything happens via the user's browser, so the session data is always going to be available on every page call.

The example does not need to be perfect IMO - so long as it works and gives people a leg-up to seeing this plugin working, it has served its purpose. It just maybe needs a few additional notes to explain what to set up and perhaps why you would or would not do similar things in production.

I'll do a PR with some minor notes added, perhaps an auto-detection of the current URL (got [something similar here](https://github.com/academe/OmniPay-SagePay-Demo/blob/master/storage.php#L15)).

**Comment by calcinai** [comment]
What was the verdict here?  Want me to explain more int he examples?

**Comment by gerrywastaken** [comment]
@calcinai I think it can be closed.

@judgej Has mentioned that he will submit a pull request.

> I'll do a PR with some minor notes added, perhaps an auto-detection of the current URL

**Comment by calcinai** [comment]
Ok.

**Comment by judgej** [comment]
Thanks. I've been away for most of the last week, so no updates. The PR would be no more than a couple of lines, but I'll try and get them done this week.

**Comment by gerrywastaken** [comment]
@judgej I don't know about @calcinai, but I prefer small pull requests as they are far easier to evaluate.

**Comment by calcinai** [comment]
@gerrywastaken absolutely.

**Comment by sujjadyzi** [comment]
hi i am stuck in the issue of Token has not been provided. @judgej  can you please tell me that what have you done to overcome it. because i added the callback domain, that is optional, in my application and added the same name at config with name call back but still same error

**Comment by samtheson** [comment]
@sujjadyzi On callback, just make sure you have set the token and the token secret to the corresponding values you got back during the authorisation URL call, as was mentioned in [an earlier comment](https://github.com/calcinai/xero-php/issues/51#issuecomment-122289410). Otherwise your callback handling will fail with errors like `Failed to validate signature` , `Token was not provided etc.
