### ISSUE TITLE
Website, Discount, Balances gone missing

### ISSUE THREAD

**Issue by AndyTurff** [calcinai/xero-php#510]
Tried getting Discount from Contacts and although there is one set in Xero nothing is returned, I thought it must be me but I did a print_r($contact); and the array returned is missing Discount and also Website and everything below Balances.
I don't mean there is no data, the whole line e.g. [Website] => [Discount] => etc is missing.
In Xero Previewer they all show up fine when doing a Contacts by Contact ID/Number.

Cuurency, which is at the same level in the array, is fine.

Any help would be greatly appreciated.
P.S. I am only using the Demo data all be it altered by myself. Would this make any difference?

**Comment by AndyTurff** [comment]
As an update, the query does return  the fields for the items but as you can see they are poulatrd in Previewer but not in the returned array. I can't see what the problemis. Please help...

This is what Previewer returns:-

         <PhoneType>MOBILE</PhoneType>
        </Phone>
      </Phones>
      <UpdatedDateUTC>2019-02-21T04:04:41.103</UpdatedDateUTC>
      <IsSupplier>false</IsSupplier>
      <IsCustomer>false</IsCustomer>
      <DefaultCurrency>GBP</DefaultCurrency>
      **<Discount>10.00</Discount>**
      **<Website>http://24lock.com</Website>**
      <HasAttachments>false</HasAttachments>
    </Contact>
  </Contacts>
</Response>

And this is the print_r of the array
Array ( [PhoneType] => MOBILE [PhoneNumber] => [PhoneAreaCode] => [PhoneCountryCode] => ) [_dirty:protected] => Array ( ) [_associated_objects:protected] => Array ( [Phones] => XeroPHP\Models\Accounting\Contact Object *RECURSION* ) [_application:protected] => ) ) ) [IsSupplier] => [IsCustomer] => [DefaultCurrency] => GBP [XeroNetworkKey] => [SalesDefaultAccountCode] => [PurchasesDefaultAccountCode] => [SalesTrackingCategories] => [PurchasesTrackingCategories] => [TrackingCategoryName] => [TrackingCategoryOption] => [PaymentTerms] => [UpdatedDateUTC] => DateTime Object ( [date] => 2019-02-21 04:04:41.103000 [timezone_type] => 3 [timezone] => UTC ) [ContactGroups] =>** [Website] =>** [BrandingTheme] => [BatchPayments] =>** [Discount] => **[Balances] => [HasAttachments] => )

**Comment by timacdonald** [comment]
@AndyTurff can you post the PHP code you are using? Might make it easier to debug if we can see what you are doing in your code.

**Comment by AndyTurff** [comment]
Hi Tim, Thanks for getting back to me. My code is below, it is just a test code so a bit long winded as I am trying to trouble shoot it. I have checked on Xero and the contact queried has all the necessary fields completed i.e. website and discount.

`<?php

use XeroPHP\Application\PrivateApplication;

require 'autoload.php';
include ('config.php');

$xero = new PrivateApplication($config);

$contacts = $xero->load('Accounting\\Contact'::class)
	//->where('UpdatedDateUTC >= DateTime(2018, 01, 31) && UpdatedDateUTC < DateTime(2019, 02, 17)')
	->where('Name', '24 Locks')
	//->where('ContactID', '8e47aa31-52b7-4a67-b794-84f2bfa0bb90')//not working
	->execute();

	$gg=0;
	$aa=0;
foreach ($contacts as $contact) {
    //print_r($contact);
	   
	//print_r($contact->toStringArray()); 

			$company = $contact->Name;
			$FirstName = $contact->FirstName;
			$emailaddress = $contact->EmailAddress;
			$contactId = $contact->ContactID;
			$ContactNumber = $contact->ContactNumber;
			$ln = $contact->LastName;
			$contactStatus = $contact->ContactStatus;
			$UpdatedDateUTC = $contact->UpdatedDateUTC;
			$Website = $contact->Website;
			$DefaultCurrency = $contact->DefaultCurrency;
			$discount = $contact->Discount;
			
			$addresses = $contact->getAddresses(0);	
			
			$addressType = $addresses[0]->getAddressType();			
			$AddressLine1 = $addresses[0]->getAddressLine1();			
			$AddressLine2 = $addresses[0]->getAddressLine2();
			$city = $addresses[0]->getCity();
			$Region = $addresses[0]->getRegion();			
			$PostalCode = $addresses[0]->getPostalCode();
			$country = $addresses[0]->getCountry();
			
			$addressTypex = $addresses[1]->getAddressType();			
			$AddressLine1x = $addresses[1]->getAddressLine1();			
			$AddressLine2x = $addresses[1]->getAddressLine2();
			$cityx = $addresses[1]->getCity();
			$Regionx = $addresses[1]->getRegion();			
			$PostalCodex = $addresses[1]->getPostalCode();
			$countryx = $addresses[1]->getCountry();
			
			$phones = $contact->getPhones(0);
			$phoneTypeDDI = $phones[0]->getPhoneType();			
			$phoneNumberDDI = $phones[0]->getPhoneNumber();
			$phoneAreaCodeDDI = $phones[0]->getPhoneAreaCode();
			$phoneCountryCodeDDI = $phones[0]->getPhoneCountryCode();

			$phoneTypeDefault = $phones[1]->getPhoneType();
			$phoneNumberDefault = $phones[1]->getPhoneNumber();
			$phoneAreaCodeDefault = $phones[1]->getPhoneAreaCode();
			$phoneCountryCodeDefault = $phones[1]->getPhoneCountryCode();

			$phoneTypeFax = $phones[2]->getPhoneType();
			$phoneNumberFax = $phones[2]->getPhoneNumber();
			$phoneAreaCodeFax = $phones[2]->getPhoneAreaCode();
			$phoneCountryCodeFax = $phones[2]->getPhoneCountryCode();

			$phoneTypeMobile = $phones[3]->getPhoneType();
			$phoneNumberMobile = $phones[3]->getPhoneNumber();
			$phoneAreaCodeMobile = $phones[3]->getPhoneAreaCode();
			$phoneCountryCodeMobile = $phones[3]->getPhoneCountryCode();


			echo"<br> <b>".$company;			
			echo"</b><br> ".$FirstName." ".$ln;

			echo"<br> ".$addressType;
			echo"<br> ".$AddressLine1;
			echo"<br> ".$AddressLine2;
			echo"<br> ".$city;			
			echo"<br> ".$Region;
			echo"<br> ".$PostalCode;			
			echo"<br> ".$country;			
			echo"<br> Email-".$emailaddress;

			echo"<br><br> ".$addressTypex;
			echo"<br> ".$AddressLine1x;
			echo"<br> ".$AddressLine2x;
			echo"<br> ".$cityx;			
			echo"<br> ".$Regionx;
			echo"<br> ".$PostalCodex;			
			echo"<br> ".$countryx;			
			//echo"<br> Email-".$emailaddressx;
			
			echo"<br><br> Phone Type-".$phoneTypeDDI;			
			echo"<br> Country Code-".$phoneCountryCodeDDI;
			echo"<br> Area Code-".$phoneAreaCodeDDI;
			echo"<br> Phone Number-".$phoneNumberDDI;
			
			echo"<br><br> Phone Type-".$phoneTypeDefault;			
			if(isset($phoneCountryCodeDefault)){
			echo"<br> Country Code-".$phoneCountryCodeDefault;
			}
			echo"<br> Area Code-".$phoneAreaCodeDefault;
			echo"<br> Phone Number-".$phoneNumberDefault;
			
			echo"<br><br> Phone Type-".$phoneTypeFax;
			if(isset($phoneCountryCodeFax)){
			echo"<br> Country Code-".$phoneCountryCodeFax;
			}
			echo"<br>Fax Number: ".$phoneAreaCodeFax." ".$phoneNumberFax;

			echo"<br><br> Phone Type: ".$phoneTypeMobile;
			if(isset($phoneCountryCodeMobile)){			
			echo"<br> Country Code: ".$phoneCountryCodeMobile;
			}
			echo"<br>Number: ".$phoneAreaCodeMobile." ".$phoneNumberMobile;

			echo"<br><br>DefaultCurrency-".$DefaultCurrency; 
			echo"<br>Discount-".$discount; 
			echo"<br>Website-".$Website;
			echo"<br>ContactID-".$contactId; 
			echo"<br>Contact Number-".$ContactNumber;
			echo"<br>Contact Status-".$contactStatus . "<br>";
			print_r($UpdatedDateUTC);
			echo"<br><br>";
		}`
