### ISSUE TITLE
Not able to generate vendor folder using composer

### ISSUE THREAD

**Issue by cnelindiahwe** [calcinai/xero-php#511]
Hello,

I am not able to get vendor folder using composer.

Please see the screenshot:
![image](https://user-images.githubusercontent.com/10735803/53024081-5ea96d00-3484-11e9-8cba-50f1f1eb0003.png)

Please help me on this. What is error in composer.json file? 
I have added version "1.5.0" after description also. But composer showing error in CMD.

Please tell me what i need to done here?
Can you provide update composer.json file?

Thanks

**Comment by calcinai** [comment]
Can you please post your composer.json?

**Comment by cnelindiahwe** [comment]
Here is my composer.json code:
`{
    "name": "calcinai/xero-php",
    "type": "library",
    "description": "A client implementation of the Xero API, with a cleaner OAuth interface and ORM-like abstraction.",
	"version": "1.5.0",
    "homepage": "https://github.com/calcinai/xero-php",
    "license": "MIT",

    "require": {
        "php": ">=5.5.0",
        "ext-curl": "*",
        "ext-openssl": "*",
        "calcinai/xero-php": "1.5.*"
    },

    "require-dev": {
        "phpunit/phpunit": "~4.7",
        "fabpot/goutte": "~2.0",
        "twig/twig": "1.16.2"
    },

    "repositories": [
    ],

    "autoload": {
        "psr-4": {
            "XeroPHP\\": "src/XeroPHP/"
        }
    }

}`

**Comment by timacdonald** [comment]
That is the `composer.json` for this project. You need to create your *own* version. Just replace the entire contents of you file with the following and run `composer install`.

```
{
    "require": {
        "calcinai/xero-php": "^1.5"
    }
}
```

But I highly recommend digging into the composer docs to understand the tool you are using: https://getcomposer.org

**Comment by cnelindiahwe** [comment]
Hello,

It still not working. 
![s](https://user-images.githubusercontent.com/10735803/53075996-8f38e780-3514-11e9-86bd-f0bb9dc1b376.png)

Here is the updated file of composer.json
http://bit.ly/2TXWBCN

Please help

**Comment by timacdonald** [comment]
I meant literally delete *everything* in your composer.json file and replace the contents with the snippet l provided

**Comment by timacdonald** [comment]
And also, just run `composer install` not `require`

**Comment by cnelindiahwe** [comment]
Yes, now i am able install generate vendor folder.
Thankyou very much.
