### ISSUE TITLE
Uncaught Error: Class 'XeroPHP\Application\PrivateApplication' not found

### ISSUE THREAD

**Issue by cnelindiahwe** [calcinai/xero-php#513]
Hello,

I have coming a fatal error.

Uncaught Error: Class 'XeroPHP\Application\PrivateApplication' not found

I have included also autoload library in my page.

You can check my screenshots:
![image](https://user-images.githubusercontent.com/10735803/53088279-45a9c600-352f-11e9-9c07-d1baa12388b2.png)

Also you can see my directory structure:
![image](https://user-images.githubusercontent.com/10735803/53088172-fa8fb300-352e-11e9-83f3-1442a65e8f5a.png)

Now what is the issue here?

Can you help me?

**Comment by calcinai** [comment]
That directory structure doesn't look correct.  Did you have a good read of [the composer documentation](https://getcomposer.org/doc/)  as @timacdonald  recommended?

**Comment by cnelindiahwe** [comment]
Hello,

Which document i need to read? Can you send me link?

I did not found @timacdonald document.
 
What is wrong in my directory structure?

**Comment by calcinai** [comment]
I’d recommend reading from the start until you feel like you’re comfortable with how composer works. 

My comment re: directory structure was because the XeroPHP directory should be _inside_ the vendor folder

**Comment by cnelindiahwe** [comment]
Hello,

I have put XeroPHP directory inside the vendor folder but i have still coming error 

**Error:** 
Fatal error: Uncaught Error: Class 'XeroPHP\Application\PrivateApplication' not found in /home/drkam418/lectures.owltalks.org/stripe-to-zero2/test.php:21 Stack trace: #0 {main} thrown in /home/drkam418/lectures.owltalks.org/stripe-to-zero2/test.php on line 21

What is mistake in my vendor directory or other directory?

![image](https://user-images.githubusercontent.com/10735803/53150499-b22bd000-35d6-11e9-9524-ef76345ff535.png)

![image](https://user-images.githubusercontent.com/10735803/53150515-bf48bf00-35d6-11e9-9ce3-87fdd6a396ae.png)


Here is code which i using inside test.php file
`ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require __DIR__ . '/vendor/autoload.php';

use XeroPHP\Application\PrivateApplication;


$config = [
		'oauth' => [
			'callback' => 'https://lectures.owltalks.org/stripe-to-zero2/response.php',
			'consumer_key' => 'XIR3R5401KMY2DIZI6TKNKNX8RZMG1',
			'consumer_secret' => 'KZEHT9CRMOCQKDWF57XUCDAYQ5WKRI',
			'rsa_private_key' => __DIR__.'/certs/privatekey.pem',
		]
	];


$xero = new PrivateApplication($config);

print_r($xero->load('Accounting\\Organisation')->execute());`

Please help on it. I really need to connect xero platform.

**Comment by calcinai** [comment]
This doesn’t look like an issue with the XeroPHP library, and is getting a bit off-topic. 

I’d recommend reading the composer documentation and you should get a pretty good idea how it works. 

For arguments’ sake, try creating a new folder with absolutely nothing in it, and run `composer require calcinai/xero-php`

If you run the test.php from inside there it should work.
