### ISSUE TITLE
How to add the Sales Settings in the  fincancial details section for a contact through the api

### ISSUE THREAD

**Issue by jaisyabraham** [calcinai/xero-php#514]

**Comment by rodjsta** [comment]
@jaisyabraham did you work out how to do this?

**Comment by calcinai** [comment]
@rodjsta do you know if it's possible according to the Xero docs?

**Comment by rodjsta** [comment]
@calcinai I couldn’t see anything in the docs. Very strange that that field seems like the only value in that section you cannot set/get from the API. I was asking and hoping for a hidden solution. Very annoying.

**Comment by calcinai** [comment]
@rodjsta Sorry I can't help more
