### ISSUE TITLE
Email Invoice (sending twice)

### ISSUE THREAD

**Issue by jaisyabraham** [calcinai/xero-php#520]
I have called the $invoice->save(); function to generate the Invoice. After which, I have called this $invoice->sendEmail(); function. However, I am receiving two emails of the same Invoice. 

`
 $invoice->save();
 $invoice->sendEmail();
`

The $invoice->sendEmail(); function is called from SendEmailTrait.php

I've then used try to debug using the API Previewer to do a post method to send the email and I getting this (refer to screenshot). And it also sending two emails of the same Invoice.

<img width="978" alt="screen shot 2019-02-26 at 5 04 01 pm" src="https://user-images.githubusercontent.com/47842670/53390820-949ca300-39e8-11e9-8cac-d02435a2a773.png">

Can anybody please advise? Thanks.

**Comment by calcinai** [comment]
@jaisyabraham How are you triggering this script? If it's a GET request, the browser will often call it twice.  I've seen similar issues in the past.

**Comment by jaisyabraham** [comment]
@calcinai I am using ajax POST method to trigger the function in the SendEmailTrait.
Below is the code that I have used to email the invoice.

<img width="623" alt="screen shot 2019-02-27 at 10 24 23 am" src="https://user-images.githubusercontent.com/47842670/53455967-91ed8c80-3a80-11e9-81b2-e7a012930755.png">

`<?php

namespace XeroPHP\Traits;

use XeroPHP\Remote\Request;
use XeroPHP\Remote\URL;
use XeroPHP\Exception;

trait SendEmailTrait
{
    public function sendEmail()
    {
        
        $uri = sprintf('%s/%s/Email', $this::getResourceURI(), $this->getGUID());
        
        $url = new URL($this->_application, $uri);
        $request = new Request($this->_application, $url, Request::METHOD_POST);
        
        $request->send();
        
        return $this;
    }
}

`
do we need to return any response code after sending the email?

Thanks.

**Comment by jaisyabraham** [comment]
@calcinai 

Can you please tell me what else should I do to ensure that the email is not send twice. This is urgent.

Is there anything I need to do in my xero settings?

or is it something with the Api or is it a global issue?

How can I solve this issue?

Thanks.
Can anybody please advise? Thanks.

**Comment by calcinai** [comment]
@jaisyabraham Can you please put some logging in place to ensure that function is only being called once?

**Comment by jaisyabraham** [comment]
@calcinai I have tried to put the log in the sendEmail function and its only executed once but I get 2 invoice emails.

I even tried to remove all the javascript codes and just called the below code and its giving me 2 emails.

` ($xero->loadByGUID('Accounting\\Invoice', '8c5be42d-e034-4860-85f3-ae692f127ecb'))->sendEmail();` 

I also tried out the API History (https://app.xero.com/Application/History/) console, and check the requests coming in. There is only one curl request in the history but i still get 2 emails

<img width="950" alt="screen shot 2019-03-01 at 4 13 11 pm" src="https://user-images.githubusercontent.com/47842670/53617899-52b86a80-3c3d-11e9-8669-b98e45023f1a.png">

<img width="1254" alt="screen shot 2019-03-01 at 4 16 55 pm" src="https://user-images.githubusercontent.com/47842670/53618003-adea5d00-3c3d-11e9-9a85-85bb8313c464.png">

Are you getting one email or 2 emails at your side?

If you are getting only 1 email at your side I would appreciate you giving me a sample code for executing the sendEmail function so that I can move forward

Thanks in advance.

**Comment by calcinai** [comment]
I’m not getting any emails, is it possibly you’ve put your email in twice (multiple contact persons)

**Comment by danielignatius** [comment]
@calcinai I am getting two emails as well when I only added one primary person contact. If you run the a test sendEmail function over at your side are you getting two emails for one invoice and for one primary person contact? It very strange when I only run the sendEmail function once but received the same emails twice for one primary contact. Please help!

**Comment by timacdonald** [comment]
@danielignatius if you application history is showing one incoming POST request but Xero is sending 2 emails for that request, that is something Xero's end and not something this library can really account for.

Can you confirm that the API history is only showing ONE incoming request? But for each request is is sending 2 emails?

**Comment by discover59** [comment]
@calcinai sometimes sendEmail functions calls invoice email api twice and as a result I got error
```
The nonce value "c2vgu2vegao080p35" has already been used
```

I checked xero api history and it has two times of api call for same invoice.
Please let me know what the problem can be.

**Comment by calcinai** [comment]
@discover59 Can you look at your application logs locally and see if you're unintentionally calling that function twice?  This has caught people out before when they use a GET request to send the email and the browser calls it twice.

**Comment by discover59** [comment]
@calcinai No, it's triggered in cron job. And before sending email it creates invoice.
Since invoice number is unique, the whole snippect can't be called twice and so for sending email.

**Comment by discover59** [comment]
@calcinai Do we need new issue for this or are you gonna resolve it here?

**Comment by calcinai** [comment]
@discover59 it this only happening sometimes? All I can suggest is putting some logging in place to see what part of the code is getting called when it sends twice.

There's no built-in retry logic, so this is definitely on odd one.  The fact that the nonce is duplicated suggests that it's getting called twice at the same time (that nonce bug is actually fixed in #621

**Comment by discover59** [comment]
@calcinai The above issue doesn't happen anymore. I have another question.
How can I get status code of sendEmail request?
