### ISSUE TITLE
Error: Argument 1 passed to XeroPHP\Application\PrivateApplication::__construct() must be of the type array, null given, called in C:\xampp\htdocs\Project\app\Facades\XeroApi.php on line 76

### ISSUE THREAD

**Issue by kunallibra** [calcinai/xero-php#522]
Hi,

I have installed the package through the composer and has installed successfully. I then followed some tutorials and I keep getting this error **_"Argument 1 passed to XeroPHP\Application\PrivateApplication::__construct() must be of the type array, null given, called in C:\xampp\htdocs\Project\app\Facades\XeroApi.php on line 76"_**

Can you please help/ let me know what is wrong.

Thanks

**Comment by Josh-G** [comment]
What are you passing to the construct call (line 76 of your facade)? As the error suggests, it sounds like you are calling
```php
new \XeroPHP\Application\PrivateApplication(null);
```

**Comment by kunallibra** [comment]
Hi, I am new to the Xero and Laravel. I am not able to understand the code. I have downloaded and installed the package using via the composer. Can you show bit of the code please. 

Thanks

**Comment by calcinai** [comment]
@kunallibra Have a look at [README.md](https://github.com/calcinai/xero-php/blob/master/README.md), it has full instructions to get you going.

**Comment by kunallibra** [comment]
Ok, i did followed, but anyways, i am not able to understand. I created a controller Test and and a public function testXero (){   
//and i wrote this:
$xero = new \XeroPHP\Application\PrivateApplication($config);
//not to sure how what is the $config here? I assume its a public/Private key, and i have defined it at Config/service.php file. Is that right?

} 

Thanks

**Comment by calcinai** [comment]
Ok, have you looked in the 
[examples](https://github.com/calcinai/xero-php/blob/master/examples) folder?

**Comment by kunallibra** [comment]
Yes, i saw those examples now. In the config.php file, we are defining all the Keys. I have also added both the files (private and public) in the certs folder. but still there is no luck. So sorry abt bothering you so much.

Thanks

**Comment by kunallibra** [comment]
And btw, the config.php file that contains in this example, has all the Keys, right. And in my project, I am using the Keys inside  the  config/service.php file. Is that causing the issues as its not able to read it?

Thanks.

**Comment by timacdonald** [comment]
You issue is you integration with Laravel, not this package. The config.php file has no meaning to this package.

**Comment by timacdonald** [comment]
I would recommend checking out a Laravel integration to help you with the process, perhaps: https://github.com/langleyfoxall/xero-laravel

**Comment by timacdonald** [comment]
I might have jumped the gun there sorry. The config.php file is in the examples, but it looks like you are trying to use this library as a facade in Laravel, as per your first message. Perhaps try using that package I mentioned to help you get everything setup and working well with Laravel

**Comment by kunallibra** [comment]
Thnaks for that. Just one last quesiton plz. I feel that my certs folder may not in the right directory. Where exactly we create this certs folders in the project. 

Thanks

**Comment by timacdonald** [comment]
As long as they are not in any publicly accessible folder, you can put them where ever you like.

**Comment by kunallibra** [comment]
ok, cool. actually i have created a folder inside (htdocs) called Xero/certs/and both files

**Comment by timacdonald** [comment]
You *definitely* do not want to put your certs (or any configuration information) in the `htdocs` folder. That is publicly available.

**Comment by kunallibra** [comment]
ok, i tried relocating the folder and files and i am getting this error now

> Cannot access private key for signing: openssl_pkey_get_private('file://certs/privatekey.pem') returned false

**Comment by timacdonald** [comment]
Looks like you might not be providing the correct path for the file.

**Comment by kunallibra** [comment]
the actual path where the files are located is : 

> C:\xampp\htdocs\assignment_Sem2\app\certs\privatekey.pem

and the controller files is in:

> C:\xampp\htdocs\assignment_Sem2\app\Http\Controllers\Admin\Test.php

and in the Test.php, inside the public function testXero () {

//i have
  $config = [
                  'oauth' => [
                  'callback' => 'http://localhost/',
                  'consumer_key' => 'K',
                  'consumer_secret' => 'S',
                  'rsa_private_key' => **'file://certs/privatekey.pem',**
               
              ],
            ];
            $xero = new PrivateApplication($config);
            print_r($xero->load('Accounting\\Organisation')->execute());

**Comment by kunallibra** [comment]
ok, got it now.

Thanks for the time and help.

**Comment by timacdonald** [comment]
No problem - glad it is working for you

**Comment by kunallibra** [comment]
Sorry, one more error. 
Sorry about this.

the error  I am getting now is:

> Class does not exist [\XeroPHP\Models\App\Http\Controllers\Admin\Contact]

So, I have checked your folders and you have it  **xero-php/src/XeroPHP/Models/Accounting/Contact.php** , so I can copy this folder and add it in my project? Indide htdocs/assignment_Sem2/xero-php/src/XeroPHP/ and all the files and folders? 


Thanks

**Comment by timacdonald** [comment]
You need to import the class: https://secure.php.net/manual/en/language.namespaces.importing.php
