### ISSUE TITLE
How to delete an Item or Mark as Inactive

### ISSUE THREAD

**Issue by owaisjamal9978** [calcinai/xero-php#524]
Is there any way i can delete the Item also Mark as inactive like i can do it directly from the xero app. Please suggest!

**Comment by owaisjamal9978** [comment]
I am using the $item>delete() but it is not deleting the record neither making it inactive!

**Comment by timacdonald** [comment]
Hey @owaisjamal9978 pretty much everything that is possible via the API is able to be updated with this package.

Can you show me what in the Xero documentation you are trying to update? For example, if you are trying update a contact status, these are the available status;: https://developer.xero.com/documentation/api/types#ContactStatuses

**Comment by owaisjamal9978** [comment]
@timacdonald  I have created an Item from the Item POST API. I can update it but i am not able to mark it **InActive** or can **Delete** it using the API. Please suggest if you know any solution to this! Thanks!

Below is the code that i am using it....
$items->setGUID($GUID)
           ->delete(true);

**Comment by timacdonald** [comment]
What class is it an instance of? Are you getting any errors?

That code snippet doesn't give me any context, can you share more?

**Comment by owaisjamal9978** [comment]
No errors getting. I am using the below API
https://developer.xero.com/documentation/api/items

$items = new \XeroPHP\Models\Accounting\Item($xero);
$items->setGUID($GUID)
           ->delete(true);
$items->save();

**Comment by timacdonald** [comment]
Try removing that `save()` call

```php
$items = new \XeroPHP\Models\Accounting\Item($xero);
$items->setGUID($GUID)->delete(true);

// $items->save(); // don't do this
```

**Comment by owaisjamal9978** [comment]
Thanks @timacdonald . Actually i want to make it **In Active** not completely deleted from xero, it is removing the record from xero in this case!

**Comment by Josh-G** [comment]
This isn't possible over the API yet, and was requested [back in 2016](https://xero.uservoice.com/forums/5528-xero-accounting-api/suggestions/15159630-should-be-able-to-retrieve-and-set-inventory-item)

**Comment by owaisjamal9978** [comment]
OK @Josh-G  Thanks bro!.. dont know why this important feature is not available yet in the API from 2016!
