### ISSUE TITLE
Add Function to Get Invoice PDF

### ISSUE THREAD

**Issue by teddyleo** [calcinai/xero-php#529]
Add a function for getting an invoice PDF from a GUID. This would be done by setting the request header before making the call, as outlined in the Xero documentation: 
 - https://developer.xero.com/documentation/api/requests-and-responses#get-individual

**Comment by timacdonald** [comment]
This has already been implemented on the Invoice model via the `PDFTrait`.

```php
$content = (new \XeroPHP\Models\Accounting\Invoice)
    ->setGUID($guid)
    ->setApplication($xero)
    ->getPDF();
```

**Comment by calcinai** [comment]
thanks @timacdonald
