### ISSUE TITLE
How can I delete a Purchase Order line item using the Xero-PHP library?

### ISSUE THREAD

**Issue by FrankEBailey** [calcinai/xero-php#530]
I've managed to load an existing Purchase Order if its reference exists, or create it if its reference doesn't exist. When it exists, and I try to update it, the line items aren't updated but rather doubled up, so I end up with multiple lines of the same items. 

Is there a way to delete a line item from a Purchase Order? The simplese workflow for me would be to load the PO, then delete all the line items, then write the updated ones as new line items, so as to avoid the duplication.

**Comment by FrankEBailey** [comment]
To expand more on this, it seems like the documentation is either incorrect, or I'm doing something wrong. Because in the docs it says that, if I try to send line items to an existing Purchase Order, if I supply LineItemIDs the lines will be updated, otherwise the will be deleted and recreated. However this doesn't seem to work in practice, because I can't load a LineItem by its GUID (I get a Resource Not Found error) so I can only add a LineItem with

    $lineitem = new \XeroPHP\Models\Accounting\PurchaseOrder\LineItem($xero);

So there either needs to be a way to load the LineItem by its GUID for updating, or deleting a LineItem so it can be recreated, but right now I can't see a way to get this to work.

**Comment by FrankEBailey** [comment]
I discovered the RemoveAll() function, used it to delete all the LineItems in the Purchase Order, did a ->save() and then was able to re-add the changed line items to no duplication takes place any longer.

**Comment by kashifau** [comment]
Hi Frank, how did you use removeAll function, it's not seem to be working for me.

**Comment by FrankEBailey** [comment]
I used it like so:

```
$po = $xero->loadByGUID('Accounting\\PurchaseOrder', $poguid);
$po->LineItems->removeAll();
$po->save();
```

You might've been missing the `save()` call?

**Comment by kashifau** [comment]
I am using this code to remove invoice lineitems but not working for me. I am able to remove one lineitem using removeAt($index) but removeAll doesn't work for me.

**Comment by kashifau** [comment]
> I am using this code to remove invoice lineitems but not working for me. I am able to remove one lineitem using removeAt($index) but removeAll doesn't work for me.

Solved. I had to add a new lineitem before saving so previous lineitems could be removed.

**Comment by futurewebsites** [comment]
@kashifau 

> Solved. I had to add a new lineitem before saving so previous lineitems could be removed.

How do you add new line items before removing all ?  something like?

`$xeroInvoice = $this->loadByGUID('INVIOICE', $id);
 $xeroInvoice->addLineItem($this->createLineItemObject($lineItem));
 $xeroInvoice->removeAll();
 $xeroInvoice->save();
`

**Comment by nilaypatel18** [comment]
> $po->LineItems->removeAll();
> $po->save();

solution worked for me .
thanks
