### ISSUE TITLE
 run composer get the error "No version set".

### ISSUE THREAD

**Issue by hiheaven** [calcinai/xero-php#562]
I have php 7.0.4, from windows run composer get the error "No version set".
would some one help to solve this? thanks

-----------------------
composer require calcinai/xero-php

Using version ^1.8 for calcinai/xero-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package calcinai/xero-php No version set (parsed as 1.0.0) is satisfiable by calcinai/xero-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by timacdonald** [comment]
Could you paste a copy of your `composer.json` file? Might help troubleshooting

**Comment by hiheaven** [comment]
After googling for the solution, it works if it has "version" in it. Thanks

{
    "name": "calcinai/xero-php",
    "type": "library",
    "description": "A client implementation of the Xero API, with a cleaner OAuth interface and ORM-like abstraction.",
    "homepage": "https://github.com/calcinai/xero-php",
    "license": "MIT",
	"version": "1.8.6",

    "require": {
        "php": ">=5.5.0",
        "ext-curl": "*",
        "ext-openssl": "*"
    },

    "require-dev": {
        "phpunit/phpunit": "~4.7",
        "fabpot/goutte": "~2.0",
        "twig/twig": "1.16.2"
    },

    "repositories": [
    ],

    "autoload": {
        "psr-4": {
            "XeroPHP\\": "src/XeroPHP/"
        }
    }

}
