### ISSUE TITLE
Fatal error: Class 'XeroPHP\Exception' not found in \src\XeroPHP\Remote\OAuth\Exception.php on line 5

### ISSUE THREAD

**Issue by dlodhia** [calcinai/xero-php#563]
Fatal error: Class 'XeroPHP\Exception' not found in \src\XeroPHP\Remote\OAuth\Exception.php on line 5

**Comment by timacdonald** [comment]
Are you adding the package to your application with composer? or did you download it manually?

**Comment by dlodhia** [comment]
Using composer.

**Comment by timacdonald** [comment]
Can you try updating composer? Maybe if you could even share you composer.json file?

I've just booted up a fresh install on my machine and I am able to create the exception without any issues on my end. Seems like it is probable an issue with your autoloader to me.

<img width="633" alt="Screen Shot 2019-04-25 at 8 00 07 pm" src="https://user-images.githubusercontent.com/24803032/56727881-f1bc9700-6794-11e9-803b-ea65cd599caf.png">

**Comment by dlodhia** [comment]
Composer.json
---- STARTS HERE ------------
{
    "name": "calcinai/xero-php",
    "type": "library",
    "description": "A client implementation of the Xero API, with a cleaner OAuth interface and ORM-like abstraction.",
	"version": "1.8.6",
    "homepage": "https://github.com/calcinai/xero-php",
    "license": "MIT",

    "require": {
        "php": ">=5.5.0",
        "ext-curl": "*",
        "ext-openssl": "*",
		"calcinai/xero-php": "^1.8"
    },

    "require-dev": {
        "phpunit/phpunit": "~4.7",
        "fabpot/goutte": "~2.0",
        "twig/twig": "1.16.2"
    },

    "repositories": [
    ],

    "autoload": {
        "psr-4": {
            "XeroPHP\\": "src/XeroPHP/"
        }
    }

}
---- ENDS HERE ------------

**Comment by timacdonald** [comment]
That is the composer file for this package. Your project needs to have its *own* composer file.

You will need to read over to documentation and find some online tutorials if you are not familiar with composer.

Composer docs: https://getcomposer.org
Introduction to composer: https://scotch.io/tutorials/a-beginners-guide-to-composer
