### ISSUE TITLE
Fatal Error when Assigning a contact to an Invoice

### ISSUE THREAD

**Issue by FrankEBailey** [calcinai/xero-php#564]
In my code I check whether the contact exists and add it to Xero if it doesn't. However if the contact DOES exist, and I try to assign it to my new invoice, I get this error:

`Fatal error: Uncaught TypeError: Argument 1 passed to XeroPHP\Models\Accounting\Invoice::setContact() must be an instance of XeroPHP\Models\Accounting\Contact, instance of XeroPHP\Remote\Collection given`

I'm loading the contact using
`$contact = $xero->load('Accounting\Contact')->where('Name.Contains("'.$customer['Cost_Sheet_Customer_Name'].'")')->execute();`

This is a requirement in my situation because the name might not be an exact match, so I have to use 'contains'. So how can I get the contact to load as an instance of `XeroPHP\Models\Accounting\Contact` ?

**Comment by timacdonald** [comment]
Hey Frank,

I've been looping through all an accounts contacts recently myself!

Something to keep in mind is that the `execute()` method will always return a `Collection` of items, even if there is 0 or more matching contacts.

See: https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/Query.php#L230

In your situation I would probably recommend doing the following checks, to ensure that the contact exists, but also to check that there are not more than one matching contacts.

```php
$contacts = $xero->load('Accounting\Contact')
    ->where('Name.Contains("'.$customer['Cost_Sheet_Customer_Name'].'")')
    ->execute();

if ($contacts->count() === 0) {
    throw new \Exception('No remote contact found for a customer named: '.$customer['Cost_Sheet_Customer_Name']);
}

if ($contacts->count() > 1) {
    throw new \Exception('More than one remote contact was found for a customer named: '.$customer['Cost_Sheet_Customer_Name']);
}

$invoice->setContact($contacts->first());
```

**Comment by FrankEBailey** [comment]
Hi Tim,

I actually just this morning had a lightbulb moment about the difference between a collection of objects, and the objects themselves, and then it became clear that I should just check inside the collection for the count of matching objects, and if any were found, take the first result indexed at zero. You beat me to writing up the solution here, you speed demon! ;)

Thanks for laying out the solution so cleanly, I'm sure it'll help others who might be experiencing similar issues.

**Comment by timacdonald** [comment]
haha - awesome. glad you got it sorted!
