### ISSUE TITLE
Unable to fetch Home Address & date of birth in Employee

### ISSUE THREAD

**Issue by Lawrence72** [calcinai/xero-php#566]
When I run the following code

$emp =  $xero->load('PayrollAU\\Employee')->execute();

foreach($emp as $employee){
	
	$firstname = $employee->getFirstName();
	$lastname  = $employee->getLastName();
	$dob = $employee->getDateOfBirth();
	$address = $employee->getHomeAddress();
	echo $firstname;
	echo $dob;
	echo $address;
}

I can get firstname and last name but not date of birth or home address. I know that at least one of the employees has both set, I am only assume I am not fetching the data correctly, but I am not sure how I should be fetching DOB and Address.

Can you help me?

**Comment by Healyhatman** [comment]
Just in case you hadn't solved this, Home Address is a HomeAddress object and DOB is a DateTime object you can't just echo them.
