### ISSUE TITLE
create contact after getting oauth_verifier

### ISSUE THREAD

**Issue by aamirshakil** [calcinai/xero-php#569]
I have successfully integrated my application with xero public application and i got oauth_token and oauth_verifier but i am confused that how to use oauth_verifier to create contact in xero..

**Comment by AndyTurff** [comment]
Here's what I use...
`use XeroPHP\Application\PrivateApplication;

require 'C:\Apache24\htdocs\xero\vendor\autoload.php';
include ('C:\Apache24\htdocs\xero\vendor\config.php');

$xero = new PrivateApplication($config);

$contact = new \XeroPHP\Models\Accounting\Contact($xero);

$contact
    ->setFirstName($firstName)
    ->setLastName($lastName)
    ->setEmailAddress($email)
    ->addAddress(
        (new \XeroPHP\Models\Accounting\Address())
			->setAddressType('POBOX')
            ->setAddressLine1($address1)
            ->setAddressLine2($address2)
            ->setAddressLine3($address3)
            ->setAddressLine4($address4)
            ->setCity($city)
            ->setRegion($county)
            ->setPostalCode($postcode)
            ->setCountry($country)
    )
    ->addPhone(
        (new \XeroPHP\Models\Accounting\Phone())
            ->setPhoneType($typePhone1)
            ->setPhoneNumber($numberPhone1)
    )->addPhone(
        (new \XeroPHP\Models\Accounting\Phone())
            ->setPhoneType($typePhone2)
            ->setPhoneNumber($numberPhone2)
    )->addPhone(
        (new \XeroPHP\Models\Accounting\Phone())
            ->setPhoneType($typePhone3)
            ->setPhoneNumber($numberPhone3)
    )
	->setName($company);

$contact->save($contact);
`

**Comment by aamirshakil** [comment]
@AndyTurff dear your example provides the solution for private application. i just wanted to know how to make a config file for public application to create or fetch any contact..
