### ISSUE TITLE
I want to get all invoices for particular status, How can i do that?

### ISSUE THREAD

**Issue by jaytasol** [calcinai/xero-php#57]
Hi, 

I have setup this package and used loadByGUID to fetch invoice from Invoice ID. But i want to fetch invoices which are set to AUTHORISED. 

How i can set where condition for this, i think in this case i can not use function loadByGUID.  can you suggest me regarding this. 

Thanks

**Comment by coop182** [comment]
You should be able to do this:

```php
$xero->load('Accounting\\Invoice')->where('Status', 'AUTHORISED')->execute();
```

**Comment by jaytasol** [comment]
Hi Matt Cooper, 

Thanks, it's working and got all invoices. 
Also can you suggest best way to set cron script in Laravel, i want to set this invoice import functionality in cron?

Thanks for you help.

**Comment by jaytasol** [comment]
Hi

Is there any way i can change header to Jason to get data from Xero in json format? I have tried to change CONTENT_TYPE_XML to CONTENT_TYPE_JSON but it did not worked. 

Thanks

**Comment by gerrywastaken** [comment]
@jaytasol It would great if you made a commit to the Readme for this project with info you just recieved about using where().

Regarding your second question. Why do you need Xero to return JSON. The xero-php objects can be converted into json like so:

```php
json_encode($invoice)
```

I have looked deeply into how xero-php transforms Xero responses into objects, but my suspicion is that it relies on them being XML and so changing them to JSON would likely break things.

**Comment by calcinai** [comment]
Unless something has changed at Xero's end (likely) they should work just fine as JSON, the objects are built based on the content-type header they'd received. 

Another note - there are class constants for all statuses etc, so you can avoid having strings like 'AUTHORIZED'. Check out the invoice model.

**Comment by jaytasol** [comment]
Hi Michael Calcinai,

Yes i have tried to change content type from xml to json by putting CONTENT_TYPE_JSON instead of
CONTENT_TYPE_XML in request.php file but then it is showing this error. 

DateTime::__construct(): Failed to parse time string (1436406730633+1200) at position 10 (6): Unexpected character

I am not sure if i am doing some thing wrong. 

And by default result returns long array with xml as well as array so i want just array of invoices and contacts without xml and other info. 

Thanks

**Comment by gerrywastaken** [comment]
It appears the Date comes back in the format "2015-04-25T00:00:00" when JSON but "1429876800000+1200" when XML.

**Comment by jaytasol** [comment]
I think it should give date like  "2015-04-25T00:00:00"  after i change headers in request file but it still giving date like "1429876800000+1200". So i think i have missed some thing to change header. 

Also with xml i got long result but it is very huge result, same invoice comes 25 times also same xml comes 25 times in array. 

Thanks

**Comment by gerrywastaken** [comment]
It's a .NET date format.

There was a bug raised for it back in 2012, so I'm sure Xero will fix it any day now: https://community.xero.com/developer/discussion/46161#answer78981

**Comment by jaytasol** [comment]
OK Thanks :)

Can you suggest any thing regarding results i get?

**Comment by gerrywastaken** [comment]
I'm not sure what is happening there regarding the duplicate invoices. It's hard for me to check if this same thing is happening for me as I have many invoices in the database that I'm using. Are you using the latest version of the xero-php?

**Comment by jaytasol** [comment]
I am using calcinai/xero-php in laravel 5. 

Here i am attaching image of my result, i needed to taken screen shot as there is huge array of result. I have separate each array with horizontal line. I think there is some problem so it is giving repeated result. 
![data](https://cloud.githubusercontent.com/assets/13366421/8844400/41f3a7ce-3132-11e5-9a5c-92f53be0332b.png)

**Comment by jaytasol** [comment]
Hi, 

I got result with short array, from query.php when i directly print this in execute function. 
$request->getResponse()->getElements();

Then there is a foreach loop in which process results and giving multiple copy of result. 

Thanks

**Comment by gerrywastaken** [comment]
@jaytasol Wow, that's a heck of an image, nearly crashes the page rendering. It might be a good idea to change that image to a link to https://cloud.githubusercontent.com/assets/13366421/8844400/41f3a7ce-3132-11e5-9a5c-92f53be0332b.png instead of displaying it inline.

I'm a bit lost here regarding your issue. Any ideas @calcinai ?

**Comment by jaytasol** [comment]
Sorry for long image, i will keep in mind to share link instead of image. 

Also i got some thing which i have shared in my earlier post. I think thing is working well when there is single thing to fetch like single invoice or single contact. But when there is multiple data then it  repeatedly store whole result multiple times in array instead of storing single item. 

Thanks

**Comment by coop182** [comment]
@jaytasol I usually do this when I get the results back from Xero to make it easier to work with.

This is what you want to do I think...

```php
$invoices_raw = $xero->load('Accounting\\Invoice')->where('Status', 'AUTHORISED')->execute();
$invoices = array();
foreach ($invoices_raw as $i) {
    $invoice = $i->toStringArray();
    $invoices[] = $invoice;
}

print_r($invoices);
```

**Comment by jaytasol** [comment]
Hi Matt Cooper,
Thanks for your reply, 

It become much easier to get data with this. But if i remove below code from execute function of Query.php then it directly giving array of invoices/contacts which i can directly use.

        $elements = array();
        foreach($request->getResponse()->getElements() as $element) {
            $built_element = new $from_class($this->app);
            $built_element->fromStringArray($element);
            $elements[] = $built_element;
        }

I am not sure about importance of this as i am working with xero first time. Result processed from this might be usable for other process but i am not sure about that.

Also when i fetch contacts from xero then it missing some data for ex. Website. so can we specify in query that what data we need from xero?

Thanks

**Comment by jaytasol** [comment]
Hi,

Can you let me know how can i handle exception, response file throwing exception in parse function. and it calls from send function of request. So i can not find way to handle this exception before before i call  $xero->load('Accounting\\Invoice')->where('Status', 'AUTHORISED')->execute();

I want to display message to user and redirect them to login page when this type of error occur. 

Thanks

**Comment by gerrywastaken** [comment]
@jaytasol I'm assuming this was closed because you are asking questions unrelated to the topic instead of opening a new topic for your new questions.

This issue tracker is not really for offering free support either. I think it would be better to open tickets describing what documentation is missing.

However if you are wanting support, generally, as with most open source projects, the best thing to do is figure it out yourself and only ask when you really get stuck. The source code is very readable and it's made better by people diving in and fixing issues. A tool such as Psysh (http://psysh.org/) or an interactive debugger can really make this quite simple and you will probably get answers a lot faster this way.

**Comment by jaytasol** [comment]
Hi Gerry, 

I already get answer of this and also about exception these was given in example file so i have posted it here. So though this will be helpful for others. 
By the way thanks for your reply. 

Thanks,
Jay
