### ISSUE TITLE
how to pass access token in config array?

### ISSUE THREAD

**Issue by aamirshakil** [calcinai/xero-php#570]
Is there any example of how to pass access token and secret for public application construct function..
$config = [   
 'oauth' => [
 		'token'=>$oauth_data['xero_oauth_access_token'],
		'token_secret'=>$oauth_data['xero_oauth_access_token_secret']
		 ]
];
$xero = new PublicApplication($config);

$response = $xero->load('Accounting\\Contact')->execute();

**Comment by timacdonald** [comment]
Check out this example: https://github.com/calcinai/xero-php/blob/master/examples/public.php#L11-L22
