### ISSUE TITLE
xero api php sdk 4 decimal places

### ISSUE THREAD

**Issue by oldfumbler** [calcinai/xero-php#575]
Hi,
Using Xero in the past we have created invoices with a unit price of 6.667. This is due to the customer having 3 items @ 6.667 ea which provides an invoice total of $22.00 inc gst. (cash transaction, no silver)

We have created these (and other "odd" value) invoices manually via the Xero UI and using the csv file import process for batch creation of invoices, without issue.

To make our operation more efficient we have had a stand alone app created to manage many parts of our operation. One part of the app is to send the data to create the invoice to Xero, via the Xero API to create invoices (replaces the csv batch file process)

Whilst our app sends item values to 3 decimal places, the Xero API only accepts 2. This causes our invoices to be incorrect and worse when the customer payment is applied for the 3 decimal place value, xero rejects the payment.

Xero responded with:

Yes, by default Xero API uses 2 decimal points. However, by using a param ?unitdp=4, the API can support up to 4 decimal points.

Our programmer is also aware of:

https://stackoverflow.com/questions/27200459/rounding-in-xero-api-integration

however cannot pass 4 decimal places to Xero.

Can anyone please advise how if/how to set the API so it will receive and apply item values to 3 decimal places, same as Xero UI and CSV file import.

Our programmer is using PHP SDK

Thanks in advance.

**Comment by Josh-G** [comment]
You can specify the `unitdp` like so:

```php
$config = [
    'xero' => [
        'unitdp' => 3,
    ],
];
$app = new \XeroPHP\Application\PrivateApplication($config);
```

**Comment by glaing** [comment]
Hi,

I need to set up a higher accuracy of unitdp for a project I'm working on and I can't work out how to set this properly

I'm sure I'm missing something here, but where would the config parameters (that @Josh-G used) go when using the following way to create an instance?

`$xero = new \XeroPHP\Application($accessToken, $tenantId);
`

 Thanks,
 George

**Comment by Josh-G** [comment]
In v2, you can set the `unitdp` option like so:
```php
$xero = new \XeroPHP\Application($accessToken, $tenantId);
$xero->setConfigOption('xero', 'unitdp', 3);
```

**Comment by glaing** [comment]
Excellent - thank you @Josh-G!
