### ISSUE TITLE
Sending invoice emails returning 411

### ISSUE THREAD

**Issue by johnshepherd** [calcinai/xero-php#580]
Hi!

We have been creating invoices and sending out invoices for months without issue, however I noticed that the emails have recently stopped sending. The requests don't throw any exceptions and just fail silently. They also do not show in the API history on Xero itself. If I `print_r` the `$request->send()` in `SendEmailTrait` I see that the HTTP response code is 411 and the body returned is:

```
<HTML><HEAD>
<TITLE>Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
Your browser sent a request that this server could not understand.<P>
Reference #7.143f655f.1559057169.56e4a0ac
</BODY>
</HTML>
```

Doing some Googling about Xero and that response code - there seems to be some mentions of not sending the content length causing issues.

Modifying [SendEmailTrait:28](https://github.com/calcinai/xero-php/blob/87df9ec43658ab9ff6914f7ec60d9a2afef2c1db/src/XeroPHP/Traits/SendEmailTrait.php#L26-L28) to add `$request->setBody('');` allows the request to complete and emails to send successfully.

Happy to PR this - however, there might be a better resolution for the whole library rather than adding a blank body in that particular request?

**Comment by tobz-nz** [comment]
Confirmed this fixes timeout issues sending email for me as well.

**Comment by calcinai** [comment]
@tobz-nz If you're happy to submit a PR, I'll review it and release a patch version.

**Comment by tobz-nz** [comment]
@calcinai Will do right now 👍

**Comment by tobz-nz** [comment]
... Well that was easy :)
