### ISSUE TITLE
Invalid email address when pushing an invoice

### ISSUE THREAD

**Issue by kashifau** [calcinai/xero-php#583]
When I push an invoice to xero and if the email address contains the letters "fi" then I get an error that it's an invalid email address. If I go back to database and rewrite the email address then the error goes away. How can I get rid of this error?

**Comment by calcinai** [comment]
Have you looked at the API history to get more information on the payload and error? Are you sure there are no special characters?

**Comment by kashifau** [comment]
I also thought there are some special characters but examining the emails doesn't show any special symbols, just for some reason its considering corresponding letters (e.g. pi, fi, etc) inside an email address as special characters. Deleting the email and rewriting by hand in the database fixes the issue.
