### ISSUE TITLE
Tracking category option not creating  

### ISSUE THREAD

**Issue by codeclouds-team** [calcinai/xero-php#584]
Hi, I am trying to create a tracking category and few options for that category. But I am failed to attach tracking options to the category.

**Steps:** 

* creating a tracking category bt `XeroPHP\Models\Accounting\TrackingCategory` model.
* Saving Xero id for that category.
* Creating an instance of `XeroPHP\Models\Accounting\TrackingCategory\TrackingOption` 
* At the of attaching options, adding saved Xero category id, and push options to the instance by `addOption` method.
* Saving them.

**Result:** 
* Options are not saving to Xero.

**Comment by gkavaliu** [comment]
I did some testing and I believe this is because

TrackingOption is not an endpoint in Xero it is actually Option

PUT https://api.xero.com/api.xro/2.0/TrackingCategories/{TrackingCategoryID}/Options

**Comment by nelwa** [comment]
Any update on this?  I'm getting the same problem...

**Comment by calcinai** [comment]
Duplicate of #256
