### ISSUE TITLE
Timesheet:  Unable to load a timesheet using its GUID. All properties are returned as null.

### ISSUE THREAD

**Issue by anujtaya** [calcinai/xero-php#585]
I am unable to retrieve a Timesheet using its GUID. I wanted to add more timesheet lines to the existing timesheet. Unfortunately, I have followed every step out there on the internet. Please fix this issue.

**Comment by lawipac** [comment]
I have similar issues using latest code, the only way to workaround is is not to use 
```
$xero->loadByGUID('PayrollAU\\Timesheet', "136018e9-7665-4481-83d6-51aa3a301ddf");

it get null value for every single  field as @anujtaya  mentioned.
```
but  instead using:
```
$existing = $xero->load('PayrollAU\\Timesheet')
        ->where('TimesheetID ==GUID("136018e9-7665-4481-83d6-51aa3a301ddf")')
        ->execute();
$existing[0] returns correct record details.
```
