### ISSUE TITLE
getAccountsPayableTaxType() returns NULL even when set

### ISSUE THREAD

**Issue by JeRoNZ** [calcinai/xero-php#588]
getAccountsPayableTaxType() etc are returning null when perhaps they should be returning the values shown in Xero

```php
$xero = new PrivateApplication($config);
$foo = $xero->load(Contact::class)->where('EmailAddress','text@example.com')->execute();
foreach($foo as $contact) {
	/* @var $contact XeroPHP\Models\Accounting\Contact */
	var_dump($contact->getAccountsPayableTaxType());
	var_dump($contact->getAccountsReceivableTaxType());
	var_dump($contact->getPurchasesDefaultAccountCode());
	var_dump($contact->getSalesDefaultAccountCode());
        var_dump($contact->getAccountNumber());
        var_dump($contact->getName());
}
```
getName, get AccountNumber return the expected values, but the others return NULL.

![Capture](https://user-images.githubusercontent.com/3641329/60562936-b7333400-9dad-11e9-8692-7b96420507dc.PNG)

Am I missing something here?

**Comment by timacdonald** [comment]
Give the query a spin in the API previewer and confirm the data is being returned from Xero correctly.

https://app.xero.com/Preview/contacts

Select the "Contacts" endpoint and in the "where" field put
```
EmailAddress="text@example.com"
```

**Comment by JeRoNZ** [comment]
It would appear it doesn't even bother with the fields, let alone the values. This seems rather different to what I'm lead to believe should be available when I look at https://developer.xero.com/documentation/api/contacts. It seems to skip SkypeUserName, BankAccountDetails, TaxNumber, AccountsReceivableTaxType and AccountsPayableTaxType  all of which should appear between EmailAddress and Addresses.

Guess that explains it.
