### ISSUE TITLE
Public app can't connect

### ISSUE THREAD

**Issue by anushkanz** [calcinai/xero-php#606]
`<?php
require 'vendor/autoload.php';
use XeroPHP\Remote\URL;
use XeroPHP\Remote\Request;
use XeroPHP\Application\PublicApplication;
// Start a session for the oauth session storage
session_start();
//These are the minimum settings - for more options, refer to examples/config.php
 $key = "-----BEGIN RSA PRIVATE KEY-----
Xn2BvJb298JEM5AE
-----END RSA PRIVATE KEY-----";
$config = [
    'oauth' => [
        'callback' => 'http://xxxxxxx.co.nz/',
        'consumer_key' => 'xxxxxxxS3ONHAO9SO5JVMGI',
        'consumer_secret' => 'xxxxxxxEF3YXYFBPMPCRFM',
        'rsa_private_key' => $key,
        'signature_location'    => XeroPHP\Remote\OAuth\Client::SIGN_LOCATION_QUERY,
    ],
    'curl' => [
        CURLOPT_CAINFO => __DIR__.'/certs/ca-bundle.crt',
    ],
];
$xero = new PublicApplication($config);

//if no session or if it is expired
if (null !== $oauth_session = getOAuthSession()) {
    $url = new URL($xero, URL::OAUTH_REQUEST_TOKEN);
    $request = new Request($xero, $url);
    //Here's where you'll see if your keys are valid.
    //You can catch a BadRequestException.
    try {
        $request->send();
    } catch (Exception $e) {

        print_r($e);
        if ($request->getResponse()) {
            print_r($request->getResponse()->getOAuthResponse());
        }

    }
    $oauth_response = $request->getResponse()->getOAuthResponse();
    setOAuthSession(
        $oauth_response['oauth_token'],
        $oauth_response['oauth_token_secret']
        
    );
    printf(
        '<a href="%s">Click here to Authorize</a>',
        $xero->getAuthorizeURL($oauth_response['oauth_token'])
    );
    exit;
}
// echo '<pre>';
// print_r($oauth_session = getOAuthSession());
// echo '</pre>';

$xero->getOAuthClient()
     ->setToken($oauth_session['token'])
     ->setTokenSecret($oauth_session['token_secret']);

if (isset($_REQUEST['oauth_verifier'])) {
    $xero->getOAuthClient()->setVerifier($_REQUEST['oauth_verifier']);
    $url = new URL($xero, URL::OAUTH_ACCESS_TOKEN);
    $request = new Request($xero, $url);
    $request->send();

    $oauth_response = $request->getResponse()->getOAuthResponse();
    setOAuthSession(
        $oauth_response['oauth_token'],
        $oauth_response['oauth_token_secret'],
        $oauth_response['oauth_expires_in']
    );
    //drop the qs
    $uri_parts = explode('?', $_SERVER['REQUEST_URI']);
    //Just for demo purposes
    header(
        sprintf(
            'Location: http%s://%s%s',
            (isset($_SERVER['HTTPS']) ? 's' : ''),
            $_SERVER['HTTP_HOST'],
            $uri_parts[0]
        )
    );
    exit;
}

//Otherwise, you're in.
//print_r($xero->load('Accounting\\Organisation')->execute());

   try {
         $orgs = $xero->load('Accounting\\Organisation')->execute();
     } catch (\Exception $e) {
         echo $e->getMessage();
     }
   $query =   $xero->load('Accounting\\Organisation');
   function execute($query)
   {
       try {
           return $query->execute();
       } catch (\XeroPHP\Remote\Exception\UnauthorizedException $e) {
           // Refresh token logic here - but only if a partner application
           // ...
           // Try executing again.
           // Need to think about how to get the new tokens in here though.
           return $query->execute();
       } catch (\Exception $e) {
           echo $e->getMessage();
           // Log in, notifying user here.
       }
   }
//The following two functions are just for a demo
//you should use a more robust mechanism of storing tokens than this!
function setOAuthSession($token, $secret, $expires = null)
{
    // expires sends back an int
    if ($expires !== null) {
        $expires = time() + (int) $expires;
    }
    $_SESSION['oauth'] = [
        'token' => $token,
        'token_secret' => $secret,
        'expires' => $expires,
    ];
}
function getOAuthSession()
{
    //If it doesn't exist or is expired, return null
    if (! isset($_SESSION['oauth'])
        || ($_SESSION['oauth']['expires'] !== null
        && $_SESSION['oauth']['expires'] <= time())
    ) {
        return;
    }
    return $_SESSION['oauth'];
}`
After click authonticate then its redirect to index.php contain this code.
 ```
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require 'vendor/autoload.php';
//require 'config.php';
use XeroPHP\Remote\URL;
use XeroPHP\Remote\Request;
use XeroPHP\Application\PublicApplication;
//use XeroPHP\Models\Accounting\Organisation;
use XeroPHP\Models\Accounting;
use XeroPHP\Models\Accounting\Contact;

  if(isset($_GET['oauth_token'])){
 $key = "-----BEGIN RSA PRIVATE KEY-----
Xn2BvJb298JEM5AE
-----END RSA PRIVATE KEY-----";
      $config = [
          'oauth' => [
               'callback' => 'http://xxxxxxx.co.nz/',
               'consumer_key' => 'xxxxxxxS3ONHAO9SO5JVMGI',
               'consumer_secret' => 'xxxxxxxEF3YXYFBPMPCRFM',
              'token'=>$_GET["oauth_token"],
              'token_secret' => $_GET["oauth_token"],
              'rsa_private_key' => $key,
              'signature_location'    => \XeroPHP\Remote\OAuth\Client::SIGN_LOCATION_QUERY,
            ],
              'curl' => [
              CURLOPT_CAINFO => __DIR__.'/certs/ca-bundle.crt',
            ],
      ];

        echo "xero";
        echo "<pre>";
        $xero = new \XeroPHP\Application\PublicApplication($config);
        $orgs = $xero->load('Accounting\\Organisation')->execute();
         try {
             $orgs = $xero->load('Accounting\\Organisation')->execute();
          } catch (\Exception $e) {
              echo $e->getMessage();
          }

      echo "</pre>";
  }
 ?>
```
![Screen Shot 2019-07-12 at 9 30 29 AM](https://user-images.githubusercontent.com/8416639/61086772-d86be280-a487-11e9-9710-5e0fffade18b.png)
Please help me to sort this matter
Thanks

**Comment by anushkanz** [comment]
Why you are closing this without giving the answer? .....

**Comment by calcinai** [comment]
@anushkanz can you please explain exactly what isn't working.  Have you tried using the sample php files without editing them?

**Comment by anushkanz** [comment]
@calcinai, You really think I am idiot use your code without anything. I am just trying to do what instruction you provide. 
Last picture I was uploaded, its show what is the error I got.

**Comment by timacdonald** [comment]
He doesn’t think your an idiot - but your post is incomprehensible and doesn’t describe the problem or what you have done to try and make it work so far.

Just a heads up that the error message in the image you put in the original post contains the error. Your token is wrong so Xero is not Authorizing the request.

**Comment by anushkanz** [comment]
Hey never mind, I changed my development language PHP to Node Js, Not required for connecting with this way, Not working properly and not given proper information.
Node js I manage to connect without any issue.
Thanks for all

**Comment by timacdonald** [comment]
Glad you got it sorted.

**Comment by calcinai** [comment]
@anushkanz That's fantastic news. Glad to hear you got something to work in the end.
