### ISSUE TITLE
Create Item and Update Item using xero-php

### ISSUE THREAD

**Issue by lvsan** [calcinai/xero-php#607]
I have a issues when the item already created and save by batch using ->saveAll,
there is no ItemID is return and therefore, I not able to do the updateItem for some information.

Or there is another way to do the update for particular item?
However, if i use the ->save(), then there is ItemID is return.

	public function actionUpdateItem()
	{
		$str = '';
		$xero = $this->xeroPHP();	
		$new = $this->createItem($xero,true);
		
		foreach ($new as $key => $val)
		{			
			foreach ($new[$key] as $updData) {
				$guid = $updData['ItemID'];
				$txtName=$updData['Name'];
				
				print_r($guid);
				//[Items:Update]
				$item = $xero->loadByGUID('Accounting\\Item', $guid);
				$item->setName($txtName . $this->getRandNum())
					 ->setDescription($updData['ItemDescp']);
				$item->save();
				
				$str = $str . "Update item: " . $item["Name"] . " -- " . $item["Description"] . "<br>";
			}
		}		
		return $str;
	}
	
Hope someone can advise me on this. Thanks.

**Comment by timacdonald** [comment]
Are you saying that when you call `->save()` it sets the `ItemID` on the model, but when you call `->saveAll()` it *does not* set the `ItemID` on the model?

**Comment by lvsan** [comment]
Hi timacdonald,

yes, I have this issues previously, anywhere I have check this is cause by my code and this is settle already. the xero-php is working fine. now I try another function for update contacts for the address, but seem not working now.
