### ISSUE TITLE
POST the Contacts with addAddress not working

### ISSUE THREAD

**Issue by lvsan** [calcinai/xero-php#609]
Hi,
I try to post the contacts to xero to update the address information, but this is not success.
I integrate the xero-php with Yii2 frameworks.
Below is my sample code:

			foreach ($rows as $rowData) {
				$contacts = $this->xeroContacts();
				$addresses =  $this->xeroContactAddress();
				$phoneses = $this->xeroContactPhones();
				$isSupplier=false;
				$isCustomer=false;
				
				//add address
				if($rowData['CompanyType']=='SUPPLIER') 
					$isSupplier=true;

				if($rowData['CompanyType']=='CUSTOMER')
					$isCustomer=true;
				
				//->setIsCustomer($isCustomer)				
				$contacts->setName($rowData['CompanyName'])
					->setEmailAddress($rowData['e_Mail'])
					->setContactStatus($rowData['CompanyStatus'])
					->setDefaultCurrency($rowData['CurrCode'])
					->addAddress($addresses->setAddressType($addresses::ADDRESS_TYPE_STREET)
											->setAddressLine1($rowData['Address_Line_1'])
											->setAddressLine2($rowData['Address_Line_2'])
											->setAddressLine3($rowData['Address_Line_3'])
											->setPostalCode($rowData['PostalCode'])
											->setCountry($rowData['CountryCode'])						
					)
					->addAddress($addresses->setAddressType($addresses::ADDRESS_TYPE_POBOX)
											->setAddressLine1($rowData['MailAddr_Line_1'])
											->setAddressLine2($rowData['MailAddr_Line_2'])
											->setAddressLine3($rowData['MailAddr_Line_3'])
											->setPostalCode($rowData['MailPostalCode'])
											->setCountry($rowData['CountryCode'])					
					)
					->addPhone($phoneses->setPhoneType($phoneses::PHONE_TYPE_DEFAULT)
										 ->setPhoneNumber($rowData['Tel_No'])
					)					
					->setIsSupplier($isSupplier);

				$sendContact[]=$contacts;
			}
		}
		try {
			$xero->saveAll($sendContact);
		} catch (NotFoundException $exception) {
			// handle not found error
		} catch (RateLimitExceededException $exception) {
			// handle rate limit error
		}

I have also try to set teh contacts is either customer or supplier, this only accept one of the value to be pass to use setIsSupplier or setIsCustomer, else the error will shows below if I use both.

				$contacts->setName($rowData['CompanyName'])
					->setEmailAddress($rowData['e_Mail'])
					->setContactStatus($rowData['CompanyStatus'])
					->setDefaultCurrency($rowData['CurrCode'])
					->setIsCustomer($isCustomer)
					->setIsSupplier($isSupplier);

exception 'yii\base\ErrorException' with message 'Call to a member function setIsSupplier() on null'

can anyone assists me on this?

**Comment by timacdonald** [comment]
`setIsCustomer` and `setIsSupplier` are both deprecated and they do not return `$this` - they return `null`, so that is why you are getting the error. Take a look at the methods in the source code to see more.

**Comment by lvsan** [comment]
hi timacdonald, thanks for your prompt response and advise.
