### ISSUE TITLE
How i can handle exception from my laravel model file?

### ISSUE THREAD

**Issue by jaytasol** [calcinai/xero-php#61]
Hi, 

I am using this example in my model file vendor/calcinai/xero-php/examples/public.php and i am using database instead of session to store tokens and token_secret. 

And i am using bellow code to import invoices to store in database also same time i am importing contacts info for particular invoices. 

 $invoices=$this->xero->load('Accounting\\Invoice')->where('Status=="AUTHORISED" OR Status=="PAID"')->modifiedAfter(new \DateTime($this->timesince))->execute();

Now there are many invoices so some time token become expired during process and at that time i want to through exception and want to store error in my log file. 

But when i try that, it can not be handled. so then i used directly send function like below code but then also it can not be halalled as it terminate script in parse function of response .php file.  

     $url = new URL($xero, \XeroPHP\Models\Accounting\Invoice::getResourceURI());
     $request = new Request($xero, $url, Request::METHOD_GET);
     $request->setParameter('where', $where);
      try {
            $request->send();
        } catch (Exception $e){
            echo($e->getCode());
            print_r($request->getResponse()->getOAuthResponse());
        }

So i want to know how can i handle exception when i got some error like token expired etc... 
Is there any way that i can handle it with this? 

$invoices=$this->xero->load('Accounting\\Invoice')->where('Status=="AUTHORISED" OR Status=="PAID"')->modifiedAfter(new \DateTime($this->timesince))->execute();

Thanks,
Jay

**Comment by calcinai** [comment]
I'm still not sure what the issue is - the script should't ever just terminate.  Have you tried wrapping your load around a try/catch block?

```php
try {
    $invoices=$this->xero->load('Accounting\Invoice')->where('Status=="AUTHORISED" OR Status=="PAID"')->modifiedAfter(new \DateTime($this->timesince))->execute();
} catch (UnauthorizedException $e) {
    ///Do something
}
```

or similar?

**Comment by jaytasol** [comment]
Thanks for your reply.

Yes i have used both Exception and UnauthorizedException in catch as you shown but then also it is showing "UnauthorizedException in Response.php line 85: Token BHG5J9QLQGYH2THCLGKKPYAI436Y3P does not match an expected ACCESS token".

**Comment by gerrywastaken** [comment]
@jaytasol I think it would be a good idea for you to delete all six of your off topic posts in #58

**Comment by jaytasol** [comment]
Hi i have removed that, Thanks. I thought it is about throw exception in model file so which is similar to my problem, i posted those in that. Bot now i have removed those.

**Comment by gerrywastaken** [comment]
@jaytasol Thank you :)

**Comment by gerrywastaken** [comment]
You should try using https://github.com/php-vcr/php-vcr to inspect the requests and responses between you and Xero. It might alert you to some issue in your code where the same token is being sent twice instead of once.

**Comment by jaytasol** [comment]
No Actually, I know there is problem in token i am sending and i am trying to handle that so when i run cron or any user sync data and error occur in b/w so i can handle that in so i can show message to user and in case of cron i can log that error in my file. 

I got solution why it could not catch exception  in my model, I added "use XeroPHP\Exception;" and it starts working, this was not set in example file public.php (https://github.com/calcinai/xero-php/blob/master/examples/public.php) so i think this need to set there as it also contain try, catch code.  

Thanks,
Jay

**Comment by mhlavac** [comment]
@jaytasol it catches all Exceptions in the try,catch block. If you want to catch XeroPHP\Exception only then you have to use whole namespace, or add use. Keep in mind that if you need to catch PHP Exception and you add use XeroPHP\Exception, then you will have to catch PHP Exception with root namespace `\Exception`

**Comment by jaytasol** [comment]
OK, Thanks for your reply :)

**Comment by calcinai** [comment]
Sorry about that - in any examples I'm assuming the XeroPHP ns.
