### ISSUE TITLE
Argument 1 passed to XeroPHP\Models\Accounting\Invoice::addLineItem() 

### ISSUE THREAD

**Issue by lvsan** [calcinai/xero-php#611]
Hi, 
I have a issues when addLineItem with array values which I wish to pass the multiple lineitem for the invoices.

Argument 1 passed to XeroPHP\Models\Accounting\Invoice::addLineItem() must be an instance of XeroPHP\Models\Accounting\Invoice\LineItem, array given, 

Can anyone assist me how can I add multiple line for the invoices create?

Thanks.

**Comment by calcinai** [comment]
@lvsan You need to iterate your array of LineItems and call `addLineItem()` for each one.

**Comment by lvsan** [comment]
@calcinai,

below is my code for the lineitems. I have populate in into the array.
	public function getLineItemForInvoice($id)
	{
		$connection = Yii::$app->db;
		$lineitems=[];
		
		$sql="...…..";
               $rows = $connection->mysqli_queryAll($sql);
		if($rows !=false )
		{
			foreach ($rows as $rowData) {				
				$lineitem = $this->xeroInvoiceItemLine();
				$lineitem->setDescription($rowData['ItemDescp'])
					->setQuantity($rowData['ItemQty'])
					->setUnitAmount($rowData['ItemUnitPrice'])
					->setTaxType('OUTPUT')
					->setTaxAmount($rowData['ItemTaxTotal'])
					->setLineAmount($rowData['ItemTotal'])
					->setAccountCode($rowData['AccountCode']);
					
				$lineitems[] = $lineitem;
			}			
		}
		return $lineitems;
	}
		
then I will call from another function which already return as below :

		$lineitems = $this->getLineItemForInvoice($data['SalesID'],true);		
		$invoice = $this->xeroInvoices();
		$invoiceLineItem="";
			
		$invoice->setInvoiceNumber($data['SalesNo'])
			->setReference('')
			->setDate(new \DateTime($data['SalesDate']))
			->setDueDate(new \DateTime($data['SalesDate']))
			->setCurrencyCode($currcode)
			->setStatus(\XeroPHP\Models\Accounting\INVOICE::INVOICE_STATUS_AUTHORISED)
			->setBrandingThemeID($brandingthemes)
			->setSubTotal($data['SalesSubTtl'])
			->setTotalTax($data['SalesTaxTtl'])
			->setTotal($data['SalesBalTtl'])
			->setType(\XeroPHP\Models\Accounting\INVOICE::INVOICE_TYPE_ACCREC)
			->addLineItem($lineitems)    ---> here is the error
			->setContact($contact)
			->setLineAmountType($taxType); 

Can advise which part I have miss out?

Thanks.

**Comment by pjw345** [comment]
Ivan,

That's the point - you cannot add an array of lineitems to the invoice, you have to add each lineitem individually.

So where you have $lineitems[] = $lineitem; replace it with $invoice->addLineItem($lineitem);

Does that make sense?

**Comment by lvsan** [comment]
@pjw345 , thanks for your advise. I have successfully figure out how to code it.
Thanks a lot.
