### ISSUE TITLE
getContacts include Archive

### ISSUE THREAD

**Issue by lvsan** [calcinai/xero-php#613]
Hi,

How can I load the parameter to getcontactid from contacts include the archive?
Below is my code to get the contactid include where condition.

$contact = $xero->load('Accounting\\Contact')->where('Name=="' . $name . '"')->execute();

hope someone can advise me.

Thanks.

**Comment by Josh-G** [comment]
You can call `includeArchived` on the query to get archived contacts as well.
Example:
```
$contact = $xero
    ->load('Accounting\Contact')
    ->where('Name=="' . $name . '"')
    ->includeArchived()
    ->execute();
```

**Comment by lvsan** [comment]
@Josh-G , thanks for your helping. I have able to get the contact id from xero now.
Thanks a lot and it is really helpful.
