### ISSUE TITLE
Error when use loadbyGUID to found item

### ISSUE THREAD

**Issue by lvsan** [calcinai/xero-php#617]
Hi 

I have a issues on get the item from xero using below code:

				$item = $xero->loadByGUID('Accounting\\Item', $guid);  ==> here is the error found 
				try {
					//$item->delete();	
				} catch (NotFoundException $exception) {   // never come to here

					// handle not found error 
					print_r($exception);
					print_r($item->toStringArray());
				} catch (RateLimitExceededException $exception) {
					// handle rate limit error
				}		

Error found as below :

[error][XeroPHP\Remote\Exception\NotFoundException] exception 'XeroPHP\Remote\Exception\NotFoundException' with message 'Resource Not Found' 

Hope someone can advise me on how to solve this.

Thanks .

**Comment by timacdonald** [comment]
This means that whatever resource you are trying to load by guid, i.e. Accouting\Item, does not exist in Xero. It is a standard 404 response.

**Comment by lvsan** [comment]
Hi timacdonald,

I know that it is because the id that I pass cannot be found in the xero. but the problem I facing is I not able to get the response from the catch, and the error I found is from yii2 app.log under runtime folder. 

In this way, I cannot pass the correct message to users that the records is not found.

$item = $xero->loadByGUID('Accounting\\Item', $guid);  
the command above should be run under the try {   ……..  } then only that will return back the response to 
catch (NotFoundException $exception) {
return "No records Found from xero";
}

Thanks.
Regards,
Low Voon San

**Comment by timacdonald** [comment]
From your original snippet, the `loadByGUID` method is not being called in the try / catch block. You need to put the call in the try block to be able to catch the exception.

```diff
- $item = $xero->loadByGUID('Accounting\\Item', $guid);  ==> here is the error found 
try {
+     $item = $xero->loadByGUID('Accounting\\Item', $guid);  ==> here is the error found 
	//$item->delete();	
} catch (NotFoundException $exception) {   // never come to here

	// handle not found error 
	print_r($exception);
	print_r($item->toStringArray());
} catch (RateLimitExceededException $exception) {
	// handle rate limit error
}	
```

**Comment by lvsan** [comment]
Hi timacdonald,

I have try it  but the result still the same which I still not able to get the response.
Below is the amended code :

try {
	$guid = $rowData['ItemSKU'];
	$item = $xero->loadByGUID('Accounting\\Item', $guid);
} catch (NotFoundException $exception) {
					// handle not found error
					print_r("y7yuyiuyiuyiuyiu");
} catch (RateLimitExceededException $exception) {
// handle rate limit error
}			

[error][XeroPHP\Remote\Exception\NotFoundException] exception 'XeroPHP\Remote\Exception\NotFoundException' with message 'Resource Not Found' in D:\wamp64\www\master\vendor\calcinai\xero-php\src\XeroPHP\Remote\Response.php:96
Stack trace:
#0 D:\wamp64\www\master\vendor\calcinai\xero-php\src\XeroPHP\Remote\Request.php(127): XeroPHP\Remote\Response->parse()
#1 D:\wamp64\www\master\vendor\calcinai\xero-php\src\XeroPHP\Application.php(202): XeroPHP\Remote\Request->send()
#2 D:\wamp64\www\......\controllers\XeroController.php(700): XeroPHP\Application->loadByGUID('Accounting\\Item', '1615091600078')

Thanks.

**Comment by timacdonald** [comment]
could be that you are not importing the exception class. 

```diff
try {
    $guid = $rowData['ItemSKU'];
    $item = $xero->loadByGUID('Accounting\Item', $guid);
- } catch (NotFoundException $exception) {
+ } catch (\XeroPHP\Remote\Exception\NotFoundException $exception) {
    // handle not found error
    print_r("y7yuyiuyiuyiuyiu");
- } catch (RateLimitExceededException $exception) {
+ } catch (\XeroPHP\Remote\Exception\RateLimitExceededException $exception) {
    // handle rate limit error
}
```

**Comment by calcinai** [comment]
Didn’t you write [a blog post](https://timacdonald.me/php-be-all-like-that-nonexistent-class-be-cool/) about this, Tim?

**Comment by lvsan** [comment]
Hi timacdonald,

thanks you for your advise. Yes now I able get the correct response now.
The issues is causing by the exception class which I never import.

after amend it as below :
try {
					$guid = $rowData['ItemSKU'];
					$item = $xero->loadByGUID('Accounting\\Item', $guid);
				} catch (\XeroPHP\Remote\Exception\NotFoundException $exception) {
					// handle not found error
					print_r("y7yuyiuyiuyiuyiu");
				} catch (\XeroPHP\Remote\Exception\RateLimitExceededException $exception) {
					// handle rate limit error
				}		

it is working fine now.
Thanks alot for the help.

Regards,
Low Voon San

**Comment by timacdonald** [comment]
Oh yea haha, for this exact reason lol.

For future readers: https://timacdonald.me/php-be-all-like-that-nonexistent-class-be-cool/

**Comment by lvsan** [comment]
Hi timacdonald,

ok noted with thanks.

**Comment by timacdonald** [comment]
@lvsan glad u got it sorted.
