### ISSUE TITLE
UpdatedDateUTC missing from Item model

### ISSUE THREAD

**Issue by gerrywastaken** [calcinai/xero-php#62]
https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Models/Accounting/Item.php#L107

Any idea, off the top of your head, why the generator would leave this out?

**Comment by calcinai** [comment]
Working on it. Some complications due to #54

**Comment by calcinai** [comment]
There is actually no ```UpdatedDateUTC``` in the Item model, it only applies to the Sales and Purchases for items.

**Comment by gerrywastaken** [comment]
@calcinai ??? But.... I was able to get one by adding the field to getProperties in the item model

Also the previewer shows the updated date:
![screen shot 2015-07-30 at 11 57 04 am](https://cloud.githubusercontent.com/assets/71481/8975528/7fab3192-36b2-11e5-8c4d-152ee8b03ac0.png)

However I hadn't noticed #54. It seems somebody has always beaten me too it. Sorry, I'll search next time.

**Comment by gerrywastaken** [comment]
It's in the XML version too btw:
![screen shot 2015-07-30 at 12 05 07 pm](https://cloud.githubusercontent.com/assets/71481/8975579/4c4d66d4-36b3-11e5-8374-40a94a4c2104.png)

**Comment by calcinai** [comment]
Haha, well you're using an undocumented feature!  What should we do here?

**Comment by gerrywastaken** [comment]
Damn... beg Xero to document it? :) Not sure, but doesn't every resource have an UpdatedDateUTC field?

**Comment by gerrywastaken** [comment]
I thought it was needed for If-Modified-Since

**Comment by calcinai** [comment]
Well if it's on every model, we can just add it to all models.. Does it say somewhere in the docs that it will be there?

**Comment by gerrywastaken** [comment]
The closest I can find is the following:

From: http://developer.xero.com/documentation/advanced-docs/dates-and-timestamps-explained/

> The following guide refers to invoices but is also relevant for other documents like credit notes, receipts, journals and bank transactions (spend and receive money)

...

> The UpdatedDateUTC element
> 
> The UpdatedDateUTC element is automatically populated by Xero (you cannot set it), and is the timestamp of the last edit to the invoice.

I just checked though and it's not returned on a lot of models :( Damn Xero, damn. I'll try giving them a poke, I might get lucky.

**Comment by gerrywastaken** [comment]
@calcinai I've sent them an email. Hopefully it won't take a year to have this one row added to a HTML table.

**Comment by calcinai** [comment]
I wouldn't get your hopes up!

**Comment by gerrywastaken** [comment]
@calcinai wow that was fast: http://developer.xero.com/documentation/api/items/

Ok so from now on I recommend sending all simple documentation update requests to api@xero.com

**Comment by gerrywastaken** [comment]
For reference I'll add the email here:

```
Hi Gerry

Thanks for letting us know - the field is actually documented though it was incorrectly buried within the 'Elements for Purchases and Sales' section so I have moved it further up.

I have also added it to the example XML: https://developer.xero.com/documentation/api/items/#GET

Let us know if the 'calcinai/xero-php' project is still struggling to discover the field and we can take another look.

Regards

Ronan

______________________________________________________________

Hi

http://developer.xero.com/documentation/api/items/

Your documentation for the Items endpoint is missing a row for UpdatedDateUTC. This row is in listed in other documents such as Invoice.

<UpdatedDateUTC>Last modified date UTC format

Adding this is important as at least one amazing project use your documentation to figure out what the Xero schema is:

https://github.com/calcinai/xero-php

This seems like it would be a very simple addition with a rather large gain.

Kind Regards

Gerard (Gerry) Caulfield
```

**Comment by coop182** [comment]
Nice work @gerrywastaken... I need to get the same field added to the ManualJournal documentation as well.

**Comment by gerrywastaken** [comment]
Ahh cool, I'll ask the same guy

**Comment by gerrywastaken** [comment]
@coop182 Sent an email.

**Comment by coop182** [comment]
Awesome thanks! Was just about to copy your email haha.

**Comment by gerrywastaken** [comment]
@coop182 They haven't replied to me, so it might not be a bad idea to send that copy and paste email.
