### ISSUE TITLE
Invoices "createdByMyApp" filter functionality

### ISSUE THREAD

**Issue by kleisto** [calcinai/xero-php#620]
I'm currently implementing an Invoices integration using this library. I can see in the Invoices API documentation that Xero supports a "createdByMyApp" optional parameter for calls to Invoices/GET, however I can't work out how to implement this parameter.  If I try to use it as a 'where' parameter, I get "No property or field 'createdByMyApp' exists in type 'Invoice'". eg. 
```
$results = $this->xeroPHP->load(Invoice::class)
     ->where('createdByMyApp', true)
     ->page($i)
     ->execute();
```
Likewise with other explicit parameters forInvoices/GET: IDs, InvoiceNumbers, ContactIDs, Statuses.

Have these special parameters been implemented? If so, how do we use them, and if not, will they be?

**Comment by calcinai** [comment]
Are you able to show how you'd do this in the API usually, or what this translates to in the Xero docs?

**Comment by kleisto** [comment]
From https://developer.xero.com/documentation/api/invoices:

Optional parameters for GET Invoices


**IDs, InvoiceNumbers, ContactIDs, Statuses**
 Filter by a comma-separated list of InvoicesIDs, InvoiceNumbers, ContactIDs or Statuses. For faster response times we recommend using these explicit parameters instead of passing OR conditions into the Where filter. e.g. GET https://.../Invoices?Statuses=DRAFT,SUBMITTED

**createdByMyApp**
When set to true you'll only retrieve Invoices created by your app e.g. GET https://..//Invoices?createdByMyApp=true

Is this what you mean? Thanks, I appreciate your response.

**Comment by calcinai** [comment]
Ah yes! You should be fine to use the `setParameter()` method instead of where.

**Comment by kleisto** [comment]
Great! Missed that functionality, thanks so much for clearing that up. I can confirm this works for anyone else looking.

eg.

```
 $results = $this->xeroPHP->load(Invoice::class)
                ->setParameter('Statuses', Invoice::INVOICE_STATUS_DRAFT)
                ->setParameter('createdByMyApp', 'true')
                ->execute();
```
