### ISSUE TITLE
$EarningsRate->save() does nothing 

### ISSUE THREAD

**Issue by Healyhatman** [calcinai/xero-php#622]
I'm trying to save a new EarningsRate to Xero and nothing's happening. If I set all the required values and save(), the response is null and as far as I can tell the request is never actually sent. There are no errors or exception, and API History is blank. 

`$rate = new EarningsRate($xero);
            $rate->setAmount(10.00)
                ->setIsExemptFromSuper("true")
                ->setIsExemptFromTax("false")
                ->setRateType(EarningsRate::RATETYPE_FIXEDAMOUNT)
                ->setName("NAME!")
                ->setEarningsType(EarningsRate::EARNINGSTYPE_ORDINARYTIMEEARNINGS)
                ->setAccountCode("477");
            $response = $rate->save();`

**Comment by Healyhatman** [comment]
Update: I figured out that you can't just save an EarningsRate, you need to get the PayItems and add an earnings rate to that, and then save the PayItems.

I managed to get a 202 response from Xero telling it to saveAll($payItemsArray), but the earnings rate is nowhere to be found. Additionally if I use $payItemsArray[0]->save() I get 'Bad Request'. Response XML:

`<?xml version="1.0"?>
<Response xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <ErrorNumber>0</ErrorNumber>
  <Type>Error</Type>
  <Message>Bad request</Message>
</Response>`

**Comment by cproetti** [comment]
Hey man

I'm probably having the same issue. I just cant figure this one out.

Here's what I'm doing, maybe you can shed some light on what might be happening.

`//START A NEW INSTANCE OF THE XERO CLASS
$xero = new \XeroPHP\Application\PrivateApplication($config);`

`//GET THE CURRENT PAYITEM
$xero_pay_item = $xero->load(\XeroPHP\Models\PayrollAU\PayItem::class)->execute()->first();`

`//CREATE THE NEW EARNINGS RATE
$earnings_rate = new \XeroPHP\Models\PayrollAU\PayItem\EarningsRate($xero);
$earnings_rate->setName('Testearnings')
    ->setDisplayName('Testearnings')
    ->setAccountCode('477')
    ->setTypeOfUnit('Hours')
    ->setIsExemptFromTax('false')
    ->setIsExemptFromSuper('false')
    ->setEarningsType('ORDINARYTIMEEARNINGS')
    ->setRateType('RATEPERUNIT')
    ->setRatePerUnit('45')
    ->setMultiplier('1')
    ->setAccrueLeave('false');`

`//ADD THE NEW EARNINGS RATE TO PAY ITEM
  $xero_pay_item->addEarningsRate($earnings_rate);`

`//TRY SAVE: doesn't seem to do anything
$xero_pay_item->save();`

`//TRY SAVE ALL: also doesn't seem to do anything
$xero->saveAll(array($xero_pay_item));`

There are no exceptions being thrown and yet there's no results. By "results" Im meaning that no new items is being created in Xero.

I've run ->validate on earnings rates and it returns TRUE so I assume thats all okay.

**Comment by calcinai** [comment]
@cproetti WHat's the bad request error you're getting?

**Comment by cproetti** [comment]
@calcinai The entirety of the exception message is just "Bad Request", code 400.

**Comment by calcinai** [comment]
Have you looked in the Xero console?  Sometimes you feet some more detail in there

**Comment by cproetti** [comment]
@calcinai Thanks for the tip. Yep, theres more context here, the error says "DisplayName is not a valid element in EarningsRate".

Its strange because I originally omitted ->setDisplayName() from my code however when I did ->validate() it said that display name is required.

I've tried again to omit ->setDisplayName() and getting the exception message "$DisplayName is mandatory and is either missing or empty."

**Comment by cproetti** [comment]
@calcinai The reason I originally omit ->setDisplayName() is because I read through the code on EarningsRate.php before starting and noticed that it was marked as deprecated.

I'll try download the latest files and update, maybe you guys have pushed an update to this matter since I started.

**Comment by cproetti** [comment]
@calcinai Updating to all the latest files didn't help.

When I include ->setDisplayName('test') I get a Bad Request error on Xero end saying "DisplayName is not a valid element in EarningsRate"

And when I omit ->setDisplayName() I get an exception on XeroPHP end saying "$DisplayName is mandatory and is either missing or empty."

**Comment by cproetti** [comment]
@calcinai The patch you did this morning has worked in terms of no longer being presented with that Bad Request "DisplayName is not a valid element in EarningsRate" error however this API request is still not working.

Using the same code example described yesterday, I'm still getting a Bad Request error. The error in the Xero console is exactly as follows:
`<Response xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><ErrorNumber>0</ErrorNumber><Type>Error</Type><Message>Bad request</Message></Response>`

Do you have any idea where I'm going wrong or why this is not working?
[test.txt](https://github.com/calcinai/xero-php/files/4057748/test.txt)
[response_message.txt](https://github.com/calcinai/xero-php/files/4057763/response_message.txt)
[request_message.txt](https://github.com/calcinai/xero-php/files/4057764/request_message.txt)

**Comment by rodjsta** [comment]
@calcinai  Where can I view the console?

**Comment by cproetti** [comment]
@rodjsta Go to developer.xero.com **>>** My Apps **>>** Select your app **>>** History.
From the History page you should be able to see all of the requests your app is making to the Xero API. Only failed requests can be clicked on to view the details.

**Comment by rodjsta** [comment]
@cproetti, is that the same for OAuth 2.0 apps? I don't see any History option. Only Webhooks and Marketplace.

**Comment by cproetti** [comment]
@rodjsta  I'm not sure if its the same with OAuth 2.0 app.  This isn't really the place for this kind of support, you should consult the Xero Documentation.
