### ISSUE TITLE
OAuth 2

### ISSUE THREAD

**Issue by alexbogo** [calcinai/xero-php#625]
Hi,

Is this package works with OAuth 2? 
https://developer.xero.com/documentation/oauth2/overview

Thanks
Alex

**Comment by calcinai** [comment]
@alexbogo not that this point but it is the plan!

**Comment by alexbogo** [comment]
Hi,

Thank you for letting me know. I would be, maybe, interested in helping you out if my current projects allow me some time... to convert it into v2. I am in NZ as well..
I am using OAuth 2 at the moment but just basic calls with Guzzel as a client. The most annoying thing is Xero token life - 12 min. 

Cheers
Alex

**Comment by davidwindell** [comment]
@calcinai could you share an update on the plans for OAuth 2? Xero are now saying that no OAuth 1 apps will be able to be created from next month so it would be good to know now if we need to make plans to move to an Oauth2 client or help with efforts in this repo.

**Comment by calcinai** [comment]
@davidwindell That happened quickly! I don't think the new Xero library is very complete just yet  so I might need to do something quickly here and swap out he underlying transport  for compatibility.. Once upon a time, I did have Guzzle working in there.

**Comment by davidwindell** [comment]
Yeah, very quick! Here's the official quote:

> From 1 December 2019 developers will no longer be able to create OAuth 1.0a apps on the Xero  platform

**Comment by SaxPlayer** [comment]
I'll be chuffed if oAuth2 support is introduced. I'm having mixed results creating a Xero app with oAuth2 at the moment using League\OAuth2. It's working in places but not in others. It's probably my fault rather than Xero's new API but I'd be far happier using a well maintained library like this one if oAuth2 support was introduced. 

That's probably not a helpful comment... I'm just agreeing that there is a need for this. ;)

**Comment by alexbogo** [comment]
This may help...
https://github.com/XeroAPI/xero-php-oauth2

**Comment by gurubobnz** [comment]
As of 2nd December Xero stopped allowing creation of private applications using the old method so we're forced to use OAuth2 now. I'm in the process of looking at the OAuth2 authorization process, but in the end does this library still work with OAuth2? I realised we no longer have a public/private key pair with OAuth2 (unless I misunderstand).

**Comment by calcinai** [comment]
@gurubobnz this is top of my list. I have found the WIP using guzzle, so will hopefully push a branch in the next couple of days for you to test.

**Comment by gurubobnz** [comment]
Excellent - I will be ready to test as soon as you are. Thanks.

**Comment by gurubobnz** [comment]
Hey by the way ... I just got this back from Xero support regarding not being able to create OAuth 1.0 apps:

Hi Bob

Our team have now released a revised URL in order to continue creating Private Apps:

https://developer.xero.com/myapps?privateAppCreation=true

The special url will be active for the next 90 days, after this time you would be expected to be creating an OAuth 2.0 alternative. 
 
Kind regards
 
Welli

**Comment by davidwindell** [comment]
Happy to test too!

**Comment by melorbany** [comment]
Thanks @gurubobnz

**Comment by muppsy007** [comment]
Hi @calcinai is there any update to this at all? I have a bit of time this week to help testing/PRs if needed

**Comment by calcinai** [comment]
@muppsy007 Not far off.  I got a little carried away...

**Comment by DivineOmega** [comment]
@calcinai Any updates regarding this? I'm willing to help out if needed.

**Comment by rochow** [comment]
@calcinai Similarly I can help with some dev or $; unfortunately the library goes from amazing to useless without being able to connect to Xero!

**Comment by rodjsta** [comment]
Also hoping for an update here.

**Comment by calcinai** [comment]
Working on it today!

**Comment by rodjsta** [comment]
> Working on it today!

Awesome! Thanks Michael.

**Comment by calcinai** [comment]
Update: WIP on feature/oauth-2, but still a way to go!  I'll keep updating here as I go.

**Comment by calcinai** [comment]
It's worth noting that this is going to be an interim patch. I've noticed several things that don't fit cleanly but for dependant BC will continue to implement.

After this is up and running, I'll focus energy back on a major release.  Since Xero have now adopted my OpenAPI spec, this should make it a whole lot easier.  Unfortunately their new (generated) SDK is not very user-friendly, so I think there is still a place for this.

**Comment by gurubobnz** [comment]
Hi Michael, thanks for your awesome work - I'm keen to test, can you give me/us a quick high level rundown of how to get the config up and running for this? I'm working through it myself right now but if you have some copy/pasta you can send that would be great.

I expecting that I can still do something like this:

```
$xero = new \XeroPHP\Application\Application($xeroConfig);
```

But not sure on what is new/expected in `$xeroConfig`. Currently I'm getting an error that `base_url` is required so I'm having a hunt looking for that. Thanks.

**Comment by calcinai** [comment]
@gurubobnz It's not working just yet sorry!  But in answer to your question, there is now no differentiation between application types, so `Application` is no longer abstract.

`$xero = new \XeroPHP\Application($xeroConfig);`

Will put some more time in this evening.

**Comment by gurubobnz** [comment]
Oh yeah oops typo there in that ... I noticed the Public/Private applications had done. Standing by then, let me know if you need anything.

**Comment by PeteAtkins** [comment]
Also keen to test as soon as you have a working version.  Thanks for the hard work in advance.

**Comment by calcinai** [comment]
Update- I have this working locally 🎉 

Got some work to do today but should be able to clean it up and release for testing over the weekend.

**Comment by rodjsta** [comment]
Excellent work Michael. Thank you very much. Looking forward to using it.

**Comment by richard-j-c** [comment]
Any progress on this? Very grateful for your efforts.

**Comment by edwardinchains** [comment]
Fair play - can't wait to work with this!

**Comment by matthewknill** [comment]
Hi, thanks so much for you work on this! Just wondering when it'll be available?

**Comment by calcinai** [comment]
It's getting there!  Sorry it's taken me so long to get this done.

**Comment by calcinai** [comment]
So I've just committed a few changes for anyone keen to test 90% of the update - check out https://github.com/calcinai/xero-php/blob/feature/oauth-2/examples/demo.php as it contains the new [OAuth2 Provider](https://github.com/calcinai/oauth2-xero) for Xero and has the flow that you'll need to build into your app.

The constructor for the (now) `Application` then takes a token and tenant that you retrieve from there.  The thought crossed my mind to let you paste transport in (also making DI easier), but not sure if that complicates things.

Thoughts? (please!)

**Comment by tobz-nz** [comment]
Cool - I'll hopefully give it a crack tomorrow.

Looks good so far. Nice work, thanks 👍 

Can the oauth2 provider be used with Laravel Socialite by any chance? I can't quite remember how it works, but pretty sure League clients can be used with little or no config... maybe?

**Comment by mradcliffe** [comment]
Nice work so far! 🙌

I came up with a similar [XeroProvider](https://github.com/mradcliffe/xeroclient/blob/master/src/XeroProvider.php) for [xeroclient](mradcliffe/xeroclient) if you want to compare or want ideas for helper methods. In my use cases/library, I pretty much always want offline_access to be default.

**Comment by calcinai** [comment]
@tobz-nz Did you (or anyone) get a chance to test this out?

**Comment by matthewknill** [comment]
I unfortunately don't know a great deal about OAuth 2. However, from what I gather so far, it seems to be working. I had to setup a DNS entry and enable https on the server (since Xero does not allow 
and IP address used for the redirect URL).

What's weird though is that sometimes I'll run it and it'll echo out 'Invalid state' and then I'll try it again and it will work.

Thanks for all your work on this!

**Comment by AndyTurff** [comment]
Similar to a Matthew except I know nothing about OAuth 2. Using the
demo.php the authentication worked fine but when it returned I get an error
(X's added by me 🤓)....

Calcinai\OAuth2\Client\XeroResourceOwner Object ( [xero_userid] =>
28a7c9c1-e5ff-4fbc-a3f3-XXXXXX [preferred_username] => XXX@XXX [email] =>
XXX@XXX.com [given_name] => XXX [family_name] => XXX )

Array ( [0] => Calcinai\OAuth2\Client\XeroTenant Object ( [id] =>
7ee05bcb-434f-4ced-8128-XXXXXXX [tenantId] =>
6e489ba3-87c9-4003-86cd-XXXXXX [tenantType] => ORGANISATION
[createdDateUtc] => DateTime Object ( [date] => 2020-01-23 06:32:17.444387
[timezone_type] => 3 [timezone] => Europe/London ) [updatedDateUtc] => ) )

*Fatal error*: Uncaught Error: Cannot instantiate abstract class
XeroPHP\Application in C:\Apache24\htdocs\x2\vendor\callback.php:65 Stack
trace: #0 {main} thrown in *C:\Apache24\htdocs\x2\vendor\callback.php* on
line *65*

$application = new \XeroPHP\Application([
    'accessToken' => $token->getToken(),
    'tenantId' => $tenants[0]->tenantId
]);

**Comment by AndyTurff** [comment]
I also occasionally get  the  'Invalid state' message

**Comment by calcinai** [comment]
I've updated this again and it seems to be working for me.  See `demo.php` for how it is now.

I'm not 100% happy with how it's put together, but I've done it for backward compatibility as much as possible, as I'd imagine there are many applications where people will just want to implement oauth2 and then forget about it.

Once we know this is working, I can FINALLY get back to the new version with the up-to-date models and things "how they should be" 🎉

**Comment by calcinai** [comment]
@AndyTurff the `invalid_state` message occurs if you refresh the example; it means that the code has already been used.

**Comment by matthewknill** [comment]
Thanks for all your hard work!

Just wondering when this will be merged into the master branch?

**Comment by rodrigomanara** [comment]
please keep up on the loop. thank you

**Comment by calcinai** [comment]
@rodrigomanara check out `demo.php` - it shows the flow that's required to migrate.  All of your app code should remain the same, it's just the authorisation flow that you'll need to add.

@matthewknill Happy to merge it to master after I've had some positive feedback.

@everyone I think this requires a 2.0 release, even though anything left running 1.x will be broken as of December due to Xero shutting down the API.

**Comment by calcinai** [comment]
I've updated the readme in that branch to explain things a bit more.

**Comment by PeteAtkins** [comment]
@calcinai I'll be testing later today/tomorrow so will let you know how I get on.

**Comment by tobz-nz** [comment]
So I've just about finished implementing this - working well.
I've had no issues with the Oauth2.0 part of it.

**Comment by PeteAtkins** [comment]
@calcinai 
I've tested with a replica of demo.php and the first call & authentication flow works well and I get data for the $org retrieved correctly.
However the token it receives back does not seem to have refresh token value set.  There I am unable to then use this to gain a new access token when the first one expires as per 'Refreshing a token' in the readme.  I've attached a screenshot of the dump output of $token after the call where you can see the refreshToken value is null.

![AccessToken](https://user-images.githubusercontent.com/445656/73380793-8d4add00-42bc-11ea-994c-b7f0a1471568.PNG)

**Comment by calcinai** [comment]
@PeteAtkins did you include offline_access in your scopes? I guess that’s quite important to mention!

**Comment by PeteAtkins** [comment]
@calcinai, I had not!  I've now added that to the scope and the $token includes a refreshToken value.  I will test the refresh procedure later tonight or first thing tomorrow morning and report back.
Thanks for the quick response!

**Comment by tobz-nz** [comment]
The `openid ` scope also includes a refresh token - fyi.

**Comment by PeteAtkins** [comment]
@calcinai Tested the refresh procedure, works perfectly.  Expired some tokens manually and all seems to work as expected.
I've also tested a few simple contact creation and retrieval scenarios, all seems to work perfectly.  I will be doing some more testing tomorrow in terms of full invoice life cycles so if I run into any issues I'll let you know.
Thank you & excellent work, very appreciated!

**Comment by Yendall** [comment]
Everything working as expected for me! I'm going to be testing various endpoints and will report back if there are any issues, but so far so good.

**Comment by tobz-nz** [comment]
I've been having some issues with tokens dropping scopes or something.
After a while I start getting 403's.

Token is still active, refershing works... Not sure if this is a you thing, a me thing or a Xero thing..

It might be  a Xero thing as I get the same problem when making a request in Paw (or postman or whatever)
Token refreshes fine, but permissions are dropped.


Oh... WTF
GET https://api.xero.com/connections

now returns no results. Why would the connection drop off?

Maybe its due to using `openid` instead of `offline_access`? Will change it and report back.

**Comment by tobz-nz** [comment]
Ah.. possible due to my Demo Company just expiring. 
FFS what a terrible Dev experience Xero is.

**Comment by calcinai** [comment]
@tobz-nz Xero do specifically say that

> To get a refresh token, you *must* request the offline_access scope. A refresh token allows you to refresh your access token and maintain an offline connection.

Just because the `openid` scope gives you one, I wouldn't count on it.

**Comment by tobz-nz** [comment]
The token is there and it works. Just seems to stuff something up. ... maybe.
I've upadted my scopes and will do more testing.

**Comment by matthewknill** [comment]
Okay the authorization process seems to be fine connecting it to Xero via my user. I am able to generate draft invoices in Xero successfully (with line items etc...), however, when trying to add an attachment to the invoice via the following:
```php
$invoice->addAttachment(Accounting\Attachment::createFromLocalFile($this->invoice_path), true);
$invoice->save();
```
it results in the following error:
```
Client error: `POST https://api.xero.com//api.xro/2.0/Invoices/***********/Attachments/***********.pdf?IncludeOnline=true` resulted in a `401 Unauthorized` response:
{"title":"Unauthorized","status":401,"detail":"AuthorizationUnsuccessful","instance":"*********** (truncated...)
```
I am able to generate add attachments to the invoice via the Xero web UI with my user, so I don't think it's a permissions.

Thanks again for all your work on this...

Regards,
Matt

**Comment by calcinai** [comment]
@matthewknill just confirming you're adding the `accounting.attachments` scope to your authorisation?

**Comment by matthewknill** [comment]
Whoops, I'm just a noob sorry, thanks for that...

**Comment by rodjsta** [comment]
I have the connection and refresh process working too now.
@calcinai is there a way to disconnect the app/authorisation once connected?

**Comment by PeteAtkins** [comment]
@rodjsta I went into the tenant organisation within xero, then settings, connected apps and disconnected the app when I needed to add additional scopes.  
But its a good question, I can't see anything on xero about doing this programatically?

**Comment by tobz-nz** [comment]
@rodjsta To disconnect an app via the API send a `DELETE https://api.xero.com/connections/{tenant_id}` request.

For new permissions you can just repeat the oAuth flow with your new scopes and the new token will.. actually I think all tokens will be upgraded with the new permissions.

**Comment by calcinai** [comment]
@tobz-nz @rodjsta I've built this into the provider with a `->disocnnect()` method.

**Comment by calcinai** [comment]
Thanks to everyone who's done some testing.  Last thing to do is write some tests then I'll release it!

**Comment by richard-j-c** [comment]
Working well for me too. Thanks!
Can we get a `public function setTransport()` in the `Application`? Being able to modify client options (or reinstantiate the client) after app instantiation would be helpful.

**Comment by calcinai** [comment]
@richard-j-c great point, I have been thinking about this.  I was aiming for the path of least resistance for the bulk of users who just want to swap this out for the previous version.  Ideally, you'd actually pass in the Guzzle instance when the app is created, rather than the tenant and auth token.  DI would also make testing more straightforward.

Where's a happy middle ground? Would adding a ->getTransport() be enough? With that, you could add/remove headers and config on the existing instance.

**Comment by richard-j-c** [comment]
@calcinai I'm content with the `__construct()` as it is (DI could be included in v2). But either way works well.

Did you mean `setTransport()` rather than `getTransport()`? `getTransport()`, which you already have, gives me the guzzle client, but I see no way of then updating a guzzle client's config (modifying headers is want I'm after!), thus wanting to `setTransport()`

**Comment by calcinai** [comment]
@richard-j-c You're right! I thought there was a way to change the default headers on the instance, but it appears this is not the case.  Happy to add a setTransport, but the it will lost the default authorisation headers.  Would it be better to pass a custom header in the Application constructor (for now)?

**Comment by richard-j-c** [comment]
@calcinai For my particular use and app flow, setTransport is what I'm after; of course will have to add in those default headers myself :)

**Comment by calcinai** [comment]
@richard-j-c just before I add that method, would a middleware suffice?

**Comment by richard-j-c** [comment]
@calcinai I couldnt say. My usage is probably pretty idiosyncratic. I handle refreshing the token externally, and need to pass the refreshed token back to the `Application` (my apps - there are a few - integrate with a number of accounting APIs in addition to Xero, and handling the refresh external to the given libraries proved best for a consistent interface where tokens were maintained in a DB). Of course I could just reinstantiate `Application`, but I figured others would have the need for mutating the Client once instantiated.

**Comment by calcinai** [comment]
That was going to be my next suggestion.  I'll add the method!

Out of curiosity, could[ something like this](https://github.com/guzzle/guzzle/issues/1740) work for you?  If you had access to add a handler?

**Comment by richard-j-c** [comment]
@calcinai It could work, but it'd be a helluva lot more work for me (and you) than `setTransport()` :)
Thanks so much!

**Comment by matthewknill** [comment]
This seems to be all working for me including refresh tokens.
Thanks again @calcinai!!

**Comment by AndyTurff** [comment]
Hi Matthew,
You mentioned in one of the earlier messages that you sorted out the
localhost issue for the callback URL. Would you mind sharing how you did
that? I have it working on the server but when accessing from a client
localhost obviously doesn't work. Cheers in advance.
Andy

**Comment by gl3nda85** [comment]
Hi!,
Is the application context going to be updated for webhooks?

**Comment by hashnz** [comment]
hey @calcinai thanks for your work on this, I'm using it in a dev branch atm and looks good :+1: 
one thing I noticed was type hints on the provider, I sent a PR over there https://github.com/calcinai/oauth2-xero/pull/2

**Comment by tkav** [comment]
Thanks @calcinai, working for me also.

Not sure if this helps anyone but I stored the token to my database using this:
`$toDatabase = base64_encode(serialize($token));  // Save to database`
`$fromDatabase = unserialize(base64_decode($token)); //Getting Saved Format`

After retrieving it, I used `getRefreshToken()` before loading objects.

**Comment by calcinai** [comment]
☝️ should I do it?

**Comment by leereichardt** [comment]
> ☝️ should I do it?

Yes, please!

**Comment by tobz-nz** [comment]
> ☝️ should I do it?

👍 I'm ready to push live so... Yeah.

**Comment by calcinai** [comment]
Done.

**Comment by rodjsta** [comment]
> Done.

I've updated to use the master branch and everything is still working. Great stuff @calcinai. Thank you for your work on this.

**Comment by lionslair** [comment]
Great work. Thank you.

**Comment by tobz-nz** [comment]
@calcinai Great work mate - thanks.

**Comment by muppsy007** [comment]
@calcinai Not sure if this has any impact on your recent changes or for the flow anyone is using here. But I thought I would post some recent changes to the Xero API as advised just today on the Developer Forum:

> Hi everyone,
> 
> We've released a new tool that makes it easy to get up and running with OAuth 2.0 apps directly from the command line. XOAuth will step through through the OAuth flow, pipe your tokens back to the terminal and save them to your local keychain. No web dev required.
> 
> And just to re-cap another couple of changes we've made based on your feedback:
> - There is now a 30min grace period for failed token refreshes. That allows you to add resiliency to your offline connection by retrying the call if you don't receive your new token.
> - The refresh token lifetime has now been increased to 60 days (from 30 days), meaning monthly jobs will be able to maintain an offline connection (without a seperate scheduled refresh).
> 
> Cheers,
> Adam

**Comment by maheshemvigo** [comment]
@calcinai , I created refresh token and i try to get contact data from xero . I got data for 3 or 5 minute , after i got empty array . I tried in local system. Please help me .How i get data using with new access token created by refresh token??
