### ISSUE TITLE
Confused by Report Models

### ISSUE THREAD

**Issue by onlinelaser** [calcinai/xero-php#629]
Sorry for asking a howto in the issues, but perhaps this can morph into a documentation PR!

I'm retrieving a BankStatement Report like this:
```
        $result = $this->xero
            ->load('Accounting\\Report\\BankStatement')
            ->setParameter('bankAccountID',env('XERO_TRANSACTION_ACCOUNT'))
            ->execute();
```
Where I pass in the account id from the .env
This all works great.

However I can see that there is also a BankStatement model in `XeroPHP\Models\Accounting\Report\BankStatement` - what I can't find is any examples of how to make use of this model to aid in loading and parsing the report. 

I thought perhaps the intent was that you could retrieve and parse the report using that model rather than the xero object?

If not what is the intended use for the report models in general (and the BankStatement one) in particular?

Thanks!

**Comment by onlinelaser** [comment]
So I've just seen that `$result[0]` contains the populated instance of the model, that makes sense - is that the intended use?

**Comment by timacdonald** [comment]
That is right. It will return an array of results. If you are only after one result you could swap `execute` for the `first` method.
