### ISSUE TITLE
Deleting Contact Persons?

### ISSUE THREAD

**Issue by FLamparski** [calcinai/xero-php#63]
Hi,

I can't seem to find a way to delete contact persons - obviously there is a way since you _can_ do it in the UI, but then I can't seem to find a way to do this in in the XeroPHP (or even the Xero docs - you can update a contact but what happens to contact persons?). Is there one?

**Comment by calcinai** [comment]
No idea! You probably have to do something silly like saving empty ones to override them. Maybe ask Xero? Ha ha

**Comment by coop182** [comment]
I think you can edit the contact setting ContactStatus to ARCHIVED

**Comment by calcinai** [comment]
@coop182 is that the contact itself, not the ContactPerson?

**Comment by FLamparski** [comment]
It's in the UI, and looking at Xero's internal API, Contact Persons have
their own IDs. Setting a contact person's details to empty values doesn't
work - I tried in the previewer. I can make it work as a hack in my
application, but it doesn't delete the actual record. Maybe it is time to
bug Xero about exposing a Contact Person endpoint.

**Comment by coop182** [comment]
Right... sorry that is for the Contact not ContactPerson... didn't read this properly on my phone this morning haha...

**Comment by coop182** [comment]
I just tried the following with the API previewer.

POST to Contact endpoint

```xml
<Contacts>
  <Contact>
      <Name>Test Contact</Name>
      <EmailAddress>test@contact.com</EmailAddress>
      <ContactPersons>
          <ContactPerson>
              <FirstName>Test 1</FirstName>
              <LastName>Person 1</LastName>
          </ContactPerson>
          <ContactPerson>
              <FirstName>Test 2</FirstName>
              <LastName>Person 2</LastName>
          </ContactPerson>
      </ContactPersons>
    </Contact>
</Contacts>
```
Response is

```xml
<Response xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Id>88749b3f-7b74-4dba-925c-f37ac00df918</Id>
  <Status>OK</Status>
  <ProviderName>Xero API Previewer</ProviderName>
  <DateTimeUTC>2015-07-29T23:19:44.6282718Z</DateTimeUTC>
  <Contacts>
    <Contact>
      <ContactID>e0c85601-1f31-4655-a122-b8d1eddec794</ContactID>
      <ContactStatus>ACTIVE</ContactStatus>
      <Name>Test Contact</Name>
      <EmailAddress>test@contact.com</EmailAddress>
      <Addresses>
        <Address>
          <AddressType>STREET</AddressType>
        </Address>
        <Address>
          <AddressType>POBOX</AddressType>
        </Address>
      </Addresses>
      <Phones>
        <Phone>
          <PhoneType>DDI</PhoneType>
        </Phone>
        <Phone>
          <PhoneType>MOBILE</PhoneType>
        </Phone>
        <Phone>
          <PhoneType>FAX</PhoneType>
        </Phone>
        <Phone>
          <PhoneType>DEFAULT</PhoneType>
        </Phone>
      </Phones>
      <UpdatedDateUTC>2015-07-29T23:19:44.533</UpdatedDateUTC>
      <IsSupplier>false</IsSupplier>
      <IsCustomer>false</IsCustomer>
      <ContactPersons>
        <ContactPerson>
          <FirstName>Test 2</FirstName>
          <LastName>Person 2</LastName>
          <IncludeInEmails>false</IncludeInEmails>
        </ContactPerson>
        <ContactPerson>
          <FirstName>Test 1</FirstName>
          <LastName>Person 1</LastName>
          <IncludeInEmails>false</IncludeInEmails>
        </ContactPerson>
      </ContactPersons>
    </Contact>
  </Contacts>
</Response>
```
Then you can post the same data again but this time with the ContactID and removing one of the ContactPerson's

```xml
<Contacts>
  <Contact>
      <ContactID>e0c85601-1f31-4655-a122-b8d1eddec794</ContactID>
      <Name>Test Contact</Name>
      <EmailAddress>test@contact.com</EmailAddress>
      <ContactPersons>
          <ContactPerson>
              <FirstName>Test 1</FirstName>
              <LastName>Person 1</LastName>
          </ContactPerson>
      </ContactPersons>
    </Contact>
</Contacts>
```
Then by running a GET request with the same ContactID you can see ContactPerson is removed from the Contact as expected... this should all work with this library as well.

```xml
<Response xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Id>8df66cb0-2bfd-4433-9542-a87de97bbca1</Id>
  <Status>OK</Status>
  <ProviderName>Xero API Previewer</ProviderName>
  <DateTimeUTC>2015-07-29T23:25:31.8218503Z</DateTimeUTC>
  <Contacts>
    <Contact>
      <ContactID>e0c85601-1f31-4655-a122-b8d1eddec794</ContactID>
      <ContactStatus>ACTIVE</ContactStatus>
      <Name>Test Contact</Name>
      <EmailAddress>test@contact.com</EmailAddress>
      <Addresses>
        <Address>
          <AddressType>STREET</AddressType>
        </Address>
        <Address>
          <AddressType>POBOX</AddressType>
        </Address>
      </Addresses>
      <Phones>
        <Phone>
          <PhoneType>DDI</PhoneType>
        </Phone>
        <Phone>
          <PhoneType>DEFAULT</PhoneType>
        </Phone>
        <Phone>
          <PhoneType>FAX</PhoneType>
        </Phone>
        <Phone>
          <PhoneType>MOBILE</PhoneType>
        </Phone>
      </Phones>
      <UpdatedDateUTC>2015-07-29T23:23:11.853</UpdatedDateUTC>
      <IsSupplier>false</IsSupplier>
      <IsCustomer>false</IsCustomer>
      <ContactPersons>
        <ContactPerson>
          <FirstName>Test 1</FirstName>
          <LastName>Person 1</LastName>
          <IncludeInEmails>false</IncludeInEmails>
        </ContactPerson>
      </ContactPersons>
      <HasAttachments>false</HasAttachments>
    </Contact>
  </Contacts>
</Response>
```

**Comment by coop182** [comment]
Actually ContactPerson.php is wrong - ContactID, ContactNumber and Name should not be properties... hopefully you can just ignore them before a fix is made to the generator.

**Comment by calcinai** [comment]
I've fixed those rogue properties but not sure what to do about the rest..

**Comment by FLamparski** [comment]
Thanks, this works even for deleting the last contact person. Odd that when
I tried this with other contact elements set it didn't work. How do I do
this in XeroPHP? Should I look at the low-level Request methods?

As for bringing this into the high-level API, may I suggest using a custom
List class that can keep track of the elements and save its state to Xero?
It would also (probably) help with InvoiceItems, Phones and Addresses.

**Comment by calcinai** [comment]
Yeah, I had planned on making a 'Collection' object that held everything that came in and out as arrays.  I actually started this not so long ago, but to keep it BC, it made the interface not-so-nice.  Would you be open to having this in a 2.x? It seems a lot of things are destined for that release!

**Comment by calcinai** [comment]
This could actually be achieved by adding a ``deleteContactPerson``` method to the Contact class.  I wonder if there would be any harm adding that for all existing array properties?

**Comment by FLamparski** [comment]
Actually I can't seem to reproduce the way I deleted the last contact person from the list using the API, unless I was just imagining things :anguished: I keep posting empty `ContactPersons` but the last person on the list keeps coming back. Wat.

**Comment by FLamparski** [comment]
Alright, it's been a while and still no response from Xero about this: https://community.xero.com/developer/discussion/11092960/ - maybe you can only delete the last contact person once in a blue moon? Idk.

**Comment by calcinai** [comment]
Did you try emailing Xero directly?

**Comment by calcinai** [comment]
@FLamparski do you think that's an appropriate solution re: collections?

**Comment by FLamparski** [comment]
I think collections would work really well, as they should also help with
invoice lines etc. Of course, it might be useful to have a method to return
an array reference for use with the array_* family.

I have emailed api@xero but so far no reply.

**Comment by calcinai** [comment]
I'm not too surprised by that!  Did you see the collections branch?

**Comment by FLamparski** [comment]
Ah, I'll check it out!

**Comment by calcinai** [comment]
I've made a PR #66

**Comment by calcinai** [comment]
Didn't intentionally close this, although I guess this isn't really the place for bugs / lack of communication from Xero!

**Comment by FLamparski** [comment]
_They replied!_

Reply to the email I sent last week:

>Hi Filip,
>
>Apologies for the delay in responding.
>
>Thanks for this. A bug tracker for this issue have been created.
>
>We are unable to provide a time frame for the fix but we will update you as soon as it is released.

Reply on the Xero Developer Community forums:

>As you said, using the empty tag won't work on contact persons. The closest thing you can do is send in null contact with IncludeInEmails set to false.
>
>```<Contact>
<ContactID>4c7370e7-6f83-43b7-b943-a0b77e5dc348</ContactID>
<ContactPersons>
<ContactPerson>
<FirstName></FirstName>
<LastName></LastName>
<EmailAddress></EmailAddress>
<IncludeInEmails>false</IncludeInEmails>
</ContactPerson>
</ContactPersons>
</Contact>
```
>
>The null contact will persist in the API and Xero UI but it's the closest you can get to deleting all contact persons via the UI.

Hopefully this will help you implement a remove method, I have a suspicion that this inability to delete from subordinate collections if there is only one element is consistent across the API.

**Comment by calcinai** [comment]
Bugger, the remove method deals with a collection and just empties it.  It's funny - the solution was what I was joking about at the start of the thread: 

> You probably have to do something silly like saving empty ones to override them. 

@ronanq - has made a couple of fixes in here already, maybe he could offer some advice (sorry Ronan!)

**Comment by FLamparski** [comment]
On the collections branch, the hack to null the contact person's data seems to be behaving itself, however in v1.2.2 it causes problems with editing the contact later.

Code that nulls the contact person:

```php
      $payload = "<Contact><ContactID>" . $xeroContact->getGUID() . "</ContactID><ContactPersons><ContactPerson><FirstName></FirstName><LastName></LastName><EmailAddress></EmailAddress><IncludeInEmails>false</IncludeInEmails></ContactPerson></ContactPersons></Contact>";
      $request = new \XeroPHP\Remote\Request($this->xero, new \XeroPHP\Remote\URL($this->xero, 'https://api.xero.com/api.xro/2.0/Contacts'), 'POST');
      $request->setBody($payload);
      $response = $request->send();
      $xeroContact->fromStringArray($response->getElements()[0]);
```

This "works", however later, after re-loading and saving the contact, some part of the system decides that empty fields in ContactPersons should not have their own tags which triggers a validation error from Xero. A request like this is sent:

```xml
<Contact>
  <ContactID>4c7370e7-6f83-43b7-b943-a0b77e5dc348</ContactID>
  <!-- snip -->
  <ContactPersons>
    <ContactPerson>
      <IncludeInEmails>false</IncludeInEmails>
    </ContactPerson>
  </ContactPersons>
</Contact>
```

Prompting a response:

```xml
        <ValidationError>
          <Message>A contact person must have at least one of: FirstName, LastName, or EmailAddress</Message>
        </ValidationError>
```

Because apparently you can have empty tags as long as they're there. :expressionless:

Again, everything seems to work fine on the collections branch so far.

**Comment by ronanq** [comment]
Hi - sorry for the late reply. It can be a fine line, but if the issue relates more to the general functioning of the Xero APIs, this isn't the best place to get a reply from Xero, but we are very happy to help out in our developer community which we are making an effort to patrol as regularly as possible: https://community.xero.com/developer/.

In terms of a solution to the issue at hand, when these fields were added in the main application, we wanted to replicate the feature quickly in the API and really only had time for replicating reading and updating them via the API, hence this crappy gap - sorry!

The proper solution would be a pattern similar to [removing a contact from a ContactGroup](http://developer.xero.com/documentation/api/contactgroups/#title6).

Apologies again the interim solution is so hacky - the proper one is definitely on our to-do list.

**Comment by calcinai** [comment]
I'm going to close this since it seems like there's not a lot that can be done about it currently.

**Comment by alexkb** [comment]
It seems @FLamparski's solution to setting an empty ContactPerson to clear out all current ContactPersons is still required (albeit 2 years on). 

The issue I can't work around now though is that if you can't remove all ContactPersons cleanly (without relying on the empty ContactPerson), you then can't remove the Email on the (parent) Contact itself - the Xero API gives you an error.  Are there any updates you can provided @ronanq ? Thanks.
