### ISSUE TITLE
Support for createdByMyApp option?

### ISSUE THREAD

**Issue by nelwa** [calcinai/xero-php#630]
Hi,

I can't seem to find anything around the createdByMyApp parameter for GET Invoices.  Is it supported in this library?  If so, can you please give me an example on how to use it?

Also, how should the order parameter on GET Invoices be used in the library.

Thanks for a great library, but the documentation is a little lacking...

**Comment by Josh-G** [comment]
> createdByMyApp parameter for GET Invoices

[Query::setParameter](https://github.com/calcinai/xero-php/blob/0a89c5ec5cb598eccf978865127c745090f5c6e1/src/XeroPHP/Remote/Query.php#L249-L254)
```php
$xero->load(Invoice::class)
    ->where('Status', Invoice::INVOICE_STATUS_AUTHORISED)
    ->where('Type', Invoice::INVOICE_TYPE_ACCREC)
    ->setParameter('createdByMyApp', 'true')
    ->execute();
```

> how should the order parameter on GET Invoices be used in the library

[Query::orderBy](https://github.com/calcinai/xero-php/blob/0a89c5ec5cb598eccf978865127c745090f5c6e1/src/XeroPHP/Remote/Query.php#L150-L155)
```php
$xero->load(Invoice::class)
    ->orderBy('InvoiceNumber', \XeroPHP\Remote\Query::ORDER_DESC)
    ->execute();
```

**Comment by nelwa** [comment]
Thank you!  Just want to thank you again, this is an excellent library!
