### ISSUE TITLE
Fatal error: Class 'XeroPHP\Application\PrivateApplication' not found

### ISSUE THREAD

**Issue by anantapon** [calcinai/xero-php#631]
My code
XeroPHP
---- Application
--------  PrivateApplication.php
index.php

<?php
  use XeroPHP\Application\PrivateApplication;
  $config = [
    'oauth' => [
        'callback' => 'http://localhost/',
        'consumer_key' => 'k',
        'consumer_secret' => 's',
        //'rsa_private_key' => 'file://certs/private.pem',
    ],
  ];
  $xero = new PrivateApplication($config);

  $contacts = $xero->load(Contact::class)->execute();

  foreach ($contacts as $contact) {
    print_r($contact);
  }
?>

**Comment by calcinai** [comment]
@anantapon did you install the library using composer?
