### ISSUE TITLE
Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /xero-php/vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php on line 27

### ISSUE THREAD

**Issue by sunnykasera3107** [calcinai/xero-php#634]
`namespace XeroPHP\tests;

use XeroPHP\Webhook;
use XeroPHP\Application;
use XeroPHP\Webhook\Event;
use XeroPHP\Application\PrivateApplication;

require_once 'vendor/autoload.php';

class XeroRS extends \PHPUnit_Framework_TestCase {

  private $config;
  private $application;

  public function __construct(){
    $this->config = [
        'oauth' => [
            'callback' => 'http://localhost/xero/xero-php/test.php',
            'consumer_key' => 'key',
            'consumer_secret' => 'secret',
            'rsa_private_key' => file_get_contents( __DIR__ . '/privatekey.pem'),
            'rsa_public_key' => file_get_contents( __DIR__ . '/publickey.pem'),
        ],
        'webhook' => [
            'signing_key' => 'key',
        ]
    ];
    $this->application = new PrivateApplication($this->config);

  }

  public function loadPayload(){
    return file_get_contents('php://input');
  }

  public function getWebHook(){
    $payload = $this->loadPayload();
    $f = fopen('sunny.txt', 'a');
    fwrite($f, print_r($payload, true));
    fclose($f);
    if(empty($payload)){
      $this->assertFalse(('This is failed'));
    }else{
      $this->webhook = new Webhook($this->application, $payload);
      $this->validateWebHook();
    }
  }

  public function validateWebHook(){
    $xeroSignatureKey = $_SERVER['HTTP_X_XERO_SIGNATURE'];
    $f = fopen('sunny.txt', 'a');
    fwrite($f, print_r($this->webhook->validate($xeroSignatureKey), true));
    fclose($f);
    if(empty($xeroSignatureKey)){
      $this->assertFalse($this->webhook->validate('This is failed'));
    }else{
      $this->assertTrue($this->webhook->validate($xeroSignatureKey));
    }
  }

}`

Not sure what is wrong there.

**Comment by timacdonald** [comment]
This error in a doctrine file, not this codebase.

> Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /xero-php/vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php on line 27

File: `/xero-php/vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php`
Line number: `27`

**Comment by sunnykasera3107** [comment]
Thank you for help, I was feeding wrong details.
