### ISSUE TITLE
Tracking on New Invoice not working

### ISSUE THREAD

**Issue by nelwa** [calcinai/xero-php#636]
Hi Calcinai,

Firstly, thank you for your help a week ago - I'm really getting much use out of this library already.

I've been struggling for around a day now to get tracking categories to work.  I've tried all the suggestions on all the previously closed issues, but none are working.  Tracking is the final thing I need to get working...

Can you please provide an example on how to use tracking on a new invoice lineitem?

```
$tracking_option = new \XeroPHP\Models\Accounting\TrackingCategory\TrackingOption($xero);
$tracking_option->setTrackingOptionID($trval['TrackingOptionID']);

$trackingcategory = new \XeroPHP\Models\Accounting\TrackingCategory($xero);
$trackingcategory->setTrackingCategoryID($trval['CatID'])->addOption($tracking_option);

$lineitem->addTracking($trackingcategory);
```

This code is not working.  I've tried using only Names &/or Options instead of IDs, but they aren't working either.  I am 100% sure that my tracking info corresponds to the info in Xero.

The Invoice is created in Xero, but without any tracking associated with it.

**Comment by mogilvie** [comment]
Hi Nelwa,
This works for me on an invoice line item:
`        $newTracking = new TrackingCategory();
        $newTracking->setName('Region');
        $newTracking->setOption('South');
        $lineItem->addTracking($newTracking);`

The tracking category and option need to exist in Xero already.
