### ISSUE TITLE
Generate xero object URL

### ISSUE THREAD

**Issue by mhlavac** [calcinai/xero-php#64]
Recently we had to generate url for Xero object in order to nicely forward user from our system to Xero directly to the object.

We did small class to do this that basically maps object to Xero urls. Should we open a pull request and add it to this library directly?

Xero uses URLs like this: https://go.xero.com/Contacts/View.aspx?contactID=F41CBE7C-DE57-4927-B8A0-49FB0151BE77

it's therefore easy to take contact with ContactId F41CBE7C-DE57-4927-B8A0-49FB0151BE77 and generate whole url.

What do you think?

**Comment by calcinai** [comment]
Yep - That can probably almost be in the base object class, it would then work for any object with a GUID ... I think.

**Comment by mhlavac** [comment]
@calcinai sorry, wrong button. Yes that would be great. If we could call something like `$contact->getXeroUrl()`.

This means we have to add the mapping to generator and generate one more method.

**Comment by calcinai** [comment]
Just looking in to this some more.  There sin't a 1:1 mapping between the structure of the endpoints and the structure of the browsing in Xero.  I'm not sure that it's the right place for it to be in this library - it should probably just be calculated in the app on an object by object basis. 

Thoughts?

**Comment by mhlavac** [comment]
@calcinai the 1:1 mapping might be a problem. We ended up with this in the code:

``` php
        if ($className === Payment::class) {
            return $this->createXeroApiObjectLink('/Bank/ViewTransaction.aspx?bankTransactionID=', $id);
        } else if ($className === Invoice::class) {
            return $this->createXeroApiObjectLink('/AccountsReceivable/View.aspx?InvoiceID=', $id);
        } else if ($className === CreditNote::class) {
            return $this->createXeroApiObjectLink('/AccountsReceivable/ViewCreditNote.aspx?creditNoteID=', $id);
        } else if ($className === Contact::class) {
            return $this->createXeroApiObjectLink('/Contacts/View.aspx?contactID=', $id);
        }
```

I just thought it might be useful for someone else as well.

**Comment by calcinai** [comment]
Cool, thanks.  

ps. It's awesome that you can now fairly safely use some of those nice things from 5.5 like ```::class```!
