### ISSUE TITLE
Overpayment reference number

### ISSUE THREAD

**Issue by DezrtRose** [calcinai/xero-php#643]
I wanted to get the reference number of the overpayments through the XERO api. But I found out that the field has been deprecated. 

Is there any other way to get that value from xero? As in xero dashboard we can still add the reference number to an overpayment.

I have searched every where and could not find an answer.

Thank you

**Comment by calcinai** [comment]
@DezrtRose No ideas sorry!  Try emailing the Xero API support team - they should be able to help you.
