### ISSUE TITLE
Retrieving Bank Transactions

### ISSUE THREAD

**Issue by taymjay** [calcinai/xero-php#644]
Hi, can we still retrieve Bank Transactions or Bank Transfers? Nothing that I have tried is working.

`$xero = new \XeroPHP\Application\PrivateApplication($config);

	$bt = new BankTransaction($xero);

	$bankacc = new BankTransaction\BankAccount();
	$bankacc->setCode(001);

	$bt->setBankAccount($bankacc);

	$new_transactions = $xero->load('Accounting\\BankTransaction')
	->page('1')
	->execute();

	print_r($new_transactions);
	foreach ($new_transactions as $new_transaction) {
	    echo '<p class="description"> BankTransaction->' . $new_transaction['SubTotal'] . '</p><p>asdf</p>';
	}
	
	$new_transactions = $xero->load('Accounting\\BankTransaction')->execute();

	print_r($new_transactions);
	foreach ($new_transactions as $new_transaction) {
	    echo '<p class="description"> BankTransaction->' . $new_transaction['SubTotal'] . '</p><p>asdf</p>';
	}

	$new_transfers = $xero->load('Accounting\\BankTransfer')->execute();

	print_r($new_transfers);
	foreach ($new_transfers as $new_transfer) {
	    echo '<p class="description"> BankTransfer->' . $new_transfer['SubTotal'] . '</p><p>asdf</p>';
	}`

**Comment by calcinai** [comment]
What exactly isn't working?  Do you have any error messages or headers?

**Comment by taymjay** [comment]
Hi Calcinai, 

Thanks for the quick reply! I do have bank transactions in the Xero company, but none is loaded/printed out. 

At my Xero history: 
/api.xro/2.0/BankTransactions | GET | 200

Thus, I suppose it was executed without any errors. 

However, print_r($new_transactions); returns the following:

XeroPHP\Remote\Collection Object ( [_associated_objects:protected] => [storage:ArrayObject:private] => Array ( ) )

What am I missing or how can I get more info on the error messages?

**Comment by calcinai** [comment]
Well that looks like it's working.  Can you see the response in the developer console?

**Comment by taymjay** [comment]
I just tried the API previewer on the xero developer page, doesn't retrieve any transactions as well. Have sent in a support form to them to seek clarifications. Will update if they do reply. Thank you!

**Comment by taymjay** [comment]
My bad, I was on the wrong end point. Should be looking at Payments endpoint instead. Here are some of their replies:

The BankTransactions endpoint is used to retrieve Spend Money and Receive Money

If you match to an existing Invoice or Bill a Payment will be created.

If you use the Create tab a new BankTransaction will be created.

If you record a transfer between two bank accounts a BankTransfer will be created.

When your bank statement data is brought through to Xero using a bank feed you will see this data as bank statement lines in the Xero UI. It isn't currently possible to retrieve this using the API.

Once you start reconciling these lines, transactions are recorded in Xero. It is these that will be returned using the Payments, BankTransactions and BankTransfers endpoints.
