### ISSUE TITLE
Contact->Website not saving

### ISSUE THREAD

**Issue by ashleyken** [calcinai/xero-php#646]
I've just started getting to grips with setting Name, Email, Phones, Addresses, etc but for some reason, I'm not able to set the Website value.

If I look at the object before I send it, I can see that Website has been correctly set, but when I look at the $repsonse from $response = $contact->save(); I can see that everything else has been updated except for Website.

Is there another value that needs to be set to update the Website value?

**Comment by Josh-G** [comment]
Have a look at previous issues #557 and #329, I'm pretty sure it's the same problem.
Looks like it's still not possible to update this value.

**Comment by ashleyken** [comment]
Thanks Josh, apologies for not checking the issues more thoroughly :)

**Comment by OPVL** [comment]
Can confirm that this is still an issue for me

**Comment by manojn-arkenea** [comment]
I am also facing the same issue, while updating website name in my contacts

**Comment by calcinai** [comment]
@manojn-arkenea It seems the website cannot be updated via the API
