### ISSUE TITLE
Remove existent items before updating the invoice

### ISSUE THREAD

**Issue by iaroel** [calcinai/xero-php#65]
Hi Michael,

Thanks for the package.
Is there a way to remove existent items from invoice before updating?

**Comment by iaroel** [comment]
Adding:
````php
public function removeLineItems() {
        $this->_data['LineItems']=[];
    }
````
In /XeroPHP/Models/Accounting/Invoice.php

Is working but I'm not sure if that's is the right way.

**Comment by calcinai** [comment]
I have this planned on https://github.com/calcinai/xero-php/issues/63#issuecomment-126240905 - just need to update the generator to add that to models.

**Comment by calcinai** [comment]
What do you think about that?  You can use ```->removeAll()``` on the property.

**Comment by iaroel** [comment]
Hi Michael,

Thanks for that sounds good.
