### ISSUE TITLE
Attaching payment to invoice 

### ISSUE THREAD

**Issue by narwy** [calcinai/xero-php#651]
Hi,

I've got an issue where I'm trying to attach a payment to an invoice:

Code:
```
protected $xero;

public function __construct()
{
    $this->xero = new Xero(config('services.xero.private'));
}

public function take_payment()
{
    $payment = $this->xero->load('Accounting\\Payment');
    $payment->setInvoice($invoiceId)->setAmount("2.00");
    $payment->save();
}
```

Throws:
`Call to undefined method XeroPHP\Remote\Query::setInvoice()`

**Comment by calcinai** [comment]
@narwy I think you're wanting to create a new payment, rather than load one?

**Comment by narwy** [comment]
How would I go about doing that @calcinai ? tia.

**Comment by calcinai** [comment]
Something like 
```
$payment = new Accounting\Payment($xero);
$payment->setInvoice($invoice)->setAmount("2.00");
$payment->save();
```
There will be other fields that you require to make this work, but you should get the idea [from here](https://developer.xero.com/documentation/api/payments)
