### ISSUE TITLE
Organisation should expose Class property

### ISSUE THREAD

**Issue by emacinty** [calcinai/xero-php#656]
The Accounting\Organisation model doesn't currently expose Class, which is documented [here](https://developer.xero.com/documentation/api/organisation). This typically shows whether an Organisation is TRIAL, PREMIUM etc. This is relevant if, for example, you want to see if multiple currencies are supported (even if they don't at present exist in the organisation).

It was a relatively simple change to make locally; I've attached my diff which others may wish to use to apply whatever style is appropriate in the project.

[diff.txt](https://github.com/calcinai/xero-php/files/3864186/diff.txt)

**Comment by calcinai** [comment]
@emacinty feel free to submit a PR and I'll merge that one in, thanks!

**Comment by emacinty** [comment]
Thanks!

**Comment by calcinai** [comment]
No, thank you!
