### ISSUE TITLE
load(employees) not including enough data

### ISSUE THREAD

**Issue by Healyhatman** [calcinai/xero-php#657]
When I use $xero->load(Employee::class)->execute() on one particular install, the retrieved employees don't include the OrdinaryEarningsRateID: they're all null. On a different install with a different organisation, the same code has the OrdinaryEarningsRateID included.

Loading a single employee by GUID includes the OrdinaryEarningsRateID.

**Comment by calcinai** [comment]
By "Install" do you mean the xero-php install and the application, or just the install itself?

**Comment by Healyhatman** [comment]
When I say install I mean a server with a deployment of my code. 

I found out from Xero API support what the problem is though - when retrieving multiple employees (without paging) it doesn't include any of the employee's Earnings Rates **if those rates are inactive**. So that's what the problem is, and the OTHER issue https://github.com/calcinai/xero-php/pull/610#issuecomment-565839595 would've helped let me know that those rates are inactive when I queried the rates.
