### ISSUE TITLE
Not able to create contact with isCustomer

### ISSUE THREAD

**Issue by bradyuen** [calcinai/xero-php#658]
Could you help to check why I'm not able to create customer contact?
It keep to create new contact to Supplier.

                $contact->setName($fullname)
                    ->setFirstName($firstName)
                    ->setLastName($lastName)
                    ->setEmailAddress($Email)
                    ->addAddress($address)
                    ->setTaxNumber($abn )
                    ->setIsCustomer(true);

**Comment by calcinai** [comment]
@bradyuen Unfortunately this property is read only.
