### ISSUE TITLE
PayItems EarningsTypes is missing CurrentRecord

### ISSUE THREAD

**Issue by cproetti** [calcinai/xero-php#668]
The [Xero API documentation for PayItems](https://developer.xero.com/documentation/payroll-api/payitems) says that the EarningsRate GET includes a CurrentRecord value that is used to specify if the EarningsRate item is active or inactive. This CurrentRecord value can also be specified in the POST to change the status from active to inactive.

Although the Xero API has this CurrentRecord property, XeroPHP does not have CurrentRecord in the properties of [EarningsRate.php](https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Models/PayrollAU/PayItem/EarningsRate.php) and XeroPHP provides no way to get the value or set the value of CurrentRecord.

**Comment by calcinai** [comment]
@cproetti Feel free to add it and make a PR - I can review it later today.

**Comment by cproetti** [comment]
@calcinai Ok, I'll try to do it tonight. Thanks.

**Comment by rodjsta** [comment]
It appears this has been implemented with #610
