### ISSUE TITLE
Curl error: name lookup timed out

### ISSUE THREAD

**Issue by joeswann** [calcinai/xero-php#67]
Probably being dumb here but not getting anywhere with the usual prodding and poking. 

Steps I took:
- Create pub/private key pair: 
  - http://developer.xero.com/documentation/advanced-docs/public-private-keypair/
- Create private app
- Install xero-php in a silex app w/ composer
- Paste example code as follows (with path adjustment)
```
use XeroPHP\Application\PrivateApplication;
//These are the minimum settings - for more options, refer to examples/config.php
$config = array(
    'oauth' => array(
        'callback'         => 'http://xero.local.io',
        'consumer_key'     => 'k',
        'consumer_secret'  => 's',
        'rsa_private_key'  => 'file://../certs/privatekey.pem',
        'rsa_public_key'   => 'file://../certs/publickey.cer'
    )
);

$xero = new PrivateApplication($config);
print_r($xero->load('Accounting\\Organisation')->execute());

```
- Run
- Get following error
```
PHP message: PHP Fatal error:  Uncaught exception 'XeroPHP\Exception' with message 'Curl error: name lookup timed out' ..snip../vendor/calcinai/xero-php/src/XeroPHP/Remote/Request.php:102
```

This is with PHP 5.5, Curl 7.39, nginx, php-fpm, ubuntu

**Comment by calcinai** [comment]
A DNS issue in your web server?

**Comment by joeswann** [comment]
Oh and copying the headers that is being curled into postman gets this
```
oauth_problem=consumer_key_unknown&oauth_problem_advice=Consumer%20key%20was%20not%20recognised
```

**Comment by joeswann** [comment]
Don't think so, I have tried both local and remote. Removing the following line managed to get past the name lookup error to the consumer key error, but at that point I was trying everything
```
curl_setopt($ch, CURLOPT_POSTFIELDS, $this->body);
```

**Comment by calcinai** [comment]
How odd. This is probably one of the arguments to use Guzzle - there has been discussion about it over at #4 

Do you know what your current/default curl timeout is?  Maybe try extending it?
```
$config = array(
    'oauth' => array(
        'callback'         => 'http://xero.local.io',
        'consumer_key'     => 'k',
        'consumer_secret'  => 's',
        'rsa_private_key'  => 'file://../certs/privatekey.pem',
        'rsa_public_key'   => 'file://../certs/publickey.cer'
    ),
  'curl' => array(
      CURLOPT_CONNECTTIMEOUT => 30
  )
);
```

**Comment by joeswann** [comment]
Don't think it's DNS, the following very dirty test script gets the same error postman does
```
// Get cURL resource
$curl = curl_init();
// Set some options - we are passing in a useragent too here
curl_setopt_array($curl, [
  CURLOPT_RETURNTRANSFER => 1,
  CURLOPT_URL            => 'https://api.xero.com/api.xro/2.0/Organisation',
  CURLOPT_USERAGENT      => 'Xero Test',
  CURLOPT_SSL_VERIFYPEER => false,
  CURLOPT_HTTPHEADER     => array(
    'Authorization: OAuth oauth_consumer_key="k", oauth_signature_method="RSA-SHA1", oauth_timestamp="1438812654", oauth_nonce="..snip..", oauth_callback="http://xero.wombat.local.io/", oauth_version="1.0", oauth_token="k", oauth_signature="..snip.."',
    'Accept: text/xml'
  )
]);

// Send the request & save response to $resp
$resp = curl_exec($curl);

if(!curl_exec($curl)){
  echo ('Error: "' . curl_error($curl) . '" - Code: ' . curl_errno($curl));
} else {
  echo (var_export($resp, 1));
}
```

**Comment by joeswann** [comment]
Same error with a timeout of 100, trying to narrow down if it's one of the curl settings in https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/Request.php

**Comment by calcinai** [comment]
Very strange.  I did a little google and it looks like that error can crop up for things unrelated to DNS.  How useful!

**Comment by joeswann** [comment]
Okay, so I was being an idiot and didn't have my k+s copied in. But still getting the timeout error with those in place.

**Comment by joeswann** [comment]
The quick and dirty script now works with the k&s in place, so I guess it's something to do with XeroPHP\Remote\Request

**Comment by calcinai** [comment]
That's a worry. Can you try getting some more info from cURL.  Maybe set the ```CURLOPT_VERBOSE``` flag?

**Comment by joeswann** [comment]
Will try that now. some extreme prodding gets the following error which may be more meaningful?
```
Curl error: SSL certificate problem: unable to get local issuer certificate
```

**Comment by calcinai** [comment]
Oh right, try point it at the CA file in the ```examples/certs/ca-bundle.crt```, dir using ```CURLOPT_CAINFO``` flag.

**Comment by joeswann** [comment]
Okay *think* it's working, for posterity this is what I ended up with
````
  'curl' => array(
    CURLOPT_CAINFO         => '../certs/ca-bundle.crt',
    CURLOPT_CONNECTTIMEOUT => 60,
    CURLOPT_TIMEOUT        => 60
  )
```

**Comment by joeswann** [comment]
Oh and thanks for all your help! Is there anywhere I can donate?

**Comment by calcinai** [comment]
https://givealittle.co.nz

**Comment by joeswann** [comment]
Haha, chur
