### ISSUE TITLE
Update to oauth 2.0

### ISSUE THREAD

**Issue by shivikatqm27** [calcinai/xero-php#672]
Hi,

When will the update for oauth 2.0 will be available for this package?

**Comment by rodjsta** [comment]
See #625 
It's available now for testing on a separate branch.

**Comment by shivikatqm27** [comment]
Will this work with partner app as well?

**Comment by rodjsta** [comment]
@shivikatqm27, if you haven't already, you should check out https://developer.xero.com/documentation/oauth2/overview
