### ISSUE TITLE
Retriving Quotes from xero using XeroOAuth-PHP Fetches Every Quote Work Item

### ISSUE THREAD

**Issue by vigneshpy** [calcinai/xero-php#675]
I am trying to retrive Quote workitems from xero using XeroOAuth-PHP .

I am not allowed to migrate to the latest release xero-php-oauth2 due to some limitations in my company.

I already retrieved Invoice workitem from xero using XeroOAuth-PHP

I use the following code to retrieve Invoice WorkItems

$params['where'] = 'InvoiceNumber=="INV-0001"';
$params['page']= 1;
$response = $XeroOAuth->request('GET', https://api.xero.com/api.xro/2.0/Invoices', $params,"","json");
$response_invoice =  $XeroOAuth->parseResponse($response['response'],"json");

It Works Fine

When I try to Retrieve Quote Work Item using the Same Following Procedure

$params['where'] = 'QuoteNumber=="QU-0001"';
$params['page']= 1;
$response   = $XeroOAuth->request('GET','https://api.xero.com/api.xro/2.0/Quotes', $params,"","json");
$response_invoice =  $XeroOAuth->parseResponse($response['response'],"json");

It Retrive Every Quote WorkItem in my xero account Instead of Single Work Item of QU-0001

Here is the Response

My Question is Why Quotes Workitem Not Work According to Param

Is There any Possible reason Im using old XeroOAuth-PHP that doesn't Support Quote Retrieval?

**Comment by Yendall** [comment]
@vigneshpy what was your solution to this problem? I am having the same issue. It returns all quotes regardless of the filters/searches I put in place
