### ISSUE TITLE
Quotes API

### ISSUE THREAD

**Issue by mikerockett** [calcinai/xero-php#679]
The new Quotes API is now available, with the GET and POST methods available:

https://developer.xero.com/documentation/api/quotes#POST

This has been a long time coming on the part of Xero, and my client has been waiting ever so patiently for it since word got out. ;-)

Could it be added to this package?

**Comment by calcinai** [comment]
@mikerockett It's pretty straightforward to add and if you've got a use-case already, have a crack at adding them.

Just create a new folder in the models directory and base it on the existing ones.  I'm sorry but I won't get a chance to do this in the short term, but let me know hw you get on.

**Comment by mikerockett** [comment]
I've started building this out and will submit a PR when done.

Quick question: Invoices and Quotes now both reference LineItems. As such, LineItem should technically be moved out of the Invoice namespace, up one level into the Accounting namespace. 

However, this is a breaking change. So, the options are:

1. Keep it where it is – no _real_ harm in referencing the Invoice namespace for a line item.
2. Move it to the Accounting namespace and do a major BC release
3. Deuplicate it to a new Quote namespace (not recommended, naturally)

If this were my package, I'd be inclined to go for option 2. While I develop, though, I'll stick option 1. 😜

**Comment by mikerockett** [comment]
Likewise with option 2, the LINEAMOUNT_TYPE_EXCLUSIVE, LINEAMOUNT_TYPE_INCLUSIVE and LINEAMOUNT_TYPE_NOTAX class constants should be moved to the LineItem class as LineItem::TYPE_X.

**Comment by mikerockett** [comment]
[My implementation](https://github.com/mikerockett/xero-php/tree/feature/quotes-api-implementation) is working correctly. 🎉

@calcinai I'll wait on your response regarding line items before submitting a PR.

**Comment by calcinai** [comment]
@mikerockett You'll probably find there are several copies of it.  Originally when this library was created, it was generated by scraping the Xero docs, and to be safe, I made the generator namespace any referenced models under the docs page it was found on.  Maybe wasn't the best idea!

Assuming that a _LineItem_ is **identical**, option 4 (my preference) would be to move the _LineItem_ up a level (as you've suggested) or maybe into a 'common' namespace, then extend it & deprecate child classes where they currently are.

Thoughts?

**Comment by mikerockett** [comment]
@calcinai Ah I see – didn't even notice the many copies! Fair enough though…

I think that's a pretty good idea actually. Then when you release the next major version, the deprecated classes can simply be dropped.

In terms of which namespace to use: if we use a common namespace, then other models might need to move into it as well, such as Item, BrandingTheme, etc. So we'd either have to do all of them in one go (creating a bit of a mess in terms of deprecated classes) or just have LineItem live in the Accounting namespace, which I think its sensible enough.

**Comment by mikerockett** [comment]
I've just taken a squiz through the docs - and the only difference I can see between them is the descriptions of the various fields. Quotes and invoices have their own sections for line items, whereas credit notes references invoice line items. The way I see it though (and this makes total sense) is that Xero sees all line items the same way - they are the same 'model'.

**Comment by Josh-G** [comment]
> move the LineItem up a level

This sounds sensible to me.

**Comment by mikerockett** [comment]
@calcinai – quick follow up on the above. I also think this should be split into two PRs. One for implementing quotes, and another for cleaning up line items. Thoughts?

**Comment by calcinai** [comment]
@mikerockett sure. Line items first probably?

**Comment by mikerockett** [comment]
Probably a good idea, will do a PR as soon as I can 🙂

**Comment by mikerockett** [comment]
PR #738 opened as a draft. Doing a practical test and then I'll open it up.

**Comment by mikerockett** [comment]
Thanks for merging :)

Have opened up https://github.com/calcinai/xero-php/pull/756 for the Quotes API.
