### ISSUE TITLE
Q: How do I get error details when OAuth fails?

### ISSUE THREAD

**Issue by judgej** [calcinai/xero-php#68]
So I have an application (either public or partner) with a registered OAuth session. The system then goes to fetch some transactions in a scheduled job. The user is not around to re-authenticate if necessary, since access is via a batch job.

If the OAuth tokens have expired or have been withdrawn (i.e. regenerated on Xero) then this transaction fetch will fail. What is the best way to get the details of the problem?

I can catch exceptions and get the last exception message:

```
    try {
        $orgs = $xero->load('Accounting\\Organisation')->execute();
    } catch (\Exception $e) {
        echo $e->getMessage();
    }
    // Gives: "The access token has expired"
```

But is there a more formal way to get the error type rather than just a human-readable text (which may change with different languages anyway)? I guess I need to be able to distinguish between permanent errors (like the expiry above) and temporary errors such as a network being down, so we know whether to alert an admin or just reschedule the job for later. I'm assuming I don't need separate catch() terms for each of the dozen-or-so exceptions that are defined.

The example applications here demonstrate access with the user present, and so doesn't need to handle authorisation errors by the time it gets to inspecting the Xero account details.

**Comment by judgej** [comment]
Perhaps there is a simple call to validate the OAuth session details before diving into the Xero account? That would help to catch authorisation errors before the main processing starts at least (though accepting the session could expire any any time, in the middle of processing for example).

**Comment by calcinai** [comment]
You could try to catch the specific exceptions - if you look at https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/Response.php you can see where it splits them off. 

You might need to define a couple more exceptions if they're not granular enough (just make sure that you extend whatever you replace for BC)... Or I could take a look?

**Comment by judgej** [comment]
I'm not so much looking for more granularity, but rather wanting to get the details of each error types that there are now, for logging and further decisions. For example, when using the `Request` object to `send()` a message to the OAuth server, I can catch `Exception $e` and there is a an error code and error reason (called "advice") that can be obtained from the response. If that is not in the response then I set the error code to "unknown" and the error reason to `$e->getMessage()` and feed that through the error logging pipeline. That is just not always possible when accessing the Xero account through the API, because we don't deal with the `Request` object directly at that point.

I will try the exception catches, but I just don't want it to look like a giant if-then-elseif-... list of all possible exceptions to catch. I guess `$e->getCode()` or `classname($e)` may be available - I'll check.

**Comment by judgej** [comment]
Here is an example of where the message code and reason can be caught easily:

        $app = new PublicApplication($config);
        ....
        $request = new Request($app, $url);

        // Send the auth request to Xero.
        try {
            $request->send();
        } catch (Exception $e) {
            // Did we get a response from Xero?
            if ($request->getResponse()) {
                $oauth_response = $request->getResponse()->getOAuthResponse();
                $error_code = $oauth_response['oauth_problem'];
                $error_reason = $oauth_response['oauth_problem_advice'];
            } else {
                $error_code = 'unknown';
                $error_reason = $e->getMessage();
            }

            // Log exception
            Log::error("Failed to authorise", $error_code, $error_reason);

            // Now act on the error_code
            ....
        }

**Comment by calcinai** [comment]
What about if when the ```UnauthorizedException``` was constructed, it was also populated with data to expose a ```->getOAuthDetails``` method (or something similar).  That way, you could specifically catch an UnauthorizedException, then get further details on it if necessary?

**Comment by judgej** [comment]
I'm just looking at this now in my current project. I think catching exceptions when communicating with Xero comes down to three classes:

* Authentication error - incorrect or expired non-renewable tokens.
* Temporary network issue.
* Any other unexpected error.

The first will involve notifying the end user that they need to reauthenticate. The second will probably just be a note to the admin, but the system will keep trying. The last is probably a fatal error and needs attention before the process can be restarted.

**Comment by judgej** [comment]
Still not clear to me. I create the application (a partner application) and give it access tokens that have previously been saved. I then try to execute a fetch, for example:

    $xero->load('Accounting\\Organisation')->execute();

This is the first point at which it calls up Xero, and so may discover the auth tokens have expired at this point and need renewing. How would that be discovered here? I see there is an `XeroPHP\Remote\Exception\UnauthorizedException` exception if the authorisation has completely expired, so for a public application the user would need to re-authenticate. Is there a separate exception to indicate that the tokens have expired and simply need renewing before trying again?

**Comment by judgej** [comment]
Or maybe what I'm missing is that an expired access token is an expired access token, regardless of whether it is a public or a partner application. Knowing that we are connecting as a partner application means we know we can renew the access tokens without any further access from the user. Knowing that we are connecting as a public application means we know we have to inform the user to get them back to authorise new access tokens. Is that right?

So I catch `XeroPHP\Remote\Exception\UnauthorizedException` on any attempt to talk to Xero, and if that exception is thrown, then if the application type is partner, I renew the tokens then attempt the same api command again. If the application type is public, then I give up and notify the user with authority to re-authorise.

???

**Comment by judgej** [comment]
How about a callback for renewing tokens? There could be many, many places in an application that talks to Xero through many different accounting objects. At any point the partner application tokens could expire, and they need to be renewed, and the API call tried again. The application using this library should not need to deal with that all over the place.

How about this library automatically renews the tokens if it needs to, and then passes the new tokens to a callback for saving? That way the application is only notified of *real* authentication issues, and the fact that tokens expire every half hour becomes invisible.

**Comment by calcinai** [comment]
Haha, this is a big conversation to wake up to!  I'm really not too sure the best way to deal with that as I've only uses this for short lived Public apps and permanent Private apps.

@coop182, I know you use this for a Partner app, how do you deal with this?

**Comment by mhlavac** [comment]
We are using only Private and Public application, but we still have to deal with refreshing Token every 30 minutes in some cases, so maybe our use case is quite similar to what you need.

We ended up with decorating Application. Our Decorator takes Application in constructor and puts try, catch block to each call of Application. If we get UnauthorizedException with a message `The access token has expired` or `The access token has not been authorized, or has been revoked by the user`, then we notify user to refresh the token.

I guess in your case with Partner integration you can refresh the token yourself. This is small example:

```
class RefreshApplicationDecorator
{
    /**
     * @var \XeroPHP\Application
     */
    private $application;

    public function __construct(XeroPHP\Application $application)
    {
        $this->application = $application;
    }

    public function load($model)
    {
        try {
            return $this->application->load($model);
        } catch (\XeroPHP\Remote\Exception\UnauthorizedException $e) {
            // Refresh token logic here
        } catch (\Exception $e) {
            // Loggin, notifying user here?
        }
    }
    
    // ... other methods implemented here
}
```

We use Decorated Application everywhere, because the methods are same as in the Application. In some special cases, we want to behave differently, then we still use Application directly.

**Comment by judgej** [comment]
Cool, thanks. The try-catch looks similar to what I ended up with. However, I am just wrapping that around the `execute()` method, as I believed that was the point at which Xero was contacted, and so the only point that you can tell whether the tokens have really expired. Am I wrong in that understanding? Does `load()`

**Comment by mhlavac** [comment]
@judgej you are correct, it happens only after you execute. In my example we also have something called XeroRepository, that has all calls we do, something like `findContacts`, `findInvoices`, `findInvoicesByUser` and so on and then we decorated this Repository.

Callback could be a nice thing to do. I am curretly working on Symfony Xero Bundle and I think most of the functionality could be exported directly to this Xero library. Including Token timeout handling, waiting for next minute while you hit 60 requests a minute etc...

**Comment by judgej** [comment]
Ah yes, rate limit handling would also be very nice indeed.

I'm using this in Laravel to move transactions between customers and banks, so the reason I'm fretting over such things is that it needs to be very robust to run unattended 24/7 doing its thing. Any recoverable errors (e.g. rate limits) should be quietly handled and anything not working exactly as expected needs to be fully logged and the relevant people alerted. It's fun :-)

**Comment by judgej** [comment]
Just got caught out by `loadByGuid()` which returns an object and not a query like `load()`. To split the query and the execute when fetching by GUID, you need to do this:

                        // To get a contact by $contact_id
                        $contact_query = $connection->load('Accounting\\Contact')
                            ->where('ContactID = Guid("'.$contact_id.'")');
                        
                        // Get the contact. This is the bit that does the remote comms.
                        $contact = $contact_query->execute();

**Comment by calcinai** [comment]
Be careful with that @judgej, that's how it used to be but had to change it.  Someone identified that the behaviour was different in some cases, and it was more consistent to use the GUID-identified path.

**Comment by judgej** [comment]
Thanks for the warning - just found out this is affecting my results.

When fetching by GUID in the path, additional read-only details are tagged onto the records (amongst other differences). I have been scratching my head trying to work out why `BatchPayments` is not coming across with my contact details, and it turns out it does, but *only* if fetching the contact by GUID. Otherwise it just gets left out. Nothing about this in the docs, so far as I can see.

**Comment by calcinai** [comment]
Yeah, from memory someone was in contact with Xero about it.  In a (kind-of) related note, the next major release will support lazy-loading of relations.

**Comment by judgej** [comment]
In fact, even then the `BatchPayments` and the `Balances` are coming across as empty strings instead of arrays or value objects.

In my getByGuid call:

    "BatchPayments" => ""
    "Balances" => ""

In the Xero online API query tool:

      <BatchPayments>
        <BankAccountNumber>12-34-56 12345678</BankAccountNumber>
        <BankAccountName>NatWest</BankAccountName>
        <Details>Banky</Details>
      </BatchPayments>
      <Balances>
        <AccountsReceivable>
          <Outstanding>180.70</Outstanding>
          <Overdue>180.70</Overdue>
        </AccountsReceivable>
        <AccountsPayable>
          <Outstanding>153.49</Outstanding>
          <Overdue>153.49</Overdue>
        </AccountsPayable>
      </Balances>

I expect this is going way off-topic now, but should these be arrays or value objects?

**Comment by calcinai** [comment]
Batch payments moved to #74 

What was the verdict with dealing with getting more info from an OAuth response?

**Comment by calcinai** [comment]
I'm putting a bit of work into this library this week - did we work out what can be done here to help?

**Comment by judgej** [comment]
I'll take a look at where I left it. Been working on other areas for a couple of weeks, but need to get back to the auth stuff.
