### ISSUE TITLE
Webhook Application for OAuth2

### ISSUE THREAD

**Issue by Yendall** [calcinai/xero-php#685]
Hello,

How do we go about creating a XeroPHP\Application for the Webhook constructor since the oAuth 2 release? 

Thanks!

**Comment by calcinai** [comment]
This hasn't actually changed.  Use the same Application as you'd use for the standard API.

**Comment by Yendall** [comment]
> This hasn't actually changed. Use the same Application as you'd use for the standard API.

Before the OAuth2 update we were having to pass a config to PartnerApplication and go through the OAuth1 signing process, that included the RSA certs, signing secrets etc. in order to create a PartnerApplication instance. Now i'm not so sure how to get an access token for the new Application instance without it being tied to a tenant.

Am I missing something?

**Comment by Yendall** [comment]
Actually I think I can see how it works without a tenant. Will test it out

**Comment by Yendall** [comment]
> Actually I think I can see how it works without a tenant. Will test it out

Just in case anyone else had the same confusion as me, got this working by passing no Bearer Token or Tenant ID to the Application instance and that seemed to do the trick as long as I set the webhook signing secret, same as the OAuth1.0 flow

Sorry for the non-issue @calcinai
