### ISSUE TITLE
Oauth2.0 - integration Laravel into background / scheduler commands

### ISSUE THREAD

**Issue by dancvrcek** [calcinai/xero-php#690]
Hi guys,

we did our own integration for Laravel scheduler, the core bits of the code are public at https://gitlab.com/keychest/xero

It can periodically refresh the access_token that expires every 30 minutes. It can be used to create an up to date "session" config file so other Xero code can always get a valid access token.

feel free to use it, if it makes sense for you.

_Update 17 March: the refresh token lasts 60 days (not 30 mins as we thought and that applies to access tokens) so you should only need the "full bootstrapping" when installing a new application and Xero offers a standalone binary for that. It may still help you if you want to keep valid access token 24x7 so that your Xero clients don't have to worry about that._ 

Cheers
  Dan

**Comment by Healyhatman** [comment]
I don't think this is necessary though is it? Thought tokens can be refreshed up to 60 days?

**Comment by dancvrcek** [comment]
Can you elaborate, please? It would certainly make integration more resilient.

**Comment by Healyhatman** [comment]
The access token lasts 30 minutes, and when it's expired you just use the
refresh token (if you've granted the offline access scope) and get a new
access token. You don't have to keep the access token alive

**Comment by dancvrcek** [comment]
Did you test that? We get:
