### ISSUE TITLE
Refresh Token is empty

### ISSUE THREAD

**Issue by oOmischaOo** [calcinai/xero-php#692]
Using demo.php as my starting point I am trying to implement the refresh token process for long lived access. When I call $token->getRefreshToken() it returns an emptry string. How do I get a refresh token to persist authentication? Many thanks.

**Comment by outdoorsnz** [comment]
I managed to get this to work. You need to refer to https://github.com/XeroAPI/xero-php-oauth2 to get the idea how getRefreshToken() works. 

My initial token storage is from a DB.

I came up with this:
`//Refresh token
$newAccessToken = $this->getAccessToken('refresh_token', [
    'refresh_token' => $this->getRefreshToken()
]);
//Update the session
$this->setToken(
     $newAccessToken->getToken(),
     $newAccessToken->getExpires(),
     $xeroauth_record->tenantId,//From DB
     $newAccessToken->getRefreshToken(),
     $newAccessToken->getValues()["id_token"]
);`
//Then load XeroPHP application etc

**Comment by muppsy007** [comment]
@outdoorsnz How are any of those method calls obtaining your initial token from DB exactly? And how did you obtain it in the first instance? Did you have to go through the manual Xero prompts on screen?

**Comment by rodjsta** [comment]
@oOmischaOo you may need to specify the 'grant_type'

Here's my refresh token code below:

if ( strtotime($accessTokenExpiry) <= time() ) {

	$provider = new Xero([
		'clientId' => $_ENV['XERO_CLIENT_ID'],
		'clientSecret' => $_ENV['XERO_CLIENT_SECRET'],
    	'redirectUri' => $_ENV['XERO_REDIRECT_URL'],
	]);

	$newAccessToken = $provider->getAccessToken('refresh_token', [
		'grant_type' => 'refresh_token',
		'refresh_token' => $refreshToken
	]);

    $accessToken = $newAccessToken->getToken();
    $accessTokenExpiry = date("Y-m-d H:i:s", $newAccessToken->getExpires());
    $refreshToken = $newAccessToken->getRefreshToken();

    // update DB

}

**Comment by outdoorsnz** [comment]
> @outdoorsnz How are any of those method calls obtaining your initial token from DB exactly? And how did you obtain it in the first instance? Did you have to go through the manual Xero prompts on screen?

@rodjsta provided a better complete example.

Code to get initial token.

`$provider = new Xero([
            'clientId' => '',
            'clientSecret' => '',
            'redirectUri' => 'http://localhost/somesite/xero-auth',
        ]);
        $xeroauth_record = XeroAuth::get()->byID($this->ID);
        
        if (!isset($_GET['code'])) {
            // If we don't have an authorization code then get one
            $authUrl = $provider->getAuthorizationUrl([
                'scope' => 'offline_access openid email profile accounting.settings accounting.transactions accounting.contacts accounting.reports.read projects accounting.journals.read'
            ]);

            $_SESSION['oauth2state'] = $provider->getState();
            header('Location: ' . $authUrl);
            exit;

        // Check given state against previously stored one to mitigate CSRF attack
        } elseif (empty($_GET['state']) || ($_GET['state'] !==  $_SESSION['oauth2state'])) {
            unset($_SESSION['oauth2state']);
            exit('Invalid state');

        } else {
            
            // Try to get an access token (using the authorization code grant)
            $token = $provider->getAccessToken('authorization_code', [
                'code' => $_GET['code']
            ]);
            
            //Get the tenants that this user is authorized to access
            $tenants = $provider->getTenants($token);
            //write to session or save to DB
           
        }`

To write token to DB:
 //to db = base64_encode(serialize($token))

To get back from DB:
$token = unserialize(base64_decode($xeroauth_record->access_token));

**Comment by oOmischaOo** [comment]
Thank you for the responses. Unfortunately I abandoned my efforts with this library. I was in a hurry and managed to get a solution using the xero-php-oauth2 library with persistence to DB. The grant_type flag may be the cause of my problems, I was not providing it. I will try and get some time to try it out and provide feedback

**Comment by calcinai** [comment]
Sorry to come in late tot he party, but could it be as simple as not requesting the `offline_acces` scope?

**Comment by outdoorsnz** [comment]
> Sorry to come in late to the party, but could it be as simple as not requesting the `offline_acces` scope?

Also you need to clear your cache and reboot browser if you change scopes having previously logged / authorised xero.
