### ISSUE TITLE
Saving model no longer returns model

### ISSUE THREAD

**Issue by futurewebsites** [calcinai/xero-php#693]
I have just upgraded to v2.0 from 1.8 in order to move to oAuth2 but I am no longer getting the model returned on save() 

`$contact = new Contact($xero);

$contact->setName('Test Contact')
    ->setFirstName('Test')
    ->setLastName('Contact')
    ->setEmailAddress('test@example.com');
return $contact-save()`

I now get a response object ?

**Comment by calcinai** [comment]
@futurewebsites Which model are you after? The contact itself is updated on save.

**Comment by futurewebsites** [comment]
@calcinai Ignore me I am a big fat lier turns out I didn't set the tenant everything works as expected after migrating to v2 and oAuth2 sorry
