### ISSUE TITLE
Atomic transactions and/or batches

### ISSUE THREAD

**Issue by paulsschwarz** [calcinai/xero-php#7]
I keep seeing hints that Xero's api allows batches.
https://community.xero.com/developer/discussion/5950207#answer5952304
https://community.xero.com/developer/discussion/37831/

A use use case in my application would be to create an invoice, attach a payment to that invoice, and create a bill. That's 3 accounting documents. Is it possible to do this in one atomic API call?

**Comment by calcinai** [comment]
It may be possible.

I am currently doing something similar to what's described in that link like this:

```php
    //Doing this in a loop of creating the invoice
    $invoices[] = $invoice->toStringArray();
}

$url = new URL($xero, Invoice::getResourceURI());
$request = new Request($xero, $url, Request::METHOD_PUT);

$invoices_string = Helpers::arrayToXML(array('Invoices' => $invoices));
$request->setBody($invoices_string);

try {
    $request->send();
} catch(Exception $e) {
}
```

Now, as far as I know, you're only allowed one type of document in the root of that XML payload.  With your example, you should be able to at least do the invoice with its payments in one hit.  Something like:

```php
$contact = new Contact();
$contact
    ->setFirstName('Test')
    ->setLastName('Contact');

$payment = new Payment();
$payment
    ->setAmount(12.34)
    ->setDate($payment_date);

$invoice = new Invoice();
$invoice
    ->setType(Invoice::INVOICE_TYPE_ACCREC)
    ->setContact($contact)
    ->setReference('Test Invoice')
    ->setDate($invoice_date)
    ->setDueDate($due_date)
    ->addPayment($payment); //It's a 1-n relation so you can add as many as you like.

//Should save the lot.
$xero->save($invoice);
```

**Comment by paulsschwarz** [comment]
Your first snippet of code is spot on. Thanks!

Your second snippet is exactly what I was trying to do but it turns out it's not possible. The generated model for Invoice indeed has a `addPayment()` method which made me very hopeful at first. However it was working. I bypassed the code and went straight for the live API testing tool on Xero; same result, no payment added.

I found this article https://community.xero.com/developer/discussion/6793645/ and suddenly I was confused. I went back to the docs http://developer.xero.com/documentation/api/invoices/ and noticed something terrible: *The following are only returned on a GET request*.

So firstly, it sucks that Xero can't create an paid invoice in one API call. But secondly, the generated Model code is a little naive because it doesn't recognised that this is a read only property. The Model should implement `getPayments()` but not `addPayment`().

**Comment by calcinai** [comment]
I'm going to reopen this, as the generator is well aware of the supported methods, so shouldn't be adding it if it's not supported.

I think it's probably worthwhile to make the ```save()``` method accept an array of objects, or create another one that does.  Thoughts?

**Comment by paulsschwarz** [comment]
I think this should be split into two issues. Your first paragraph is a bug fix, the second is a feature request. And yes, it sounds well worthwhile since it is a reflection of what the API is naturally capable of.
