### ISSUE TITLE
Class 'XeroPHP\Payslip\TimesheetEarningsLine' not found

### ISSUE THREAD

**Issue by onesce** [calcinai/xero-php#710]
Hi Guys

Firstly thanks for the great work.

Just to make you aware of the following error after doing a composer update for version v2.0.2
`Class 'XeroPHP\Payslip\TimesheetEarningsLine' not found`

Looks like this line was added on a recent commit: [https://github.com/calcinai/xero-php/commit/3f5555eb1c18561fe302a3aa9090e30832719b02](https://github.com/calcinai/xero-php/commit/3f5555eb1c18561fe302a3aa9090e30832719b02)

`($singular_node_name == Payslip\TimesheetEarningsLine::getRootNodeName() && $child_name == 'EarningsLine')`

Thanks :)

**Comment by calcinai** [comment]
@onesce Wow, how did that happen.  I've pushed a quick fix [6c471b01](https://github.com/calcinai/xero-php/commit/6c471b01587ca95d35322301a0d3920c86a92de1)

Need better code coverage, huh?

**Comment by Healyhatman** [comment]
That addition was for PayrollAU \ Payslip, not PayrollUS \ Paystub

**Comment by calcinai** [comment]
@Healyhatman see following commit. It doesn't make a difference in this case as the strings are the same, but I fixed it for consistency.
