### ISSUE TITLE
Default User-Agent not right for Partner Certification

### ISSUE THREAD

**Issue by Healyhatman** [calcinai/xero-php#715]
One of the checklist points for Partner Certification is that your User-Agent includes your client access token (unless of course this has changed for OAuth 2?). 

I would recommend adding a $userAgent = null to the Application -> __construct  method but wasn't sure how you'd prefer to go about it.

**Comment by calcinai** [comment]
I don't think this is a requirement anymore... They're already going to have visibility into this.

**Comment by Healyhatman** [comment]
From my Xero Support guy:

> Yes you are right, user-agent is no-longer required for OAuth 2.0 apps, JWT token issued now has client key encrypted so we can use that to run search queries.
