### ISSUE TITLE
Problems fetching tenantId $provider->getTenants method is undefined

### ISSUE THREAD

**Issue by StoyanPenev** [calcinai/xero-php#719]
Hi there, I tried to get this up and running but 
as described in the demo https://github.com/calcinai/xero-php/blob/master/examples/demo.php
all is good until I reach this point
```php
 $identity = $provider->getResourceOwner($token); 
// This one gives me Invalid response received from Authorization Server. Expected JSON.
// The response is 'oauth_problem=consumer_key_unknown&oauth_problem_advice=Consumer key was not recognised'
    print_r($identity);

    //Get the tenants that this user is authorized to access
    $tenants = $provider->getTenants($token); 
// There is no such method defined in the provider class so this gives me 

(1/1) FatalThrowableErrorCall to undefined method getTenants()

```
My access scopes are 
```php
$options = [
            'scope' => [
                'accounting.transactions accounting.contacts accounting.settings',
            ],
        ];
```
I checked the app credentials multiple times but they are obviously fine because I get to the user presmissions screen and can then get to the accessToken but cannot retreive any tenantId to bootstrap the Xero Application class.
What am I doing wrong? The code in my app is 1:1 with the demo example.

Any help will be much appreciated, thanks.

**Comment by calcinai** [comment]
@StoyanPenev What is the provider object? That error is showing an undefined method?

**Comment by StoyanPenev** [comment]
Hi @calcinai, this is the last part of the exception trace:
```php
1/1) FatalThrowableErrorCall to undefined method Calcinai\OAuth2\Client\Provider\Xero::getTenants()
--
in AuthController.php line 51
at AuthController->index()
at call_user_func_array(array(object(AuthController), 'index'), array())in Controller.php line 55
at Controller->callAction('index', array())in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(AuthController), 'index')in Route.php line 203
at Route->runController()in Route.php line 160
at Route->run()in Router.php line 559
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
```

**Comment by calcinai** [comment]
@StoyanPenev Bizzare, take a look here: https://github.com/calcinai/oauth2-xero/blob/master/src/Provider/Xero.php#L63

What version of that dependency do you have?

**Comment by StoyanPenev** [comment]
Hi, thanks for the quick response, I installed this yesterday  I ran composer require calcinai/xero-php:
"calcinai/xero-php": "^2.0"

**Comment by calcinai** [comment]
@StoyanPenev have a look in your composer.lock - that has the installed versions.

**Comment by StoyanPenev** [comment]
Here it is
"name": "calcinai/oauth2-xero",
            "version": "v0.1.0",
            "source": {
                "type": "git",
                "url": "https://github.com/calcinai/oauth2-xero.git",
                "reference": "8a1d1b35f9092f56e643c891835c63bb764988b6"
            },

**Comment by StoyanPenev** [comment]
Maybe some package dependency was not bumped: I got stuck on
https://github.com/calcinai/oauth2-xero/commit/8a1d1b35f9092f56e643c891835c63bb764988b6
while the getTenants is introduced in 
https://github.com/calcinai/oauth2-xero/commit/6f2d7f1f4351f14530d3cc0691cee69eda115dce
as per

**Comment by calcinai** [comment]
Hmm. Not sure why it wouldn't have pulled the latest...

**Comment by StoyanPenev** [comment]
Hi @calcinai I guess you need to bump the dependency version in the main package composer.json from 
 "calcinai/oauth2-xero": "^0.1.0",
to 
 "calcinai/oauth2-xero": "^0.1.4", or whatever seems suitable
Maybe https://github.com/calcinai/oauth2-xero/releases/tag/v0.1.4 ?
thanks :)

**Comment by StoyanPenev** [comment]
Hi @calcinai, I think the issue with not updating is because you use caret with version < 1.0.0 
have a look here:
https://stackoverflow.com/questions/53529212/why-composer-dont-pull-newer-package-by-caret-version-range
I can create a pull request if you can merge this today so I can continue implementation, I am on a deadline for this one, many thanks!

**Comment by calcinai** [comment]
From my interpretation of that post, it should be working?  Anyway, I'll bump it to 1.0 since it's well in production now!

**Comment by StoyanPenev** [comment]
Yes @calcinai you are right it should update to 0.1.X as far as its < 0.2.0 but it does not, maybe there are some dependency conflicts in my composer that would not let the package to be updated, very confusing :confused: , thanks for the bump, will try again when you merge it :+1: !

**Comment by calcinai** [comment]
Should be fixed in #721

**Comment by calcinai** [comment]
@StoyanPenev update to https://github.com/calcinai/xero-php/releases/tag/v2.0.4 and let me know how you go.

**Comment by StoyanPenev** [comment]
Thanks for your help I updated my composer.json to
"calcinai/xero-php": "dev-master#v2.0.4", and ran composer update calcinai/xero-php
here is the output which did not result in update of the oauth dependency:

  Problem 1
    - Can only install one of: calcinai/oauth2-xero[v1.0.0, v0.1.0].
    - Can only install one of: calcinai/oauth2-xero[v1.0.0, v0.1.0].
    - Can only install one of: calcinai/oauth2-xero[v1.0.0, v0.1.0].
    - calcinai/xero-php dev-master requires calcinai/oauth2-xero ^1.0 -> satisfiable by calcinai/oauth2-xero[v1.0.0].
    - Installation request for calcinai/xero-php dev-master#v2.0.4 -> satisfiable by calcinai/xero-php[dev-master].
    - Installation request for calcinai/oauth2-xero (locked at v0.1.0) -> satisfiable by calcinai/oauth2-xero[v0.1.0].

**Comment by calcinai** [comment]
@StoyanPenev your composer should be  `"calcinai/xero-php": "^v2.0.4"`

And you should run `composer update`

**Comment by StoyanPenev** [comment]
Thanks, there are composer dependencies conflicts  I have
"guzzlehttp/guzzle": "^5.3.1|^6.2.1",
"guzzlehttp/psr7": "^1.4.1",
which I will have to resolve by tracking the vendor package that uses them.

Thanks for your support on this one :)
I think this is the issue for not updating the package, will close this one for now, and try to fix my composer dependencies, thanks!

**Comment by StoyanPenev** [comment]
Finally I managed to fix my composer dependencies running
```
composer require -vvv --update-with-dependencies "calcinai/xero-php:^2.0.4" "guzzlehttp/guzzle:^6.5" "google/apiclient:2.2.0"
```
The issue for not updating from 0.1.0 to later is because of the  in https://github.com/calcinai/oauth2-xero/commit/6f2d7f1f4351f14530d3cc0691cee69eda115dce
```
"firebase/php-jwt": "^5.0"
```
Updating my google api client to 2.2.0 bumped the firbebase/php-jwt package and I have the latest Calcinai\OAuth2\Client\Provider\Xero :)
