### ISSUE TITLE
Incorrect Type of DeductionTypeCalculationType of Payroll Employee's PayTemplate

### ISSUE THREAD

**Issue by cproetti** [calcinai/xero-php#723]
https://github.com/calcinai/xero-php/blob/53c14a944bc69ece43046be320bd2d1f7cbd4972/src/XeroPHP/Models/PayrollAU/Employee/PayTemplate/DeductionLine.php#L96

At first glance this seems incorrect to me that the type is FLOAT when I'd expect it to be a ENUM / STRING.

See the documentation of allowed options on Xero: https://developer.xero.com/documentation/payroll-api/types-and-codes#DeductionTypeCalculationType

I think this should be changed to PROPERTY_TYPE_STRING

**Comment by Healyhatman** [comment]
#770
