### ISSUE TITLE
Error Class not Found new \XeroPHP\Application\PrivateApplication

### ISSUE THREAD

**Issue by alivingmind** [calcinai/xero-php#724]
Class not found Error with Version 2.0

**Comment by Healyhatman** [comment]
There's no PrivateApplication anymore, it's just Application

**Comment by calcinai** [comment]
For others' benefit [https://github.com/calcinai/xero-php#migration-from-1xoauth-1a](https://github.com/calcinai/xero-php#migration-from-1xoauth-1a)
