### ISSUE TITLE
\Calcinai\OAuth2\Client\Provider\Xero class not found

### ISSUE THREAD

**Issue by gvanto** [calcinai/xero-php#726]
Trying to run code according to README:
![image](https://user-images.githubusercontent.com/8372918/79955131-a1971400-847e-11ea-96e8-289887ff3a19.png)

But says cannot find the above class ... have done composer require of the package.

Trying to get authorization url in order to get access token (in order to do rest of queries).

Thanks for any help
G

**Comment by gvanto** [comment]
Is there another package that Calcinai\Oauth2 should be referencing from composer.json? The only references to getAuthorizationUrl (in this repo) are in demo.php and the README:
https://github.com/calcinai/xero-php/search?q=getAuthorizationUrl&unscoped_q=getAuthorizationUrl

**Comment by gvanto** [comment]
composer require is pulling repos which is different than what is current latest master on here ( ?! )

**Comment by calcinai** [comment]
>composer require is pulling repos which is different than what is current latest master on here

Can you please elaborate

**Comment by gvanto** [comment]
@calcinai nevermind was a bizarre issue we sorted out. Getting right repos + code now
