### ISSUE TITLE
Which tenant id to use?

### ISSUE THREAD

**Issue by gvanto** [calcinai/xero-php#728]
When running the getTenants(), getting 2 id's for each returned object - which one to use when instantiating Application ('id' or 'tenantId' ? )

![image](https://user-images.githubusercontent.com/8372918/80075269-ba6cfb80-854a-11ea-8432-68e7dbcf2fd1.png)

**Comment by gvanto** [comment]
tenantId

**Comment by rodjsta** [comment]
id is the connection id and tenantId is the Xero Company you're connected to.

You will need tenantId when making calls. You will need id when you want to disconnect.
