### ISSUE TITLE
How to get token which lasts more than 30min?

### ISSUE THREAD

**Issue by gvanto** [calcinai/xero-php#729]
Hello, I'm using the oAuth2 flow outlined in README. It all works, except that the token is only valid for 30minutes. Also, getting a refresh token every 30min is quite annoying/counterproductive. Is there a way to get a longer lifetime token?

**Comment by Healyhatman** [comment]
You don't need to refresh every 30 minutes. You only need to refresh it if it's expired when you want to use it - so if it's 2 weeks old, refresh it and you're good to use for another 30 minutes. They last 60 days without being refreshed before you need to reauthorise from the beginning. 

Just make sure you request the offline access scope. The 30 minute token lifetime is a Xero thing, nothing to do with Calcinai.

**Comment by gvanto** [comment]
Thanks @Healyhatman 
> so if it's 2 weeks old, refresh it and you're good to use for another 30 minutes.
Doesn't this mean it expires every 30min? (in which case, for continued usage, it would need to be refreshed every 30min (worst case, if API is called a lot). 

I've requested new code (+token) with offline access and it didn't say "Access for 30min" in the web prompt (which I take to mean it will last for longer, but how long?)  

Not sure I entirely understand 'offline access' - we still need to be online to access the API :)

Ie what setup to use in Production - offline access so as to have longer token life?

**Comment by Healyhatman** [comment]
I you don't request offline access scope, then once the 30 minutes runs out without a refresh, the client has to log back in again. If you request the offline access scope then once the 30 minutes runs out you have 60 days to refresh the token before the client has to log in again.

**Comment by gvanto** [comment]
OK so ideally we want the code to handle this automatically (refresh the token if expired). But the League\OAuth2\Client\Token\AccessToken (needed to create refresh token) would need to be reconstructed using the access_token (string), expiryDate, etc - is this how it's typically done do you know perhaps?

I have a server-to-server case whereby ideally there's minimal (zero) user interaction required (for refreshing oauth tokens)

**Comment by Healyhatman** [comment]
Store the expiry in the database. When you go to use the token, check if it's expired or about to and refresh it. No user interaction necessary.

**Comment by gvanto** [comment]
Don't we need to also store the refresh token? (to be used below instead of "$token->getRefreshToken()"

The refresh of the token requires a refresh token to be passed (and we don't have access to a $token object at this point, only to a access_token (string)):

```
$newToken = $provider->getAccessToken(‘refresh_token’, [
‘grant_type’ => ‘refresh_token’,
‘refresh_token’ => $token->getRefreshToken()
]);
```

**Comment by rodjsta** [comment]
@gvanto 
I am storing all of the following:
![image](https://user-images.githubusercontent.com/32949856/80204507-57738580-866c-11ea-90f1-6dd1476f9e15.png)

My .env file has the ClientId, ClientSecret and RedirectUri.

My Laravel application has a XeroController with an index(), auth() and refresh() method. In the very first instance, the user will want to create a connection between my application and their Xero account. So they will hit my XeroController@index route.

Here I check the DB to see if there are any tokens at all for this particular client. If not I redirect them to the auth() method. If there are tokens stored, I check to see if the access_token_expiry is within the last 30 minutes and if it is, that's great and I will display the page which says they're connected. If not, I will redirect to the refresh() method to get a new access token.

On any other methods throughout my application where I need to call the Xero API, I essentially do the same checks (are there tokens and are they valid). Depending on that answer I will redirect to the appropriate method or carry on with the rest of the method.

**Comment by GavG** [comment]
> Don't we need to also store the refresh token? (to be used below instead of "$token->getRefreshToken()"
> 
> The refresh of the token requires a refresh token to be passed (and we don't have access to a $token object at this point, only to a access_token (string)):
> 
> ```
> $newToken = $provider->getAccessToken(‘refresh_token’, [
> ‘grant_type’ => ‘refresh_token’,
> ‘refresh_token’ => $token->getRefreshToken()
> ]);
> ```

I believe the refresh token is generated on the fly based of the client id and secret when getRefreshToken() is called.

They way I have approached using tokens in background jobs is to store a serialized copy of the access token object:
```
       $accessToken = $provider->getAccessToken('authorization_code', [
            'code' => $auth_code,
        ]);

        serialize($accessToken); //Store this
```
Then when it's needed I deserialize it and check if it's valid, if not refresh it:

```
        $api_token = unserialize($token_from_storage);

        if ($api_token->hasExpired()) {
            $api_token = $provider->getAccessToken('refresh_token', [
                'refresh_token' => $api_token->getRefreshToken()
            ]);

           serialize($api_token); //Store this
```

**Comment by gvanto** [comment]
How long is 'code' (auth code) valid for **before** first use? 

Currently (in dev not production live system yet) I putting this in config, but it will only be cached on first Xero application load, if it's only valid for 30min it would mean deployment to live (AND first Xero application load) would have to happen within 30min (not always feasible with deployment pipelines, etc)

**Comment by GavG** [comment]
According to the docs the auth code is valid for 5mins. 

You can make more requests to get fresh auth codes as needed:

https://developer.xero.com/documentation/oauth2/auth-flow

As such I wouldn't recommend storing it under source control.

**Comment by rodjsta** [comment]
Do not put the tokens in your config file. Config file should only have the client secret / Id and uri for your application that was set up in Xero developer console. 

Also when you say ‘code’ are you referring to the temporary authorisation code that is per of the first stage of the OAuth2 process? That code is temporary and will only last 5 minutes.

**Comment by gvanto** [comment]
Thanks for the input @rodjsta @GavG @Healyhatman 
Looks like a web-flow for auth is unavoidable with this so we've implemented that, works now.
