### ISSUE TITLE
Any chance of another maintenance release?

### ISSUE THREAD

**Issue by judgej** [calcinai/xero-php#73]
There are a tonne of great changes in this repository since the last release on 28 June. Any change another release can be made, so we can take advantage of them without running against the *bleeding edge*? It's the little things like much `__isset()` magic methods and fluent chaining support that are not in that last release, but are incredibly useful.

Thanks! (fingers crossed)

**Comment by judgej** [comment]
Out of curiosity, is the "collections" branch there to replace arrays of object with collections, offering a bit more functionality than simple arrays?

**Comment by calcinai** [comment]
Yeah, there were a few reasons for it.  I was going to hold off until the new major release but the #63 really needed something like it.  I actually merged the collections branch into master a while ago, was just waiting on some confirmation from others that it was ok before making a release!
