### ISSUE TITLE
Rate Limit Exceeded

### ISSUE THREAD

**Issue by walkingtrackmedia** [calcinai/xero-php#731]
Rate Limit Exceed has an error code of 429 but this isn't being picked up by the Response class.

I think some code needs updating to catch this error such as the following

const STATUS_RATE_LIMIT_EXCEEDED = 503;
to
const STATUS_RATE_LIMIT_EXCEEDED = 429;

/calcinai/xero-php/src/XeroPHP/Remote/Response.php

**Comment by calcinai** [comment]
Can you find a reference in the docs that confirms this?  i.e. there will **never** be a 503 returned in this case.

**Comment by walkingtrackmedia** [comment]
This actually happened when we were syncing invoices. We found our php script was just returning a blank white screen.

So we debugged the file and found xero was returning a 429 error and it wasn't being caught.

I've done a search and found a link which confirms the 429 error is returned for oauth2 https://developer.xero.com/documentation/oauth2/limits
