### ISSUE TITLE
Caching of Account object

### ISSUE THREAD

**Issue by gvanto** [calcinai/xero-php#734]
For improved performance (avoiding unnecessary calls to API) I am trying to cache (Laravel's cache::remember) the account object once loaded but getting [serialization error](https://stackoverflow.com/questions/61439086/laravel-cacheremember-cannot-serialize-closure). Also shown here when trying to serialize Account object:

![image](https://user-images.githubusercontent.com/8372918/80379340-427e3880-889e-11ea-8639-090d532385fa.png)

![image](https://user-images.githubusercontent.com/8372918/80379944-157e5580-889f-11ea-9bbc-192028e276f1.png)

Anyone running into similar problems?

**Comment by Josh-G** [comment]
Models contain a reference to the Application which contain an instance of a Guzzle client, which itself has properties that contains closures.
PHPs `serialize` function is not able to serialize Closures: https://3v4l.org/1MIpd

A possibility would be calling `toStringArray` and `fromStringArray` when you store and retrieve a model.

**Comment by calcinai** [comment]
I think @Josh-G's is the best solution.  We could implement __sleep() and __wakeup() but would need to serialise running guzzle config etc and seems a bit messy...

**Comment by gvanto** [comment]
Thanks @Josh-G that works.
