### ISSUE TITLE
Update or delete a phone number or address on a Contact?

### ISSUE THREAD

**Issue by FrankEBailey** [calcinai/xero-php#736]
This is probably one of those obvious things that I'm somehow just looking past, but I'm trying to work out how to update or delete an existing phone number on a Contact. 

From what I can see both in the example app and the Xero API documentation, it's easy to add one or more phone numbers to a Contact, and that works fine. However, it's not clear how to go about updating a particular phone type (eg. Mobile) or deleting it entirely.

Is there something like a deletePhone() method, or a way to clear the info so as to have the same effect as deleting that phone number from the Contact?

**Comment by calcinai** [comment]
@FrankEBailey I'd love to say I knew.  Have you tried anything using the API previewer? (like sending the complete list back, updated)

**Comment by FrankEBailey** [comment]
Hi Michael, some testing in the Previewer has shown that to delete a phone number, you have to pass the PhoneType and all (previously populated) details as empty fields:

        <Phone>
          <PhoneType>DEFAULT</PhoneType>
          <PhoneNumber></PhoneNumber>
        </Phone>          
      </Phones>

So according to my understanding of the Xero-PHP mechanism for updating a Contact, to delete a phone number needs something like this:

	$phone = new XeroPHP\Models\Accounting\Phone();
	$phone
		->setPhoneType('DEFAULT')
		->setPhoneNumber('');
	$contact->addPhone($phone);

My one concern was that, if Xero's API allowed more than one of each PhoneType, trying to overwrite, for example, the DEFAULT phone number might just add a new one. Some additional testing shows that this doesn't happen, which is a relief.

**Comment by FrankEBailey** [comment]
Just an afterthought here, would there be any support, do you think, for creating a deletePhone($phoneType) and deleteAddress($addressType) method which could provide a shortcut for passing in all the possible fields with empty values, thereby effectively deleting that phone or address type from the Contact?
