### ISSUE TITLE
TenantId to Organisation Mapping

### ISSUE THREAD

**Issue by gvanto** [calcinai/xero-php#737]
Looking at [docs](https://developer.xero.com/documentation/oauth2/auth-flow), can't quite figure out following:

When getting tenants using $provider->getTenants(token), 
Do all tenants have access to all organisations authorised by the app?
Or is it one tenant per organisation? and if so, how to know which tenant maps to which org? (can only see string IDs and type='ORGANISATION' on the tenant object, not org name)

**Comment by gvanto** [comment]
Ok have done a test: one tenant maps to one org, but how to do mapping programmatically? (or best to store tenantId in config?)

**Comment by calcinai** [comment]
From memory `id` is actually the `OrganizationID`, you can then load the model and save the relevant one.

**Comment by gvanto** [comment]
OK thanks @calcinai We're going to use one app per company for now, as there's potential for issues with wrong tenant.
