### ISSUE TITLE
The save() method doesn't appear to throw an exception when status code 429 (too many requests) is returned

### ISSUE THREAD

**Issue by scottjs** [calcinai/xero-php#739]
Hi,

I'm trying to batch insert some invoices and I'm finding that the save() method doesn't throw an exception when 429 response is returned:

```
try {
    $response = $xeroInvoice->save();
} catch (NotFoundException $exception) {
    Log::info('we dont get here');
} catch (RateLimitExceededException $exception) {
    Log::info('or here');
} catch (\Exception $e) {
    Log::info('or even here');
}

// If I've hit a request limit, this will return 429.
Log::info($response->getStatus());
```

For me to handle this properly I'm having to check for a 200:

```
if ($response->getStatus() !== 200) {
  // terminate
}

// continue with next steps
```

Am I missing something, is there a better way? 

Thanks,
Scott.

**Comment by calcinai** [comment]
@scottjs are you using OAuth2? I _think_ it still throws 503s for OAuth1, butt hat should still be being caught in your code.  Do you see 429 in `$response->getStatus()`?

**Comment by scottjs** [comment]
Hey :) Thanks for the reply!

I am using OAuth2 and I do eventually see a 429 from `$response->getStatus()` after I've hit the API too many times. 

I'm wondering if there should a check for this status code in the `parse()` method in `Response.php`?

**Comment by scottjs** [comment]
Hey :) 

I've just noticed this PR: https://github.com/calcinai/xero-php/pull/732

This is exactly what I need to solve my problem as it's causing me quite a few issues, mainly because I'm creating a contact in the system if it doesn't already exist. 

Problem is that the query to check if a contact already exists may return `null` (for not found) or `null` if the API returns 429.

Without it throwing an exception my code will then think that the contact doesn't exist and tries to create it, so there's a chance it will create duplicate contacts. 

When do you think you'll be able to release the code in the approve PR?

**Comment by scottjs** [comment]
Fixed by https://github.com/calcinai/xero-php/pull/732 and https://github.com/calcinai/xero-php/pull/740
