### ISSUE TITLE
Contact BatchPayments and Balances are not parsed

### ISSUE THREAD

**Issue by judgej** [calcinai/xero-php#74]
Contact `BatchPayments` and the `Balances` are coming across as empty strings instead of arrays or value objects.

In my getByGuid call:

    "BatchPayments" => ""
    "Balances" => ""

In the Xero online API query tool:

      <BatchPayments>
        <BankAccountNumber>12-34-56 12345678</BankAccountNumber>
        <BankAccountName>NatWest</BankAccountName>
        <Details>Banky</Details>
      </BatchPayments>
      <Balances>
        <AccountsReceivable>
          <Outstanding>180.70</Outstanding>
          <Overdue>180.70</Overdue>
        </AccountsReceivable>
        <AccountsPayable>
          <Outstanding>153.49</Outstanding>
          <Overdue>153.49</Overdue>
        </AccountsPayable>
      </Balances>

The BatchPayments is set as a string here:

https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Models/Accounting/Contact.php#L320

Just so I'm not going about this wrong, if I wanted to create a new value object for this, would I do that manually, or would it need to be set in your metadata and used to generate a new set of models?

**Comment by calcinai** [comment]
Stink. They're not defined in the docs, so will have to make a manual definition (like Attachments), I think.  I'll have a crack at it tonight.

**Comment by judgej** [comment]
I've just done one for BatchPayments (copied Currency) and it works fine for me. Not sure how to ensure it is read-only, so probably needs some tweaks. Want a PR?

**Comment by judgej** [comment]
[Here is a gist of the BatchPayments object I'm using](https://gist.github.com/judgej/3c4694fbf7ead9466526) - just too late here right now to be doing a PR tonight. Hopefully it is helpful if you are adding this, or I can do a PR tomorrow.

**Comment by judgej** [comment]
Started PR for this.

**Comment by judgej** [comment]
Not sure where we left this. Did you want the `BatchPayments` object as a PR, or did you have another way to take this forward?

**Comment by judgej** [comment]
Current state in comments on this commit:

https://github.com/academe/xero-php/commit/4acacb20c79e7ad42100f41468dd399dbda31084#diff-167c4d5f6610234f268d340ab70c9e4f

**Comment by judgej** [comment]
Since I updated to the latest code, I'm finding that every single object on a contact is coming out as a 'XeroPHP\Remote\Collection' object. Even the BatchPayments with my customer class is being supplied as a Collection. And they are all empty Collections - ContactPersons, BankAccountDetails, Addresses - all of them.

Has something fundamentally changed in the way the response from Xero is parsed?

**Comment by calcinai** [comment]
Not as far as I know. I'm going to put some time aside this afternoon to go through all of these issues.

**Comment by calcinai** [comment]
I've made a little update in #98, does that look ok?  For unknown properties, they're returned as an object at the list dimension and assoc arrays from then on.

My test code is using like ```$contact->Balances->AccountsReceivable['Outstanding']```

Alternatively, it can be done all the way down to the nodes, but I'm not sure that's actually desirable.

**Comment by judgej** [comment]
Hmm, not seeing BatchPayments with that latest update. It is just coming across as an empty string from Xero, and an empty array when a contact is converted to an array. Balances are the same.

**Comment by judgej** [comment]
Apart from the base objects that have their own endpoints for managing, are there any other instances of structured data from Xero being available through this package?

I've switched back to my fork with the PaymentBatches object defined, as that works for me.

https://github.com/academe/xero-php

**Comment by calcinai** [comment]
I had a play around with the contacts and found that some or all or none of the Balances and BatchPayments are returned from Xero depending on if they've actually got invoices etc owing. 

The string type is just a fallback in the case that there is no real passable type - it's not actually used in the parsing out from Xero for casting etc. 

If the current version isn't working, I guess the best way forward is to define a basic model for each, and manually specify that it uses those types. How consistent do you think the fields from Xero are...?

**Comment by judgej** [comment]
The three batch payments fields are listed in the xero docs, and thry map 1:1 to fields on the edit contact screen. Xero don't define them though, but I'm fairly confident they are here to stay.

The balances are in the same boat, but I don't use them, so have not coded a patch for it.

**Comment by judgej** [comment]
I've written the class assuming all three fields are optional.

**Comment by calcinai** [comment]
I assume you were using the dev-issue-74 branch?

**Comment by judgej** [comment]
The master branch here: https://github.com/academe/xero-php I've bypassed the generator for my project, and would not know how to define this class so the generator can work around it.

**Comment by calcinai** [comment]
Sorry - I was meaning for the updates to the parsing that I made.

> Hmm, not seeing BatchPayments with that latest update.

**Comment by matthewjumpsoffbuildings** [comment]
@calcinai Im still having this issue - `Balances` appears to be an empty string when using `$contact-> toStringArray()` even if the Contact should have a value for that field

**Comment by calcinai** [comment]
@judgej what did  you end up doing here?
