### ISSUE TITLE
OAuth 1.0 -> 2.0 Migration

### ISSUE THREAD

**Issue by leereichardt** [calcinai/xero-php#747]
Have there been any handling of the migration endpoint into this library or should I just roll my own?

**Comment by calcinai** [comment]
@leereichardt I didn't know there was one!

**Comment by leereichardt** [comment]
Yeah. Unfortunately, it's part of the OAuth1.0 Endpoint though so it probably won't work now that your library is updated to 2.0! So unless there was a patch for a OAuth1.0 branch might be a bit hard?

https://developer.xero.com/documentation/oauth2/migrate

**Comment by Josh-G** [comment]
@leereichardt would it be easier if a patch was available for the v2 library? Then you can migrate tokens just in time, then immediately use them with the v2 library?

Only issue I see with a patch for v1 would be that you can't use the token after migrating it. You would need to migrate all tokens, then deploy a new version of your app using the v2 library? 

Let me know what you think about that, and I'd be happy to propose a solution. If calcinai doesn't want to merge migration functionality into v2, I think I can release a separate package just to handle migrations alongside v2.

**Comment by leereichardt** [comment]
Hi @Josh-G, it would be easier, but that would involve putting the OAuth1.0 code back into the repo as it goes through that whole flow, with the certs and all. This could possibly be a separate package to handle migrations. I took Xero's 5yr old code samples/library and altered it a little bit for our purpose to get the migration working. I took this library (https://github.com/XeroAPI/XeroOAuth-PHP). Was super easy to slot everything in and get it working. The only thing in that one is that they had a rule to strip out `*secret` keys from the request, so I had to remove this to allow the client_secret to be passed through during the migration

**Comment by leereichardt** [comment]
Just going to close this for now as unsure if this is something that should be done in this library or a separate package.

**Comment by jodamo5** [comment]
> The only thing in that one is that they had a rule to strip out `*secret` keys from the request, so I had to remove this to allow the client_secret to be passed through during the migration

Yes, we found the same thing ... it was stripping any parameter name with "secret" in it, so we were constantly getting the error message that the client_secret was required!

For others, the file to adjust in that library is OAuthSimple.php line 392 where there is a preg_match looking for any parameter name that has "secret" in it.

**Comment by tiaguinhor** [comment]
I also didn't find anything related to `migrate` and `revocation` endpoint in this library, just wondering how it can be done using it. Any clue? Thanks.

**Comment by latchaprabu** [comment]
> Hi @Josh-G, it would be easier, but that would involve putting the OAuth1.0 code back into the repo as it goes through that whole flow, with the certs and all. This could possibly be a separate package to handle migrations. I took Xero's 5yr old code samples/library and altered it a little bit for our purpose to get the migration working. I took this library (https://github.com/XeroAPI/XeroOAuth-PHP). Was super easy to slot everything in and get it working. The only thing in that one is that they had a rule to strip out `*secret` keys from the request, so I had to remove this to allow the client_secret to be passed through during the migration

Hi, can you please help me on this ?

Error: {"errors":["'client_id' must be supplied","'client_secret' must be supplied","'scope' must be supplied","You can only migrate an OAuth1.0a connection to an OAuth2.0 connection for the currently authorised app"]} 

when I comment below code :
/*
if($paramName=='xml'){
               if($filter=="true")
                   continue;
               }
            if (preg_match('/\w+_secret/',$paramName))
                continue;
                
                */
     got error "Failed to validate signature". Can you please help me on this ? Where to change code to migrate existing oauth1.0 tokens to oauth2.0           
i am using https://github.com/XeroAPI/XeroOAuth-PHP for oauth token migration.
