### ISSUE TITLE
"Object" is globally defined so cannot be used as namespace

### ISSUE THREAD

**Issue by judgej** [calcinai/xero-php#75]
> PHP Fatal error:  Cannot use XeroPHP\Models\Files\Object as Object because the name is already in use in /.../vendor/calcinai/xero-php/src/XeroPHP/Remote/Query.php on line 7

The line is:

    use XeroPHP\Models\Files\Object;

This is a bit of a mystery. If I run this statement before running a query (a *Payment* load with some where-conditions):

    echo \XeroPHP\Models\Accounting\Payment::PAYMENT_TYPE_ACCRECPAYMENT;

Then the above error happens when the query is autoloaded. If I run that echo statement *after* running the query, I don't see this error. This feels like some vague PHP namespace "feature", and I guess comes from loading the classes in a different order.

**Comment by calcinai** [comment]
Yep - Looks like there is a collision there.  Might need to use the NS one level higher internally in the models to avoid this.

**Comment by judgej** [comment]
Here we go, this causes the exception:

    echo class_exists('\XeroPHP\Models\Accounting\Payment');
    echo class_exists('\XeroPHP\Remote\Query');

and this does not:

    echo class_exists('\XeroPHP\Remote\Query');
    echo class_exists('\XeroPHP\Models\Accounting\Payment');

**Comment by judgej** [comment]
Ah, I see, it's because `Query` is already and object in the `\XeroPHP\Remote` namespace. I think I understand how the `use` statement works better now - it creates an alias in the namespace of the file that it is in. But it can only create that alias if there is not already a real class in that namespace.

But it depends on what order it is done in - you can load a real class over an alias, but can't create an alias over a real (loaded) class. TIL :-)

**Comment by judgej** [comment]
Or remote the use statement completely. I don't think `Object` is even used in that file.
