### ISSUE TITLE
Getting authEventId from multiple tenants

### ISSUE THREAD

**Issue by davebashford** [calcinai/xero-php#751]
My app has the potential to have multiple tenants so I need to be able to correctly associate the tenant with the account that was just authorised. Per Xero's documentation I can match the `authentication_event_id` in the JWT with the `authEventId` on the tenant. However `getTenants($token)` doesn't return an `authEventId`.

If I add in `$data['authEventId']` to the `Calcinai\OAuth2\Client\XeroTenant` I can correctly retrieve the id for matching. Am I missing something or should that be added in?

Thanks

**Comment by niko5** [comment]
It would be useful to also at least have 'tenantType' 'tenantName' in the Calcinai\OAuth2\Client\XeroTenant - this then gives you a quick way of storing tenantId's with your Xero Organisation name.

**Comment by calcinai** [comment]
@davebashford @niko5 If you get a chance, feel free to add these properties in [this repo](https://github.com/calcinai/oauth2-xero) and I'll release a version for it.  When I first made that other repo I think I had all the properties that existed at the time.
