### ISSUE TITLE
Not sure what to do after getting the initial token?

### ISSUE THREAD

**Issue by FrankEBailey** [calcinai/xero-php#752]
Hi all, I've gotten to the point of getting the initial token after manually authorizing one of my tenants via the Xero auth screen, and getting the user info and tenant info as per the example on the readme. However I'm not sure how to proceed after that.

What do I do then to get a refresh token? I know I'm meant to use the first token in some way but the below doesn't work, giving an 'invalid grant' error:

	// Try to get an access token (using the authorization code grant)
	$token = $provider->getAccessToken('authorization_code', [
		'code' => $_GET['code']
	]);

	$newAccessToken = $provider->getAccessToken('refresh_token', [
	    'refresh_token' => $token->getRefreshToken()
	]);

Any help will be much appreciated!!

**Comment by davebashford** [comment]
After you get the `$token` you will want to get the access token, refresh token and tenant ID. 

```
$token = $provider->getAccessToken('authorization_code', [
	'code' => $_GET['code']
]);
$accessToken = $token->getToken();
$refreshToken = $token->getRefreshToken();
$tenants = $provider->getTenants($token);
```
With the tenant ID and access token you can make requests to Xero:

```
$application = new \XeroPHP\Application($accessToken, $tenants[0]->tenantId);
```

You then need to get a new access token after every 30 mins with this:

```
$newAccessToken = $provider->getAccessToken('refresh_token', [
    'refresh_token' => $refreshToken
]);
```
Hopefully that helps

**Comment by Healyhatman** [comment]
Point(s) of order:
You can only refresh the token if you've gotten the offline_access scope
You don't need to refresh it every 30 minutes, you need to refresh it AFTER 30 minutes. So you can leave it for 20 days, and then refresh it. That point of confusion caught out another dev thinking he needed a cron job to keep refreshing it constantly.

**Comment by FrankEBailey** [comment]
Ah that all makes a lot more sense, thanks for the clarifications Dave and Healy!

So if my flow is as follows it should be fine, right?

```
**Initial Auth Script:**
- Do manual auth as above
- store access token and refresh token with expiry date in database

**API Call Script:**
- Load access and refresh token info from db
- Check whether the token is still live based on the stored expiry
- If still live, use access token without refreshing
- If expired, issue a refresh request to the Provider to liven up the access token
- Make API call with refreshed access token and relevant tenant ID
```

**Comment by davebashford** [comment]
Yes, looks good to me. That's how I do it

**Comment by FrankEBailey** [comment]
Fantastic! Thanks guys!
