### ISSUE TITLE
Unable to refresh token

### ISSUE THREAD

**Issue by hassanuos** [calcinai/xero-php#754]
I am using this package for Xero implementation but I am unable to refresh token. Below is my source code.

      function actionRedirectXero(){

        $session = Yii::$app->session;
        $request = Yii::$app->request;

        if (empty($session->get('access_token'))){
            $token = $this->provider->getAccessToken('authorization_code', [
                'code' => $request->get('code')
            ]);
            $session->set('access_token', $token);
        }

        $sessionToken = $session->get('access_token');
        $identity = $this->provider->getResourceOwner($sessionToken);

        $newAccessToken = $this->provider->getAccessToken('refresh_token', [
                'refresh_token' => $sessionToken->getToken()
        ]);
       dd($newAccessToken);
     }
            
Here is the error that I am facing every time.

Exception 'Calcinai\OAuth2\Client\Provider\Exception\XeroProviderException' with message 'invalid_grant' 

in D:\Bitnami\apps\gathern\htdocs\vendor\calcinai\oauth2-xero\src\Provider\Xero.php:132

Stack trace:
#0 D:\Bitnami\apps\gathern\htdocs\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(628): Calcinai\OAuth2\Client\Provider\Xero->checkResponse(Object(GuzzleHttp\Psr7\Response), Array)
#1 D:\Bitnami\apps\gathern\htdocs\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request))
#2 D:\Bitnami\apps\gathern\htdocs\backend\modules\xero\controllers\DefaultController.php(152): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array)
#3 [internal function]: backend\modules\xero\controllers\DefaultController->actionRedirectXero()
#4 D:\Bitnami\apps\gathern\htdocs\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#5 D:\Bitnami\apps\gathern\htdocs\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#6 D:\Bitnami\apps\gathern\htdocs\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('redirect-xero', Array)
#7 D:\Bitnami\apps\gathern\htdocs\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('xero/default/re...', Array)
#8 D:\Bitnami\apps\gathern\htdocs\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#9 D:\Bitnami\apps\gathern\htdocs\backend\web\index.php(23): yii\base\Application->run()
#10 {main}

**Comment by mikejatech** [comment]
@hassanuos You need to add the grant type so the $newAccessToken should look like this;

`		$newAccessToken = $provider->getAccessToken('refresh_token', [
			'grant_type' => 'refresh_token',
			'refresh_token' => $token->getRefreshToken()
		]);`

https://github.com/calcinai/xero-php/issues/692

Hope this helps.

**Comment by hassanuos** [comment]
Thanks you @mikejatech actually was missing `offline_acces` in the scope. Now its fixed.

**Comment by amalranganath** [comment]
Hi @hassanuos 
I'm facing the same problem and I've added offline_acces in the scope, but still getting "invalid_grant" error. 
If you could please help me

**Comment by hassanuos** [comment]
@amalranganath can you send me the complete error description here.

**Comment by amalranganath** [comment]
Yes here it's, (I've implemented it to store the token in the db settings table)

Calcinai\OAuth2\Client\Provider\Exception\XeroProviderException
invalid_grant

Stack trace
1. in /home/gcfilter/test4/vendor/calcinai/oauth2-xero/src/Provider/Xero.phpat line 132
2. in /home/gcfilter/test4/vendor/league/oauth2-client/src/Provider/AbstractProvider.php at line 628– Calcinai\OAuth2\Client\Provider\Xero::checkResponse(GuzzleHttp\Psr7\Response, ['error' => 'invalid_grant'])
3. in /home/gcfilter/test4/vendor/league/oauth2-client/src/Provider/AbstractProvider.php at line 537– League\OAuth2\Client\Provider\AbstractProvider::getParsedResponse(GuzzleHttp\Psr7\Request)
4. in /home/gcfilter/test4/controllers/SiteController.php at line 91– League\OAuth2\Client\Provider\AbstractProvider::getAccessToken('refresh_token', ['refresh_token' => 'eyJhbGciOiJSUzI1NiIsImtpZCI6IjFD...'])
85868788899091929394959697                        
public function actionRefresh() {
        $provider = new \Calcinai\OAuth2\Client\Provider\Xero( Yii::$app->params['xero']['oauth2'] );
        $settings = Settings::findOne(1);
        $newAccessToken = $provider->getAccessToken('refresh_token', [
              'refresh_token' => $settings->token
        ]);
        $settings->token = $newAccessToken;
        $settings->save();
        $xero = new \XeroPHP\Application($settings->token, $settings->tenantId);
        $contacts = $xero->load(Contact::class)->execute();
                }
5. app\controllers\SiteController::actionRefresh()
6. in /home/gcfilter/test4/vendor/yiisoft/yii2/base/InlineAction.php at line 57– call_user_func_array([app\controllers\SiteController, 'actionRefresh'], [])
7. in /home/gcfilter/test4/vendor/yiisoft/yii2/base/Controller.php at line 157– yii\base\InlineAction::runWithParams(['r' => 'site/refresh'])
8. in /home/gcfilter/test4/vendor/yiisoft/yii2/base/Module.php at line 528– yii\base\Controller::runAction('refresh', ['r' => 'site/refresh'])
9. in /home/gcfilter/test4/vendor/yiisoft/yii2/web/Application.php at line 103– yii\base\Module::runAction('site/refresh', ['r' => 'site/refresh'])
10. in /home/gcfilter/test4/vendor/yiisoft/yii2/base/Application.php at line 386– yii\web\Application::handleRequest(yii\web\Request)
11. in /home/gcfilter/test4/web/index.php at line 12– yii\base\Application::run()


Thanks a lot for your attention.

**Comment by hassanuos** [comment]
@amalranganath here is the successful and running code. That is working fine on production. I hope this will help you.

`function get_xero_config()
{
    if (\Yii::$app instanceof \yii\console\Application) {
        $uid = 51100;
    } else {
        $uid = Yii::$app->user->identity->id;
    }

    $configs = XeroConfigs::find()->where(['created_by' => $uid])->one();
    $provider = new Xero(get_xero_keys());

    if ($configs) {
        if ($configs->expiry < time()) {

            $newAccessToken = $provider->getAccessToken('refresh_token', [
                'grant_type' => 'refresh_token',
                'refresh_token' => $configs->refresh_token
            ]);

            $tenants = $provider->getTenants($newAccessToken);
            $xeroConf = XeroConfigs::findOne($configs->id);
            $xeroConf->access_token = $newAccessToken;
            $xeroConf->refresh_token = $newAccessToken->getRefreshToken();
            $xeroConf->expiry = $newAccessToken->getExpires();
            $xeroConf->tenant_id = isset($tenants[0]) ? $tenants[0]->id : 0;;
            $xeroConf->token_object = serialize($newAccessToken);;
            $xeroConf->updated_at = Carbon::now()->toDateTimeString();
            $xeroConf->created_by = $uid;
            $xeroConf->save();

            $configs = XeroConfigs::find()->where(['created_by' => $uid])->one();
        }
    }
    return $configs;
}`

**Comment by amalranganath** [comment]
@hassanuos Great! Thank you so much for your help.
I didn't know about getAccessToken() returned object could get the refresh token.
