### ISSUE TITLE
Models\Accounting\Attachment must implement abstract method isPageable()

### ISSUE THREAD

**Issue by drawmyattention** [calcinai/xero-php#76]
The class ```XeroPHP\Models\Accounting\Attachment``` extends ```Object``` and therefore must implement the abstract method ```isPageable()```.

Adding:

    static function isPageable()
    {
        return false;
    }

should fix this issue.

**Comment by calcinai** [comment]
Closed by #78

**Comment by drawmyattention** [comment]
Can you release an update with this patch included? As it stands, I can't do a composer update because my autoloader throws an exception because of the missing method implementation.

**Comment by calcinai** [comment]
Sorry - done!
