### ISSUE TITLE
Remote\Query does not use the resource id endpoint

### ISSUE THREAD

**Issue by StoyanPenev** [calcinai/xero-php#771]
This affets all Remote\Models, the Remote\Query cannot fetch resources using their id endpoint as described  [here](https://developer.xero.com/documentation/api/requests-and-responses#get-individual)
For some resources (Prepayment for example) GUID is not working so we have to query all Prepayments of contact and then foreach compare the PrepaymentID matches to retrieve the correct one.
When querying with GUID if page is not specified the resource has missing items in the payload, for the Invoice its missing LineItems (displays them as Excluded instead).
Modifying the Remote\Query with the following snippet solves the issue
```php
public function findById($id) {
    $this->findById = $id;
}
//and later on when executing
public function execute()
    {
        /**
         * @var ObjectInterface
         */
        $from_class = $this->from_class;
        $endpoint = $from_class::getResourceURI();
        if ($this->findById) {
            $endpoint .= '/' . $this->findById;
        }
      
        $url = new URL(
            $this->app,
            $endpoint,
            $from_class::getAPIStem()
        );
//.... rest of the code
```
This is not ideal as it will fail with BadRequestException if filters are applied (but I hope you get the idea) so it should be reworked to direclty send the request (without applying filters) if findById is set or have another method similar to execute but without setting request parameters called findById($resourceId).

**Comment by calcinai** [comment]
@StoyanPenev Is there a reason you can't use the `->loadByGUID()` method, or am I missing something?

**Comment by StoyanPenev** [comment]
Sorry to bother, I must have missed that one, closing.
