### ISSUE TITLE
loadByGUIDS returning all records

### ISSUE THREAD

**Issue by Karl456** [calcinai/xero-php#775]
I am trying to load multiple records by their GUID, but when passing through two Payment ID's, the response returns all 61 records within the "Demo Company" account.

```
$payments = $xero->loadByGUIDs(Payment::class, 'fe1eb97c-81f3-4777-8f16-6185d71d197b,a8678d04-6752-4ec3-97cb-209a40018a76');

echo count($payments);
```

This echo's 61, when there should only be 2.

**Comment by Healyhatman** [comment]
Just making sure, but in your actual code are you doing loadByGUIDs ? Because you typed GUID.

**Comment by Karl456** [comment]
Yes, apologies I am actually calling loadByGUIDS, not loadByGUID.

**Comment by Healyhatman** [comment]
I had a look for you and only Invoices and Contacts can retrieve using a list of IDs

**Comment by Healyhatman** [comment]
@calcinai I reckon you can close this one, as per my previous comment

**Comment by calcinai** [comment]
👍
