### ISSUE TITLE
Disconnect() & AccessTokenInterface

### ISSUE THREAD

**Issue by UniqueeeeeeeeeeeeeeeeeeUsername** [calcinai/xero-php#777]
Hey, so at the end of your demo.php, you have the following line:
`//$provider->disconnect($token, $tenants[0]->id);`
I'm struggling to use it with our use case.

The disconnect() function requires an 'AccessTokenInterface' object type, but in our application we're serializing the token out to the DB, and when they're loading back in, they come back as an array object not a custom object.

- Fetching a refresh or new token just to pass it in, defeats the purpose of saving it to the database in the first place I feel.
- Using a plugin that could serialize and de-serialize items back into their original objects, (something I'm surprised PHP can't natively do) seems like overkill to me and isn't something we want to do for the application.

I don't have this problem when initializing a new \XeroPHP\Application, as it takes string data just fine. Any chance anyone could suggest a way forward from this problem? I am still rather new to PHP and could be missing something.

But also, why would disconnect() use $provider, requiring the token & tenant to be passed in again at all? When I've already created a XeroPHP\Application that has those things in it. Would be nicer to just end the object with a clean: `$xero_connection->disconnect();`

Thanks for reading.

**Comment by Healyhatman** [comment]
$provider->disconnect(
                    new AccessToken(['access_token' => $connection->access_token]),
                    $connection->connection_id);

In my case, $connection is the DB object with my connection deets in it.

**Comment by UniqueeeeeeeeeeeeeeeeeeUsername** [comment]
@Healyhatman Thankyou so much for your reply! It helped a lot.

My final line of code ended up being this for anyone else that is having trouble:
```
// Attempt do disconnect the tenant on Xero's end.
$this->_xero_oauth_object->disconnect( new \League\OAuth2\Client\Token\AccessToken(['access_token' => $this->_xero_access_token['access_token']]), $this->_xero_tenant[0]['id'] );
```
