### ISSUE TITLE
Using  serialize/unserialize to store the token is not working

### ISSUE THREAD

**Issue by matthewknill** [calcinai/xero-php#778]
I have had OAuth2 working fine for most of this year, however recently it seems that I'm now having the following errors after refreshing the token: "You are not permitted to access this resource"

The following is my code refresh the token:
```php
$xero_config = Parse::parseIniBetter("/home/admin/billing/pdf_generator.conf", true); // Need to change name
$provider = new Xero([
    'clientId' => $xero_config['xero']['clientId'],
    'clientSecret' => $xero_config['xero']['clientSecret'],
    'redirectUri' => $xero_config['xero']['redirectUri'],
]);

$new_token = $provider->getAccessToken('refresh_token', [
    'grant_type' => 'refresh_token',
    'refresh_token' => $token->getRefreshToken()
]);
$tenants = $provider->getTenants($new_token);

//The above is only required for the authorization process
//At this  point, you can be using your stored token and desired tenant-id to
//construct the XeroPHP application and make authenticated requests
if ($new_token->getToken() && $tenants[0]->tenantId) {
    $db->query("UPDATE privileges.users SET
            xero_token=".$db->sqlFix(base64_encode(serialize($token))).",
            xero_connection_id=".$db->sqlFix($tenants[0]->id).",
            xero_tenant_id=".$db->sqlFix($tenants[0]->tenantId)."
        WHERE email=".$db->sqlFix(PageRenderer::getUser()));
    if (!empty($db->error())) {
        print_error("Could not save token error: ".$db->error());
    } else {
        $application = new Application($new_token->getToken(), $tenants[0]->tenantId);
        $org = $application->load(Organisation::class)->execute();
        if ($org) {
            print_success("r/".$org[0]->Name);
        }
    }
}
```
I also do a very similar thing to the above in the initial Xero connection (i.e. serializing the token).

Following that, I can then use the access token with the following:
```php
$user_data = $pr_db->querySingleRowArray("SELECT * FROM privileges.users WHERE email=". $db->sqlFix($_SESSION["email"]));
$application = new Application($token->getToken(), $user_data['xero_tenant_id']);
$org = $application->load(Organisation::class)->execute();
if ($org) {
    echo $org[0]->Name;
}
```

The issue though is that the above only works for the initial connection (i.e. first 30 mins). After having to do a refresh though, the serialize/unserialize process does not work and I have to refresh the token every time.

Any help would be much appreciated...

**Comment by matthewknill** [comment]
Interestingly, I have noticed that that the access token is different after the "." in the unserialized token as it is for the same access token before it's serialized.

I understand I may just need to not serialize the token and rather store it in the `$_SESSION` variable instead.

**Comment by calcinai** [comment]
@matthewknill It's pretty hard to see what's going on there - you shouldn't need to serialise the token like that as it's all utf-8 anyway.  Have you tried just saving the strings in the database?

**Comment by matthewknill** [comment]
Yep storing the strings directly in the database worked.
Cheers
