### ISSUE TITLE
Updating SalesTrackingCategories on Contact 

### ISSUE THREAD

**Issue by alexhiggins** [calcinai/xero-php#781]
When I retrieve a contact I can see the following

```
"SalesTrackingCategories" => XeroPHP\Remote\Collection^ {#2670
    #_associated_objects: array:1 [
      "SalesTrackingCategories" => XeroPHP\Models\Accounting\Contact^ {#2677}
    ]
    flag::STD_PROP_LIST: false
    flag::ARRAY_AS_PROPS: false
    iteratorClass: "ArrayIterator"
    storage: array:1 [
      0 => XeroPHP\Models\Accounting\TrackingCategory^ {#2676
        #_data: array:7 [
          "TrackingCategoryID" => null
          "Name" => null
          "TrackingCategoryName" => "Department"
          "TrackingOptionName" => "someValue
          "Status" => null
          "Options" => null
          "Option" => null
        ]
        #_dirty: []
        #_associated_objects: array:1 [
          "SalesTrackingCategories" => XeroPHP\Models\Accounting\Contact^ {#2677}
        ]
        #_application: null
      }
    ]
  }
```
I'm wondering if there's a way to update 'TrackingOptionName'?

I've tried addSalesTrackingCategory assuming that if it found a SalesTrackingCategory with the same name it would update the value but I get the following 'Cannot have two SalesTrackingCategories with the same name'.

**Comment by calcinai** [comment]
@alexhiggins What happenes if you either modify the existing object, or clear and add a new one?

**Comment by alexhiggins** [comment]
@calcinai the value updates when overwriting or pushing up a new value.

I'm happy to PR something up for this, I am just not sure on the best way to approach this.
