### ISSUE TITLE
Unable to get AppliedAmount on CreditNotes, OverPayments, PrePayments

### ISSUE THREAD

**Issue by alok-shukla2510** [calcinai/xero-php#782]
Hi,

I want to fetch multiple credit notes on single invoice with different amount of each credit notes. I am not getting Applied Amount in the object. It provides only Total Amount. So could you please suggest how to fetch it?

**Comment by calcinai** [comment]
@alok-shukla2510 Some endpoints return limited information when fetched in bulk.  Can you confirm that the documentation/API supports this functionality?

**Comment by alok-shukla2510** [comment]
> @alok-shukla2510 Some endpoints return limited information when fetched in bulk. Can you confirm that the documentation/API supports this functionality?

Hi,

As per the following link, can we merge that pull request?

https://github.com/davidwindell/xero-php/commit/b54463f6830aeb9be7270e3f16281ccc5a831b26

**Comment by Healyhatman** [comment]
Looking at the documentation for credit notes at https://developer.xero.com/documentation/api/credit-notes it looks like it should but as part of the Allocations attached to the credit note.

**Comment by alok-shukla2510** [comment]
> Looking at the documentation for credit notes at https://developer.xero.com/documentation/api/credit-notes it looks like it should but as part of the Allocations attached to the credit note.

Yep. but even though using allocation also I am unable to get AppliedAmount in that object.

**Comment by calcinai** [comment]
@alok-shukla2510 done.

**Comment by alok-shukla2510** [comment]
@calcinai - Thanks for merge that request. But I have removed package & install again but the merge request is not reflected in the code. Could you please check once again?

**Comment by Healyhatman** [comment]
It won't be in the main branch until he makes a new release. You can either wait til then, ask nicely (if enough changes have been made to make it worth it), or switch to the dev branch.

**Comment by alok-shukla2510** [comment]
> It won't be in the main branch until he makes a new release. You can either wait til then, ask nicely (if enough changes have been made to make it worth it), or switch to the dev branch.

@Healyhatman - Okay, Thanks for the update.

**Comment by Healyhatman** [comment]
There you go, the legend updated it :D

**Comment by alok-shukla2510** [comment]
Okay. Great.!!! Closing issue.

Thanks @calcinai @Healyhatman
