### ISSUE TITLE
Invoice LineItemID being overwritten by Xero on save

### ISSUE THREAD

**Issue by rodjsta** [calcinai/xero-php#784]
Hi All,

I am (or was) creating a guid for each invoice line item using the setLineItemID() method. When saving, each line item was given a different LineItemID guid by Xero.

The docs do say that the LineItemID is "The Xero generated identifier for a LineItem", but I'm a little thrown off by the setter on the LineItem object.

I've since built a workaround on my end to save actual LineItemIDs (involving an additional call), but wondering if anybody has managed to set their own?

Cheers,
Rod.

**Comment by Healyhatman** [comment]
What are you trying to achieve exactly? You're not really supposed to set the ID of anything, unless you're trying to UPDATE a specific item.  You definitely shouldn't generate your own GUIDs.

**Comment by rodjsta** [comment]
Right, okay. So setting the ID is for when I need to update it. Got it! Thanks.
