### ISSUE TITLE
Get InvoiceID after creating invoice.

### ISSUE THREAD

**Issue by TG-NC** [calcinai/xero-php#799]
Is it possible to get multiple invoices searching for an array of possible invoice names (not invoice GUIDs) in one API call?
I am trying to reduce the number of API calls I am using to avoid the Xero OAuth2.0 API limits. I have a large number of invoices I need to retrieve to attach files to.

**Comment by calcinai** [comment]
Great question! To be honest, I’m not sure. Invoices behave slightly different to other entities as the number is also unique, is this what you mean by names?

**Comment by Healyhatman** [comment]
This question is confusing because the title has nothing to do with the actual question being asked
