### ISSUE TITLE
Batch saving of objects

### ISSUE THREAD

**Issue by calcinai** [calcinai/xero-php#8]
Update the ```Application::save()``` method to accept either an object or an array of objects.

Alternatively, make a ```saveBatch()``` method to handle it.

The method needs to asses each object, and determine which ones can be in the batch and which should be updated individually.

**Comment by paulsschwarz** [comment]
If I understand correctly, the batch must be homogenous. So you could create a batch of invoices or a batch of contacts, but not a mixed batch of invoices and contacts (at least not in a single API call). I think this is also your understanding.

As such, I think a `saveAll()` method that throws an exception if the array isn't homogenous would suffice. I fear it's too magical if it knows how to split your array of models into smaller batches and, as a result, fire off multiple API calls. KISS is my opinion here.

**Comment by calcinai** [comment]
Correct, the batch must be homogenous.

The reference to which ones need saving directly, in case you had an array of invoices, some existing, some new.  Do you think that's allowing too much?

**Comment by paulsschwarz** [comment]
Oh I see. Apologies for the misunderstanding.

On the one hand, if you mixed invoices to create and to update into the same batch, at worst you'd trigger two API calls.

My opinion is still leaning towards that approach being too magical. Especially since the result would be two distinct https calls.

Therefore I'd imagine something like `createAll()` and `updateAll()`. I also can't imagine many use cases where you'd create a batch of work of this nature where there would be a mix of new vs existing models.

**Comment by calcinai** [comment]
Yeah, I think an ```updateAll()``` method might be a little redundant, as you really need to be doing that in individual calls anyway - ```POST /<uri>/<guid>``` per object.

**Comment by paulsschwarz** [comment]
Hmm, why do they have an `update_contacts` method but not an `update_invoices` method? https://github.com/xero-gateway/xero_gateway/blob/master/lib/xero_gateway/gateway.rb#L105

**Comment by calcinai** [comment]
That's interesting.. It looks like you can update by just ```POST```ing to the base uri, and if the GUIDs exist, it'll just update not insert.  

Based on that, the batch save simply needs to be a wrapper for that code snippet I mentioned in #7

**Comment by paulsschwarz** [comment]
Elegant.

**Comment by paulsschwarz** [comment]
Up to you, but I'd prefer a separate `save()` and `saveAll()` method for clarity. Then I guess the only other implementation detail would be ensuring homogeneity which could be done by asking the first model in the array what type it is and then if any subsequent models in the array don't match the established type then throw an exception.

**Comment by calcinai** [comment]
Yep - exactly what I've just done.  Will push changes soon.

**Comment by paulsschwarz** [comment]
Awesome!
