### ISSUE TITLE
Putting dates into the correct timezone

### ISSUE THREAD

**Issue by judgej** [calcinai/xero-php#80]
This issue has a long stream of my ramblings, trying to get to the bottom of how Xero accepts, stores and presents dates:

https://github.com/calcinai/xero-php/issues/79

The result of my testing is: dates are provided by the API as strings exactly as typed by the user in the Xero admin pages. It makes no difference what the organisation timezone is set to, either when the records were created, or now - the date is as typed. I have not explored dates supplied in the PUT or POST API schemas, as I am just dealing with GET at the moment.

So when reading these dates, they need to be interpreted in the timezone of the organisation. Those timezones in Xero are UCT plus or minus an offset, and do not appear to have a DST. I don't know if non-DST timezones are supported by PHP - I suspect not (but would love to be corrected).

I think at the very least, when configuring the application, you should be able to provide the timezone to be used when interpreting these dates, e.g. "Europe/London".

The workaround for now is to set the default system timezone, which is a bit of a hack IMO (dates and time parsing should never rely on the local timezone when dealing with remote data - it needs to be more explicit).

Thoughts?

**Comment by FLamparski** [comment]
In my previous job, I scraped the surface of this strange intersection of timezones and general Xero API silliness - I can't remember exactly what we did but I think we interpreted the UTC dates as UTC, and it worked out for us.

Also note that converting between the Windows Registry timezone names and PHP's timezones (based on the IANA database) is... _fun_.

**Comment by judgej** [comment]
Oh yes, those timezone conversions really do look like an awful lot of fun :-(

I've had confirmation from a Xero dev that any date field in the XML API results with a name that ends in "UTC" should be treated as UTC.

In my own tests, all other dates (even though Xero presents them as datetimes with a 00:00:00 time) are returned by the API *as typed by the end user*. So they have no real timezone (they are just dates after all) so you need to be careful what timezone you put them into if you want to do any arithmetic on them. This seems to hold true even when dates are entered between DST dates, and regardless of what Xero timezone is set for the organisation. Something niggles the back of my mind that this could come back to bite us, but I've not put my finger on it yet.

For my project now, we are defining the IANA timezone for an organisatino *outside* of Xero. That seems to be the safest option - we don't care what timezone is used to display times to the end Xero user, and we know exactly what dates they have typed into the screens (as that is what the API gives us) so we parse them according to the timezone we define.
