### ISSUE TITLE
oauth 1.0 deprecated

### ISSUE THREAD

**Issue by abhimanusharma** [calcinai/xero-php#800]
any update on new release as oauth version1.0 has been deprecated by xero?

**Comment by rodjsta** [comment]
Search closed issues.

One of the biggest issues threads for this library is on the OAuth 2 issue.

https://github.com/calcinai/xero-php/issues/625

Basically... it's done. It's now over to you.

**Comment by calcinai** [comment]
Thanks @rodjsta
