### ISSUE TITLE
Call to undefined method GuzzleHttp\Psr7\Uri::withQueryValues()

### ISSUE THREAD

**Issue by DPineault** [calcinai/xero-php#803]
Can anyone offer guidance on receiving the error

Call to undefined method GuzzleHttp\Psr7\Uri::withQueryValues()

where it flags line 105 from calcinai\xero-php\src\XeroPHP\Remote\Request.php

which in turn comes from line 316 from calcinai\xero-php\src\XeroPHP\Remote\Query.php at line 316 – XeroPHP\Remote\Request::send() 

which in turn is coming from 

$org = $application->load(\XeroPHP\Models\Accounting\Organisation::class)->execute();

If this makes any difference: Apache/2.4.41 (Win64) OpenSSL/1.0.2s PHP/7.1.32

**Comment by Josh-G** [comment]
Looks like you might be using an old version of `calcinai/xero-php`. Please can you try updating to the latest version or let us know which version you're on.

**Comment by DPineault** [comment]
I tried

"calcinai/xero-php": "~2.2.4",

but that gives me 

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for calcinai/xero-php ~2.2.4 -> satisfiable by calcinai/xero-php[v2.2.4].
    - Conclusion: remove calcinai/oauth2-xero v0.1.4
    - Conclusion: don't install calcinai/oauth2-xero v0.1.4
    - calcinai/xero-php v2.2.4 requires calcinai/oauth2-xero ^1.0 -> satisfiable by calcinai/oauth2-xero[v1.0.0, v1.0.1,
 v1.0.2, v1.0.3, v1.0.4, v1.0.5].
    - Can only install one of: calcinai/oauth2-xero[v1.0.0, v0.1.4].
    - Can only install one of: calcinai/oauth2-xero[v1.0.1, v0.1.4].
    - Can only install one of: calcinai/oauth2-xero[v1.0.2, v0.1.4].
    - Can only install one of: calcinai/oauth2-xero[v1.0.3, v0.1.4].
    - Can only install one of: calcinai/oauth2-xero[v1.0.4, v0.1.4].
    - Can only install one of: calcinai/oauth2-xero[v1.0.5, v0.1.4].
    - Installation request for calcinai/oauth2-xero (locked at v0.1.4) -> satisfiable by calcinai/oauth2-xero[v0.1.4].

I don't know what to do to fix any of this.

Can you help?  What is the current version, I can't find it listed anywhere.

**Comment by DPineault** [comment]
I removed the entire thing and then reinstalled it, which seems to have work.  Thank you for the suggestion.
