### ISSUE TITLE
Get a single contact is throwing error

### ISSUE THREAD

**Issue by abhimanusharma** [calcinai/xero-php#804]
This is my code: `$contact = $xero->loadByGUID(Contact::class, $guid);`

This is the error.

XeroPHP\Remote\Exception\ForbiddenException: You are not permitted to access this resource in /var/www/html/project_dev/vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php:127
Stack trace:
#0 /var/www/html/project_dev/vendor/calcinai/xero-php/src/XeroPHP/Remote/Request.php(119): XeroPHP\Remote\Response->parse()
#1 /var/www/html/project_dev/vendor/calcinai/xero-php/src/XeroPHP/Remote/Query.php(330): XeroPHP\Remote\Request->send()
#2 /var/www/html/project_dev/vendor/calcinai/xero-php/src/XeroPHP/Remote/Query.php(347): XeroPHP\Remote\Query->execute()
#3 /var/www/html/project_dev/app/Service/XeroApiService.php(144): XeroPHP\Remote\Query->loadByGUID()

**Comment by calcinai** [comment]
Whoops, it looks like you're trying to access something you don't have permission to access

**Comment by abhimanusharma** [comment]
Then how to resolve this issue? I have all the scopes that is needed to access the contacts as I am creating a contact and that is working fine. So why is this throwing this error?
