### ISSUE TITLE
Issue Searching

### ISSUE THREAD

**Issue by DPineault** [calcinai/xero-php#807]
I'm not sure if this is a library issue, a Xero issue, ... so please advise me if I should be posting this elsewhere.

I have code like

```
$Name = 'Company, FirstName LastName (ID)'; //This is the general format of the Name which come from a db and matches the entry in XERO
$contact = $xero->load(Contact::class)
	->where('Name', $Name)
	->andWhere('ContactStatus', Contact::CONTACT_STATUS_ACTIVE)
	->execute()
	->first();
```

I also saw the following syntax in this forum.  I tried it and it made no difference

`->where('Name=="' . $Name . '"')`

That I have been using for a couple years now without issue.

I am suddenly having an issue with one (there may be more who knows)  particular contact that it can't find, yet they are there.

If I search by Email Address I can find them, extract their Name and it matches what I am searching with, yet it doesn't work.  If I copy the name from the XERO interface and hard code it into the search, it also fails to find the entry.

I extracted the Name (by searching with their Email) and the used bin2hex() to compare with what I've been using, and they match.

The only thing I can think is their name includes a couple special characters +,( ) in it, yet this never posed an issue previously.

Note I recently upgraded to the latest oAuth2 version.  Does the new version have issues with special characters?  Can anyone offer any guidance.

**Comment by calcinai** [comment]
@DPineault I have no idea why migrating to OAuth2 would cause this, but your mention of special characters is probably it.  Xero allows queries to be constructed with `()` etc, so you're probably breaking the query by searching with those.  Have you tried anything in the API previewer?  I'd recommend testing there, maybe adding `\` or something before the bracket, and see if that helps.

**Comment by Healyhatman** [comment]
urlencode($Name) should work, for example if you have names with an apostrophe ' in them

**Comment by DPineault** [comment]
Thank you both for the assist.  Healyhatman's solution has resolved the issue.
What is perplexing to me is that I have been using code without the urlencode for well over a year now, and only suddenly has this become an issue?  At least it is resolve.

Thank you both once again!
