### ISSUE TITLE
Load XML

### ISSUE THREAD

**Issue by temppeck** [calcinai/xero-php#811]
I have an existing project that has already created the valid XML for invoices, purchase orders etc.
Is there a way to use this wrapper to send the XML?

**Comment by calcinai** [comment]
@temppeck it's probably possible, but you'd need to set up the authorisation first.

If you look at Remote/Request, there's a `setBody()` method in there that you could push some XML into.

**Comment by temppeck** [comment]
Thanks @calcinai
