### ISSUE TITLE
Works with Custom Connections?

### ISSUE THREAD

**Issue by empsean** [calcinai/xero-php#814]
Can this intergration be used with Xero's "Custom Connections" without any further modifications?
https://developer.xero.com/documentation/guides/oauth2/custom-connections/#purchasing-custom-connection-subscriptions

**Comment by calcinai** [comment]
I don't see why not. The authorisation is handled in a separate flow anyway- [This library](https://github.com/calcinai/oauth2-xero) is bundled with xero-php and should have what you need to construct the request with the correct grant type and scopes, then everything else would be the same. i.e.

`$xero = new \XeroPHP\Application($accessToken, $tenantId);`

**Comment by stuartford** [comment]
I've gone down this path too, since I don't have a user application, rather a billing system which creates invoices in Xero.

The issue I'm having is that I have an access token back from Xero as per https://developer.xero.com/documentation/guides/oauth2/custom-connections/#setting-up-a-custom-connection

But when I try to pass this token (which comes back as a base64 encoded string) to getTenants() it throws an exception saying that it needs to be an instance of League\OAuth2\Client\Token\AccessTokenInterface.

That's fair enough, but how do we convert the token sent back from Xero into an object of this type?

Additionally, the authentication example in the documentation doesn't seem to work:

 $authUrl = $provider->getAuthorizationUrl([
        'scope' => 'openid email profile accounting.transactions'
    ]);

**Comment by stuartford** [comment]
Update: Never mind, found out how:

`$accessToken = new AccessToken(['access_token' => $result->access_token]);`

**Comment by olimortimer** [comment]
@stuartford may I ask how you got on using Xero Custom Connections with calcinai/xero-php please?

I also have a system that handles everything via CLI, so Custom Connections is perfect for me.  However I note that you say you didn't need to pass a $tenantId, however if I leave that out I receive an error;

`Too few arguments to function XeroPHP\Application::__construct()`

If I find out my $tenantId for my Custom Connection, assuming it's the ID in the Xero URL for managing the app, ie `https://developer.xero.com/app/manage/app/XYZ`, and pass that through, I get another error;

`You are not permitted to access this resource`

I have added every single scope to my Xero App, to ensure it's not that, but it still throws the error.

Looking at the troubleshooting docs, it seems to suggest that "The Xero-tenant-id header is missing, incorrect or isn’t authorized for use with this access token"

https://developer.xero.com/documentation/guides/oauth2/troubleshooting/#:~:text=%7B%0A%20%20%20%20%22title%22%3A%20%22-,Forbidden,-%22%2C%0A%20%20%20%20%22status%22%3A%20403%2C%0A%20%20%20%20%22detail

**Comment by olimortimer** [comment]
Figured it out - it does need the $tenantId passing through, but the ID is not what's found in the URL; `https://developer.xero.com/app/manage/app/XYZ`

Requesting connections using the `access_token` given, provides the tenants;

`$tenants = Http::withToken($access['access_token'])->get('https://api.xero.com/connections');
printf($tenants->json());`

**Comment by Josh-G** [comment]
Rather than using curl directly, you can use the `oauth2-xero` library as provided and suggested by @calcinai:
```php
$provider = new \Calcinai\OAuth2\Client\Provider\Xero([
    'clientId' => 'your client id',
    'clientSecret' => 'your client secret',
]);
$token = $provider->getAccessToken('client_credentials');
$tenants = $provider->getTenants($token);
```

**Comment by olimortimer** [comment]
> Rather than using curl directly, you can use the `oauth2-xero` library as provided and suggested by @calcinai:
> 
> ```
> $provider = new \Calcinai\OAuth2\Client\Provider\Xero([
>     'clientId' => 'your client id',
>     'clientSecret' => 'your client secret',
> ]);
> $token = $provider->getAccessToken('client_credentials');
> $tenants = $provider->getTenants($token);
> ```

Is there a way of using that and specifying `grant_type` and `scope`?

**Comment by empsean** [comment]
> Rather than using curl directly, you can use the `oauth2-xero` library as provided and suggested by @calcinai:
> 
> ```
> $provider = new \Calcinai\OAuth2\Client\Provider\Xero([
>     'clientId' => 'your client id',
>     'clientSecret' => 'your client secret',
> ]);
> $token = $provider->getAccessToken('client_credentials');
> $tenants = $provider->getTenants($token);
> ```

Using this I just get 'invalid_client'

**Comment by calcinai** [comment]
@empsean I'm assuming you've confirmed `your client id` and `your client secret` are the correct values? (sorry, have to ask)

Have a look at https://developer.xero.com/documentation/guides/oauth2/troubleshooting/#access-token-request-errors

**Comment by empsean** [comment]
> /**
>      * Set up new Custom Connection
>      *
>      * @return \XeroPHP\Application
>      */
>     private static function customConnection()
>     {
>         if (Cache::has('xero.access_token')) {
> 
>             // access token in cache should still be good
>             $result = Cache::get('xero.access_token');
> 			
>         } else {
> 
>             // request an access token
>             $ch = curl_init();
> 
>             $body = "grant_type=client_credentials&\r\nscopes=".implode(' ', config('dms.xero.scopes'))."\r\n";
> 
>             curl_setopt($ch, CURLOPT_URL, 'https://identity.xero.com/connect/token');
>             curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
>             curl_setopt($ch, CURLOPT_POST, true);
>             curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
>             curl_setopt($ch, CURLINFO_HEADER_OUT, true);
>             curl_setopt($ch, CURLOPT_HTTPHEADER, [
>                 'authorization: Basic '.base64_encode(
>                     config('dms.xero.customClientId').':'.config('dms.xero.customSecret')
>                 ),
>                 'Content-Type: application/x-www-form-urlencoded',
>             ]);
> 
>             $result = json_decode(curl_exec($ch));
>             curl_close($ch);
> 
>             // store in cache
>             Cache::put('xero.access_token', $result, 1800);
>         }
> 
>         // create AccessToken object from result
>         $accessToken = new AccessToken([
>             'access_token' => $result->access_token,
>             'expires' => $result->expires_in,
>         ]);
> 
>         // new custom application
>         return new \XeroPHP\Application($accessToken, null);
>     }

Yup absolutely.
Got it working through Postman.

Using that config, not sure where it actually sends the request too given that Custom Connections go to a different URL.

**Comment by empsean** [comment]
> @empsean I'm assuming you've confirmed `your client id` and `your client secret` are the correct values? (sorry, have to ask)
> 
> Have a look at https://developer.xero.com/documentation/guides/oauth2/troubleshooting/#access-token-request-errors

Yup absolutely.
Got it working through Postman.

Using that config, not sure where it actually sends the request too given that Custom Connections go to a different URL.

**Comment by empsean** [comment]
@calcinai never mind, secret was wrong, had some weird character encoding going on.

Using the method on the front page works :)
