### ISSUE TITLE
XeroPHP\Helpers::getPackageVersion issues with open_basedir

### ISSUE THREAD

**Issue by SDF-of-BC** [calcinai/xero-php#815]
Hey all!
One of our servers recently had it's PHP updated

> PHP 7.4.21 (cli) (built: Jul  7 2021 17:35:08) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>    with Zend OPcache v7.4.21, Copyright (c), by Zend Technologies

This server is shared and using open_basedir to help keep sites separated.

Following the update when a customer's system attempted to raise an invoice in Xero or interact with Xero in any other way:
>PHP message: Unable to create order: sizzlecreative\\firefly\\core\\PhpErrorException: file_exists(): open_basedir restriction in effect. File(/VERSION) is not within the allowed path(s): (/var/www/customers/webs/[...]/portal.[...].com:/var/www/customers/tmp/[...]:/usr/share/pear:/usr/share/php:/tmp) in /var/www/customers/webs/[...]/portal.[...].com/vendor/calcinai/xero-php/src/XeroPHP/Helpers.php:276

I'm not exactly sure what change would have caused this to suddenly start misbahaving, no configs have been updated, no code has been updated except the PHP package. But I thought opening an issue might be helpful as PHP ends up searching for a file called VERSION in the root dir and maybe this isn't such a good idea.

At the moment I have just commented out the code such that the default is returned.

Let me know if you need any more info,
Thanks in advance.

**Comment by calcinai** [comment]
@SDF-of-BC fair point. The intent with this was to use the package version in the user agent so Xero could report on what version of the SDK was being used.  I couldn't figure out a way to do it automagically without loading the whole composer.json or something, but was going to make a little travis job to populate that VERSION file, which I never did.

**Comment by SDF-of-BC** [comment]
@calcinai Yeah I could see what you were trying to do, I coded up some internal stuff last year and ran into similar issues trying to work out versions, to start with I loaded the lock file, it wasn't nice. Composer 2.0 really helped though, it comes with a Composer\InstalledVersions::getVersion which is available at runtime, you pass the name of your package in and you get a version string back. There is more info here, https://getcomposer.org/doc/07-runtime.md#knowing-a-package-s-own-installed-version

If you're happy to I could code something up to use that if the class exists at runtime, otherwise fall back to the current way of working?

**Comment by calcinai** [comment]
@SDF-of-BC That'd be great!

**Comment by christopherbolt** [comment]
Just ran into this issue as well. Writing to a file in the server root is a bad idea, you are assuming that your application will be the only thing running on the server. Consider writing it to somewhere within the package itself, or if you must write to a shared location use the /tmp folder, but even that's not ideal as other sites could overwrite it

**Comment by calcinai** [comment]
@christopherbolt um, I just looked at the code and wow. That's not how it ever was intended, I must have got the point above and removed the base path or something – maybe I got halfway through updating the travis job and forgot write that file into the library root, not the system root!

**Comment by calcinai** [comment]
@SDF-of-BC & @christopherbolt thoughts on the above?

**Comment by christopherbolt** [comment]
@calcinai that fix looks perfect. Thanks for updating this so quickly!

**Comment by calcinai** [comment]
Cool, PR #816

**Comment by SDF-of-BC** [comment]
Thanks I'd not got around to working on a fix myself. I've tested it and it all looks good! :)

**Comment by SDF-of-BC** [comment]
I'll close this issue, thanks again!
