### ISSUE TITLE
PayItems Earnings Rates invalid validation requirement for TypeOfUnits

### ISSUE THREAD

**Issue by cproetti** [calcinai/xero-php#817]
Starting with a fresh Xero account you'll have some PayItems EarningsRates created by default, particularly the one called "Redundancy" which does not have a TypeOfUnits possible.

To make changes to the EarningsRates via the API requires you to GET all, modify/add EarningsRates and then POST the whole lot back.

Right off the bat, you cannot save back (even if no changes were made) due to a validation error "A validation exception occurred (The Type Of Units is required) Validation errors: ."

Sorry this Issue post is very rough and vague, I'm in bit of a hurry and will hope to have time to come back later and fix up this post's details.

**Comment by Healyhatman** [comment]
This is more an issue with Xero doing something dumb - they're creating invalid rates and then not letting you to send back the exact same data. The error is coming from Xero, not from this package.

**Comment by calcinai** [comment]
Agreed
