### ISSUE TITLE
Parse error: syntax error, unexpected 'empty' (T_EMPTY)

### ISSUE THREAD

**Issue by mishadaut** [calcinai/xero-php#818]
Hi,

Getting bellow error using xero-php v2.3.0: 

**Parse error: syntax error, unexpected 'empty' (T_EMPTY), expecting identifier (T_STRING) in vendor/calcinai/xero-php/src/XeroPHP/Remote/Collection.php on line 25**

May be good idea to rename function empty() of XeroPHP/Remote/Collection.php to isEmpty() ? empty() is php's built in function.

Thanks.

**Comment by davidwindell** [comment]
Same here, will open a pull request.
