### ISSUE TITLE
PayrollAU\Employee missing DateOfBirth

### ISSUE THREAD

**Issue by digiwise** [calcinai/xero-php#82]
The PayrollAU\Employee model seems to be missing the DateOfBirth field.

(Thanks for the great library - much better than Xero's!)

**Comment by digiwise** [comment]
PayrollAU\Employee model also seems to be missing the Phone field

**Comment by digiwise** [comment]
Fixed so promptly - thanks heaps!

**Comment by calcinai** [comment]
Will need to contact Xero about the malformed HTML in their docs for the Phone field..  It's as follows:

```html
<tr>
<td>Gender</td>
<td>The employee’s gender (M or F)</td>
</tr>
<td>Phone</td>
<td>Employee phone number (max length = 50)</td>

<tr>
<td>Mobile</td>
<td>Employee mobile number (max length = 50)</td>
</tr>
```

Which is mucking up the scraper.

**Comment by digiwise** [comment]
Yep, that HTML looks hard to scrape.  I had assumed it would be a similar issue to the DateOfBirth field, so I didn't think it warranted it's own issue.

Thanks again for following up so promptly.
