### ISSUE TITLE
Need the ability to set the PayrollAU\Employee TerminationReason (now required by Xero)

### ISSUE THREAD

**Issue by victormacko** [calcinai/xero-php#822]
Xero's added in the requirement to pass across a 'TerminationReason' when marking an employee's status as 'TERMINATED';

it's part of the Australian Taxation Office's push for Single Touch Payroll;
https://developer.xero.com/documentation/api/payrollau/stp-changes

Unfortunately it doesn't look like i'm able to set this variable in the PayrollAU\Employee .. is this something which can be added in? (or can I add it in via a PR? ... I wasn't sure if the models are automatically generated from the docs, or manually done...)

**Comment by calcinai** [comment]
Merged that PR, thanks.
