### ISSUE TITLE
setLineItem missing

### ISSUE THREAD

**Issue by irricheck** [calcinai/xero-php#827]
When I create a new invoice, I get an error that setLineItems is not valid, yet all samples I can find online says its the way to add the line items to an invoice before creating it. Must be missing something

here is my code:

```

$jobdescription = 'test line item 1';
$quantity = 5;
$rateperhour = 150.10;
$accountcode = '1120';
  
$contact = new \XeroPHP\Models\Accounting\Contact;
$contact->setContactId($contactid);

$lineitem = new \XeroPHP\Models\Accounting\LineItem;
$lineitem->setDescription($jobdescription)
	->setQuantity($quantity)
	->setUnitAmount(number_format($rateperhour, 2))
	->setAccountCode($accountcode);

$arr_lineitems=[]; 

array_push($arr_lineitems, $lineitem);

$invoice = new \XeroPHP\Models\Accounting\Invoice($xero);

$invoice->setContact($contact)	;	
$invoice->setLineItems($lineitem);   //this fails with function is not defined. I can also not find this function in any of the code in the src folder
$invoice->save(); 
```

**Comment by jaytee117** [comment]
use 
$invoice->addLineItem($lineitem);

**Comment by jaytee117** [comment]
`
$jobdescription = 'test line item 1';
$quantity = 5;
$rateperhour = 150.10;
$accountcode = '1120';
  
$contact = new \XeroPHP\Models\Accounting\Contact;
$contact->setContactId($contactid);

$lineitem = new \XeroPHP\Models\Accounting\LineItem;
$lineitem->setDescription($jobdescription)
	->setQuantity($quantity)
	->setUnitAmount(number_format($rateperhour, 2))
	->setAccountCode($accountcode);

$invoice = new \XeroPHP\Models\Accounting\Invoice($xero);

$invoice->setContact($contact)	;	
$invoice->addLineItem($lineitem);   
$invoice->save(); 
`

**Comment by irricheck** [comment]
thanks, this somehow works perfect.
