### ISSUE TITLE
Remote/Collection.php Empty method in release 2.3.0 throws error

### ISSUE THREAD

**Issue by Good4zb** [calcinai/xero-php#828]
The addition of the empty function in tag 2.3.0 throws the below error in PHP 5.6 when adding a line to an invoice with $invoice->addLineItem($lineItem)

PHP Parse error:  syntax error, unexpected 'empty' (T_EMPTY), expecting identifier (T_STRING) in calcinai/xero-php/src/XeroPHP/Remote/Collection.php on line 25`

Commenting out the function solves the error.

**Comment by calcinai** [comment]
@Good4zb this is fixed in master, pending release.
