### ISSUE TITLE
Xero Bill LineItems rounding to 2 decimal places

### ISSUE THREAD

**Issue by l1ngoman** [calcinai/xero-php#852]
Hello,

I'm experiencing an issue with syncing across a Bill with more than 2 decimal places. Note: I'm aware of [Issue #575](https://github.com/calcinai/xero-php/issues/575).

The strange thing is that the associated Purchase Order is syncing across with the correct decimal precision - just not the Bill.

The config array has the 'xero' => ['unitdp' => 4] code that should be overriding the default 2-decimal setting (which again is definitely working since the PO is correct), and all of this has been working as expected to my knowledge until a customer just brought it up.

I have verified that the numbers are correct on the database side, and I even hard-coded the amount just to be sure it wasn't an issue with the data itself.

I'm stumped at this point, so any suggestions are welcomed.

Thank you!

CONFIG:
$config = [
	'redirectUri' 	=> $redirectUri,
	'clientId' 		=> $clientId,
	'clientSecret' 	=> $clientSecret,
	'xero' => [
		'unitdp' => 4,
	],
];

CODE: 
$invoice = new Invoice($xero);

$tmpItem = new LineItem($xero);
$tmpItem->setQuantity($Quantity);
$tmpItem->setUnitAmount($UnitPrice);

$invoice->addLineItem($tmpItem);

![image](https://user-images.githubusercontent.com/41375558/168187790-73c91f9f-8522-4f9f-86c5-0e442976b0f2.png)
![image](https://user-images.githubusercontent.com/41375558/168187843-6735c99f-09ba-47ef-bc65-81e4629b498a.png)

**Comment by l1ngoman** [comment]
Just an update on this: I reached out to Xero Support as well, and they responded stating that the API call for creating the Bill in question did not include the unitdp=4 parameter. They also mentioned that the Purchase Order endpoint is newer and defaults to 4 decimals automatically.

Please advise if there is a different way to set the default decimal value than I have outlined above.

Thanks!

**Comment by l1ngoman** [comment]
- [ ]

**Comment by calcinai** [comment]
Sorry for the slow response.  The request in question is [here](https://github.com/calcinai/xero-php/blob/55dc1f6d86bb603899276bfa3330117cdc03535e/src/XeroPHP/Application.php#L401), have you debugged in your case to see if it is actually adding that parameter? It should be universal throughout the package as long as the `unitdp` is set in your config.

**Comment by l1ngoman** [comment]
> Sorry for the slow response. The request in question is [here](https://github.com/calcinai/xero-php/blob/55dc1f6d86bb603899276bfa3330117cdc03535e/src/XeroPHP/Application.php#L401), have you debugged in your case to see if it is actually adding that parameter? It should be universal throughout the package as long as the `unitdp` is set in your config.

Hi,

I added this ($request->setParameter('unitdp', 4);) to the request in the saveAll() method, and it seems to be working for now. Thanks for pointing me to the right file!

Cheers
