### ISSUE TITLE
Quotes endpoint returning all quotes regardless of filter/search

### ISSUE THREAD

**Issue by Yendall** [calcinai/xero-php#853]
When I construct a query to fetch Quotes filtering by QuoteNumber, the package is returning all quotes with no filtering being performed. The same query when used against an Invoice works as intended.

Quote request:
`
["from_class":"XeroPHP\Remote\Query":private]=>
  string(31) "XeroPHP\Models\Accounting\Quote"
  ["where":"XeroPHP\Remote\Query":private]=>
  array(1) {
    [0]=>
    string(51) "QuoteNumber.ToLower().Contains("quo_20220617_0001")"
  }
`

Invoice request:
`
  ["from_class":"XeroPHP\Remote\Query":private]=>
  string(33) "XeroPHP\Models\Accounting\Invoice"
  ["where":"XeroPHP\Remote\Query":private]=>
  array(1) {
    [0]=>
    string(53) "InvoiceNumber.ToLower().Contains("inv_20220623_0211")"
  }
`

Not sure where it's failing here, but I noticed there was a closed issue with the same problem: #675

**Comment by calcinai** [comment]
@Yendall do you know if this is consistent with behaviour in the API previewer?

**Comment by Yendall** [comment]
@calcinai The API Explorer works as intended with this particular query. This is why I thought it must be package related.

In the explorer I can't run the .ToLower() stuff but I tried a basic query of QuoteNumber= quo_20220617_0001 with my connected company through both the package and the Explorer, and the package returned all quotes and the Explorer returned the specific quote

**Comment by Yendall** [comment]
@calcinai an update on this. I contacted Xero and they don't have support for Where queries on the Quotes endpoint. So it's nothing wrong with the package, but is still incredibly annoying! Hopefully they add this in

**Comment by calcinai** [comment]
So weird, but good to know.
