### ISSUE TITLE
Facing problem to migrate the xero-php to using oauth2 at yii2 framework

### ISSUE THREAD

**Issue by lvsan** [calcinai/xero-php#856]
Hi,
I have integrate my system with the xero accounting using calcinai/xero-php few years ago.
Currently, our company would like to begin the integration with xero accounting  and I notice the api have been change.

So would like to know anyone can assist me how can I migrate the old methods to oauth2 methods?

Thanks.

**Comment by calcinai** [comment]
Hi @lvsan check out here- this should be all you need! https://github.com/calcinai/xero-php#migration-from-1xoauth-1a

**Comment by lvsan** [comment]
I able to open the xero page to authorize me to access. but then will need the token to call the xero api right for contacts and etc?

but i have the error show as below :

2022-06-28 16:09:19 [127.0.0.1][105e5162-f8f5-11e7-95c5-68f7282584d2][2fi9cglbdb6igqi9tjl03dvbgk][error][GuzzleHttp\Exception\RequestException] GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://identity.xero.com/connect/token in D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:211
Stack trace:
#0 D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\Client.php(107): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 D:\wamp64\www\master\vendor\guzzlehttp\guzzle\src\Client.php(123): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array)
#13 D:\wamp64\www\master\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(608): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request))
#14 D:\wamp64\www\master\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(621): League\OAuth2\Client\Provider\AbstractProvider->getResponse(Object(GuzzleHttp\Psr7\Request))
#15 D:\wamp64\www\master\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request))
#16 D:\wamp64\www\myRetailerPlus_V4_New\views\xero\index.php(25): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\AuthorizationCode), Array)
#17 D:\wamp64\www\master\vendor\yiisoft\yii2\base\View.php(348): require('D:\\wamp64\\www\\m...')
#18 D:\wamp64\www\master\vendor\yiisoft\yii2\base\View.php(257): yii\base\View->renderPhpFile('D:\\wamp64\\www\\m...', Array)
#19 D:\wamp64\www\master\vendor\yiisoft\yii2\base\View.php(156): yii\base\View->renderFile('D:\\wamp64\\www\\m...', Array, Object(app\controllers\XeroController))
#20 D:\wamp64\www\master\vendor\yiisoft\yii2\base\Controller.php(410): yii\base\View->render('index', Array, Object(app\controllers\XeroController))
#21 D:\wamp64\www\myRetailerPlus_V4_New\controllers\XeroController.php(165): yii\base\Controller->render('index', Array)
#22 [internal function]: app\controllers\XeroController->actionIndex('87bfc6c387286bb...', 'openid email pr...', '2d2ddc3f8343698...')
#23 D:\wamp64\www\master\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#24 D:\wamp64\www\master\vendor\yiisoft\yii2\base\Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#25 D:\wamp64\www\master\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('index', Array)
#26 D:\wamp64\www\master\vendor\yiisoft\yii2\web\Application.php(104): yii\base\Module->runAction('xero/index', Array)
#27 D:\wamp64\www\master\vendor\yiisoft\yii2\base\Application.php(392): yii\web\Application->handleRequest(Object(yii\web\Request))
#28 D:\wamp64\www\myRetailerPlus_V4_New\web\index.php(12): yii\base\Application->run()
#29 {main}
2022-06-28 16:09:18 [127.0.0.1][105e5162-f8f5-11e7-95c5-68f7282584d2][2fi9cglbdb6igqi9tjl03dvbgk][info][application] $_GET = [
    'code' => '87bfc6c387286bb3b18ed3ef917a4db76e8322bafb61ccd0652e4a02916ad0d9'
    'scope' => 'openid email profile accounting.settings accounting.transactions accounting.contacts accounting.journals.read offline_access'
    'state' => '2d2ddc3f8343698928c9eb38d5a05578'
    'session_state' => 'Q-BeKcg31riE6Z8pmWtJRZLr9iuP2_DlQFxzNt7aarY.7cb787cf45a2a29cfff0e899a61ae7cf'
]


Able to advise me on this? currently i using my local pc to connect but there is https in my local pc.

Thanks.

Regards,

Lvsan
