### ISSUE TITLE
Line Breaks in LineItem description

### ISSUE THREAD

**Issue by maxresnikoff** [calcinai/xero-php#858]
Is there a way to add a new line in the item description when creating a new line item?

I have tried all variations; `<br></br>\n\r` Unicode etc etc. No luck.

Does the library escape and cleanse the input? As any characters I add are actually shown in the description eg. Red Shirt<br>Medium

**Comment by rodjsta** [comment]
Hi @maxresnikoff,

Use \n\n and you'll find that works.

Also, Xero UI will only show you the line breaks in Edit mode or when generating the PDF.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/32949856/176420623-c99314d9-c5bb-442b-b520-bd44634643b6.png">

I hope this helps.

**Comment by maxresnikoff** [comment]
Ahh that worked! Many thanks! 

\n\n does add a line in between, so changed to \n

Previously, I had it enclosed in single quotes (noob error right there), which I didn't even think about the fact it would not escape the \n 🤦

Also checked the UI, and it does show the line break?!

**Comment by rodjsta** [comment]
Sorry @maxresnikoff, the \n is what you want for a new line, \n\n will give you two line breaks.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/32949856/176421879-5a6359e4-6c58-4a48-9f5f-4343eb423560.png">

**Comment by rodjsta** [comment]
Glad I could help.

The UI of Classing Invoicing doesn't show the line break. It looks like the New Invoicing UI does.
