### ISSUE TITLE
How can I get the response or convert to array to be readable for xero invoices

### ISSUE THREAD

**Issue by lvsan** [calcinai/xero-php#860]
HI,
I able to create the invoice to xero through the api. Now the problem is i try to get the response back with the INVOICEID and LineItemID that will be return.

Possible to guide me how can I do this?

Below is the return that i will get where i using the print_r.
<pre class='xdebug-var-dump' dir='ltr'>
<small>D:\wamp64\www\xxxxx\controllers\XeroController.php:1511:</small>
<b>object</b>(<i>XeroPHP\Models\Accounting\Invoice</i>)[<i>500</i>]
  <i>protected</i> '_data' <font color='#888a85'>=&gt;</font> 
    <b>array</b> <i>(size=32)</i>
      'InvoiceNumber' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'BDM-00000166'</font> <i>(length=12)</i>
      'Reference' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>''</font> <i>(length=0)</i>
      'Date' <font color='#888a85'>=&gt;</font> 
        <b>object</b>(<i>DateTime</i>)[<i>501</i>]
          <i>public</i> 'date' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'2022-05-08 00:00:00.000000'</font> <i>(length=26)</i>
          <i>public</i> 'timezone_type' <font color='#888a85'>=&gt;</font> <small>int</small> <font color='#4e9a06'>3</font>
          <i>public</i> 'timezone' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Asia/Singapore'</font> <i>(length=14)</i>
      'DueDate' <font color='#888a85'>=&gt;</font> 
        <b>object</b>(<i>DateTime</i>)[<i>503</i>]
          <i>public</i> 'date' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'2022-05-08 00:00:00.000000'</font> <i>(length=26)</i>
          <i>public</i> 'timezone_type' <font color='#888a85'>=&gt;</font> <small>int</small> <font color='#4e9a06'>3</font>
          <i>public</i> 'timezone' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Asia/Singapore'</font> <i>(length=14)</i>
      'CurrencyCode' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'SGD'</font> <i>(length=3)</i>
      'CurrencyRate' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'1.000000'</font> <i>(length=8)</i>
      'Status' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'AUTHORISED'</font> <i>(length=10)</i>
      'BrandingThemeID' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'72a8b331-0431-4343-8e83-a69f17a70f83'</font> <i>(length=36)</i>
      'Type' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'ACCREC'</font> <i>(length=6)</i>
      'Contact' <font color='#888a85'>=&gt;</font> 
        <b>object</b>(<i>XeroPHP\Models\Accounting\Contact</i>)[<i>499</i>]
          <i>protected</i> '_data' <font color='#888a85'>=&gt;</font> 
            <b>array</b> <i>(size=1)</i>
              ...
          <i>protected</i> '_dirty' <font color='#888a85'>=&gt;</font> 
            <b>array</b> <i>(size=1)</i>
              ...
          <i>protected</i> '_associated_objects' <font color='#888a85'>=&gt;</font> 
            <b>array</b> <i>(size=0)</i>
              ...
          <i>protected</i> '_application' <font color='#888a85'>=&gt;</font> 
            <b>object</b>(<i>XeroPHP\Application</i>)[<i>41</i>]
              ...
      'LineAmountTypes' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Exclusive'</font> <i>(length=9)</i>
      'LineItems' <font color='#888a85'>=&gt;</font> 
        <b>object</b>(<i>XeroPHP\Remote\Collection</i>)[<i>504</i>]
          <i>protected</i> '_associated_objects' <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
          <i>private</i> 'storage' <small>(ArrayObject)</small> <font color='#888a85'>=&gt;</font> 
            <b>array</b> <i>(size=1)</i>
              ...
      'Url' <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
      'SentToContact' <font color='#888a85'>=&gt;</font> <small>boolean</small> <font color='#75507b'>false</font>
      'ExpectedPaymentDate' <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
      'PlannedPaymentDate' <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
      'SubTotal' <font color='#888a85'>=&gt;</font> <small>float</small> <font color='#f57900'>80.5</font>
      'TotalTax' <font color='#888a85'>=&gt;</font> <small>float</small> <font color='#f57900'>5.64</font>
      'Total' <font color='#888a85'>=&gt;</font> <small>float</small> <font color='#f57900'>86.14</font>
      'TotalDiscount' <font color='#888a85'>=&gt;</font> <small>float</small> <font color='#f57900'>0</font>
      'InvoiceID' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'129a2cca-aad8-45a2-af3b-fe016c954cf3'</font> <i>(length=36)</i>
      'RepeatingInvoiceID' <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
      'HasAttachments' <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
      'Payments' <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
      'Prepayments' <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
      'Overpayments' <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
      'AmountDue' <font color='#888a85'>=&gt;</font> <small>float</small> <font color='#f57900'>86.14</font>
      'AmountPaid' <font color='#888a85'>=&gt;</font> <small>float</small> <font color='#f57900'>0</font>
      'FullyPaidOnDate' <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
      'AmountCredited' <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
      'UpdatedDateUTC' <font color='#888a85'>=&gt;</font> 
        <b>object</b>(<i>DateTime</i>)[<i>516</i>]
          <i>public</i> 'date' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'2022-07-14 06:23:20.630000'</font> <i>(length=26)</i>
          <i>public</i> 'timezone_type' <font color='#888a85'>=&gt;</font> <small>int</small> <font color='#4e9a06'>3</font>
          <i>public</i> 'timezone' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'UTC'</font> <i>(length=3)</i>
      'CreditNotes' <font color='#888a85'>=&gt;</font> <font color='#3465a4'>null</font>
  <i>protected</i> '_dirty' <font color='#888a85'>=&gt;</font> 
    <b>array</b> <i>(size=0)</i>
      <i><font color='#888a85'>empty</font></i>
  <i>protected</i> '_associated_objects' <font color='#888a85'>=&gt;</font> 
    <b>array</b> <i>(size=0)</i>
      <i><font color='#888a85'>empty</font></i>
  <i>protected</i> '_application' <font color='#888a85'>=&gt;</font> 
    <b>object</b>(<i>XeroPHP\Application</i>)[<i>41</i>]
      <i>protected</i> 'config' <font color='#888a85'>=&gt;</font> 
        <b>array</b> <i>(size=1)</i>
          'xero' <font color='#888a85'>=&gt;</font> 
            <b>array</b> <i>(size=6)</i>
              ...
      <i>private</i> 'transport' <font color='#888a85'>=&gt;</font> 
        <b>object</b>(<i>GuzzleHttp\Client</i>)[<i>427</i>]
          <i>private</i> 'config' <font color='#888a85'>=&gt;</font> 
            <b>array</b> <i>(size=8)</i>
              ...
</pre>An internal server error occurred.

**Comment by rodjsta** [comment]
The invoice object has a method `getInvoiceID()` to easily access the Invoice ID. You can also use the `getLineItems()` method to access the line item objects.

I believe you can also convert the response object into an array using the `toStringArray()` method.

Happy to assist more if you show your code.

**Comment by lvsan** [comment]
Hi rodjsta,

Thanks for your reply.  i able to get the information that I need.

But when i try retrieve the LineItemID using getLineItemID(), but there is error return. 
I cannot found any information regards this through the object that is return.

<pre class='xdebug-var-dump' dir='ltr'>
<small>D:\wamp64\www\xxxxxxx\controllers\XeroController.php:1526:</small>
<b>object</b>(<i>XeroPHP\Models\Accounting\Invoice\LineItem</i>)[<i>502</i>]
  <i>protected</i> '_data' <font color='#888a85'>=&gt;</font> 
    <b>array</b> <i>(size=9)</i>
      'ItemCode' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'BM00162'</font> <i>(length=7)</i>
      'Description' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Tab S7FE LTE I SM-T736 I Other Replacement'</font> <i>(length=42)</i>
      'Quantity' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'1.000'</font> <i>(length=5)</i>
      'UnitAmount' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'342.490000'</font> <i>(length=10)</i>
      'DiscountAmount' <font color='#888a85'>=&gt;</font> <small>float</small> <font color='#f57900'>-0</font>
      'TaxType' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'OUTPUT'</font> <i>(length=6)</i>
      'TaxAmount' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'23.970000'</font> <i>(length=9)</i>
      'LineAmount' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'342.490000000'</font> <i>(length=13)</i>
      'AccountCode' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'200'</font> <i>(length=3)</i>
  <i>protected</i> '_dirty' <font color='#888a85'>=&gt;</font> 
    <b>array</b> <i>(size=0)</i>
      <i><font color='#888a85'>empty</font></i>
  <i>protected</i> '_associated_objects' <font color='#888a85'>=&gt;</font> 
    <b>array</b> <i>(size=0)</i>
      <i><font color='#888a85'>empty</font></i>
  <i>protected</i> '_application' <font color='#888a85'>=&gt;</font> 
    <b>object</b>(<i>XeroPHP\Application</i>)[<i>41</i>]
      <i>protected</i> 'config' <font color='#888a85'>=&gt;</font> 
        <b>array</b> <i>(size=1)</i>
          'xero' <font color='#888a85'>=&gt;</font> 
            <b>array</b> <i>(size=6)</i>
              ...
      <i>private</i> 'transport' <font color='#888a85'>=&gt;</font> 
        <b>object</b>(<i>GuzzleHttp\Client</i>)[<i>427</i>]
          <i>private</i> 'config' <font color='#888a85'>=&gt;</font> 
            <b>array</b> <i>(size=8)</i>
              ...
</pre>


Any advice for this part?
Thanks.

**Comment by rodjsta** [comment]
Hi @lvsan I have put together an example of one approach for you. I hope this helps.

![image](https://user-images.githubusercontent.com/32949856/178972002-d112d8e7-4c60-494f-b06b-e04c789b8ff5.png)

**Comment by lvsan** [comment]
Hi rodjsta,

Thanks for the sample and it is working fine for my site. really appreciate your help with the example that given to me.
