### ISSUE TITLE
No GUID property on TaxRates

### ISSUE THREAD

**Issue by FLamparski** [calcinai/xero-php#87]
[...]Models/Accounting/TaxRate.php:

``` php
    public static function getGUIDProperty(){
        return '';
    }
```

The GUID property on TaxRates should be `TaxType`. Otherwise if you try to update an existing Tax Rate with the library, it tries to create a new one and gets a name conflict exception.

**Comment by calcinai** [comment]
I'm not sure about this - it's not really a GUID...

**Comment by FLamparski** [comment]
It's not a GUID in a sense that it follows the standard GUID format, but it does seem to be the primary key (ie. if I change getGUIDProperty of a Tax Rate to return TaxType, POST requests update existing Tax Rates). Otherwise this violates the principle of least surprise (ie. editing and saving an existing tax rate should not attempt to create a new one!)

**Comment by calcinai** [comment]
Haha, you're probably right! The Tax* classes/calls don't seem to follow the same rules as the others at all.  I've run into it already.

I'll try to get it generating with that.
