### ISSUE TITLE
Editing a contact's phone number does not save correctly

### ISSUE THREAD

**Issue by FLamparski** [calcinai/xero-php#88]
Sorry to bug you again so soon, but either I'm not doing something right, or editing phones is buggy.

Say I have the following piece of (pseudo)code:

```php
$phone = find($contact->getPhones(), function ($p) => $p->getPhoneType() === 'DEFAULT');
$phone->setPhoneNumber($_POST['phone']);
$xero->save($contact);
```

After running that code, the new phone number is not persisted to Xero. I looked at the requests the save call was making and it was sending an empty `<Phones></Phones>` element. I don't have an exact case to reproduce the error but I tried stuff like `$contact->fromStringArray($contact->toStringArray())` or adding another `DEFAULT` phone, and nothing persisted.

**Comment by FLamparski** [comment]
Yeah, I don't think that's working right. I updated and while saving phones works now, invoices are broken! If I add the line item using `$invoice->addLineItem($item)`, XeroPHP tries to persist `<LineItems></LineItems>`; trying to add line items using `$invoice->getLineItems()[] = $item` fails with 
```
Undefined index: LineItems in /[path]/vendor/calcinai/xero-php/src/XeroPHP/Models/Accounting/Invoice.php on line 364
```

**Comment by FLamparski** [comment]
Tested with 1.2.4 and master; 1.2.4 works but master does not.

**Comment by calcinai** [comment]
Oh no!  I can't immediately see why that's failing - don't you want it to persist the LineItems?

**Comment by calcinai** [comment]
Do you have a bit more of the payload that you can share?

**Comment by FLamparski** [comment]
The payload was

```xml
<Invoice>
    <Type>ACCREC</Type>
    <Contact>
        <ContactID>fb85120e-f46c-48bd-a3c1-1b117c34ea6f</ContactID>
        <ContactStatus>ACTIVE</ContactStatus>
        <Name>GB One</Name>
        <FirstName>GB</FirstName>
        <LastName>One</LastName>
        <EmailAddress>filiplamparski+99gbone@gmail.com</EmailAddress>
        <AccountsReceivableTaxType>OUTPUT2</AccountsReceivableTaxType>
        <Addresses>
            <Address><AddressType>POBOX</AddressType><AddressLine1>-1 Weird Street</AddressLine1><City>Test Town</City><Region></Region><PostalCode>SQ3 5DG</PostalCode><Country>United Kingdom</Country></Address>
            <Address><AddressType>STREET</AddressType></Address>
        </Addresses>
        <Phones>
            <Phone>
                <PhoneType>DDI</PhoneType>
            </Phone>
            <Phone>
                <PhoneType>DEFAULT</PhoneType>
                <PhoneNumber>+440000000000</PhoneNumber>
            </Phone>
            <Phone>
                <PhoneType>FAX</PhoneType>
            </Phone>
            <Phone>
                <PhoneType>MOBILE</PhoneType>
            </Phone>
        </Phones>
        <IsSupplier>false</IsSupplier>
        <IsCustomer>false</IsCustomer>
        <UpdatedDateUTC>2015-09-09T12:33:46+00:00</UpdatedDateUTC>
        <HasAttachments>false</HasAttachments>
    </Contact>
    <LineItems></LineItems>
    <Date>2015-09-09T13:03:09+01:00</Date>
    <DueDate>2015-09-16T13:03:09+01:00</DueDate>
    <LineAmountTypes>Exclusive</LineAmountTypes>
    <BrandingThemeID>5d4dd402-c851-497e-aae1-9ff265c0d15a</BrandingThemeID>
    <CurrencyCode>GBP</CurrencyCode>
    <Status>AUTHORISED</Status>
</Invoice>
```

Adding line items works with the same code in 1.2.4

**Comment by calcinai** [comment]
I think I can see what's going on.  It just needs to instantiate an empty collection, not an array on properties that have not yet been set.  Give me a few mins.

**Comment by calcinai** [comment]
@FLamparski Did that work?

**Comment by FLamparski** [comment]
I'll have a look today, sorry I haven't been able to test it sooner

**Comment by calcinai** [comment]
No problems at all - just want to fix it up if it isn't already.

**Comment by FLamparski** [comment]
Alright, it seems to be working so far - just created and saved a new invoice in psysh with a line item, and it did in fact get added. I'll try to test it more extensively tomorrow. For now, thanks!
