### ISSUE TITLE
Get the list of currently granted scopes?

### ISSUE THREAD

**Issue by FrankEBailey** [calcinai/xero-php#890]
Hi, is there a way to retrieve from the Provider a list of the currently granted scopes?

I see there's the method _getDefaultScopes_ but is there a similar one that lists all granted scopes in the current context?

**Comment by mogilvie** [comment]
Hi Frank
You can put the AccessToken generated by the Xero OAuth is an encoded JSONWebToken. Take the token and decode it at [jwt.io](https://jwt.io/).
The scopes are in the token.
I'm not sure if this package contains a JWT token decoder, but you could use something like https://github.com/firebase/php-jwt if you needed decode the JWT in your application.

**Comment by FrankEBailey** [comment]
Thanks for the great suggestions, Mark and Michael!
