### ISSUE TITLE
No phones on a contact that has phones

### ISSUE THREAD

**Issue by FLamparski** [calcinai/xero-php#91]
(Continuing discussion from #88)

To display the billing details page in the app I'm working on, I have to select the `DEFAULT` phone.

The code I'm using to select which phone to display is

```php
      'phone' => array_find(function($phone) {
        return $phone->getPhoneType() === 'DEFAULT';
      }, $xeroContact->getPhones())->toStringArray()
```

After updating to master (including fixes for #88), this started crashing:

```
PHP Fatal error:  Call to a member function toStringArray() on null in /<snip>/billing/BillingInfoController.php on line 122
```

Upon further examination, it seems that `$xeroContact->getPhones()` started returning an empty collection. IMO, if you want to wrap the Xero API as faithfully as possible, it should never do that, as even on a completely empty contact (check out the 7-Eleven contact in a Demo Company), there are skeleton Phones and Addresses defined:

```xml
      <Addresses>
        <Address>
          <AddressType>STREET</AddressType>
        </Address>
        <Address>
          <AddressType>POBOX</AddressType>
        </Address>
      </Addresses>
      <Phones>
        <Phone>
          <PhoneType>DDI</PhoneType>
        </Phone>
        <Phone>
          <PhoneType>DEFAULT</PhoneType>
        </Phone>
        <Phone>
          <PhoneType>FAX</PhoneType>
        </Phone>
        <Phone>
          <PhoneType>MOBILE</PhoneType>
        </Phone>
      </Phones>
```

**Comment by calcinai** [comment]
I'm not sure why you're getting that. It should be picking up whatever is returned from the xero API. 

I'm away from my computer for the next week but I can test when I get back if you've not worked something out prior. 

Sorry to be so unhelpful!

**Comment by calcinai** [comment]
Sorry, that was auto closed, but it does seem to be fixed.
