### ISSUE TITLE
Paginated Responses are not building the objects correctly

### ISSUE THREAD

**Issue by bretto36** [calcinai/xero-php#916]
Having an issue due to the recent changes to the Xero API. When you specify a pageNumber on an API Request it can't find the values

$xero->load(\XeroPHP\Models\Accounting\Contact::class)
                ->includeArchived();
                
                this works

$xero->load(\XeroPHP\Models\Accounting\Contact::class)
                ->where('(IsCustomer==FALSE and IsSupplier==FALSE) or IsCustomer==TRUE')
                ->includeArchived()
->page(1);

This fails

**Comment by lewiswilbynm** [comment]
Hello,

With the latest changes (not this PR but other things tagged in the latest tag), you have changes this this project to no longer be PHP 5.6 + and instead it is now PHP 7.4 +.

From what I can see, it is only the following files with PHP 7.4 syntax:

1. Application
2. Request

Thoughts on removing the PHP 7.4 syntax vs changing the readme? (we currently have a project using PHP 7.1 using this library)

**Comment by calcinai** [comment]
PHP 7 is probably a weird constraint to ahem anyway, it might make sense to have a major version bump and fix 2.x to still only require PHP 5. Thoughts?

**Comment by lewiswilbynm** [comment]
> PHP 7 is probably a weird constraint to ahem anyway, it might make sense to have a major version bump and fix 2.x to still only require PHP 5. Thoughts?

Sounds like the best idea to me.

**Comment by lewiswilbynm** [comment]
> PHP 7 is probably a weird constraint to ahem anyway, it might make sense to have a major version bump and fix 2.x to still only require PHP 5. Thoughts?

I have submitted a PR with some changes to remove the PHP 7.4 syntax. 

Not sure how this is approved / merged and tagged on this project.

https://github.com/calcinai/xero-php/pull/919#pullrequestreview-2153155883
