### ISSUE TITLE
"Failed to validate signature" renewing tokens for partner application

### ISSUE THREAD

**Issue by judgej** [calcinai/xero-php#92]
Been tearing my hair out all afternoon trying to get this working. Is there any way I can monitor what is being sent to Xero to see if there are any clues as to what could be going wrong?

* I have the correct curl SSL certificates, since it can get through to the partner URL.
* I have the correct consumer key and secret, since authorising at the start works. I get the initial 30 minute access tokens, and they work for access.
* The RSA private key appears to be correct, and works on the production site (in a different application).

All these things seem to be set up correctly in the request (I've var-dumped the request and all the stuff I expect to see is in the correct place - except the callback URL which has a localhost domain, but the callback is not used when renewing tokens - or is it?), but when I `send()` the request to renew the tokens, I get this error from Xero:

> Failed to validate signature

The support details on the Xero site seem to say, "your code is messed up; use our code", which is of no help whatsoever. I'm sure I am missing something really obvious, but how can I tell what it is?

**Comment by judgej** [comment]
Fixed the callback URL domain (the renewal is done in a cron job, and that wasn't picking up the correct domain), but still the same error.

Just so I understand the way OAuth works here, it uses the previous valid token and session handle (but not the oauth secret) to renew the tokens?

**Comment by judgej** [comment]
Is this problem related to the RSA key?

For a private application only the private RSA key is needed, and that seems to work. But the Xero demo application does use the RSA public key for some of its signature creation:

https://github.com/XeroAPI/XeroOAuth-PHP/blob/7b6a4a9cc7d2fb13f7de37d57089aa4c745b2fa7/lib/OAuthSimple.php#L204

Unless I'm missing it, the example partner application here is not given the RSA public key at all, so it cannot possibly use it in a signature.

**Comment by judgej** [comment]
I had better ask: has the Partner example application ever been tried out? Does it work, not only to initially authenticate, but to renew tokens offline when they expire each half hour? I just need to know whether I am bug-fixing just my code, or bug-fixing the whole OAuth process.

**Comment by judgej** [comment]
I've added this question here: https://community.xero.com/developer/discussion/11847486/ also asked on reddit. It has got kind of urgent now, as it has set us back two days.

**Comment by calcinai** [comment]
Hey, from what I understand it has been tested (and working) by a few people. 

@coop182, can you shed any light on this?

**Comment by judgej** [comment]
Thanks, that is good to know, and helps me focus on my code.

There is a live site using the official Xero library that does renew the tokens correctly. My dev site (using this package) is using all the same keys and certificates as the live site. The domains for both the live and the dev site are set as callback domains in the Partner Application. This is what I'm starting with, so I know all the credentials are working (which is not to say I'm using them correctly).

**Comment by judgej** [comment]
This is the renewal logic I'm using. A request query is created then passed to `sendRequest` with the application. An attempt is made to execute the query, which will send the resource request to Xero. If an `UnauthorizedException` is thrown then the tokens are assumed to be expired; this is caught. If the application is Partner, then the tokens should be renewable. If not Partner, then they won't be, and the exception is thrown back up to the user or the cron scheduler for logging as fatal. Hopefully that outer logic makes sense.

~~~php
    public static function sendRequest(Query $query, Application $application)
    {
        try {
            return $query->execute();
        } catch(UnauthorizedException $e) {
            // Catch expired access tokens.
            // Renew the tokens if a partner application then try again.
            // Otherwise log the error and raise it again.

            if (is_a($application, PartnerApplication::class)) {
                // *** Renew tokens here ***
                
                // Try again.
                return $query->execute();
            }

            // Could just rethrow $e instead
            throw new UnauthorizedException('OAuth tokens expired or invalid; please renew tokens', 0, $e);
        } catch(Exception $e) {
            throw $e;
        }
    }
~~~

**Comment by coop182** [comment]
I can confirm that this library definitely works with the Partner API... we use it extensively and refreshing works well... I made a few changes to the partner example code a while back while I was getting this going so it should definitely work as it currently is.

The only thing we do differently from the example is we sign in the query string rather than the headers... that shouldn't make a difference but you might want to try that out.

**Comment by judgej** [comment]
Thanks, I'll give that a try.

**Comment by judgej** [comment]
Hell's Bells - that was it! I set the OAuth signature location:

~~~php
$config = [
    'oauth' => [
        ...
        'signature_location' => XeroPHP\Remote\OAuth\Client::SIGN_LOCATION_QUERY,
    ],
    ...
];
~~~

then pressed my "test connection" button on the front end, and *voila*!

> SUCCESS: Connection was successful.

The test button follows the logic I described a couple of posts back, and just fetches the company name to see if it works, with the token being renewed in that process if it has expired.

**Comment by judgej** [comment]
I would recommend the example code is changed to sign in the query, until we get to the bottom of why the header approach doesn't work, at least for my setup and so likely others too.

**Comment by judgej** [comment]
I'd buy you a beer if you were a little closer. Instead, I'll have a New Zealand cider in the free glass I got with four bottles of Old Mout last week, and drink to your health, timing, and sanity-rescuing information :-)

**Comment by coop182** [comment]
Glad that worked for you! I'll make a pull request now to update the example to have the signing in the query string.

**Comment by calcinai** [comment]
Awesome, thanks @coop182 - I knew you'd have an answer! 

Who knows why the header signing doesn't work…

**Comment by judgej** [comment]
Looking through the official library, it only seems to sign on the URL:

https://github.com/XeroAPI/XeroOAuth-PHP/blob/7b6a4a9cc7d2fb13f7de37d57089aa4c745b2fa7/lib/XeroOAuth.php#L256

The curl object is initialised with a "signed_url" every time, so maybe that should be the default?

The really confusing thing is that the header signature method works fine for the initial authorisation, and works fine for all resource transactions for the first 30 minutes. It is just when renewing the tokens that it falls down. So the signature construction logic works most of the time, but something is different when renewing expired tokens. That may just be an issue at the Xero end, but there may be a clue here in something that differs in the signature construction between token renewals and resource transactions in this package that you may know of. I personally can't see what it could be - all signatures are constructed in one place regardless of the transaction type, so my money is going to be on Xero.

**Comment by calcinai** [comment]
I can't see anything wrong with the header signing.  Closing and assuming it's an issue at Xero's end.

**Comment by judgej** [comment]
Just had this error again, switching to the new partner URLs. Glad I raised this issue back in 2015, because it was the only source I could find to hint that I should switch back from a query signature to a header signature :-)
