### ISSUE TITLE
Backwards incompatible change made in 2.6.1

### ISSUE THREAD

**Issue by alexbowers** [calcinai/xero-php#922]
Release `2.6.1` released backwards incompatible changes.

Notably: https://github.com/calcinai/xero-php/compare/v2.6.0...v2.6.1#diff-81ec8d43e702e6037a412211a5482db13c5cecdd63552e311c4a299f4ead49f2R32-R36

This is not compatible with PHP 7.1 (the Readme lists PHP 5.6+ as supported).

Thanks,
Alex.

**Comment by lewiswilbynm** [comment]
> Release `2.6.1` released backwards incompatible changes.
> 
> Notably: [v2.6.0...v2.6.1#diff-81ec8d43e702e6037a412211a5482db13c5cecdd63552e311c4a299f4ead49f2R32-R36](https://github.com/calcinai/xero-php/compare/v2.6.0...v2.6.1#diff-81ec8d43e702e6037a412211a5482db13c5cecdd63552e311c4a299f4ead49f2R32-R36)
> 
> This is not compatible with PHP 7.1 (the Readme lists PHP 5.6+ as supported).
> 
> Thanks, Alex.

I've created a PR for this already: https://github.com/calcinai/xero-php/pull/919

More information / discussion can be seen here: https://github.com/calcinai/xero-php/issues/916

**Comment by calcinai** [comment]
I've released v2.6.2 to resolve this.

**Comment by alexbowers** [comment]
Thanks for the swift response everybody
