### ISSUE TITLE
Filter function to search for records. Lack of examples.

### ISSUE THREAD

**Issue by mediabeastnz** [calcinai/xero-php#93]
Filter function to search for records. ~~Currently only GUID is searchable~~

Maybe this issue can be for the lack of examples around filtering?
For example how would do multiple elements with AND as doesn't the where function only take two variables?

**Comment by FLamparski** [comment]
You can drop a ->where() between load and execute to filter records. Check
the Xero API docs for more info. Also note that not all searching and
filtering may be possible in the API that is possible in the UI.

**Comment by coop182** [comment]
@mediabeastnz the `where()` function can take one or two arguments

So for multiple where conditions with AND you can call it in two ways:

```php
$xero->load('Accounting\\Invoices')->where('Status','AUTHORISED')->where('Type', 'ACCREC')->execute();
```
```php
$xero->load('Accounting\\Invoices')->where('Status=="AUTHORISED" AND Type=="ACCREC"')->execute();
```
If you want to do OR you have to use the single argument method as multiple `where()` calls are automatically put together with an AND as you can see [here](https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/Query.php#L59).

**Comment by mediabeastnz** [comment]
Thank you for clarifying this!
