### ISSUE TITLE
I have used Xero Invoice API using this package. But I have confusion about last update. Please help.

### ISSUE THREAD

**Issue by ujjwalmejora** [calcinai/xero-php#930]
Hi,
I have a query about the Xero update (https://developer.xero.com/documentation/api/changelog/accountingapi-high-threshold-update), I used the function below.
```

$invoices = $xero->load('Accounting\\Invoice')
->where(
'Status == "AUTHORISED" AND                              
Type == "ACCPAY" '
)
->execute();
```

AND

```
$invoices_PAID = $xero->load('Accounting\\Invoice')
				->where(
					'Status == "' . 'PAID' . '" AND                              
					  Type == "' . 'ACCPAY' . '"  AND
					  Date > DateTime(' . date('Y', strtotime($pre_custom_date)) . ',' . date('m', strtotime($pre_custom_date)) . ',' . date('d', strtotime($pre_custom_date)) . ')  AND
					  Date <= DateTime(' . date('Y', strtotime($custom_date)) . ',' . date('m', strtotime($custom_date)) . ',' . date('d', strtotime($custom_date)) . ')'
				)
				->execute();
```

I have already updated the calcinai/xero-php package a few days ago (v2.7.0 Fix Xero's Breaking changes). Will this still work after the '[Accounting API High Threshold Update](https://developer.xero.com/documentation/api/changelog/accountingapi-high-threshold-update)'? Or needs any changes? (Mainly "where" and "pagination")

**Comment by calcinai** [comment]
Hi @ujjwalmejora. I can't speak to if your code in itself will work, but the library itself will be fine.

**Comment by ujjwalmejora** [comment]
Do we need to change the where parameter pattern after the 'Accounting API High Threshold Update'? I used this package.
