### ISSUE TITLE
Some Response statuses and messages not parsed correctly (can't distiguish between rate limit and offline reasons)

### ISSUE THREAD

**Issue by judgej** [calcinai/xero-php#95]
I've been getting this error for an hour:

> API is currently unavailable.

Digging into the exception behind that, I get this:

> exception 'XeroPHP\Remote\Exception\NotAvailableException' with message 'oauth_problem=rate%20limit%20exceeded&oauth_problem_advice=please%20wait%20before%20retrying%20the%20xero%20api'
in /var/www/vhosts/.../httpdocs/vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php:108 

Note the problem is "rate%20limit%20exceeded". This exception is raised here:

https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/Response.php#L105

    } elseif(false !== stripos($this->response_body, 'Rate limit exceeded')){

Note that there are three status codes grouped into one, and then `$this->response_body` is searched for specific strings. Except `$this->response_body` is URL encoded, so contains no spaces - but `%20`. For this reason, I was not getting the message that the rate limit had been exceeded, but getting the generic fallback message instead.

I think what needs to happen for the generic message at least, is that the `oauth_problem` string is decoded and added to that exception as a message. Getting that message down the chain through the message stack would help in analysing connection issues. Decoding that `oauth_problem` first would also allow the above `stripos` to match correctly, so the correct exception is thrown.

It's not clear just why the message is parsed like this anyway, when there are three separate status codes that tell us what happened, assuming they are working.

**Comment by judgej** [comment]
I'm getting this error:

> "The API rate limit for your organisation\/application pairing has been exceeded."

if I change line 105 to:

    } elseif(false !== stripos($this->response_body, 'Rate%20limit%20exceeded')){

**Comment by calcinai** [comment]
Hey, thanks for picking this up.  Are you able to submit a PR? 

ps. careful about changing applications to circumvent rate limits, Xero specifically forbid this in their t&c.  From what I understand, you can actually contact them and if your case is good enough, they can bump up your app's limit.

**Comment by coop182** [comment]
I've just done a quick pull request for this as I need it as well.

**Comment by judgej** [comment]
Thanks for that. It was on my list to tackle today, so I can tick that off and get an extra half hour of sleep instead :-)
